Repository ComplianceAsCode/content, pull requests merged in 2018-07, with the labels that each got.

#3069 Deduplicated partition tests in the test suite.
  tests/data/group_system/group_permissions/group_partitions/partition.sh
  tests/data/group_system/group_permissions/group_partitions/removable_partitions.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_home_nosuid/fstab.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_home_nosuid/runtime.pass.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_home_nosuid/separate.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_noexec_removable_partitions/dvd_bad_opts.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_noexec_removable_partitions/dvd_good_opts.pass.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_tmp_noexec/fstab.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_tmp_noexec/partition.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_tmp_noexec/runtime.pass.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_tmp_noexec/separate.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_noexec/fstab.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_noexec/partition.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_noexec/runtime.pass.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_noexec/separate.fail.sh
Labels: SSGTestSuite, refactoring

#3071 Test suite python3
  tests/data/__init__.py
  tests/test_suite.py
Labels: SSGTestSuite

#3054 Enable Travis CI with containerized build
  .travis.yml
  README.md
Labels: Infrastructure

#3074 Fix test suite
  tests/README.md
  tests/test_suite.py
Labels: BLOCKER, SSGTestSuite, bugfix

#3080 Unshadow dovecot_disable_plaintext_auth
  rhel6/checks/oval/dovecot_disable_plaintext_auth.xml
  shared/checks/oval/dovecot_disable_plaintext_auth.xml
Labels: RHEL6, refactoring

#3078 Unshadow dovecot_enable_ssl
  rhel6/checks/oval/dovecot_enable_ssl.xml
  shared/checks/oval/dovecot_enable_ssl.xml
Labels: RHEL6, refactoring

#3079 Unshadow network_ipv6_privacy_extensions
  rhel6/checks/oval/network_ipv6_privacy_extensions.xml
  shared/checks/oval/network_ipv6_privacy_extensions.xml
Labels: RHEL6, refactoring

#3076 Unshadow the xwindows_runlevel OVAL
  rhel6/checks/oval/xwindows_runlevel_setting.xml
  shared/checks/oval/xwindows_runlevel_setting.xml
Labels: RHEL6, refactoring

#3081 Unshadowed postfix_network_listening_disabled
  rhel6/checks/oval/postfix_network_listening_disabled.xml
  shared/checks/oval/postfix_network_listening_disabled.xml
Labels: RHEL6, refactoring

#3084 Unshadow display_login_attempts
  rhel6/checks/oval/display_login_attempts.xml
  shared/checks/oval/display_login_attempts.xml
Labels: RHEL6, refactoring

#3083 Unshadow ntpd_specify_remote_server and ntpd_specify_multiple_servers
  rhel6/checks/oval/ntpd_specify_multiple_servers.xml
  rhel6/checks/oval/ntpd_specify_remote_server.xml
  shared/checks/oval/ntpd_specify_multiple_servers.xml
  shared/checks/oval/ntpd_specify_remote_server.xml
Labels: RHEL6, refactoring

#3082 Unshadow network_ipv6_default_gateway
  rhel6/checks/oval/network_ipv6_default_gateway.xml
  shared/checks/oval/network_ipv6_default_gateway.xml
Labels: RHEL6, refactoring

#3088 Unshadowed some stray osp7 ovals.
  rhel-osp7/checks/oval/system_info_architecture_x86.xml
  rhel-osp7/checks/oval/system_info_architecture_x86_64.xml
Labels: refactoring

#3085 Unshadow rhel6 audit_rules_time_
  rhel6/checks/oval/audit_rules_time_adjtimex.xml
  rhel6/checks/oval/audit_rules_time_clock_settime.xml
  rhel6/checks/oval/audit_rules_time_settimeofday.xml
  rhel6/checks/oval/audit_rules_time_stime.xml
  rhel6/checks/oval/audit_rules_time_watch_localtime.xml
  shared/checks/oval/audit_rules_time_adjtimex.xml
  shared/checks/oval/audit_rules_time_clock_settime.xml
  shared/checks/oval/audit_rules_time_settimeofday.xml
  shared/checks/oval/audit_rules_time_stime.xml
  shared/checks/oval/audit_rules_time_watch_localtime.xml
Labels: RHEL6, refactoring

#3086 No OVAL for xwindows_runlevel_setting when product uses systemd and targets OVAL 5.10
  shared/checks/oval/xwindows_runlevel_setting.xml
Labels: bugfix

#3091 Unshadow sshd set keepalive and sshd set idle timeout
  rhel6/fixes/bash/sshd_set_idle_timeout.sh
  rhel6/fixes/bash/sshd_set_keepalive.sh
Labels: RHEL6, refactoring

#3092 Unshadow network_ipv6_disable_rpc on RHEL6
  rhel6/fixes/bash/network_ipv6_disable_rpc.sh
  shared/fixes/bash/network_ipv6_disable_rpc.sh
Labels: RHEL6, refactoring

#3090 Unshadow bash fix display_login_attempts on RHEL6
  rhel6/fixes/bash/display_login_attempts.sh
  shared/fixes/bash/display_login_attempts.sh
Labels: RHEL6, refactoring

#3089 exec-shield requires special handling, don't use the template for it …
  rhel6/templates/csv/sysctl_values.csv
  shared/checks/oval/sysctl_kernel_exec_shield.xml
Labels: RHEL6, refactoring

#3077 Unshadow network_ipv6_static_address
  rhel6/checks/oval/network_ipv6_static_address.xml
  shared/checks/oval/network_ipv6_static_address.xml
Labels: RHEL6, refactoring

#3098 Unshadow dir_perms_world_writable_system_owned on RHEL6
  rhel6/checks/oval/dir_perms_world_writable_system_owned.xml
  shared/checks/oval/dir_perms_world_writable_system_owned.xml
Labels: RHEL6, refactoring

#3093 Unshadow disable ctrlaltdel
  rhel6/checks/oval/disable_ctrlaltdel_reboot.xml
  rhel6/fixes/bash/disable_ctrlaltdel_reboot.sh
  shared/checks/oval/disable_ctrlaltdel_reboot.xml
  shared/fixes/bash/disable_ctrlaltdel_reboot.sh
Labels: RHEL6, refactoring

#3094 Unshadow disable_interactive_boot bash fix on RHEL6
  rhel6/fixes/bash/disable_interactive_boot.sh
  shared/fixes/bash/disable_interactive_boot.sh
Labels: RHEL6, refactoring

#3095 Unshadow enable_selinux_bootloader bash fix on RHEL6
  rhel6/fixes/bash/enable_selinux_bootloader.sh
  shared/fixes/bash/enable_selinux_bootloader.sh
Labels: RHEL6, refactoring

#3101 Travis CI - Python 2 build
  .travis.yml
  Dockerfiles/fedora_python2
  Dockerfiles/fedora_python3
  Dockerfiles/ubuntu
Labels: Infrastructure, enhancement, refactoring

#3100 Unshadow configure ldap ca
  rhel6/checks/oval/ldap_client_start_tls.xml
  rhel6/checks/oval/ldap_client_tls_cacertpath.xml
  shared/checks/oval/ldap_client_start_tls.xml
  shared/checks/oval/ldap_client_tls_cacertpath.xml
Labels: RHEL6, refactoring

#3110 Unshadow audit_rules_mac_modification
  rhel6/checks/oval/audit_rules_mac_modification.xml
  shared/checks/oval/audit_rules_mac_modification.xml
Labels: refactoring

#3109 Unshadow RHEL6 OVAL and BASH audit_rules_immutable
  rhel6/checks/oval/audit_rules_immutable.xml
  rhel6/fixes/bash/audit_rules_immutable.sh
  shared/checks/oval/audit_rules_immutable.xml
  shared/fixes/bash/audit_rules_immutable.sh
Labels: refactoring

#3116 Fix parallel make regression
  cmake/SSGCommon.cmake
Labels: BLOCKER, Infrastructure, bugfix

#3075 Update unit tests to work with new SSG layout and Python3
  ssg/oval.py
  tests/CMakeLists.txt
  tests/unit/ssg/test_build_remediations.py
  tests/unit/ssg/test_oval.py
Labels: Infrastructure

#3117 Unshadow rhel6 audit rules kernel module loading
  rhel6/checks/oval/audit_rules_kernel_module_loading.xml
  shared/checks/oval/audit_rules_kernel_module_loading.xml
  shared/checks/oval/audit_rules_kernel_module_loading_delete.xml
  shared/checks/oval/audit_rules_kernel_module_loading_init.xml
  shared/checks/oval/audit_rules_kernel_module_loading_insmod.xml
  shared/checks/oval/audit_rules_kernel_module_loading_modprobe.xml
  shared/checks/oval/audit_rules_kernel_module_loading_rmmod.xml
Labels: refactoring

#3114 Add uid_min and implied auid product.yml
  rhel6/product.yml
  shared/checks/oval/dir_perms_world_writable_system_owned.xml
  shared/templates/template_BASH_audit_rules_dac_modification
  shared/templates/template_OVAL_audit_rules_dac_modification
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
  ssg/constants.py
  ssg/yaml.py
Labels: enhancement

#3119 Drop rhel6 check audit_rules_usergroup_modification
  rhel6/checks/oval/audit_rules_usergroup_modification.xml
  shared/checks/oval/audit_rules_usergroup_modification.xml
Labels: refactoring

#3103 Travis - CentOS 6
  .travis.yml
  Dockerfiles/centos6
Labels: Infrastructure

#3123 Unshadow rhel6 bash fix for audit_rules_time_clock_settime
  rhel6/fixes/bash/audit_rules_time_clock_settime.sh
  shared/fixes/bash/audit_rules_time_clock_settime.sh
Labels: refactoring

#3122 Unshadow rhel6 audit_rules_session_events
  rhel6/checks/oval/audit_rules_session_events.xml
  shared/checks/oval/audit_rules_session_events.xml
Labels: refactoring

#3127 Improve logic around uid_min and auid
  ssg/yaml.py
Labels: refactoring

#3128 Make yaml parsing errors clear about source file
  ssg/yaml.py
Labels: usability

#3108 Unshadow audit_rules_media_export
  rhel6/checks/oval/audit_rules_media_export.xml
  shared/checks/oval/audit_rules_media_export.xml
Labels: refactoring

#3121 Drop rhel6 audit_rules_networkconfig_modification
  rhel6/checks/oval/audit_rules_networkconfig_modification.xml
  shared/checks/oval/audit_rules_networkconfig_modification.xml
  shared/checks/oval/audit_rules_networkconfig_modification_domainname.xml
  shared/checks/oval/audit_rules_networkconfig_modification_hostname.xml
Labels: refactoring

#3102 Unshadow require single user
  rhel6/checks/oval/require_singleuser_auth.xml
  rhel6/fixes/bash/require_singleuser_auth.sh
  shared/checks/oval/require_singleuser_auth.xml
  shared/fixes/bash/require_singleuser_auth.sh
Labels: RHEL6, refactoring

#3137 Drop rhel6 bash remediation for audit_rules_kernel_module_loading
  rhel6/fixes/bash/audit_rules_kernel_module_loading.sh
Labels: refactoring

#3138 Avoid jinja eating the whitespace after the platform identifier in fixes
  build-scripts/combine_remediations.py
  shared/fixes/bash/enable_selinux_bootloader.sh
  shared/fixes/bash/require_singleuser_auth.sh
Labels: BLOCKER

#3143 Remove FIPS remediations from CentOS as well as RHEL CCEs
  ssg/build_derivatives.py
Labels: bugfix

#3141 Html table tests and fixes
  cmake/SSGCommon.cmake
  rhel6/CMakeLists.txt
  rhel7/CMakeLists.txt
  rhel7/profiles/anssi_nt28_enhanced.profile
  rhel7/profiles/anssi_nt28_high.profile
  rhel7/profiles/anssi_nt28_intermediary.profile
  rhel7/profiles/anssi_nt28_minimal.profile
Labels: BLOCKER

#3107 Unshadow audit_rules_file_deletion_events
  rhel6/checks/oval/audit_rules_file_deletion_events.xml
  shared/checks/oval/audit_rules_file_deletion_events.xml
  shared/templates/template_OVAL_audit_rules_file_deletion_events
Labels: refactoring

#3145 Removed formatting leftovers.
  chromium/guide/benchmark.yml
  debian8/guide/benchmark.yml
  eap6/guide/benchmark.yml
  firefox/guide/benchmark.yml
  fuse6/guide/benchmark.yml
  jre/guide/benchmark.yml
  linux_os/guide/benchmark.yml
  wrlinux/guide/benchmark.yml
Labels: bugfix, easy fix

#3147 Py2py3 sanity
  tests/python2_vs_python3_sanity.sh
  utils/compare_generated.sh
Labels: SSGTestSuite

#3153 wrlinux -> linux_os guide merger
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed.rule
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords.rule
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_netrc_files.rule
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero.rule
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay.rule
  linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions.rule
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_dirs.rule
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write.rule
  linux_os/guide/system/accounts/accounts-session/root_paths/root_path_no_dot.rule
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs.rule
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile.rule
  wrlinux/product.yml
Labels: Infrastructure, enhancement, refactoring, usability

#3157 Move signal logic from template to generator
  shared/templates/create_accounts_password.py
  shared/templates/template_OVAL_accounts_password
Labels: BLOCKER, bugfix

#3158 Fix template_OVAL_package_installed
  shared/templates/template_OVAL_package_installed
Labels: BLOCKER, bugfix

#3162 Refactor and update template generation restrictions
  rhel6/templates/csv/sysctl_values.csv
  rhel7/templates/csv/mount_options.csv
  shared/templates/template_common.py
  sle12/templates/csv/sysctl_values.csv
Labels: Infrastructure, enhancement

#3161 Add missing OCIL Clause in file permission rules
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_cron_allow.rule
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_cron_allow.rule
  linux_os/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_restrict_file_dir_access/file_permissions_httpd_server_conf_d_files.rule
  linux_os/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_restrict_file_dir_access/file_permissions_httpd_server_conf_files.rule
  linux_os/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_restrict_file_dir_access/file_permissions_httpd_server_modules_files.rule
  linux_os/guide/services/ssh/file_permissions_sshd_private_key.rule
  linux_os/guide/services/ssh/file_permissions_sshd_pub_key.rule
  linux_os/guide/system/bootloader-grub-legacy/file_groupowner_grub_conf.rule
  linux_os/guide/system/bootloader-grub-legacy/file_owner_grub_conf.rule
  linux_os/guide/system/bootloader-grub2/file_groupowner_efi_grub2_cfg.rule
  linux_os/guide/system/bootloader-grub2/file_groupowner_grub2_cfg.rule
  linux_os/guide/system/bootloader-grub2/file_owner_efi_grub2_cfg.rule
  linux_os/guide/system/bootloader-grub2/file_owner_grub2_cfg.rule
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_etc_group.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_etc_gshadow.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_etc_passwd.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_etc_shadow.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_etc_group.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_etc_gshadow.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_etc_passwd.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_etc_shadow.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_group.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_gshadow.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_passwd.rule
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_shadow.rule
  shared/macros.jinja
  utils/fix_file_ocilclause.py
Labels: bugfix

#3159 Reduce build warnings by updating templates
  debian8/templates/csv/sysctl_values.csv
  fedora/templates/csv/packages_installed.csv
  fedora/templates/csv/packages_removed.csv
  fedora/templates/csv/services_disabled.csv
  fedora/templates/csv/services_enabled.csv
  ol7/templates/csv/sysctl_values.csv
  opensuse/templates/csv/packages_installed.csv
  opensuse/templates/csv/packages_removed.csv
  opensuse/templates/csv/services_disabled.csv
  rhel-osp7/templates/csv/packages_removed.csv
  rhel6/templates/csv/packages_removed.csv
  rhel6/templates/csv/services_disabled.csv
  rhel6/templates/csv/sysctl_values.csv
  rhel7/templates/csv/packages_installed.csv
  rhel7/templates/csv/packages_removed.csv
  rhel7/templates/csv/services_disabled.csv
  shared/checks/oval/kernel_module_ipv6_option_disabled.xml
  shared/checks/oval/sshd_disable_empty_passwords.xml
  shared/checks/oval/sshd_disable_rhosts_rsa.xml
  shared/checks/oval/sshd_disable_root_login.xml
  shared/checks/oval/sshd_disable_user_known_hosts.xml
  shared/checks/oval/sshd_enable_x11_forwarding.xml
  shared/checks/oval/sshd_set_idle_timeout.xml
  shared/checks/oval/sshd_set_keepalive.xml
  shared/checks/oval/sssd_conf_exists.xml
  shared/checks/oval/sysctl_kernel_ipv6_disable.xml
  shared/fixes/bash/kernel_module_ipv6_option_disabled.sh
  sle11/templates/csv/packages_installed.csv
  sle11/templates/csv/packages_removed.csv
  sle11/templates/csv/services_disabled.csv
  sle11/templates/csv/sysctl_values.csv
  sle12/templates/csv/packages_installed.csv
  sle12/templates/csv/packages_removed.csv
  sle12/templates/csv/services_disabled.csv
  sle12/templates/csv/services_enabled.csv
  ubuntu1404/templates/csv/sysctl_values.csv
  ubuntu1604/templates/csv/sysctl_values.csv
  wrlinux/templates/csv/sysctl_values.csv
Labels: bugfix

#3169 Refactored the compare_generated.sh script.
  utils/compare_generated.sh
Labels: Infrastructure, refactoring

#3170 Jinja cleanup + tests
  ssg/jinja.py
  ssg/yaml.py
  tests/unit/ssg/data/definitions.jinja
  tests/unit/ssg/test_jinja.py
Labels: refactoring
