Repository ComplianceAsCode/content, pull requests merged in 2018-12, with the labels that each got.

#3633 Limit configure_crypto_policy symlink checking to oval 5.11
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/oval/shared.xml
Labels: OVAL, bugfix

#3627 Introduce platform dependent test scenarios
  chromium/product.yml
  debian8/product.yml
  eap6/product.yml
  example/product.yml
  fedora/product.yml
  firefox/product.yml
  fuse6/product.yml
  jre/product.yml
  ocp3/product.yml
  ol7/product.yml
  opensuse/product.yml
  rhel6/product.yml
  rhel7/product.yml
  rhel8/product.yml
  rhosp13/product.yml
  rhv4/product.yml
  sle11/product.yml
  sle12/product.yml
  ssg/build_ovals.py
  ssg/build_remediations.py
  ssg/build_yaml.py
  ssg/constants.py
  ssg/products.py
  tests/README.md
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/xml_operations.py
  tests/test_suite.py
  tests/unit/ssg_test_suite/test_matches_platform.py
  ubuntu1404/product.yml
  ubuntu1604/product.yml
  ubuntu1804/product.yml
  wrlinux/product.yml
Labels: SSGTestSuite, enhancement

#3619 Fix auditd_audispd_encrypt_sent_records on Fedora and RHEL8
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/rule.yml
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/encrypt_sent_records.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/encrypt_sent_records_not_activated.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/encrypt_sent_records_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/transport_bogus_value.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/transport_correct_value.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/transport_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_encrypt_sent_records/transport_wrong_value.fail.sh
Labels: bugfix

#3620 Fix auditd_audispd_syslog_plugin_activated on Fedora and RHEL8
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/rule.yml
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audisp_syslog_plugin_activated.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audisp_syslog_plugin_activated_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audisp_syslog_plugin_not_activated.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audit_syslog_plugin_activated.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audit_syslog_plugin_activated_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_syslog_plugin_activated/audit_syslog_plugin_not_activated.fail.sh
Labels: bugfix

#3621 Fix auditd_audispd_configure_remote_server on Fedora and RHEL8
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_audispd_remote_server.var
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/audisp_remote_server_hostname.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/audisp_remote_server_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/audit_remote_server_hostname.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/audit_remote_server_not_there.fail.sh
Labels: bugfix

#3639 Move verbose argument closer to last submodule
  tests/ssg_test_suite/oscap.py
Labels: bugfix

#3648 Fix the machine/container filter for Ansible remediations.
  shared/transforms/xccdf-addremediations.xslt
Labels: bugfix

#3649 Extend ol7 CPE dict with container and machine platforms
  ol7/cpe/ol7-cpe-dictionary.xml
Labels: bugfix, enhancement

#3647 adding ansible remediation for auditing finit module with rhel7
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/ansible/shared.yml
Labels: Ansible

#3651 fix variable definitions
  ocp3/profiles/opencis-ocp-node.profile
Labels: bugfix

#3642 Improve parameters for ensure_fedora_gpgkey_installed
  fedora/product.yml
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/oval/shared.xml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh
Labels: enhancement

#3662 Make the man page depend of derivate contents
  cmake/SSGCommon.cmake
Labels: Infrastructure, bugfix

#3663 Fixed stable IDs test for RHEL8 and increased robustness.
  tests/stable_profile_ids.py
Labels: bugfix

#3623 New rule to enable FIPS mode on RHEL8 and Fedora
  fedora/profiles/ospp.profile
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  rhel8/profiles/ospp.profile
Labels: enhancement

#3667 Simply some product profile names
  chromium/profiles/stig.profile
  firefox/profiles/stig.profile
  jre/profiles/stig.profile
  ocp3/profiles/opencis-master.profile
  ocp3/profiles/opencis-node.profile
  rhosp13/profiles/stig.profile
Labels: enhancement
