Repository ComplianceAsCode/content, pull requests merged in 2018-09, with the labels that each got.

#3250 Enable rsyslog_remote_loghost OVAL on Fedora
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/oval/shared.xml
Labels: Fedora

#3252 Add fedora platform and tests for selinux_policytype rule
  linux_os/guide/system/selinux/selinux_policytype/bash/shared.sh
  linux_os/guide/system/selinux/selinux_policytype/oval/shared.xml
  tests/data/group_system/group_selinux/rule_selinux_policytype/selinuxtype_missing.fail.sh
  tests/data/group_system/group_selinux/rule_selinux_policytype/selinuxtype_targeted.pass.sh
Labels: enhancement

#3254 Removed obsolete and duplicated README files
  debian8/README
  rhel-osp7/README
  rhel6/README
  rhel7/README
  sle11/README
  sle12/README
  ubuntu1404/README
  ubuntu1604/README
Labels: bugfix

#3255 These files are not used and can be confusing to contributors
  chromium/guide.xslt
  debian8/guide.xslt
  eap6/guide.xslt
  example/guide.xslt
  fedora/guide.xslt
  firefox/guide.xslt
  fuse6/guide.xslt
  jre/guide.xslt
  ocp3/guide.xslt
  ol7/guide.xslt
  opensuse/guide.xslt
  rhel-osp7/guide.xslt
  rhel6/guide.xslt
  rhel7/guide.xslt
  sle11/guide.xslt
  sle12/guide.xslt
  ubuntu1404/guide.xslt
  ubuntu1604/guide.xslt
  wrlinux/guide.xslt
Labels: bugfix

#3249 Provide checks and remediations for package_screen_installed
  fedora/templates/csv/packages_installed.csv
Labels: bugfix

#3234 Add OVAL and remediation for auditd_audispd_configure_remote_server
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_audispd_remote_server.var
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/remote_server_hostname.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/remote_server_not_there.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_audispd_configure_remote_server/remote_server_numeric_address.pass.sh
Labels: Bash, OVAL, SSGTestSuite

#3236 Filter out swap files
  tests/data/utils.py
Labels: Infrastructure, SSGTestSuite

#3258 Add Fedora to rule accounts_tmout
  fedora/profiles/ospp.profile
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/oval/shared.xml
Labels: Fedora, enhancement

#3257 Add selinux_confinement_of_daemons for Fedora
  linux_os/guide/system/selinux/selinux_confinement_of_daemons/oval/shared.xml
Labels: Fedora, bugfix

#3261 Dconf gnome fixes fedora
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_login_retries/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_info/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_locks/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_session_idle_user_locks/bash/shared.sh
Labels: enhancement

#3213 Fix misleading description of syscalls checked on audit_rules_kernel_module_loading
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/rule.yml
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/syscalls_multiple_per_arg.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/syscalls_one_per_arg.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/syscalls_one_per_line.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/test_audit.rules
Labels: Rule, SSGTestSuite

#3264 Audit auid!=unset and auid!=4294967295 are equivalent
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_media_export/oval/shared.xml
  shared/templates/template_OVAL_audit_rules_dac_modification
  shared/templates/template_OVAL_audit_rules_file_deletion_events
  shared/templates/template_OVAL_audit_rules_privileged_commands
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
Labels: OVAL, enhancement

#3266 Minor readme improvements
  README.md
Labels: documentation

#3268 namedtuple ended up being a bottleneck in ID linking code
  ssg/id_translate.py
Labels: bugfix

#3259 Update sysctl jinja macros for sysctl.d locations
  shared/macros.jinja
Labels: bugfix

#3251 Use implied properties to parametrize package manager configuration settings rules
  docs/manual/developer_guide.adoc
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  linux_os/guide/system/software/updating/group.yml
  ssg/constants.py
  ssg/yaml.py
Labels: Infrastructure, enhancement

#3269 Map service_auditd_enabled to PCI-DSS Req 10.1
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
Labels: bugfix

#3274 Finish rule gnome_gdm_disable_automatic_login for Fedora
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/bash/shared.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_automatic_login/comment.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_automatic_login/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_automatic_login/line_not_there.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_automatic_login/wrong_value.fail.sh
Labels: Fedora, enhancement

#3281 Tests and bash for gnome_gdm_disable_guest_login
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_guest_login/bash/shared.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_guest_login/comment.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_guest_login/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_guest_login/line_not_there.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_gnome_gdm_disable_guest_login/wrong_value.fail.sh
Labels: enhancement

#3279 Audit rules for unsuccessful file ownership change
  fedora/profiles/ospp.profile
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_fchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_fchownat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_lchown/rule.yml
  rhel7/profiles/ospp42-draft.profile
  shared/templates/csv/audit_rules_unsuccessful_file_modification.csv
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_chown/default.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_chown/empty.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_chown/one_filter.fail.sh
Labels: Rule, SSGTestSuite

#3265 Audit rules unsuccesful file deletion
  fedora/profiles/ospp.profile
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_unlinkat/rule.yml
  rhel7/profiles/ospp42-draft.profile
  shared/templates/csv/audit_rules_unsuccessful_file_modification.csv
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_unlink/default.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_unlink/empty.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_unlink/only_eacces.fail.sh
Labels: Rule, SSGTestSuite

#3287 Add bash and tests for rule grub2_audit_argument
  linux_os/guide/system/auditing/grub2_audit_argument/bash/shared.sh
  tests/data/group_system/group_auditing/rule_grub2_audit_argument/arg_not_there.fail.sh
  tests/data/group_system/group_auditing/rule_grub2_audit_argument/correct_value.pass.sh
  tests/data/group_system/group_auditing/rule_grub2_audit_argument/wrong_value.fail.sh
Labels: Bash, SSGTestSuite

#3293 Ansible remediation fails on setting owner of file if cron.allow doesn't exist
  shared/templates/template_ANSIBLE_file_owner
Labels: bugfix

#3289 Add Fedora to Bash for sshd_disable_gssapi_auth
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/bash/shared.sh
Labels: enhancement

#3106 [WIP] Inconsistent memcache_timeout, ssh_known_hosts_timeout wrt man sssd.conf
  linux_os/guide/services/sssd/sssd_memcache_timeout/oval/shared.xml
  linux_os/guide/services/sssd/sssd_memcache_timeout/rule.yml
  linux_os/guide/services/sssd/sssd_ssh_known_hosts_timeout/oval/shared.xml
  linux_os/guide/services/sssd/sssd_ssh_known_hosts_timeout/rule.yml
  linux_os/guide/services/sssd/var_sssd_memcache_timeout.var
  linux_os/guide/services/sssd/var_sssd_ssh_known_hosts_timeout.var
  rhel7/profiles/stig-rhel7-disa.profile
Labels: enhancement

#3290 Add Fedora to Bash for sshd_disable_kerb_auth
  linux_os/guide/services/ssh/ssh_server/sshd_disable_kerb_auth/bash/shared.sh
Labels: enhancement

#3296 Run crypto command in Ansible script
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/ansible/fedora.yml
Labels: bugfix

#3277 Fix testoval.py
  ssg/oval.py
Labels: bugfix

#3295 Finished grub2_disable_interactive_boot and grub_legacy_disable_interactive_boot rules
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/rule.yml
  linux_os/guide/system/accounts/accounts-physical/grub_legacy_disable_interactive_boot/bash/rhel6.sh
  linux_os/guide/system/accounts/accounts-physical/grub_legacy_disable_interactive_boot/oval/rhel6.xml
  shared/fixes/ansible/disable_interactive_boot.yml
  shared/fixes/bash/disable_interactive_boot.sh
  tests/data/group_system/group_accounts/group_accounts-physical/rule_grub2_disable_interactive_boot/disabled_interactive_boot.pass.sh
  tests/data/group_system/group_accounts/group_accounts-physical/rule_grub2_disable_interactive_boot/enabled_interactive_boot.fail.sh
Labels: enhancement

#3288 Move bootloader_audit_argument content to a correct place
  linux_os/guide/system/auditing/grub_legacy_audit_argument/ansible/rhel6.yml
  linux_os/guide/system/auditing/grub_legacy_audit_argument/bash/rhel6.sh
  linux_os/guide/system/auditing/grub_legacy_audit_argument/oval/rhel6.xml
  shared/fixes/bash/bootloader_audit_argument.sh
Labels: bugfix

#3301 Add missing Ansible ctrlaltdel OSPP remediations
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/ansible/shared.yml
Labels: enhancement

#3297 Audit rule to watch /etc/passwd for writes from open syscall
  fedora/profiles/ospp.profile
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_open/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_open/rule.yml
  rhel7/profiles/ospp42-draft.profile
  tests/data/group_system/group_auditing/group_auditd_configure_rules/audit_path_syscall/rule_audit_rules_etc_passwd_open/auditctl_correct_rule.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/audit_path_syscall/rule_audit_rules_etc_passwd_open/auditctl_multiple_syscalls.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/audit_path_syscall/rule_audit_rules_etc_passwd_open/auditctl_wrong_dir.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/audit_path_syscall/rule_audit_rules_etc_passwd_open/augenrules_correct_rule.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/audit_path_syscall/rule_audit_rules_etc_passwd_open/augenrules_wrong_dir.fail.sh
Labels: OVAL, Rule, SSGTestSuite

#3262 Add rule and check for detailed logging of unsuccesful file opens
  fedora/profiles/ospp.profile
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_o_creat/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_o_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_o_trunc_write/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_o_trunc_write/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_rule_order/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_rule_order/rule.yml
  rhel7/profiles/ospp42-draft.profile
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/audit_open.rules
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/audit_open_o_creat.rules
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/audit_open_o_trunc_write.rules
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/audit_o_creat_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/audit_o_trunc_write_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/empty.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/open_rules.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/rules-amis.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/empty.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/o_creat_rules.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/o_trunc_write_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/open_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/rules-amis.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write/empty.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write/o_creat_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write/o_trunc_rules.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write/open_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write/rules-amis.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_rule_order/one_rule_missing.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_rule_order/ordered_by_arch.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_rule_order/ordered_by_filter.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_rule_order/sorted_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_rule_order/unordered.fail.sh
Labels: OVAL, Rule, SSGTestSuite

#3304 Enable the OSPP 4.2 profile.
  rhel7/profiles/ospp42.profile
Labels: RHEL7

#3294 Remove use of loops for single items in Ansible templates
  shared/templates/template_ANSIBLE_audit_rules_dac_modification
  shared/templates/template_ANSIBLE_audit_rules_file_deletion_events
  shared/templates/template_ANSIBLE_audit_rules_login_events
  shared/templates/template_ANSIBLE_audit_rules_usergroup_modification
  shared/templates/template_ANSIBLE_file_groupowner
  shared/templates/template_ANSIBLE_file_owner
  shared/templates/template_ANSIBLE_file_permissions
  shared/templates/template_ANSIBLE_kernel_module_disabled
  shared/templates/template_ANSIBLE_package_installed
  shared/templates/template_ANSIBLE_package_removed
  shared/templates/template_ANSIBLE_permissions
  shared/templates/template_ANSIBLE_service_disabled
  shared/templates/template_ANSIBLE_service_enabled
Labels: bugfix

#3309 Fixed grep usage.
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_use_fips_hashes/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_acls/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_ext_attributes/bash/shared.sh
  shared/bash_remediation_functions/firefox_cfg_setting.sh
  shared/bash_remediation_functions/firefox_js_setting.sh
  shared/fixes/bash/directory_permissions_var_log_audit.xml
Labels: enhancement

#3314 Change amount of space needed before exit filter
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
Labels: bugfix

#3317 Unknown severity shouldn't be used when a different severity is specified
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/install_antivirus/rule.yml
Labels: bugfix

#3316 Fix regex for unauthorized syscall rule with one syscall and filter
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_unlink/one_sys_with_filter.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_unlink/two_sys_with_filter.fail.sh
Labels: bugfix

#3300 Add missing dconf OSPP Ansible remediations
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_enable_smartcard_auth/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_login_retries/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_login_retries/rule.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_credential_prompt/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_encryption/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_locks/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_session_idle_user_locks/ansible/shared.yml
Labels: enhancement

#3219 Rule dir tools tests
  ssg/rule_dir_stats.py
  tests/unit/ssg/test_rule_dir_stats.py
Labels: SSGTestSuite, bugfix

#3320 Fix syscall in last position
  shared/templates/template_OVAL_audit_rules_path_syscall
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification_o_creat
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification_o_trunc_write
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification_rule_order
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/open_before_last.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open/open_last.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/o_creat_before_last.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_unsuccessful_file_modification/rule_audit_rules_unsuccessful_file_modification_open_o_creat/o_creat_last.pass.sh
Labels: SSGTestSuite, bugfix, enhancement

#3223 SSG Test Suite results analysis
  tests/CMakeLists.txt
  tests/README.md
  tests/analyze_results.py
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/test_env.py
  tests/unit/ssg-module/data/definitions.jinja
  tests/unit/ssg-module/data/group_dir/group.yml
  tests/unit/ssg-module/data/group_dir/rule_dir/bash/not-a-shell-script.py
  tests/unit/ssg-module/data/group_dir/rule_dir/bash/rhel.sh
  tests/unit/ssg-module/data/group_dir/rule_dir/bash/something.sh
  tests/unit/ssg-module/data/group_dir/rule_dir/oval/not-an-oval.txt
  tests/unit/ssg-module/data/group_dir/rule_dir/oval/rhel.xml
  tests/unit/ssg-module/data/group_dir/rule_dir/oval/shared.xml
  tests/unit/ssg-module/data/group_dir/rule_dir/rule.yml
  tests/unit/ssg-module/data/random_dir/not-a-rule
  tests/unit/ssg-module/test_build_remediations.py
  tests/unit/ssg-module/test_checks.py
  tests/unit/ssg-module/test_id_translate.py
  tests/unit/ssg-module/test_jinja.py
  tests/unit/ssg-module/test_oval.py
  tests/unit/ssg-module/test_products.py
  tests/unit/ssg-module/test_rules.py
  tests/unit/ssg-module/test_utils.py
  tests/unit/ssg_test_suite/data/rules.json
  tests/unit/ssg_test_suite/test_analyze_results.py
Labels: SSGTestSuite, refactoring

#3327 Add incremental_async as a flush option
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_flush.var
Labels: enhancement

#3328 Changed shell command
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/ansible/shared.yml
Labels: bugfix

#3341 Update shell command in shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/ansible/shared.yml
Labels: bugfix

#3340 Ubuntu1804
  CMakeLists.txt
  shared/checks/oval/installed_OS_is_ubuntu1804.xml
  ubuntu1804/CMakeLists.txt
  ubuntu1804/cpe/ubuntu1804-cpe-dictionary.xml
  ubuntu1804/overlays/.gitkeep
  ubuntu1804/product.yml
  ubuntu1804/profiles/anssi_np_nt28_average.profile
  ubuntu1804/profiles/anssi_np_nt28_high.profile
  ubuntu1804/profiles/anssi_np_nt28_minimal.profile
  ubuntu1804/profiles/anssi_np_nt28_restrictive.profile
  ubuntu1804/profiles/standard.profile
  ubuntu1804/templates/csv/file_dir_permissions.csv
  ubuntu1804/templates/csv/mount_options.csv
  ubuntu1804/templates/csv/mounts.csv
  ubuntu1804/templates/csv/packages_installed.csv
  ubuntu1804/templates/csv/packages_removed.csv
  ubuntu1804/templates/csv/services_disabled.csv
  ubuntu1804/templates/csv/services_enabled.csv
  ubuntu1804/templates/csv/sysctl_values.csv
  ubuntu1804/transforms/constants.xslt
  ubuntu1804/transforms/shorthand2xccdf.xslt
  ubuntu1804/transforms/table-srgmap.xslt
  ubuntu1804/transforms/table-style.xslt
  ubuntu1804/transforms/xccdf-apply-overlay-stig.xslt
  ubuntu1804/transforms/xccdf2table-byref.xslt
  ubuntu1804/transforms/xccdf2table-cce.xslt
  ubuntu1804/transforms/xccdf2table-profileanssirefs.xslt
  ubuntu1804/transforms/xccdf2table-profileccirefs.xslt
  ubuntu1804/transforms/xccdf2table-profilecisrefs.xslt
  ubuntu1804/transforms/xccdf2table-profilenistrefs.xslt
  ubuntu1804/transforms/xccdf2table-stig.xslt
Labels: enhancement

#3324 Add OpenSC content
  fedora/templates/csv/packages_installed.csv
  fedora/templates/csv/services_enabled.csv
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_opensc_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/var_smartcard_drivers.var
  rhel7/templates/csv/packages_installed.csv
  shared/references/cce-rhel-avail.txt
Labels: enhancement

#3329 Untemplate rule mount_option_var tmp_bind
  debian8/templates/csv/mount_options.csv
  fedora/templates/csv/mount_options.csv
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_bind/bash/shared.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_bind/oval/shared.xml
  ol7/templates/csv/mount_options.csv
  opensuse/templates/csv/mount_options.csv
  rhel-osp7/templates/csv/mount_options.csv
  rhel6/templates/csv/mount_options.csv
  rhel7/templates/csv/mount_options.csv
  sle11/templates/csv/mount_options.csv
  sle12/templates/csv/mount_options.csv
  tests/data/group_system/group_permissions/group_partitions/partition.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_home_nosuid/fstab.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_tmp_noexec/fstab.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_bind/configured_and_mounted.pass.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_bind/just_configured.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_bind/just_mounted.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_bind/separated_and_mounted.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_bind/wrong_bind.fail.sh
  tests/data/group_system/group_permissions/group_partitions/rule_mount_option_var_tmp_noexec/fstab.fail.sh
  ubuntu1404/templates/csv/mount_options.csv
  ubuntu1604/templates/csv/mount_options.csv
  wrlinux/templates/csv/mount_options.csv
Labels: bugfix

#3350 Remove RHEL STIG overlays in Ubuntu content
  ubuntu1404/overlays/stig_overlay.xml
  ubuntu1604/overlays/stig_overlay.xml
Labels: Infrastructure, bugfix

#3351 Tests and fixes for gnome screensaver lock delay
  shared/bash_remediation_functions/include_dconf_settings.sh
  tests/data/group_system/group_software/group_gnome/dconf_test_functions.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_screen_locking/rule_dconf_gnome_screensaver_lock_enabled/comment.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_screen_locking/rule_dconf_gnome_screensaver_lock_enabled/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_screen_locking/rule_dconf_gnome_screensaver_lock_enabled/correct_value_unlocked.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_screen_locking/rule_dconf_gnome_screensaver_lock_enabled/setting_not_there.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_screen_locking/rule_dconf_gnome_screensaver_lock_enabled/wrong_value.fail.sh
Labels: Bash, SSGTestSuite

#3334 Add test scenarios for privileged_commands_sudo
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_auditctl_4294967295_configured.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_auditctl_unset_configured.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_augenrules_4294967295_configured.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_augenrules_remove_all_rules.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_augenrules_substring_rule.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_augenrules_superstring_rule.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_augenrules_unset_configured.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_privileged_commands/rule_audit_rules_privileged_commands_sudo/rhel7_rules_with_own_key.pass.sh
Labels: SSGTestSuite

#3353 Select missing audit privileged commands rules for OSPP42
  fedora/profiles/ospp.profile
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_crontab/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_umount/rule.yml
  rhel7/profiles/ospp42.profile
Labels: enhancement

#3354 Add Fedora 29 and 30 CPEs
  fedora/cpe/fedora-cpe-dictionary.xml
  fedora/product.yml
Labels: BLOCKER

#3332 Fix regular expression in sssd_memcache_timeout
  linux_os/guide/services/sssd/sssd_memcache_timeout/bash/shared.sh
  linux_os/guide/services/sssd/sssd_memcache_timeout/oval/shared.xml
  tests/data/group_services/group_sssd/rule_sssd_memcache_timeout/wrong_section.fail.sh
Labels: bugfix

#3303 Add missing OSPP FIPS remediations
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/bash/shared.sh
Labels: bugfix

#3331 Finish rule accounts_passwords_pam_faillock_interval for Fedora
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/bash/shared.sh
  shared/bash_remediation_functions/include_set_faillock_option.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/account_missing.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/all_correct.pass.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/all_missing.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/authfail_missing.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/only_password_auth_correct.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/only_system_auth_correct.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/password-auth
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/preauth_missing.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/shared.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/supercompliant_fail_interval.pass.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/system-auth
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/wrong_fail_interval.fail.sh
Labels: bugfix

#3352 Add SSSD rule to enable smart cards and add smart card rules to RHEL7 OSPP
  linux_os/guide/services/sssd/sssd_enable_smartcards/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/bash/shared.sh
  linux_os/guide/services/sssd/sssd_enable_smartcards/oval/shared.xml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  rhel7/profiles/ospp.profile
Labels: enhancement

#3357 Add checks for removals of abrt and sendmail to OSPP
  fedora/profiles/ospp.profile
  fedora/templates/csv/packages_removed.csv
  linux_os/guide/services/base/group.yml
  linux_os/guide/services/base/package_abrt_removed/rule.yml
  linux_os/guide/services/mail/package_sendmail_removed/rule.yml
  rhel7/profiles/ospp42.profile
Labels: enhancement

#3361 Added sysctl kernel parameter rules to RHEL OSPP4.2 and Fedora OSPP
  fedora/profiles/ospp.profile
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_kexec_load_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml
  rhel7/profiles/ospp42.profile
  rhel7/templates/csv/sysctl_values.csv
  tests/data/group_system/group_permissions/group_restrictions/rule_sysctl_kernel_dmesg_restrict/disabled.fail.sh
  tests/data/group_system/group_permissions/group_restrictions/rule_sysctl_kernel_kexec_load_disabled/disabled.fail.sh
  tests/data/group_system/group_permissions/group_restrictions/rule_sysctl_kernel_kptr_restrict/disabled.fail.sh
  tests/data/group_system/group_permissions/group_restrictions/rule_sysctl_kernel_yama_ptrace_scope/disabled.fail.sh
  tests/data/group_system/group_permissions/group_restrictions/sysctl.sh
Labels: BLOCKER

#3362 Fix file permissions for rule_file_permissions_sshd_private_key
  fedora/templates/csv/file_dir_permissions.csv
  rhel7/templates/csv/file_dir_permissions.csv
Labels: bugfix

#3356 Enable OVAL for rule grub2_enable_fips_mode on Fedora
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
Labels: BLOCKER

#3366 Fix an underscore
  shared/bash_remediation_functions/include_set_faillock_option.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_interval/fail_interval_missing.fail.sh
Labels: bugfix

#3367 Initial implementation of the stable profile ID test
  tests/CMakeLists.txt
  tests/stable_profile_ids.py
Labels: enhancement

#3368 Fix Python2.7 and Python2.6 incompatibilities.
  ssg/oval.py
  tests/test_parse_affected.py
Labels: bugfix

#3308 Rule require_singleuser_auth for Fedora
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml
  tests/data/group_system/group_accounts/group_accounts-physical/rule_require_singleuser_auth/correct_value.pass.sh
  tests/data/group_system/group_accounts/group_accounts-physical/rule_require_singleuser_auth/wrong_value.fail.sh
Labels: BLOCKER, enhancement

#3369 Add sysctl kernel parameter rules to Fedora OSPP
  fedora/templates/csv/sysctl_values.csv
  shared/templates/template_BASH_sysctl
Labels: BLOCKER

#3379 Enable OCP3 builds and add C2S rules
  applications/benchmark.yml
  applications/intro/general-principles/group.yml
  applications/intro/general-principles/principle-encrypt-transmitted-data/group.yml
  applications/intro/general-principles/principle-least-privilege/group.yml
  applications/intro/general-principles/principle-separate-servers/group.yml
  applications/intro/general-principles/principle-use-security-tools/group.yml
  applications/intro/group.yml
  applications/intro/how-to-use/group.yml
  applications/intro/how-to-use/intro-formatting-conventions/group.yml
  applications/intro/how-to-use/intro-read-sections-completely/group.yml
  applications/intro/how-to-use/intro-reboot-required/group.yml
  applications/intro/how-to-use/intro-root-shell-assumed/group.yml
  applications/intro/how-to-use/intro-test-non-production/group.yml
  applications/openshift/group.yml
  applications/openshift/ocp-permissions/group.yml
  applications/openshift/ocp-permissions/ocp-files/directory_permissions_etc_origin/rule.yml
  applications/openshift/ocp-permissions/ocp-files/directory_permissions_var_lib_etcd/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_kubeconfig/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_node_config/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_openshift_node_client_crt/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_openshift_node_service/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_owner_node_config/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_owner_node_kubeconfig/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_owner_openshift_node_client_crt/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_owner_openshift_node_service/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_permissions_node_config/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_permissions_node_kubeconfig/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_permissions_openshift_node_client_crt/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_permissions_openshift_node_service/rule.yml
  applications/openshift/ocp-permissions/ocp-files/group.yml
  ocp3/product.yml
  ocp3/profiles/C2S-master.profile
  ocp3/profiles/C2S-node.profile
  ocp3/profiles/opencis-ocp-master.profile
  ocp3/profiles/opencis-ocp-node.profile
  ocp3/templates/csv/file_dir_permissions.csv
Labels: enhancement

#3390 Update platform in OVAL for derivatives
  build-scripts/enable_derivatives.py
  ssg/build_derivatives.py
Labels: bugfix

#3398 Fixed more Python2.6 and Python2.7 incompatibilities.
  ssg/oval.py
  tests/test_parse_platform.py
Labels: bugfix

#3393 Added more stabilized profile IDs
  tests/stable_profile_ids.py
Labels: Infrastructure, enhancement

#3399 Fix permission templates to allow non-existing filename
  shared/templates/create_permissions.py
Labels: bugfix

#3397 Initial k8s scheduler content
  applications/openshift/kubernetes/master/scheduler/address_argument/rule.yml
  applications/openshift/kubernetes/master/scheduler/profiling_argument/rule.yml
  ocp3/profiles/opencis-ocp-master.profile
Labels: enhancement

#3414 Rename scheduler ocp rules
  applications/openshift/scheduler/scheduler_address_argument/rule.yml
  applications/openshift/scheduler/scheduler_profiling_argument/rule.yml
  ocp3/profiles/opencis-ocp-master.profile
Labels: bugfix

#3415 Add etcd rules
  applications/openshift/etcd/etcd_auto_tls/rule.yml
  applications/openshift/etcd/etcd_cert_file/rule.yml
  applications/openshift/etcd/etcd_client_cert_auth/rule.yml
  applications/openshift/etcd/etcd_key_file/rule.yml
  applications/openshift/etcd/etcd_max_wals/rule.yml
  applications/openshift/etcd/etcd_peer_auto_tls/rule.yml
  applications/openshift/etcd/etcd_peer_cert_file/rule.yml
  applications/openshift/etcd/etcd_peer_client_cert_auth/rule.yml
  applications/openshift/etcd/etcd_peer_key_file/rule.yml
  applications/openshift/etcd/etcd_unique_ca/rule.yml
  applications/openshift/etcd/etcd_wal_dir/rule.yml
  applications/openshift/etcd/group.yml
Labels: enhancement
