Repository ComplianceAsCode/content, pull requests merged in 2018-11, with the labels that each got.

#3577 Added ansible-lint and yamllint checks of ansible playbooks into CTest
  BUILD.md
  CMakeLists.txt
  cmake/SSGCommon.cmake
  tests/ansible_playbook_check.sh
  tests/ansible_playbook_syntax_check.sh
  tests/yamllint_config.yml
Labels: Ansible, enhancement

#3589 Fix RHOSP CPE
  rhosp13/cpe/rhosp13-cpe-dictionary.xml
Labels: bugfix

#3590 Add RHV4 Directory structure
  CMakeLists.txt
  rhv4/CMakeLists.txt
  rhv4/checks/oval/.gitkeep
  rhv4/cpe/rhv4-cpe-dictionary.xml
  rhv4/fixes/ansible/.gitkeep
  rhv4/fixes/bash/.gitkeep
  rhv4/overlays/nist800171_support.xml
  rhv4/overlays/nist_support.xml
  rhv4/product.yml
  rhv4/templates/.gitkeep
  rhv4/templates/csv/.gitkeep
  rhv4/transforms/cci2html.xsl
  rhv4/transforms/constants.xslt
  rhv4/transforms/shorthand2xccdf.xslt
  rhv4/transforms/table-add-srgitems.xslt
  rhv4/transforms/table-sortbyref.xslt
  rhv4/transforms/table-srgmap.xslt
  rhv4/transforms/table-style.xslt
  rhv4/transforms/xccdf-apply-overlay-stig.xslt
  rhv4/transforms/xccdf2stigformat.xslt
  rhv4/transforms/xccdf2table-byref.xslt
  rhv4/transforms/xccdf2table-cce.xslt
  rhv4/transforms/xccdf2table-profileccirefs.xslt
  rhv4/transforms/xccdf2table-profilecisrefs.xslt
  rhv4/transforms/xccdf2table-profilenistrefs-cui.xslt
  rhv4/transforms/xccdf2table-profilenistrefs.xslt
  rhv4/transforms/xccdf2table-stig.xslt
  shared/checks/oval/installed_OS_is_rhv4.xml
  shared/checks/oval/installed_app_is_rhv4.xml
  shared/transforms/shared_constants.xslt
  ssg/products.py
Labels: enhancement

#3593 Added Crypto Policy rule for SSH
  fedora/profiles/standard.profile
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_ssh_crypto_policy/absent.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_ssh_crypto_policy/comment.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_ssh_crypto_policy/no_config_file.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_ssh_crypto_policy/overrides.fail.sh
Labels: enhancement

#3595 Fix OVAL error when encryption policy file doesn't exist
  applications/openshift/api-server/api_server_experimental_encryption_provider_cipher/oval/shared.xml
Labels: bugfix

#3594 Added Crypto Policy rule for OpenSSL.
  fedora/profiles/standard.profile
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_openssl_crypto_policy/common.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_openssl_crypto_policy/nothing.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_openssl_crypto_policy/ok.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_openssl_crypto_policy/section_not_include.fail.sh
Labels: enhancement

#3585 Add ocp-node checks to master
  ocp3/profiles/opencis-ocp-master.profile
Labels: bugfix

#3584 Add Crypto Policy for Kerberos
  fedora/profiles/standard.profile
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/ansible/fedora.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/bash/fedora.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_kerberos_crypto_policy/kerberos_correct_policy.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_kerberos_crypto_policy/kerberos_missing_policy.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_kerberos_crypto_policy/kerberos_wrong_policy.fail.sh
Labels: enhancement

#3579 Added Crypto Policy rule for the BIND service.
  Dockerfiles/test_suite-fedora
  fedora/profiles/standard.profile
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_bind_crypto_policy/absent.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_bind_crypto_policy/no_config_file.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_bind_crypto_policy/ok.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_bind_crypto_policy/overrides.fail.sh
Labels: enhancement

#3600 Fix product naming in OCP content
  ocp3/cpe/ocp3-cpe-dictionary.xml
  ocp3/overlays/c2s_support.xml
  ocp3/overlays/nist800171_support.xml
  ocp3/overlays/nist_support.xml
  ocp3/product.yml
  ocp3/transforms/constants.xslt
Labels: bugfix

#3612 Ignore warnings on tasks using rpm shell command
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/ansible/shared.yml
Labels: Ansible, bugfix

#3609 Prefix file permissions to be octal numbers
  fedora/templates/csv/file_dir_permissions.csv
  ol7/templates/csv/file_dir_permissions.csv
  rhel6/templates/csv/file_dir_permissions.csv
  rhel7/templates/csv/file_dir_permissions.csv
  sle12/templates/csv/file_dir_permissions.csv
Labels: Ansible, bugfix

#3580 Added Crypto Policy rule for JRE.
  jre/guide/java/java_jre_configure_crypto_policy/ansible/shared.yml
  jre/guide/java/java_jre_configure_crypto_policy/bash/shared.sh
  jre/guide/java/java_jre_configure_crypto_policy/oval/shared.xml
  jre/guide/java/java_jre_configure_crypto_policy/rule.yml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_java_jre_configure_crypto_policy/commented_out.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_java_jre_configure_crypto_policy/common.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_java_jre_configure_crypto_policy/empty_file.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_java_jre_configure_crypto_policy/false.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_java_jre_configure_crypto_policy/ok.pass.sh
Labels: enhancement

#3608 Fix ansible-lint mount option errors
  shared/templates/template_ANSIBLE_mount_option
  shared/templates/template_ANSIBLE_mount_option_var
Labels: Ansible

#3615 Add aarch64 64-bit OVAL check and add to 64-bit system checks
  shared/checks/oval/system_info_architecture_64bit.xml
  shared/checks/oval/system_info_architecture_aarch_64.xml
Labels: enhancement

#3602 Update configure_crypto_policy rule and add tests for it
  fedora/profiles/standard.profile
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/oval/fedora.xml
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/bad_symlink.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/missing_policy.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/missing_policy_file.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/missing_symlink.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/policy_set.pass.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/symlink_to_wrong_policy.fail.sh
  tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/wrong_policy.fail.sh
Labels: OVAL, SSGTestSuite

#3616 Fix file_permissions generation
  fedora/templates/csv/file_dir_permissions.csv
  ocp3/templates/csv/file_dir_permissions.csv
  rhel6/templates/csv/file_dir_permissions.csv
  rhel7/templates/csv/file_dir_permissions.csv
  shared/templates/create_permissions.py
  shared/templates/template_ANSIBLE_file_regex_permissions
  sle12/templates/csv/file_dir_permissions.csv
Labels: BLOCKER, bugfix

#3606 Fix ANSIBLE0012 in tasks for security mount option in remote filesystems
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/mounting_remote_filesystems/mount_option_krb_sec_remote_filesystems/ansible/shared.yml
  shared/templates/template_ANSIBLE_mount_option_remote_filesystems
Labels: Ansible

#3610 Galaxy Upload script refactoring.
  utils/upload_ansible_roles_to_galaxy.py
Labels: refactoring

#3603 Update ol7 parts of linux_os guide
  linux_os/guide/services/ldap/openldap_client/group.yml
  linux_os/guide/services/mail/group.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/obsolete/telnet/package_telnet_removed/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/group.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_password/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_uefi_password/rule.yml
  linux_os/guide/system/permissions/group.yml
  linux_os/guide/system/selinux/group.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/group.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/group.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_certified/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/group.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/install_hids/rule.yml
  linux_os/guide/system/software/integrity/fips/group.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
Labels: enhancement

#3624 Enable and update kernel_module_loading remediation for RHEL6
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/bash/shared.sh
Labels: bugfix

#3622 Update ensure_redhat_gpgkey_installed for RHEL8
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/oval/shared.xml
Labels: bugfix

#3628 Fix duplicated rhel8 entry in bash remediation metadata
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/bash/shared.sh
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/bash/shared.sh
  linux_os/guide/services/sssd/sssd_enable_smartcards/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_insmod/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_modprobe/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_rmmod/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_tallylog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/bash/shared.sh
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_login_retries/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_guest_login/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_network_settings/dconf_gnome_disable_wifi_create/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_network_settings/dconf_gnome_disable_wifi_notification/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_delay/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_info/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_locks/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_session_idle_user_locks/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/bash/shared.sh
Labels: bugfix

#3607 Fix Ansible remediations to be parseable by oscap
  ssg/build_remediations.py
Labels: bugfix

#3634 Add crypto-policy rules to RHEL8
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/ansible/fedora.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/bash/fedora.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
Labels: enhancement

#3635 Removed a stray print of a profile id.
  ssg/build_derivatives.py
Labels: bugfix
