Repository ComplianceAsCode/content, pull requests merged in 2018-05, with the labels that each got.

#2809 Remove all references for dropped OVALs
  shared/utils/relabel-ids.py
Labels: BLOCKER

#2814 Add benchmark metadata element to shorthand
  shared/utils/yaml-to-shorthand.py
Labels: BLOCKER

#2796 Fix missing elements and description in var_auditd_admin_space_left_action and var_auditd_space_left_action
  shared/guide/system/auditing/configure_auditd_data_retention/var_auditd_admin_space_left_action.var
  shared/guide/system/auditing/configure_auditd_data_retention/var_auditd_space_left_action.var
Labels: enhancement

#2820 Fix dconf_gnome_disable_geolocation script and add missing dconf remedation scripts
  shared/fixes/bash/dconf_gnome_disable_geolocation.sh
  shared/fixes/bash/dconf_gnome_disable_wifi_create.sh
  shared/fixes/bash/dconf_gnome_disable_wifi_notification.sh
Labels: bugfix

#2822 Bump version to 0.1.40
  CMakeLists.txt
Labels: Infrastructure

#2804 Find shadowed files
  shared/misc/find_shadowed_files.py
Labels: Infrastructure, refactoring

#2826 Change DRAFT marker in Profile titles
  rhel7/profiles/C2S-docker.profile
  rhel7/profiles/anssi_nt28_enhanced.profile
  rhel7/profiles/anssi_nt28_high.profile
  rhel7/profiles/anssi_nt28_intermediary.profile
  rhel7/profiles/anssi_nt28_minimal.profile
  rhel7/profiles/docker-host.profile
  rhel7/profiles/ospp42-draft.profile
  rhel7/profiles/pci-dss.profile
  rhel7/profiles/stig-ansible-tower-upstream.profile
  rhel7/profiles/stig-http-disa.profile
  rhel7/profiles/stig-ipa-server-upstream.profile
  rhel7/profiles/stig-rhvh-upstream.profile
  rhel7/profiles/stig-satellite-upstream.profile
Labels: bugfix

#2827 Fix Kdump Anaconda script typo
  shared/fixes/anaconda/service_kdump_disabled.anaconda
Labels: bugfix

#2819 Add mcafee_antivirus_definitions_updated OVAL and XCCDF variable
  rhel7/profiles/stig-rhel7-disa.profile
  shared/checks/oval/mcafee_antivirus_definitions_updated.xml
  shared/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/var_mcafee_antivirus_definition_expire.var
Labels: enhancement

#2829 add missing python-jinja2 PyYAML
  Dockerfile
Labels: bugfix

#2828 Untemplatize package_dracut-fips_installed as passing check can denote FIPS certification
  shared/checks/oval/package_dracut-fips_installed.xml
  shared/templates/csv/packages_installed.csv
Labels: bugfix

#2844 Add warnings into YAML
  shared/guide/system/accounts/accounts-restrictions/password_expiration/var_accounts_password_minlen_login_defs.var
  shared/guide/system/software/integrity/fips/package_dracut-fips_installed.rule
  shared/utils/yaml-to-shorthand.py
Labels: bugfix

#2845 Fix broken Python 3 build
  shared/utils/yaml-to-shorthand.py
Labels: Infrastructure, bugfix

#2848 Install PyYAML and python-jinja2 for centos CI
  .cico.yaml
Labels: bugfix

#2846 Do not depend on Python 2
  CMakeLists.txt
Labels: Infrastructure

#2847 Rewrite and reformat BUILD.md
  BUILD.md
Labels: documentation

#2853 Output on ctest failure when running on CentOS CI
  .cico.yaml
Labels: enhancement

#2864 Sysctl unification2
  debian8/templates/template_OVAL_sysctl_static
  debian8/templates/template_OVAL_sysctl_static_var
  rhel7/templates/template_OVAL_sysctl_static
  rhel7/templates/template_OVAL_sysctl_static_var
  shared/templates/template_OVAL_sysctl_static
  shared/templates/template_OVAL_sysctl_static_var
  sle12/templates/template_OVAL_sysctl_static
  sle12/templates/template_OVAL_sysctl_static_var
  ubuntu1404/templates/template_OVAL_sysctl_static
  ubuntu1404/templates/template_OVAL_sysctl_static_var
  ubuntu1604/templates/template_OVAL_sysctl_static
  ubuntu1604/templates/template_OVAL_sysctl_static_var
Labels: refactoring

#2854 Added a build system schema to illustrate what SSG is about
  README.md
  docs/readme_images/build_schema.svg
Labels: documentation

#2868 Fix link to reference documentation for PAM configuration file
  rhel6/guide/system/accounts/accounts-pam/accounts-pam.group
  shared/guide/system/accounts/accounts-pam/accounts-pam.group
Labels: bugfix

#2865 Removed redundant template_BASH_package_removed
  debian8/templates/template_BASH_package_removed
  ubuntu1404/templates/template_BASH_package_removed
  ubuntu1604/templates/template_BASH_package_removed
Labels: refactoring

#2874 Unified the sysctl_ipv6 templates
  rhel6/templates/template_OVAL_sysctl_ipv6
  rhel7/templates/template_OVAL_sysctl_ipv6
  shared/templates/template_OVAL_sysctl_ipv6
  sle12/templates/template_OVAL_sysctl_ipv6
  ubuntu1404/templates/template_OVAL_sysctl_ipv6
  ubuntu1604/templates/template_OVAL_sysctl_ipv6
Labels: refactoring

#2879 Ansible service result deprecation warning
  shared/templates/template_ANSIBLE_service_disabled
  shared/utils/build-all-remediation-roles.py
Labels: ansible
