Repository ComplianceAsCode/content, pull requests merged in 2018-02, with the labels that each got.

#2588 Fix Ansible remediations broken by Ansible bug.
  shared/fixes/ansible/dconf_gnome_banner_enabled.yml
  shared/fixes/ansible/dconf_gnome_disable_automount.yml
  shared/fixes/ansible/dconf_gnome_disable_geolocation.yml
  shared/fixes/ansible/dconf_gnome_disable_restart_shutdown.yml
  shared/fixes/ansible/dconf_gnome_disable_thumbnailers.yml
  shared/fixes/ansible/dconf_gnome_disable_user_admin.yml
  shared/fixes/ansible/dconf_gnome_disable_user_list.yml
  shared/fixes/ansible/dconf_gnome_disable_wifi_create.yml
  shared/fixes/ansible/dconf_gnome_disable_wifi_notification.yml
  shared/fixes/ansible/dconf_gnome_screensaver_idle_activation_enabled.yml
  shared/fixes/ansible/dconf_gnome_screensaver_lock_enabled.yml
  shared/fixes/ansible/dconf_gnome_screensaver_user_info.yml
  shared/fixes/ansible/gnome_gdm_disable_automatic_login.yml
  shared/fixes/ansible/gnome_gdm_disable_guest_login.yml
Labels: bugfix

#2611 It's HIPAA, not HIPPA
  rhel7/guide.xslt
  rhel7/profiles/hipaa.xml
  shared/transforms/shared_constants.xslt
  shared/transforms/shared_shorthand2xccdf.xslt
  shared/xccdf/system/software/disk_partitioning.xml
Labels: bugfix

#2546 Script to auto-upload / update ansible galaxy roles from SSG
  shared/misc/ansible_galaxy_meta_template.yml
  shared/misc/ansible_galaxy_readme_template.md
  shared/misc/upload_ansible_roles_to_galaxy.py
  shared/modules/ssgcommon.py
  shared/utils/build-all-remediation-roles.py
Labels: Infrastructure, ansible

#2615 Enable correct ansible templte for file modification audit rules
  shared/templates/create_audit_rules_unsuccessful_file_modification.py
Labels: bugfix

#2627 Tests for ctrlaltdel burstaction and audit rules time
  tests/data/group_system/group_accounts/group_accounts-physical/rule_disable_ctrlaltdel_burstaction/correct_value.pass.sh
  tests/data/group_system/group_accounts/group_accounts-physical/rule_disable_ctrlaltdel_burstaction/line_not_there.fail.sh
  tests/data/group_system/group_accounts/group_accounts-physical/rule_disable_ctrlaltdel_burstaction/wrong_value.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_adjtimex/correct_value.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_adjtimex/line_not_there.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_settimeofday/correct_value.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_settimeofday/line_not_there.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_stime/correct_value.pass.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_time_rules/rule_audit_rules_time_stime/line_not_there.fail.sh
Labels: SSGTestSuite

#2628 Fixes #2607 - audit_rules_login_events
  shared/templates/create_audit_rules_login_events.py
  shared/templates/csv/audit_rules_login_events.csv
Labels: bugfix

#2630 Add tests for accounts_passwords_pam_faillock_deny
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/config_without_skip.pass.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/default_die_pam_unix.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/disablefaillock_authconfig.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_default_die_pam_unix
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_skip_correctly
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_skip_correctly_short
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_skip_longer
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_skip_longer_comment
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/pam_config_without_skip
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/skip_correctly.pass.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/skip_correctly_short.pass.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/skip_longer.fail.sh
  tests/data/group_system/group_accounts/group_accounts-pam/group_locking_out_password_attempts/rule_accounts_passwords_pam_faillock_deny/skip_longer_comment.fail.sh
Labels: SSGTestSuite

#2633 Introduced draft of SSG Bash scripting guidelines.
  docs/manual/developer_guide.adoc
  shared/bash_remediation_functions/die.sh
Labels: enhancement

#2634 Glob source xccdf files recursively
  cmake/SSGCommon.cmake
Labels: Infrastructure, bugfix

#2635 This is a shorthand XCCDF, not the actual XCCDF 1.1, the xmlns makes …
  chromium/profiles/stig-chromium-upstream.xml
  firefox/profiles/stig-firefox-upstream.xml
  jre/profiles/stig-java-upstream.xml
  rhel6/profiles/pci-dss.xml
  rhel6/profiles/rht-ccp.xml
  rhel7/profiles/pci-dss.xml
  rhel7/profiles/rht-ccp.xml
  rhevm3/profiles/stig-rhevm3.xml
  webmin/profiles/common.xml
Labels: bugfix
