Repository ComplianceAsCode/content, pull requests merged in 2018-03, with the labels that each got.

#2614 Fix kernel module loading and unloading rules
  shared/fixes/bash/audit_rules_kernel_module_loading.sh
  shared/fixes/bash/audit_rules_kernel_module_loading_delete.sh
  shared/fixes/bash/audit_rules_kernel_module_loading_init.sh
  shared/xccdf/system/auditing.xml
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading_delete/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading_init/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading_insmod/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading_modprobe/default.fail.sh
  tests/data/group_system/group_auditing/group_auditd_configure_rules/group_audit_kernel_module_loading/rule_audit_rules_kernel_module_loading_rmmod/default.fail.sh
Labels: bugfix

#2422 Add initial C2S Docker Profile
  rhel7/guide.xslt
  rhel7/profiles/C2S-docker.xml
Labels: enhancement

#2641 Add override to C2S-docker Profile
  rhel7/profiles/C2S-docker.xml
Labels: bugfix

#2643 Fix install of PCI-DSS centric HTML guides
  cmake/SSGCommon.cmake
Labels: Infrastructure, bugfix

#2644 Fix a mismatched tag issue in RHEL6 sudo.xml
  rhel6/xccdf/system/software/sudo.xml
Labels: bugfix

#2645 Moved the .gitkeep file to where the author most likely intended it
  debian8/overlays/.gitkeep
Labels: bugfix

#2646 Chromium XCCDF was in shared even though it uses nothing else from sh…
  chromium/guide.xslt
  chromium/xccdf/chromium.xml
Labels: bugfix

#2647 Moved firefox shorthand XML to the firefox product folder from shared
  firefox/guide.xslt
  firefox/xccdf/firefox.xml
Labels: bugfix

#2648 Untangle shared shorthands
  jboss_eap6/guide.xslt
  jboss_eap6/xccdf/eap6.xml
  jboss_fuse6/guide.xslt
  jboss_fuse6/xccdf/amq.xml
  jboss_fuse6/xccdf/camel.xml
  jboss_fuse6/xccdf/cxf.xml
  jboss_fuse6/xccdf/fuse6.xml
  jboss_fuse6/xccdf/karaf.xml
  jboss_fuse6/xccdf/policy.xml
  jre/guide.xslt
  jre/xccdf/java.xml
Labels: bugfix

#2652 eaccess should actually be eacces
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
Labels: bugfix

#2650 Hippaaahhh
  rhel7/profiles/hipaa.xml
  shared/xccdf/services/base.xml
  shared/xccdf/services/cron.xml
  shared/xccdf/services/nfs.xml
  shared/xccdf/services/obsolete.xml
  shared/xccdf/services/quagga.xml
  shared/xccdf/services/ssh.xml
  shared/xccdf/system/accounts/physical.xml
  shared/xccdf/system/accounts/restrictions/password_storage.xml
  shared/xccdf/system/accounts/restrictions/root_logins.xml
  shared/xccdf/system/auditing.xml
  shared/xccdf/system/logging.xml
  shared/xccdf/system/network/ipsec.xml
  shared/xccdf/system/permissions/execution.xml
  shared/xccdf/system/permissions/mounting.xml
  shared/xccdf/system/selinux.xml
  shared/xccdf/system/software/disk_partitioning.xml
  shared/xccdf/system/software/gnome.xml
  shared/xccdf/system/software/integrity.xml
  shared/xccdf/system/software/updating.xml
Labels: enhancement

#2653 Removed duplicate sudo related selects in rhel7's HIPAA
  rhel7/profiles/hipaa.xml
Labels: BLOCKER, bugfix

#2659 RHEL6 to only use its local shorthand content
  rhel6/guide.xslt
  rhel6/xccdf/services/sssd.xml
  rhel6/xccdf/system/accounts/accounts.xml
  rhel6/xccdf/system/accounts/restrictions/restrictions.xml
  rhel6/xccdf/system/permissions/permissions.xml
  rhel6/xccdf/system/software/software.xml
Labels: bugfix

#2661 Source only local shorthand XCCDF to build debian8 content
  debian8/guide.xslt
  debian8/xccdf/system/accounts/accounts.xml
  debian8/xccdf/system/accounts/restrictions/restrictions.xml
  debian8/xccdf/system/permissions/permissions.xml
  debian8/xccdf/system/software/software.xml
Labels: bugfix

#2669 Add test scenarios for aide_scan_notification
  tests/data/group_system/group_software/group_integrity/group_software-integrity/group_aide/rule_aide_scan_notification/cron_weekly_configured.pass.sh
  tests/data/group_system/group_software/group_integrity/group_software-integrity/group_aide/rule_aide_scan_notification/crontab_configured.pass.sh
  tests/data/group_system/group_software/group_integrity/group_software-integrity/group_aide/rule_aide_scan_notification/crontab_just_periodic_checking.fail.sh
  tests/data/group_system/group_software/group_integrity/group_software-integrity/group_aide/rule_aide_scan_notification/default.fail.sh
  tests/data/group_system/group_software/group_integrity/group_software-integrity/group_aide/rule_aide_scan_notification/var_cron_configured.pass.sh
Labels: SSGTestSuite

#2670 Initial OSPP v4.2 draft profile
  rhel7/guide.xslt
  shared/references/cce-rhel-avail.txt
  shared/transforms/shared_constants.xslt
  shared/transforms/shared_shorthand2xccdf.xslt
  shared/transforms/shared_xccdf2table-byref.xslt
  shared/xccdf/services/ssh.xml
  shared/xccdf/services/sssd.xml
  shared/xccdf/system/accounts/banners.xml
  shared/xccdf/system/accounts/pam.xml
  shared/xccdf/system/accounts/physical.xml
  shared/xccdf/system/accounts/restrictions/password_expiration.xml
  shared/xccdf/system/accounts/restrictions/password_storage.xml
  shared/xccdf/system/accounts/session.xml
  shared/xccdf/system/auditing.xml
  shared/xccdf/system/logging.xml
  shared/xccdf/system/network/firewalld.xml
  shared/xccdf/system/software/gnome.xml
  shared/xccdf/system/software/updating.xml
Labels: RHEL7

#2673 Change ID of Rule that checks for IPV6 disabled
  rhel7/profiles/C2S.xml
  rhel7/profiles/ospp-rhel7.xml
  rhel7/profiles/rht-ccp.xml
  shared/xccdf/system/network/ipv6.xml
Labels: bugfix

#2676 remediation functions xml is no longer in shared
  chromium/guide.xslt
  firefox/guide.xslt
  jre/guide.xslt
Labels: bugfix

#2680 Add disabled OVAL 5.11 services for SSHD for OpenSUSE
  opensuse/templates/csv/oval_5.11/services_disabled.csv
  opensuse/templates/oval_5.11_templates/template_OVAL_service_disabled
Labels: bugfix

#2681 Added the forgotted ospp42 profile
  rhel7/profiles/ospp42-draft-rhel7.xml
Labels: BLOCKER, bugfix

#2689 Further improved replace_or_append
  shared/bash_remediation_functions/replace_or_append.sh
Labels: enhancement

#2690 Remove the dumper scripts
  rhel7/profiles/dump_profiles.py
  shared/guide/dump_shorthand.py
Labels: enhancement

#2695 Configure python interpreter
  CMakeLists.txt
  cmake/SSGCommon.cmake
  shared/templates/template_common.py
Labels: Infrastructure

#2694 shorthand.xml target should depend on the yaml-to-shorthand script
  cmake/SSGCommon.cmake
Labels: Infrastructure

#2692 Force SSG developers to put product code into the right folders
  cmake/SSGCommon.cmake
Labels: enhancement

#2697 Make it possible to build SSG with python3
  shared/utils/add_stig_references.py
  shared/utils/build-all-guides.py
  shared/utils/build-all-remediation-roles.py
  shared/utils/combine-ovals.py
  shared/utils/combine-remediations.py
  shared/utils/cpe-generate.py
  shared/utils/enable-derivatives.py
  shared/utils/generate-bash-remediation-functions.py
  shared/utils/yaml-to-shorthand.py
Labels: Infrastructure

#2699 Added print function support for Python2 where applicable.
  shared/utils/add_stig_references.py
  shared/utils/build-all-guides.py
  shared/utils/build-all-remediation-roles.py
  shared/utils/cpe-generate.py
  shared/utils/create-stig-overlay.py
  shared/utils/enable-derivatives.py
  shared/utils/generate-from-templates.py
  shared/utils/profile-stats.py
  shared/utils/relabel-ids.py
  shared/utils/sds-move-ocil-to-checks.py
  shared/utils/unselect-empty-xccdf-groups.py
  shared/utils/verify-input-sanity.py
  shared/utils/verify-references.py
  shared/utils/yaml-to-shorthand.py
Labels: Infrastructure

#2688 Tests and OVAL fix for Rule sssd_enable_pam_services
  shared/checks/oval/sssd_enable_pam_services.xml
  shared/fixes/bash/sssd_enable_pam_services.sh
  tests/data/group_services/group_sssd/rule_sssd_enable_pam_services/services_pam_missing.fail.sh
  tests/data/group_services/group_sssd/rule_sssd_enable_pam_services/services_pam_wrong_section.fail.sh
  tests/data/group_services/group_sssd/rule_sssd_enable_pam_services/sssd_pam_services.pass.sh
  tests/data/group_services/group_sssd/rule_sssd_enable_pam_services/wrong_sssd.conf
Labels: SSGTestSuite
