Repository ComplianceAsCode/content, pull requests merged in 2018-04, with the labels that each got.

#2701 Update build instructions to include PyYAML
  BUILD.md
Labels: BLOCKER, bugfix

#2712 Remove ignore option for auditing configuration
  shared/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action.rule
  shared/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left_action.rule
  shared/guide/system/auditing/configure_auditd_data_retention/var_audispd_disk_full_action.var
  shared/guide/system/auditing/configure_auditd_data_retention/var_audispd_network_failure_action.var
  shared/guide/system/auditing/configure_auditd_data_retention/var_auditd_admin_space_left_action.var
  shared/guide/system/auditing/configure_auditd_data_retention/var_auditd_max_log_file_action.var
  shared/guide/system/auditing/configure_auditd_data_retention/var_auditd_space_left_action.var
Labels: bugfix

#2725 Extra Apache STIG rules
  rhel7/profiles/stig-http-disa.profile
  shared/guide/services/http/securing_httpd/httpd_configure_log_format.rule
  shared/guide/services/http/securing_httpd/httpd_configure_max_keepalive_requests.rule
  shared/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_antivirus_scan_uploads.rule
  shared/guide/services/http/securing_httpd/httpd_configure_os_protect_web_server/httpd_restrict_file_dir_access/http_configure_log_file_ownership.rule
  shared/guide/services/http/securing_httpd/httpd_configure_perl_securely/httpd_configure_perl_taint.rule
  shared/guide/services/http/securing_httpd/httpd_directory_restrictions/httpd_anonymous_content_sharing.rule
  shared/guide/services/http/securing_httpd/httpd_directory_restrictions/httpd_configure_script_permissions.rule
  shared/guide/services/http/securing_httpd/httpd_directory_restrictions/httpd_disable_anonymous_ftp_access.rule
  shared/guide/services/http/securing_httpd/httpd_directory_restrictions/httpd_ignore_htaccess_files.rule
  shared/guide/services/http/securing_httpd/httpd_disable_mime_types.rule
  shared/guide/services/http/securing_httpd/httpd_enable_error_logging.rule
  shared/guide/services/http/securing_httpd/httpd_enable_loglevel.rule
  shared/guide/services/http/securing_httpd/httpd_enable_system_logging.rule
  shared/guide/services/http/securing_httpd/httpd_entrust_passwords.rule
  shared/guide/services/http/securing_httpd/httpd_minimize_loadable_modules/httpd_core_modules/httpd_enable_log_config.rule
  shared/guide/services/http/securing_httpd/httpd_modules_improve_security/httpd_deploy_mod_ssl/httpd_configure_tls.rule
  shared/guide/services/http/securing_httpd/httpd_modules_improve_security/httpd_deploy_mod_ssl/httpd_configure_valid_server_cert.rule
  shared/guide/services/http/securing_httpd/httpd_modules_improve_security/httpd_deploy_mod_ssl/httpd_require_client_certs.rule
  shared/guide/services/http/securing_httpd/httpd_nipr_accredited_dmz.rule
  shared/guide/services/http/securing_httpd/httpd_no_compilers_in_prod.rule
  shared/guide/services/http/securing_httpd/httpd_private_server_on_separate_subnet.rule
  shared/guide/services/http/securing_httpd/httpd_public_resources_not_shared.rule
  shared/guide/services/http/securing_httpd/httpd_remove_backups.rule
  shared/references/cce-rhel-avail.txt
Labels: enhancement

#2723 aide cron flex
  shared/checks/oval/aide_periodic_cron_checking.xml
Labels: enhancement

#2743 Fix typo in set_faillock_option_to_value_in_pam_file.sh
  shared/bash_remediation_functions/set_faillock_option_to_value_in_pam_file.sh
Labels: bugfix

#2746 Add Docker SELinux check in daemon.json
  rhel7/checks/oval/docker_selinux_enabled.xml
Labels: enhancement

#2711 Apply elements with relevant prodtype when generating xccdf xml
  shared/transforms/shared_shorthand2xccdf.xslt
Labels: Infrastructure, bugfix

#2730 OL7 standard profile extra rules
  ol7/profiles/standard.profile
  ol7/templates/csv/mount_options.csv
  shared/fixes/ansible/rpm_verify_hashes.yml
  shared/fixes/bash/rpm_verify_permissions.sh
  shared/guide/system/permissions/partitions/mount_option_dev_shm_nodev.rule
  shared/guide/system/permissions/partitions/mount_option_dev_shm_nosuid.rule
  shared/templates/template_ANACONDA_mount_options
Labels: enhancement

#2744 Not escaping / character breaks perform_audit_rules_privileged_commands_remediation.sh
  shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh
Labels: bugfix

#2749 Fix accounts_passwords_pam_faillock_deny.sh script
  shared/fixes/bash/accounts_passwords_pam_faillock_deny.sh
Labels: bugfix

#2750 Add missing rpm_verify_ownership bash script
  shared/fixes/bash/rpm_verify_ownership.sh
Labels: bugfix, enhancement

#2760 Update RHEL 6 STIG Reference to V1R18
  rhel6/CMakeLists.txt
  shared/references/disa-stig-rhel6-v1r18-xccdf-manual.xml
Labels: bugfix

#2764 Add Anaconda Kdump disable script
  shared/fixes/anaconda/service_kdump_disable.anaconda
Labels: enhancement

#2745 Simplify display_login_attempts remediation script logic
  shared/fixes/bash/display_login_attempts.sh
Labels: bugfix

#2737 Don't load yaml booleans as python booleans
  shared/utils/yaml-to-shorthand.py
Labels: bugfix

#2771 Document minimum Ansible version in User/Developer Guides
  docs/manual/developer_guide.adoc
  docs/manual/user_guide.adoc
Labels: bugfix

#2773 Add create_module and finit_module scripts
  shared/fixes/bash/audit_rules_kernel_module_loading_create.sh
  shared/fixes/bash/audit_rules_kernel_module_loading_finit.sh
Labels: bugfix

#2742 When enabling FIPS, set boot= arg using /boot UUID.
  rhel7/fixes/bash/grub2_enable_fips_mode.sh
Labels: bugfix

#2772 Extended definitions contribute their variables
  shared/modules/parse_oval.py
  shared/utils/relabel-ids.py
Labels: bugfix

#2776 rhel7: fix titles/descriptions, indicate draft status (rebase of #2717)
  rhel7/profiles/C2S-docker.profile
  rhel7/profiles/anssi_nt28_enhanced.profile
  rhel7/profiles/anssi_nt28_high.profile
  rhel7/profiles/anssi_nt28_intermediary.profile
  rhel7/profiles/anssi_nt28_minimal.profile
  rhel7/profiles/docker-host.profile
  rhel7/profiles/ospp42-draft.profile
  rhel7/profiles/pci-dss.profile
  rhel7/profiles/rht-ccp.profile
  rhel7/profiles/stig-ansible-tower-upstream.profile
  rhel7/profiles/stig-http-disa.profile
  rhel7/profiles/stig-ipa-server-upstream.profile
  rhel7/profiles/stig-rhel7-disa.profile
  rhel7/profiles/stig-rhvh-upstream.profile
  rhel7/profiles/stig-satellite-upstream.profile
Labels: bugfix

#2781 Unify sshd disable empty passwords
  rhel6/fixes/bash/sshd_disable_empty_passwords.sh
  rhel7/fixes/bash/sshd_disable_empty_passwords.sh
  shared/fixes/bash/sshd_disable_empty_passwords.sh
Labels: enhancement

#2775 Require the python yaml module, fatal error if it's not found
  CMakeLists.txt
  cmake/FindPythonModule.cmake
Labels: enhancement

#2787 Template ubuntu packages
  ubuntu1404/fixes/bash/package_auditd_installed.sh
  ubuntu1404/fixes/bash/package_cron_installed.sh
  ubuntu1404/fixes/bash/package_inetutils-telnetd_removed.sh
  ubuntu1404/fixes/bash/package_nis_removed.sh
  ubuntu1404/fixes/bash/package_ntp_installed.sh
  ubuntu1404/fixes/bash/package_ntpd_installed.sh
  ubuntu1404/fixes/bash/package_ntpdate_removed.sh
  ubuntu1404/fixes/bash/package_rsh-client_removed.sh
  ubuntu1404/fixes/bash/package_rsh-server_removed.sh
  ubuntu1404/fixes/bash/package_rsyslog_installed.sh
  ubuntu1404/fixes/bash/package_talk_removed.sh
  ubuntu1404/fixes/bash/package_talkd_removed.sh
  ubuntu1404/fixes/bash/package_telnetd-ssl_removed.sh
  ubuntu1404/fixes/bash/package_telnetd_removed.sh
  ubuntu1404/templates/csv/oval_5.11/packages_installed.csv
  ubuntu1404/templates/csv/packages_installed.csv
  ubuntu1404/templates/csv/packages_removed.csv
  ubuntu1604/fixes/bash/package_auditd_installed.sh
  ubuntu1604/fixes/bash/package_cron_installed.sh
  ubuntu1604/fixes/bash/package_inetutils-telnetd_removed.sh
  ubuntu1604/fixes/bash/package_nis_removed.sh
  ubuntu1604/fixes/bash/package_ntp_installed.sh
  ubuntu1604/fixes/bash/package_ntpd_installed.sh
  ubuntu1604/fixes/bash/package_ntpdate_removed.sh
  ubuntu1604/fixes/bash/package_rsh-client_removed.sh
  ubuntu1604/fixes/bash/package_rsh-server_removed.sh
  ubuntu1604/fixes/bash/package_rsyslog_installed.sh
  ubuntu1604/fixes/bash/package_talk_removed.sh
  ubuntu1604/fixes/bash/package_talkd_removed.sh
  ubuntu1604/fixes/bash/package_telnetd-ssl_removed.sh
  ubuntu1604/fixes/bash/package_telnetd_removed.sh
  ubuntu1604/templates/csv/oval_5.11/packages_installed.csv
  ubuntu1604/templates/csv/packages_installed.csv
  ubuntu1604/templates/csv/packages_removed.csv
Labels: Infrastructure, enhancement

#2765 Add dconf functions for fix scripts
  shared/bash_remediation_functions/dconf_lock.sh
  shared/bash_remediation_functions/dconf_settings.sh
Labels: enhancement

#2790 Don't exit with 0 when product.yml loading fails
  shared/utils/yaml-to-shorthand.py
Labels: bugfix

#2795 Add Missing DISA RHEL7 STIG XCCDF rules
  rhel7/profiles/stig-rhel7-disa.profile
  shared/checks/oval/dconf_gnome_screensaver_idle_activation_locked.xml
  shared/checks/oval/dconf_gnome_screensaver_lock_locked.xml
  shared/fixes/bash/dconf_gnome_screensaver_idle_activation_locked.sh
  shared/fixes/bash/dconf_gnome_screensaver_lock_locked.sh
  shared/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_locked.rule
  shared/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_locked.rule
  shared/references/cce-rhel-avail.txt
Labels: bugfix

#2789 Add external content to yaml
  shared/guide/system/software/updating/security_patches_up_to_date.rule
  shared/utils/yaml-to-shorthand.py
Labels: BLOCKER, bugfix

#2792 Make sure that dconf dirs exist
  shared/bash_remediation_functions/dconf_lock.sh
  shared/bash_remediation_functions/dconf_settings.sh
Labels: bugfix

#2783 jinja2 for fixes, checks and the opencontrol yaml
  CMakeLists.txt
  chromium/product.yml
  cmake/SSGCommon.cmake
  debian8/product.yml
  debian8/templates/oval_5.11_templates/template_OVAL_package_installed
  debian8/templates/template_OVAL_package_installed
  debian8/templates/template_OVAL_package_removed
  eap6/product.yml
  fedora/product.yml
  fedora/templates/template_OVAL_package_installed
  fedora/templates/template_OVAL_package_removed
  firefox/product.yml
  fuse6/product.yml
  jre/product.yml
  ol7/product.yml
  ol7/templates/template_OVAL_package_installed
  ol7/templates/template_OVAL_package_removed
  opensuse/product.yml
  opensuse/templates/template_OVAL_package_installed
  rhel-osp7/product.yml
  rhel-osp7/templates/oval_5.11_templates/template_OVAL_package_installed
  rhel-osp7/templates/oval_5.11_templates/template_OVAL_package_removed
  rhel6/product.yml
  rhel6/templates/template_OVAL_package_installed
  rhel6/templates/template_OVAL_package_removed
  rhel7/product.yml
  rhel7/templates/template_OVAL_package_installed
  rhel7/templates/template_OVAL_package_removed
  shared/guide/system/software/updating/security_patches_up_to_date.rule
  shared/modules/ssgcommon.py
  shared/templates/template_OVAL_package_installed
  shared/templates/template_OVAL_package_removed
  shared/utils/combine-ovals.py
  shared/utils/combine-remediations.py
  shared/utils/yaml-to-shorthand.py
  sle11/product.yml
  sle12/product.yml
  sle12/templates/template_OVAL_package_removed
  ubuntu1404/product.yml
  ubuntu1404/templates/oval_5.11_templates/template_OVAL_package_installed
  ubuntu1404/templates/template_OVAL_package_installed
  ubuntu1404/templates/template_OVAL_package_removed
  ubuntu1604/product.yml
  ubuntu1604/templates/oval_5.11_templates/template_OVAL_package_installed
  ubuntu1604/templates/template_OVAL_package_installed
  ubuntu1604/templates/template_OVAL_package_removed
  wrlinux/product.yml
Labels: Infrastructure, enhancement

#2797 Add regex handling for SRG and STIG reference versions in CMake
  cmake/SSGCommon.cmake
  eap6/CMakeLists.txt
  ocp3/CMakeLists.txt
  rhel6/CMakeLists.txt
  rhel7/CMakeLists.txt
Labels: enhancement

#2799 Add python jinja2 package to build doc
  BUILD.md
Labels: bugfix

#2793 Remove disabling all usb devices in kernel for OSPP and HIPAA profile
  rhel7/profiles/hipaa.profile
  rhel7/profiles/ospp.profile
Labels: bugfix

#2791 Use new dconf bash functions for bash scripts and add some missing dconf scripts
  rhel7/fixes/bash/dconf_gnome_screensaver_idle_activation_enabled.sh
  rhel7/fixes/bash/dconf_gnome_screensaver_idle_delay.sh
  rhel7/fixes/bash/dconf_gnome_screensaver_lock_enabled.sh
  rhel7/fixes/bash/dconf_gnome_screensaver_mode_blank.sh
  shared/fixes/bash/dconf_gnome_banner_enabled.sh
  shared/fixes/bash/dconf_gnome_disable_automount.sh
  shared/fixes/bash/dconf_gnome_disable_ctrlaltdel_reboot.sh
  shared/fixes/bash/dconf_gnome_disable_geolocation.sh
  shared/fixes/bash/dconf_gnome_disable_restart_shutdown.sh
  shared/fixes/bash/dconf_gnome_disable_thumbnailers.sh
  shared/fixes/bash/dconf_gnome_disable_user_admin.sh
  shared/fixes/bash/dconf_gnome_disable_user_list.sh
  shared/fixes/bash/dconf_gnome_enable_smartcard_auth.sh
  shared/fixes/bash/dconf_gnome_login_banner_text.sh
  shared/fixes/bash/dconf_gnome_login_retries.sh
  shared/fixes/bash/dconf_gnome_remote_access_credential_prompt.sh
  shared/fixes/bash/dconf_gnome_remote_access_encryption.sh
  shared/fixes/bash/dconf_gnome_screensaver_idle_activation_enabled.sh
  shared/fixes/bash/dconf_gnome_screensaver_idle_delay.sh
  shared/fixes/bash/dconf_gnome_screensaver_lock_delay.sh
  shared/fixes/bash/dconf_gnome_screensaver_lock_enabled.sh
  shared/fixes/bash/dconf_gnome_screensaver_mode_blank.sh
  shared/fixes/bash/dconf_gnome_screensaver_user_info.sh
  shared/fixes/bash/dconf_gnome_screensaver_user_locks.sh
  shared/fixes/bash/dconf_gnome_session_idle_user_locks.sh
Labels: bugfix, enhancement

#2800 Use yaml.safe_load for build related yaml files
  shared/modules/ssgcommon.py
Labels: enhancement

#2807 testoval_module.py not processing oval version correctly
  shared/modules/testoval_module.py
Labels: bugfix

#2803 Add minimum package version check with jinja2 template
  ol7/profiles/sap.profile
  ol7/templates/csv/packages_installed.csv
  shared/guide/system/software/sap/package_glibc_installed.rule
  shared/templates/create_package_installed.py
  shared/templates/template_OVAL_package_installed
Labels: enhancement

#2794 Fix sudo audit rules
  shared/templates/template_BASH_audit_rules_privileged_commands
Labels: bugfix

#2786 Package command apt get
  debian8/templates/oval_5.11_templates/template_BASH_package_installed
  debian8/templates/template_BASH_package_installed
  fedora/templates/template_BASH_package_removed
  opensuse/templates/template_BASH_package_removed
  rhel7/fixes/bash/grub2_enable_fips_mode.sh
  rhel7/fixes/bash/service_chronyd_or_ntpd_enabled.sh
  rhel7/fixes/bash/smartcard_auth.sh
  shared/bash_remediation_functions/package_command.sh
  shared/bash_remediation_functions/package_install.sh
  shared/bash_remediation_functions/package_remove.sh
  shared/fixes/bash/aide_build_database.sh
  shared/fixes/bash/aide_periodic_cron_checking.sh
  shared/fixes/bash/aide_scan_notification.sh
  shared/fixes/bash/aide_use_fips_hashes.sh
  shared/fixes/bash/aide_verify_acls.sh
  shared/fixes/bash/aide_verify_ext_attributes.sh
  shared/fixes/bash/configure_firewalld_ports.sh
  shared/fixes/bash/install_smartcard_packages.sh
  shared/templates/template_BASH_package_installed
  shared/templates/template_BASH_package_removed
  ubuntu1404/templates/template_BASH_package_installed
  ubuntu1604/templates/template_BASH_package_installed
Labels: Infrastructure, enhancement

#2812 remove kernel IPv6 from RHEL6 STIG
  rhel6/profiles/standard.profile
  rhel6/profiles/usgcb-rhel6-server.profile
Labels: bugfix
