Repository ComplianceAsCode/content, pull requests merged in 2019-10, with the labels that each got.

#4880 Map AU-9(3) and AU-5(2) for CoreOS
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_disk_full_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_network_failure_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_error_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_full_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_action_mail_acct/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_admin_space_left_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left_action/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls/rule.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
Labels: CoreOS

#4855 Fix regexes in template_oval_service_disabled and template_oval_service_enabled
  linux_os/guide/services/cron_and_at/service_atd_disabled/tests/service_disabled.pass.sh
  linux_os/guide/services/cron_and_at/service_atd_disabled/tests/service_disabled_rpcstatd_enabled.pass.sh
  linux_os/guide/services/cron_and_at/service_atd_disabled/tests/service_enabled.fail.sh
  shared/templates/template_OVAL_service_disabled
  shared/templates/template_OVAL_service_enabled
Labels: OVAL

#4886 Remove slash from audit rules login failock
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/bash/shared.sh
Labels: bugfix

#4887 Remove installation of packages from RHEL8 kickstarts as it is handled by rules
  rhel7/kickstart/ssg-rhel7-ospp-ks.cfg
  rhel7/kickstart/ssg-rhel7-pci-dss-server-with-gui-oaa-ks.cfg
  rhel8/kickstart/ssg-rhel8-ospp-ks.cfg
  rhel8/kickstart/ssg-rhel8-pci-dss-ks.cfg
Labels: bugfix

#4879 Update coreos-ncp profile and map AU-12(1), AC-12, and AC-2(5)
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
  linux_os/guide/system/auditing/grub2_audit_argument/rule.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
  ocp4/profiles/coreos-ncp.profile
Labels: CoreOS

#4890 Map AU-7 and AU-10 to audit package
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
Labels: CoreOS

#4891 fix grub2_argument bash remediation
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/arg_not_there.fail.sh
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/correct.pass.sh
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/wrong_value.fail.sh
  shared/templates/template_BASH_grub2_bootloader_argument
Labels: Bash, bugfix

#4878 Remove extraneous *.* from description and check of rule 'rsyslog_remote_tls_cacert'
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/oval/shared.xml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/tests/cacert_configured.pass.sh
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/tests/syntax_error.fail.sh
Labels: bugfix

#4889 Add rule for NIST AC-18(4)
  linux_os/guide/system/network/network_nmcli_permissions/ansible/shared.yml
  linux_os/guide/system/network/network_nmcli_permissions/bash/shared.sh
  linux_os/guide/system/network/network_nmcli_permissions/oval/shared.xml
  linux_os/guide/system/network/network_nmcli_permissions/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: enhancement

#4892 Map AC-17(2) to crypto SSH policies
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_ssh_client_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_crypto_policy/rule.yml
  ocp4/profiles/coreos-ncp.profile
Labels: CoreOS

#4894 Map AC-17
  linux_os/guide/services/ldap/openldap_client/enable_ldap_client/rule.yml
  linux_os/guide/services/ldap/openldap_client/ldap_client_start_tls/rule.yml
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_allow_only_protocol2/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts_rsa/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_print_last_log/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_info/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/rule.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/rule.yml
  linux_os/guide/system/network/network-ipsec/package_libreswan_installed/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_ssh_client_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/grub_legacy_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  ocp4/profiles/coreos-ncp.profile
Labels: CoreOS

#4896 Map AC-6(5) and add AC-6(9) audit rules to CoreOS
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/rule.yml
  linux_os/guide/system/software/sudo/package_sudo_installed/rule.yml
  ocp4/profiles/coreos-ncp.profile
Labels: CoreOS

#4888 Update audit_rules_unsuccessful_file_modification regex to match multiple "-S" syscall args
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/tests/default.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/tests/syscalls_multiple_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/tests/syscalls_one_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/tests/syscalls_one_per_line.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/tests/test_audit.rules
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
Labels: bugfix

#4904 Removed stray whitespace discard directive.
  shared/macros-bash.jinja
Labels: Bash

#4905 Fix NTP-Chrony remediation + check.
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/bash/shared.sh
  shared/templates/extra_ovals.yml
Labels: Bash, OVAL

#4921 [object_api_server_experimental_encryption_provider_cipher] Fix unclosed capture group & subexpression
  applications/openshift/api-server/api_server_experimental_encryption_provider_cipher/oval/shared.xml
Labels: bugfix

#4911 Fix ansible lint issues
  cmake/SSGCommon.cmake
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/ansible/shared.yml
  shared/templates/template_ANSIBLE_service_disabled
  tests/ansible-lint_config.yml
  tests/ansible_playbook_check.sh
  tests/yamllint_config.yml
Labels: Ansible

#4919 Added missing CCEs.
  linux_os/guide/services/avahi/disable_avahi_group/service_avahi-daemon_disabled/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypbind_removed/rule.yml
  linux_os/guide/services/obsolete/r_services/package_rsh-server_removed/rule.yml
  linux_os/guide/services/obsolete/r_services/package_rsh_removed/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk-server_removed/rule.yml
  linux_os/guide/services/obsolete/telnet/package_telnet-server_removed/rule.yml
  linux_os/guide/services/proxy/disabling_squid/package_squid_removed/rule.yml
  linux_os/guide/services/proxy/disabling_squid/service_squid_disabled/rule.yml
  linux_os/guide/services/routing/disabling_quagga/package_quagga_removed/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_print_last_log/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_info/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_setfiles/rule.yml
  linux_os/guide/system/network/network_sniffer_disabled/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/rule.yml
  linux_os/guide/system/software/sudo/sudo_remove_no_authenticate/rule.yml
  linux_os/guide/system/software/sudo/sudo_remove_nopasswd/rule.yml
  linux_os/guide/system/software/sudo/sudo_require_authentication/rule.yml
  linux_os/guide/system/software/system-tools/package_cryptsetup-luks_installed/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: Text

#4930 Add missing prodtypes for apt rules
  linux_os/guide/services/apt/apt_conf_disallow_unauthenticated/rule.yml
  linux_os/guide/services/apt/apt_sources_list_official/rule.yml
Labels: bugfix

#4834 Fail when a template does not exist
  docs/manual/developer_guide.adoc
  ssg/templates.py
Labels: Python

#4957 Remove directory_access_var_log_audit from RHEL 7 OSPP
  rhel7/profiles/ospp.profile
Labels: bugfix

#4944 Remove openshift api_server_profiling check
  ocp3/profiles/opencis-master.profile
Labels: OpenShift

#4942 Ocp3 audit config
  applications/openshift/api-server/api_server_audit_log_maxage/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxbackup/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxsize/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_path/oval/shared.xml
Labels: OpenShift
