Repository ComplianceAsCode/content, pull requests merged in 2019-08, with the labels that each got.

#4675 Add new rhel8 aux gpg pubkey
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/oval/shared.xml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
  tests/data/group_system/group_software/group_updating/rule_ensure_redhat_gpgkey_installed/key_installed.pass.sh
  tests/data/group_system/group_software/group_updating/rule_ensure_redhat_gpgkey_installed/missing_key.fail.sh
Labels: OVAL

#4678 Add sysclt entries for file system
  rhel8/templates/csv/sysctl_values.csv
Labels: bugfix

#4677 Generate RHEL8 templated content to check for partition existence
  rhel8/templates/csv/mounts.csv
Labels: bugfix

#4686 Jinja bash support
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  shared/macros-bash.jinja
  ssg/constants.py
  ssg/jinja.py
Labels: Bash

#4683 Parameterize Red Hat's GPG release public key.
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/oval/shared.xml
  rhel6/product.yml
  rhel7/product.yml
  rhel8/product.yml
  rhv4/product.yml
  tests/data/group_system/group_software/group_updating/rule_ensure_redhat_gpgkey_installed/fedora_key.fail.sh
Labels: Ansible, Bash, OVAL, RHEL

#4689 Build only SCAP 1.3 content
  CMakeLists.txt
  cmake/SSGCommon.cmake
Labels: CMake

#4698 Fix typos in auditd_local_events texts.
  linux_os/guide/system/auditing/auditd_local_events/rule.yml
Labels: Text

#4699 Fix typo in api_server_admission_control_plugin_NodeRestriction description
  applications/openshift/api-server/api_server_admission_control_plugin_NodeRestriction/rule.yml
Labels: Text

#4694 Updated the Bash guide wrt introduction of bash jinja macros.
  docs/manual/developer_guide.adoc
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  shared/macros-bash.jinja
Labels: Bash

#4702 Enable unit-testing of bash shared jinja macros
  build-scripts/expand_jinja.py
  build-scripts/generate_bash_remediation_functions.py
  shared/bash_remediation_functions/include_lineinfile.sh
  shared/macros-bash.jinja
  ssg/jinja.py
  tests/CMakeLists.txt
  tests/unit/bash/execute_tests.sh
  tests/unit/bash/test_set_config_file.bats.jinja
Labels: Bash

#4708 Add option in build_product to build SCAP 1.2 content.
  build_product
Labels: Bash

#4713 Minor fixes
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_media_export/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_networkconfig_modification/bash/shared.sh
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/bash/shared.sh
  shared/bash_remediation_functions/fix_audit_syscall_rule.sh
  shared/bash_remediation_functions/include_dconf_settings.sh
  shared/bash_remediation_functions/include_mount_options_functions.sh
  shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh
  ssg/yaml.py
Labels: Bash

#4687 Updated Fedora GPG info.
  fedora/product.yml
Labels: Text

#4727 ds_unselect_rules.sh: updated to work with namespaced SCAP 1.3 datastreams
  tests/ds_unselect_rules.sh
Labels: Bash

#4730 Add documentation to known issue in the test suite.
  tests/README.md
Labels: Text

#4729 Document building SCAP 1.2 content instead of SCAP 1.3
  docs/manual/developer_guide.adoc
Labels: Text

#4745 Update STIG Antivirus Language
  linux_os/guide/system/software/integrity/endpoint_security_software/install_antivirus/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/install_hids/rule.yml
  rhel7/profiles/rhelh-stig.profile
  rhel7/profiles/stig.profile
  rhv4/profiles/rhvh-stig.profile
Labels: bugfix

#4760 Fix typos.
  rhel6/profiles/stig.profile
  rhel7/profiles/stig.profile
  rhv4/profiles/rhvh-vpp.profile
Labels: Text, rhel-h

#4725 Fix STIG IDs reference processing
  shared/transforms/shared_shorthand2xccdf.xslt
  ssg/build_yaml.py
  tests/unit/ssg-module/test_build_yaml.py
Labels: Python

#4755 Build both scap versions, but 1.3 is default
  CMakeLists.txt
  build_product
  cmake/SSGCommon.cmake
  docs/manual/developer_guide.adoc
  tests/run_scapval.py
Labels: CMake, Python

#4750 Add suport for rule refinement
  build-scripts/yaml_to_shorthand.py
  rhel8/profiles/ospp.profile
  ssg/build_yaml.py
  ssg/constants.py
Labels: Python

#4714 SSG Test suite: Add function to find remediation in the datastream.
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/xml_operations.py
Labels: SSGTestSuite

#4761 Update CSRF cookie secure
  applications/openstack/horizon/horizon_csrf_cookie_secure/ansible/shared.yml
  applications/openstack/horizon/horizon_csrf_cookie_secure/rule.yml
  applications/openstack/horizon_container/container_horizon_csrf_cookie_secure/ansible/shared.yml
  applications/openstack/horizon_container/container_horizon_csrf_cookie_secure/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenStack, enhancement

#4754 Profile Restructuring
  rhel7/profiles/ospp.profile
  rhel8/profiles/ospp.profile
Labels: Text

#4767 Fix _check_rule method call in SSG test suite.
  tests/ssg_test_suite/combined.py
  tests/ssg_test_suite/rule.py
Labels: Python

#4751 Remove remaining CCE identifiers from RHEL derivatives.
  build-scripts/enable_derivatives.py
  ssg/build_derivatives.py
Labels: OVAL

#4770 Fix sshd_required logic in OVAL macro
  shared/macros-oval.jinja
Labels: OVAL

#4752 Use product attribute to build OVAL check which checks for Redhat gpgkey
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/oval/shared.xml
Labels: OVAL

#4780 Install 1.2 datastreams
  cmake/SSGCommon.cmake
Labels: bugfix

#4779 Remove rule configure_opensc_nss_db from RHEL8 product.
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/rule.yml
  rhel8/profiles/pci-dss.profile
Labels: Ansible, Bash, OVAL, Text

#4777 Revert PR #4766
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/ansible/shared.yml
Labels: BLOCKER

#4785 Fail rpm_verify ansible fixes only if rc returns error code greater than 1
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/ansible/shared.yml
Labels: bugfix
