Repository ComplianceAsCode/content, pull requests merged in 2019-05, with the labels that each got.

#4323 Make sure that registered variables are defined for SSSD Ansible content
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca_dir/ansible/shared.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_memcache_timeout/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_ssh_known_hosts_timeout/ansible/shared.yml
Labels: Ansible, bugfix

#4299 Update FIPS regulatory warning
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/grub_legacy_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
Labels: bugfix

#4300 Add content to handle AES-NI
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
Labels: bugfix, enhancement

#4305 [issue 4253] api_server_authorization_mode XCCDF and OVAL updates
  applications/openshift/api-server/api_server_authorization_mode/oval/shared.xml
  applications/openshift/api-server/api_server_authorization_mode/rule.yml
Labels: OpenShift

#4326 Do not overwrite 1.2 DS with 1.3 DS during xmllint
  cmake/SSGCommon.cmake
Labels: bugfix

#4324 Profile/Product statistics in HTML - improvement for profile_stats.py and jenkins integration
  CMakeLists.txt
  README.md
  build-scripts/profile_tool.py
  cmake/SSGCommon.cmake
  docs/manual/developer_guide.adoc
Labels: CMake, Python

#4333 Small ansible bugfix
  shared/templates/template_ANSIBLE_mount_option
  shared/templates/template_ANSIBLE_mount_option.retry
  shared/templates/template_ANSIBLE_mount_option_var
Labels: Ansible, bugfix

#4359 Remove double entry section in ansible remediation for sssd_ldap_start_tls.
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/ansible/shared.yml
Labels: Ansible

#4362 Rebranded scap-security-guide to ComplianceAsCode.
  README.md
  docs/manual/developer_guide.adoc
  docs/manual/user_guide.adoc
Labels: Text

#4365 Use right variable for ansible remediation in sssd_ssh_known_hosts_timeout rule.
  linux_os/guide/services/sssd/sssd_ssh_known_hosts_timeout/ansible/shared.yml
Labels: bugfix

#4367 User Guide: Update table of old content
  docs/manual/user_guide.adoc
Labels: documentation

#4370 Update RHEL to Red Hat Enterprise Linux in DISA STIG profile and add language for containers
  rhel7/profiles/stig.profile
Labels: bugfix, enhancement

#4368 Update information about project structure
  docs/manual/developer_guide.adoc
Labels: bugfix, documentation

#4369 Correct links in Developer Guide
  docs/manual/developer_guide.adoc
Labels: bugfix, documentation

#3771 Possible fix for #3735
  CMakeLists.txt
  cmake/CopyFiles.cmake
  cmake/SSGCommon.cmake
Labels: bugfix

#4378 Update ensure_oracle_gpgkey_installed for OL8
  linux_os/guide/system/software/updating/ensure_oracle_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_oracle_gpgkey_installed/oval/shared.xml
Labels: bugfix, enhancement

#4374 OL8 profiles update
  ol8/profiles/cjis.profile
  ol8/profiles/hipaa.profile
  ol8/profiles/ospp.profile
  ol8/profiles/pci-dss.profile
Labels: Oracle Linux, enhancement

#4381 Remove firewalld DefaultZone=drop check from rhel7/ccc profile
  rhel7/profiles/ccc.profile
Labels: bugfix

#4377 Smartcards auth in OL8 should be done via sssd
  linux_os/guide/services/sssd/package_sssd_installed/rule.yml
  linux_os/guide/services/sssd/service_sssd_enabled/rule.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/bash/shared.sh
  linux_os/guide/services/sssd/sssd_enable_smartcards/oval/shared.xml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_nss_db/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/group.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_opensc_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_pcsc-lite_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/anaconda/shared.anaconda
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/rule.yml
  ol7/templates/csv/packages_installed.csv
  ol8/profiles/pci-dss.profile
  ol8/templates/csv/packages_installed.csv
Labels: Oracle Linux, enhancement
