Repository ComplianceAsCode/content, pull requests merged in 2019-04, with the labels that each got.

#4235 remove ensure_gpgcheck_repo_metadata from HIPAA profiles
  rhel7/profiles/hipaa.profile
  rhel8/profiles/hipaa.profile
  rhv4/profiles/rhvh-stig.profile
Labels: bugfix

#4232 Various Ansible fixes
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/mounting_remote_filesystems/mount_option_krb_sec_remote_filesystems/ansible/shared.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca_dir/ansible/shared.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_memcache_timeout/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_ssh_known_hosts_timeout/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/ansible/shared.yml
  linux_os/guide/system/auditing/grub_legacy_audit_argument/ansible/rhel6.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_binary_dirs/ansible/shared.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/ansible/shared.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_binary_dirs/ansible/shared.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
  shared/templates/template_ANSIBLE_sebool_var
Labels: bugfix

#4247 More Ansible lint fixes
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/ansible/shared.yml
  shared/templates/template_ANSIBLE_mount_option
  shared/templates/template_ANSIBLE_mount_option_remote_filesystems
  shared/templates/template_ANSIBLE_mount_option_var
Labels: Ansible, bugfix

#4251 Fix incorrectly formatted template_ANSIBLE_mount_option
  shared/templates/template_ANSIBLE_mount_option
Labels: bugfix

#4250 Update STIG and NIST CUI naming
  eap6/CMakeLists.txt
  eap6/profiles/stig.profile
  fuse6/profiles/amq-stig.profile
  fuse6/profiles/stig.profile
  ol7/profiles/stig.profile
  rhel6/CMakeLists.txt
  rhel6/profiles/stig.profile
  rhel7/CMakeLists.txt
  rhel7/profiles/cui.profile
  rhel7/profiles/http-stig.profile
  rhel7/profiles/ipa-stig.profile
  rhel7/profiles/satellite-stig.profile
  rhel7/profiles/stig.profile
  rhel7/profiles/tower-stig.profile
  tests/stable_profile_ids.py
Labels: bugfix

#4055 Update ansible template, readme, and script to bring in line with Ansible Galaxy
  utils/ansible_galaxy_meta_template.yml
  utils/ansible_galaxy_readme_template.md
  utils/upload_ansible_roles_to_galaxy.py
Labels: Ansible, bugfix

#4268 update OpenShift CIS rule mappings
  applications/openshift/api-server/api_server_admission_control_plugin_DenyEscalatingExec/rule.yml
  applications/openshift/api-server/api_server_admission_control_plugin_EventRateLimit/rule.yml
  applications/openshift/api-server/api_server_admission_control_plugin_NamespaceLifecycle/rule.yml
  applications/openshift/api-server/api_server_admission_control_plugin_NodeRestriction/rule.yml
  applications/openshift/api-server/api_server_admission_control_plugin_PodSecurityPolicy/rule.yml
  applications/openshift/api-server/api_server_admission_control_plugin_ServiceAccount/rule.yml
  applications/openshift/api-server/api_server_advanced_auditing/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxage/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxbackup/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxsize/rule.yml
  applications/openshift/api-server/api_server_audit_log_path/rule.yml
  applications/openshift/api-server/api_server_authorization_mode/rule.yml
  applications/openshift/api-server/api_server_client_ca/rule.yml
  applications/openshift/api-server/api_server_etcd_cert/rule.yml
  applications/openshift/api-server/api_server_etcd_key/rule.yml
  applications/openshift/api-server/api_server_experimental_encryption_provider_cipher/rule.yml
  applications/openshift/api-server/api_server_experimental_encryption_provider_config/rule.yml
  applications/openshift/api-server/api_server_insecure_allow_any_token/rule.yml
  applications/openshift/api-server/api_server_kubelet_certificate_authority/rule.yml
  applications/openshift/api-server/api_server_kubelet_client_cert/rule.yml
  applications/openshift/api-server/api_server_kubelet_client_key/rule.yml
  applications/openshift/api-server/api_server_request_timeout/rule.yml
  applications/openshift/api-server/api_server_service_account_key/rule.yml
  applications/openshift/api-server/api_server_tls_cert/rule.yml
  applications/openshift/api-server/api_server_token_auth/rule.yml
  applications/openshift/kubelet/kubelet_enable_server_cert_rotation/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_master_controller_manager/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_groupowner_master_etcd/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_owner_master_controller_manager/rule.yml
  applications/openshift/ocp-permissions/ocp-files/file_permissions_master_controller_manager/rule.yml
  applications/openshift/scheduler/scheduler_profiling_argument/rule.yml
Labels: OpenShift

#4283 Remove mixed tabs with spaces in xccdf-create-ocil.xslt
  shared/transforms/xccdf-create-ocil.xslt
Labels: bugfix

#4292 Update Ansible mount templates
  shared/templates/template_ANSIBLE_mount_option
  shared/templates/template_ANSIBLE_mount_option_var
Labels: bugfix

#4193 Fix for issue #2872
  linux_os/guide/system/bootloader-grub2/file_groupowner_efi_grub2_cfg/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/file_groupowner_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/file_groupowner_grub2_cfg/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/file_owner_efi_grub2_cfg/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/file_owner_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/file_owner_grub2_cfg/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/file_permissions_efi_grub2_cfg/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/file_permissions_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/file_permissions_grub2_cfg/oval/shared.xml
  ol7/templates/csv/file_dir_permissions.csv
  ol8/templates/csv/file_dir_permissions.csv
  shared/checks/oval/system_boot_mode_is_uefi.xml
  shared/macros.jinja
Labels: bugfix

#4297 Remove building of ScientificLinux 8
  rhel8/CMakeLists.txt
  ssg/constants.py
Labels: bugfix

#4296 Add missing transforms for RHEL8
  rhel8/transforms/cci2html.xsl
  rhel8/transforms/table-add-srgitems.xslt
  rhel8/transforms/table-sortbyref.xslt
  rhel8/transforms/xccdf2stigformat.xslt
Labels: bugfix

#4301 Remove remaining references to ScientificLinux8.
  rhel8/cpe/rhel8-cpe-dictionary.xml
  shared/checks/oval/installed_OS_is_sl8.xml
Labels: bugfix

#4304 [issue 4252] update kubelet_disable_readonly_port rationale
  applications/openshift/kubelet/kubelet_disable_readonly_port/rule.yml
Labels: OpenShift

#4303 OpenShift prose and bugfixes
  applications/openshift/api-server/api_server_audit_log_maxage/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxage/rule.yml
  applications/openshift/group.yml
Labels: OpenShift

#4310 ETCD_PEER_CERT_FILE uses '=' as separator, not space
  applications/openshift/etcd/etcd_peer_cert_file/ansible/shared.yml
  applications/openshift/etcd/etcd_peer_cert_file/bash/shared.sh
  applications/openshift/etcd/etcd_peer_cert_file/oval/shared.xml
  applications/openshift/etcd/etcd_peer_cert_file/rule.yml
Labels: OpenShift, bugfix

#4309 update ./etcd/etcd_peer_key_file/ to use = instead of space
  applications/openshift/etcd/etcd_peer_key_file/ansible/shared.yml
  applications/openshift/etcd/etcd_peer_key_file/bash/shared.sh
  applications/openshift/etcd/etcd_peer_key_file/oval/shared.xml
  applications/openshift/etcd/etcd_peer_key_file/rule.yml
Labels: OpenShift, bugfix

#4311 update etcd_cert_file to use equal sign
  applications/openshift/etcd/etcd_cert_file/ansible/shared.yml
  applications/openshift/etcd/etcd_cert_file/bash/shared.sh
  applications/openshift/etcd/etcd_cert_file/oval/shared.xml
  applications/openshift/etcd/etcd_cert_file/rule.yml
Labels: OpenShift, bugfix

#4312 update etcd_key_file to use equal sign as separator
  applications/openshift/etcd/etcd_key_file/ansible/shared.yml
  applications/openshift/etcd/etcd_key_file/oval/shared.xml
  applications/openshift/etcd/etcd_key_file/rule.yml
Labels: OpenShift, bugfix

#4314 Make sure that registered variable is defined
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
Labels: bugfix

#4294 add rhel8 disa tables
  rhel8/CMakeLists.txt
  rhel8/transforms/table-srgmap.xslt
  rhel8/transforms/xccdf-apply-overlay-stig.xslt
  rhel8/transforms/xccdf2table-stig.xslt
Labels: enhancement

#4315 Make sure that audit_arch is defined for Ansible kernel modules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
Labels: bugfix

#4318 Update kubelet checks to pass for default values
  applications/openshift/api-server/api_server_audit_log_path/rule.yml
  applications/openshift/api-server/api_server_service_account_lookup/oval/shared.xml
  applications/openshift/api-server/api_server_service_account_lookup/rule.yml
  applications/openshift/kubelet/kubelet_configure_client_ca/oval/shared.xml
  applications/openshift/kubelet/kubelet_disable_cadvisor_port/oval/shared.xml
  applications/openshift/kubelet/kubelet_disable_readonly_port/oval/shared.xml
  applications/openshift/kubelet/kubelet_enable_iptables_util_chains/oval/shared.xml
  applications/openshift/kubelet/kubelet_enable_iptables_util_chains/rule.yml
  applications/openshift/kubelet/kubelet_enable_streaming_connections/oval/shared.xml
  ocp3/profiles/opencis-master.profile
Labels: OpenShift, bugfix

#4306 create general OCP security prose
  applications/openshift/general/general_configure_imagepolicywebhook/oval/shared.xml
  applications/openshift/general/general_configure_imagepolicywebhook/rule.yml
  applications/openshift/general/general_create_network_segmentation/rule.yml
  applications/openshift/general/general_enable_seccomp/rule.yml
  applications/openshift/general/general_least_privilege_scc/rule.yml
  applications/openshift/general/general_limit_cluster_admin/rule.yml
  applications/openshift/general/general_scc_for_privileged_containers/rule.yml
  applications/openshift/general/general_use_openshift_projects/rule.yml
  applications/openshift/general/group.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenShift

#4307 [issue 4264] disable controller profiling
  applications/openshift/controller/controller_disable_profiling/oval/shared.xml
  applications/openshift/controller/controller_disable_profiling/rule.yml
  ocp3/profiles/opencis-master.profile
  shared/references/cce-redhat-avail.txt
Labels: OpenShift

#4322 Fix ansible kernel module ansible scripts
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_create/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/ansible/shared.yml
Labels: Ansible, bugfix

#4321 Fix typo -> ansible-role not ansible-product-profile-role
  utils/upload_ansible_roles_to_galaxy.py
Labels: bugfix
