Repository ComplianceAsCode/content, pull requests merged in 2019-12, with the labels that each got.

#5038 Fix RHV4 DS applicability
  shared/checks/oval/installed_OS_is_rhv4.xml
Labels: bugfix

#5049 Add rhv4 and ocp4 dir entry to product_directories constant.
  ssg/constants.py
Labels: Python

#5064 Enable ansible template for service_fapolicyd_enable rule.
  linux_os/guide/services/fapolicyd/service_fapolicyd_enabled/rule.yml
Labels: Ansible

#5039 Update api-server XCCDF and OVAL for ocp4-isms
  applications/openshift/api-server/api_server_admission_control_plugin_AlwaysAdmit/oval/shared.xml
  applications/openshift/api-server/api_server_admission_control_plugin_AlwaysAdmit/rule.yml
  applications/openshift/api-server/api_server_anonymous_auth/oval/shared.xml
  applications/openshift/api-server/api_server_anonymous_auth/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxage/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxage/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxbackup/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxbackup/rule.yml
  applications/openshift/api-server/api_server_audit_log_maxsize/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_maxsize/rule.yml
  applications/openshift/api-server/api_server_audit_log_path/oval/shared.xml
  applications/openshift/api-server/api_server_audit_log_path/rule.yml
  applications/openshift/api-server/api_server_authorization_mode/oval/shared.xml
  applications/openshift/api-server/api_server_authorization_mode/rule.yml
  applications/openshift/api-server/api_server_basic_auth/oval/shared.xml
  applications/openshift/api-server/api_server_basic_auth/rule.yml
  applications/openshift/api-server/api_server_client_ca/oval/shared.xml
  applications/openshift/api-server/api_server_client_ca/rule.yml
  applications/openshift/api-server/api_server_etcd_ca/oval/shared.xml
  applications/openshift/api-server/api_server_etcd_ca/rule.yml
  applications/openshift/api-server/api_server_etcd_cert/oval/shared.xml
  applications/openshift/api-server/api_server_etcd_cert/rule.yml
  applications/openshift/api-server/api_server_etcd_key/oval/shared.xml
  applications/openshift/api-server/api_server_etcd_key/rule.yml
  applications/openshift/api-server/api_server_insecure_bind_address/oval/shared.xml
  applications/openshift/api-server/api_server_insecure_bind_address/rule.yml
  applications/openshift/api-server/api_server_insecure_port/oval/shared.xml
  applications/openshift/api-server/api_server_insecure_port/rule.yml
  applications/openshift/api-server/api_server_kubelet_certificate_authority/oval/shared.xml
  applications/openshift/api-server/api_server_kubelet_certificate_authority/rule.yml
  applications/openshift/api-server/api_server_kubelet_client_cert/oval/shared.xml
  applications/openshift/api-server/api_server_kubelet_client_cert/rule.yml
  applications/openshift/api-server/api_server_kubelet_client_key/oval/shared.xml
  applications/openshift/api-server/api_server_kubelet_client_key/rule.yml
  applications/openshift/api-server/api_server_kubelet_https/oval/shared.xml
  applications/openshift/api-server/api_server_kubelet_https/rule.yml
  applications/openshift/api-server/api_server_request_timeout/oval/shared.xml
  applications/openshift/api-server/api_server_request_timeout/rule.yml
  applications/openshift/api-server/api_server_secure_port/oval/shared.xml
  applications/openshift/api-server/api_server_secure_port/rule.yml
  applications/openshift/api-server/api_server_service_account_public_key/oval/shared.xml
  applications/openshift/api-server/api_server_service_account_public_key/rule.yml
  applications/openshift/api-server/api_server_tls_cert/oval/shared.xml
  applications/openshift/api-server/api_server_tls_cert/rule.yml
  applications/openshift/api-server/api_server_tls_cipher_suites/rule.yml
  applications/openshift/api-server/api_server_tls_private_key/oval/shared.xml
  applications/openshift/api-server/api_server_tls_private_key/rule.yml
  applications/openshift/api-server/api_server_token_auth/oval/shared.xml
  applications/openshift/api-server/api_server_token_auth/rule.yml
  applications/openshift/api-server/group.yml
  ocp4/profiles/opencis-master.profile
Labels: enhancement

#4847 Stig sle12 initial
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/oval/shared.xml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/rule.yml
  shared/references/disa-stig-sle12-v1r2-xccdf-manual.xml
  sle12/profiles/stig.profile
  sle12/transforms/constants.xslt
  ssg/constants.py
Labels: enhancement
