Repository ComplianceAsCode/content, pull requests merged in 2019-11, with the labels that each got.

#4938 Fix various typos/incorrect descriptions in rules/groups metadata.
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/system/bootloader-grub2/group.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysconfig_network_IPV6_AUTOCONF_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_ra_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_redirects_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/tests/comment.fail.sh
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/tests/correct_value.pass.sh
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/tests/line_not_there.fail.sh
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/tests/wrong_value.fail.sh
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_forwarding/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_forwarding_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_ra_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_redirects_value.var
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_source_route/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_source_route_value.var
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/grub_legacy_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_use_fips_hashes/rule.yml
  tests/test_parse_affected.py
Labels: Text

#4959 Use only first occurence from /etc/mtab
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/multiple_entries_in_mtab.fail.sh
  shared/bash_remediation_functions/include_mount_options_functions.sh
Labels: bugfix

#4960 Don't require that files exist when path is regex
  docs/manual/developer_guide.adoc
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_cron_allow/oval/rhel7.xml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_cron_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_cron_allow/oval/rhel7.xml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_cron_allow/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_pub_key/rule.yml
  shared/templates/template_OVAL_file_groupowner
  shared/templates/template_OVAL_file_owner
  shared/templates/template_OVAL_file_permissions
  ssg/templates.py
Labels: bugfix

#4966 add SRG to rule
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_rp_filter/rule.yml
Labels: enhancement

#4967 mapped ipv4 and ipv6 SRGs to rules
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/sysctl_net_ipv6_conf_all_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/sysctl_net_ipv6_conf_all_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/sysctl_net_ipv6_conf_default_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/sysctl_net_ipv6_conf_default_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/disabling_ipv6_autoconfig/sysctl_net_ipv6_conf_default_accept_source_route/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_log_martians/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_rp_filter/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_secure_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_icmp_ignore_bogus_error_responses/rule.yml
Labels: enhancement

#4971 Updated to include SRG number
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_log_martians/rule.yml
Labels: enhancement

#4968 Added SRG to rules
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_secure_redirects/rule.yml
Labels: enhancement

#4906 Fixed the remediation for rsyslog_files_permissions
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/tests/perms_0600.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/tests/perms_0601.fail.sh
Labels: Bash

#4973 add srg-os-000378-GPOS-00163 reference to usbguard install and enable
  linux_os/guide/services/usbguard/package_usbguard_installed/rule.yml
  linux_os/guide/services/usbguard/service_usbguard_enabled/rule.yml
Labels: enhancement

#4969 SRG Mapping - misc rules
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
  linux_os/guide/services/sssd/sssd_run_as_sssd_user/rule.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid/rule.yml
  linux_os/guide/services/usbguard/usbguard_allow_hub/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_user_max_user_namespaces/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_crypto_policy/rule.yml
  linux_os/guide/system/software/updating/timer_dnf-automatic_enabled/rule.yml
Labels: enhancement

#4982 added SRG rule for Exec Shield
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/rule.yml
Labels: enhancement

#4974 day 2 changes to rules with SRG info
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: enhancement

#4975 Day 2 - Yasir's Contributions
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/rule.yml
Labels: enhancement

#4981 additional srg mappings
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_temp_expire_date/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_passwd/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
Labels: enhancement

#4940 DISA STIG SRG mappings
  linux_os/guide/system/permissions/files/sysctl_fs_protected_hardlinks/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_symlinks/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_kptr_restrict/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_pattern/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_dmesg_restrict/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_kexec_load_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_perf_event_paranoid/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_unprivileged_bpf_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_net_core_bpf_jit_harden/rule.yml
Labels: RHEL, enhancement

#4988 Added SRG rule for auditd_audispd_configure_remote_server
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/rule.yml
Labels: enhancement

#4931 Update upload_ansible_roles_to_galaxy.py
  utils/upload_ansible_roles_to_galaxy.py
Labels: bugfix

#4992 Fix command module typo
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
Labels: bugfix

#4993 Use service_facts to get services in template_ANSIBLE_service_disabled
  shared/templates/template_ANSIBLE_service_disabled
Labels: enhancement

#4986 Fix grub2 enable fips mode rule
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/anaconda/shared.anaconda
  shared/macros-bash.jinja
Labels: Bash

#5002 Small Bash style fixes.
  linux_os/guide/system/network/network-ipv6/disabling_ipv6/network_ipv6_disable_rpc/bash/shared.sh
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/bash/shared.sh
Labels: Bash

#4991 Add draft RHEL8 STIG profile
  rhel8/profiles/stig.profile
Labels: enhancement

#4934 Add Network Policies rule to OCP
  applications/openshift/general/general_configure_network_policies/rule.yml
  applications/openshift/general/general_create_network_segmentation/rule.yml
Labels: OpenShift

#4932 Add some NIST mappings for FISMA high
  linux_os/guide/services/fapolicyd/configure_fapolicyd_mounts/rule.yml
  linux_os/guide/services/fapolicyd/package_fapolicyd_installed/rule.yml
  linux_os/guide/services/fapolicyd/service_fapolicyd_enabled/rule.yml
  linux_os/guide/services/ldap/openldap_client/ldap_client_start_tls/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca/rule.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca_dir/rule.yml
  linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_start_tls/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_opensc_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_pcsc-lite_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/package_firewalld_installed/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_rate_limiting/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/set_firewalld_default_zone/rule.yml
  linux_os/guide/system/network/network-iptables/iptables_activation/service_ip6tables_enabled/rule.yml
  linux_os/guide/system/network/network-iptables/iptables_activation/service_iptables_enabled/rule.yml
  linux_os/guide/system/network/network-iptables/iptables_activation/set_ip6tables_default_rule/rule.yml
  linux_os/guide/system/network/network-iptables/iptables_ruleset_modifications/set_iptables_default_rule/rule.yml
  linux_os/guide/system/network/network-iptables/iptables_ruleset_modifications/set_iptables_default_rule_forward/rule.yml
  linux_os/guide/system/network/network-iptables/package_iptables_installed/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_enable_smartcard_auth/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_ssh_client_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/grub_legacy_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_use_fips_hashes/rule.yml
  linux_os/guide/system/software/sudo/package_sudo_installed/rule.yml
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_repo_metadata/rule.yml
  linux_os/guide/system/software/updating/ensure_oracle_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
Labels: CoreOS

#5008 Update etcd rules
  applications/openshift/etcd/etcd_auto_tls/rule.yml
  applications/openshift/etcd/etcd_cert_file/rule.yml
  applications/openshift/etcd/etcd_client_cert_auth/rule.yml
  applications/openshift/etcd/etcd_key_file/rule.yml
  applications/openshift/etcd/etcd_peer_auto_tls/rule.yml
  applications/openshift/etcd/etcd_peer_cert_file/rule.yml
  applications/openshift/etcd/etcd_peer_client_cert_auth/rule.yml
  applications/openshift/etcd/etcd_peer_key_file/rule.yml
  applications/openshift/etcd/etcd_unique_ca/rule.yml
  applications/openshift/etcd/etcd_wal_dir/rule.yml
  applications/openshift/etcd/group.yml
  ocp4/profiles/opencis-master.profile
  ocp4/profiles/opencis-node.profile
Labels: enhancement

#5027 Enable more STIG/SRG table builds in RHEL8
  rhel8/CMakeLists.txt
Labels: enhancement

#5028 FIX SRG tables
  eap6/transforms/constants.xslt
  rhel6/transforms/constants.xslt
  rhel7/transforms/constants.xslt
  rhel8/transforms/constants.xslt
  shared/references/disa-os-srg-v1r6.xml
  shared/transforms/shared_table-srgmap.xslt
Labels: bugfix

#5026 Firefox content fixes
  firefox/guide/firefox/firefox_preferences-home_page/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_obscure/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-open_confirmation/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-verification/bash/firefox.sh
  shared/macros-bash.jinja
  ssg/jinja.py
Labels: Bash, OVAL

#5024 Updated the e8 profile for RHEL8.
  rhel8/profiles/e8.profile
Labels: bugfix

#5036 Update ETCD XCCDF and OVAL for ocp4-isms
  applications/openshift/etcd/etcd_auto_tls/oval/shared.xml
  applications/openshift/etcd/etcd_cert_file/oval/shared.xml
  applications/openshift/etcd/etcd_cert_file/rule.yml
  applications/openshift/etcd/etcd_client_cert_auth/oval/shared.xml
  applications/openshift/etcd/etcd_key_file/oval/shared.xml
  applications/openshift/etcd/etcd_key_file/rule.yml
  applications/openshift/etcd/etcd_peer_auto_tls/oval/shared.xml
  applications/openshift/etcd/etcd_peer_cert_file/oval/shared.xml
  applications/openshift/etcd/etcd_peer_cert_file/rule.yml
  applications/openshift/etcd/etcd_peer_client_cert_auth/oval/shared.xml
  applications/openshift/etcd/etcd_peer_key_file/oval/shared.xml
  applications/openshift/etcd/etcd_peer_key_file/rule.yml
  applications/openshift/etcd/etcd_unique_ca/oval/shared.xml
  applications/openshift/etcd/etcd_unique_ca/rule.yml
Labels: enhancement

#5035 Update SRG table to DISA requirements
  shared/transforms/shared_table-srgmap.xslt
Labels: enhancement

#5040 Add draft RHELH content for rhel8
  rhel8/profiles/rhelh-stig.profile
  rhel8/profiles/rhelh-vpp.profile
Labels: enhancement
