Repository ComplianceAsCode/content, pull requests merged in 2019-09, with the labels that each got.

#4782 Unselect rule directory_access_var_log_audit in OSPP Profile
  rhel8/profiles/ospp.profile
Labels: bugfix

#4778 Move audit rules to correct group
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/rule.yml
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/commented.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/correct_value.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/correct_value_capital.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/double_assignment.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/missing_file.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/missing_value.pass.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/wrong_value.fail.sh
  tests/data/group_system/group_auditing/group_configure_auditd_data_retention/rule_auditd_local_events/wrong_value_capital.fail.sh
Labels: bugfix

#4791 Improve Bash code based on shellcheck feedback
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_immutable/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/bash/shared.sh
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/bash/shared.sh
  linux_os/guide/system/permissions/partitions/mount_option_nodev_nonroot_local_partitions/bash/rhel6.sh
  shared/bash_remediation_functions/fix_audit_syscall_rule.sh
  shared/bash_remediation_functions/include_mount_options_functions.sh
  shared/bash_remediation_functions/perform_audit_adjtimex_settimeofday_stime_remediation.sh
  shared/bash_remediation_functions/service_command.sh
  shared/macros-bash.jinja
Labels: Bash

#4744 Update identifers and references in rule section of documentation
  docs/manual/developer_guide.adoc
Labels: documentation

#4792 SSG Test Suite: Fix (all) profile execution when running test suite in rule mode
  ssg/constants.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/rule.py
  tests/test_suite.py
Labels: Python, SSGTestSuite

#4805 Rename disable_prelink -> bash_disable_prelink
  docs/manual/developer_guide.adoc
  linux_os/guide/system/software/integrity/disable_prelink/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
  shared/macros-bash.jinja
Labels: Bash

#4807 ansible_set_sshd: add before first commented Match
  shared/macros-ansible.jinja
Labels: Ansible

#4771 Update DISA STIG related files to newest version V2R4
  docs/man_page_template.jinja
  rhel7/overlays/stig_overlay.xml
  shared/references/disa-stig-rhel7-v2r4-xccdf-manual.xml
  utils/create-stig-overlay.py
Labels: Text

#4811 SSG Test Suite: Continue even when rule is not found on benchmark.
  tests/ssg_test_suite/rule.py
Labels: Python

#4813 Fix /etc/shadow permissions documentation
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_shadow/rule.yml
Labels: bugfix

#4818 Add DISA severity levels to Developer Guide
  docs/manual/developer_guide.adoc
Labels: documentation

#4816 update api_server_audit_log_path to evaluate any log path
  applications/openshift/api-server/api_server_audit_log_path/oval/shared.xml
Labels: bugfix

#4812 Ensure proper permissions on /etc/ssh/sshd_config
  linux_os/guide/services/ssh/file_groupowner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_groupowner_sshd_config/tests/is_root.pass.sh
  linux_os/guide/services/ssh/file_groupowner_sshd_config/tests/other_group.fail.sh
  linux_os/guide/services/ssh/file_owner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_owner_sshd_config/tests/is_root.pass.sh
  linux_os/guide/services/ssh/file_owner_sshd_config/tests/other_user.fail.sh
  linux_os/guide/services/ssh/file_permissions_sshd_config/rule.yml
  ol7/templates/csv/file_dir_permissions.csv
  ol8/templates/csv/file_dir_permissions.csv
  rhel6/profiles/C2S.profile
  rhel6/templates/csv/file_dir_permissions.csv
  rhel7/profiles/C2S.profile
  rhel7/templates/csv/file_dir_permissions.csv
  rhel8/templates/csv/file_dir_permissions.csv
Labels: enhancement

#4817 update kubelet_enable_streaming_connections variable handling
  applications/openshift/kubelet/kubelet_enable_streaming_connections/oval/shared.xml
  applications/openshift/kubelet/var_streaming_connection_timeouts.var
Labels: bugfix

#4814 Use int zero (0) for never in unlock_time setting for pam_faillock
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_accounts_passwords_pam_faillock_deny.var
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_accounts_passwords_pam_faillock_fail_interval.var
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_accounts_passwords_pam_faillock_unlock_time.var
Labels: bugfix

#4819 Assign CCEs to SSH permission checks
  linux_os/guide/services/ssh/file_groupowner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_owner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_config/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL

#4823 Fix kubelet_enable_streaming_connections Rule
  applications/openshift/kubelet/kubelet_enable_streaming_connections/oval/shared.xml
  applications/openshift/kubelet/kubelet_enable_streaming_connections/rule.yml
  applications/openshift/kubelet/var_streaming_connection_timeouts.var
  ocp3/templates/csv/ocp_service_runtime_config.csv
Labels: bugfix

#4822 Fix OCP runtime template
  ocp3/templates/csv/ocp_service_runtime_config.csv
  shared/templates/template_OVAL_ocp_service_runtime_config
Labels: bugfix

#4821 insecure-port should not be configured
  applications/openshift/api-server/api_server_insecure_port/oval/shared.xml
  applications/openshift/api-server/api_server_insecure_port/rule.yml
Labels: bugfix

#4836 Fix accounts password rules template name
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_difok/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxclassrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minclass/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minlen/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ucredit/rule.yml
  utils/migrate_template_csv_to_rule.py
Labels: bugfix

#4810 Migrate more Bash remediations to Jinja2 macros
  docs/manual/developer_guide.adoc
  firefox/guide/firefox/firefox_preferences-addons_plugin_updates/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-auto-download_actions/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-auto-update_of_firefox/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-autofill_forms/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-autofill_passwords/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-cookies/firefox_preferences-cookies_clear/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-cookies/firefox_preferences-cookies_user_notice/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-home_page/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_context_menus/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_status_bar_changes/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_status_bar_text/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_window_changes/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_window_resizing/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_obscure/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-non-secure_page_warning/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-open_confirmation/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-password_store/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-pop-up_windows/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-search_update/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-shell_protocol/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-ssl_protocol_tls/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-ssl_version_2/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-ssl_version_3/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-verification/bash/firefox.sh
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/bash/rhel6.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/bash/shared.sh
  shared/bash_remediation_functions/firefox_cfg_setting.sh
  shared/bash_remediation_functions/firefox_js_setting.sh
  shared/bash_remediation_functions/service_command.sh
  shared/macros-bash.jinja
Labels: Bash, Infrastructure

#4842 A couple of minor upload_ansible_roles_to_galaxy fixes
  utils/upload_ansible_roles_to_galaxy.py
Labels: bugfix

#4800 Improved the build_product script.
  build_product
Labels: Bash

#4832 Postfix network listening to loopback-only
  linux_os/guide/services/mail/postfix_client/postfix_network_listening_disabled/ansible/shared.yml
  linux_os/guide/services/mail/postfix_client/postfix_network_listening_disabled/oval/shared.xml
  linux_os/guide/services/mail/postfix_client/postfix_network_listening_disabled/rule.yml
  linux_os/guide/services/mail/postfix_client/var_postfix_inet_interfaces.var
  rhel6/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
Labels: enhancement

#4853 fips rules passing for rhel8
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/oval/shared.xml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/grub_legacy_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_use_fips_hashes/rule.yml
Labels: bugfix

#4863 Add coreos to RHEL8 installed checks
  shared/checks/oval/installed_OS_is_rhel8.xml
Labels: CoreOS, enhancement

#4859 Add Essential Eight profiles
  rhel7/profiles/e8.profile
  rhel8/profiles/e8.profile
Labels: enhancement

#4865 Add coreos NCP profile
  ocp4/profiles/coreos-ncp.profile
Labels: CoreOS, enhancement

#4864 Fix playbook permissions for audisp when creating configuration file
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/ansible/shared.yml
Labels: bugfix

#4871 Fix typo in installed_OS_is_rhv4.xml file.
  shared/checks/oval/installed_OS_is_rhv4.xml
Labels: bugfix

#4862 Fix oval applicability for wrlinux and ubuntu
  linux_os/guide/services/ssh/package_openssh-server_installed/oval/wrlinux.xml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/oval/wrlinux.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_groupownership/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/oval/shared.xml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/oval/wrlinux.xml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/oval/wrlinux.xml
  linux_os/guide/system/selinux/selinux_confinement_of_daemons/oval/shared.xml
  shared/templates/template_OVAL_service_disabled
  ssg/build_ovals.py
  ssg/constants.py
  wrlinux1019/templates/csv/packages_installed.csv
  wrlinux8/templates/csv/packages_installed.csv
Labels: bugfix

#4872 Fix rhel6 nist mapping typo
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
Labels: bugfix

#4873 Add rules for FISMA Low to CoreOS NCP
  ocp4/profiles/coreos-ncp.profile
Labels: enhancement

#4868 Use defaults/main.yml and not vars/main.yml
  utils/ansible_galaxy_readme_template.md
Labels: bugfix

#4867 Map OCP SCC to Kubernetes benchmark
  applications/openshift/general/general_least_privilege_scc/rule.yml
Labels: bugfix

#4875 Double quote value when setting runtime sysctl configuration.
  shared/templates/template_BASH_sysctl
Labels: Bash
