Repository ComplianceAsCode/content, pull requests merged in 2019-06, with the labels that each got.

#4351 Anssi updates
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/rule.yml
  linux_os/guide/system/selinux/package_setroubleshoot_removed/rule.yml
  linux_os/guide/system/selinux/selinux_policytype/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_acls/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_ext_attributes/rule.yml
  linux_os/guide/system/software/sudo/sudo_remove_nopasswd/rule.yml
  rhel7/profiles/anssi_nt28_enhanced.profile
  rhel7/profiles/anssi_nt28_high.profile
Labels: enhancement

#4382 Introduced the "DConf System DBs are in sync with keyfiles" rule.
  fedora/profiles/ospp.profile
  fedora/profiles/pci-dss.profile
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/bash/shared.sh
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/oval/shared.xml
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/rule.yml
  ol7/profiles/pci-dss.profile
  ol7/profiles/stig.profile
  ol8/profiles/ospp.profile
  ol8/profiles/pci-dss.profile
  rhel7/profiles/C2S.profile
  rhel7/profiles/hipaa.profile
  rhel7/profiles/ospp.profile
  rhel7/profiles/ospp42.profile
  rhel7/profiles/pci-dss.profile
  rhel7/profiles/stig.profile
  rhel8/profiles/cjis.profile
  rhel8/profiles/hipaa.profile
  rhel8/profiles/ospp.profile
  rhel8/profiles/pci-dss.profile
  shared/references/cce-redhat-avail.txt
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_banner_enabled/correct_value.pass.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_banner_enabled/wrong_value.fail.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/correct_value.pass.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/wrong_value.fail.sh
  tests/data/group_system/group_software/group_gnome/dconf_test_functions.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_disable_restart_shutdown/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_disable_restart_shutdown/wrong_value.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_disable_user_list/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_disable_user_list/wrong_value.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_enable_smartcard_auth/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_enable_smartcard_auth/wrong_value.fail.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_login_retries/correct_value.pass.sh
  tests/data/group_system/group_software/group_gnome/group_gnome_login_screen/rule_dconf_gnome_login_retries/wrong_value.fail.sh
  tests/data/group_system/group_software/group_gnome/rule_dconf_db_up_to_date/db_not_up_to_date.fail.sh
  tests/data/group_system/group_software/group_gnome/rule_dconf_db_up_to_date/db_up_to_date.pass.sh
  tests/data/group_system/group_software/group_gnome/rule_dconf_db_up_to_date/no_db_files.fail.sh
  tests/data/group_system/group_software/group_gnome/rule_dconf_db_up_to_date/no_keyfiles.pass.sh
Labels: Bash, OVAL, Text

#4371 vars should be in defaults for user customization in ansible roles
  utils/upload_ansible_roles_to_galaxy.py
Labels: bugfix

#4393 Call dconf update in all dconf-related shared remediation functions.
  shared/bash_remediation_functions/include_dconf_settings.sh
Labels: Bash

#4406 Fix example in csv_map
  shared/templates/template_common.py
Labels: Python

#4413 Move jinja macro loading out of ssg.yaml
  ssg/jinja.py
  ssg/yaml.py
Labels: Python, refactoring

#4415 Macros everywhere
  shared/templates/template_common.py
  ssg/build_remediations.py
  ssg/oval.py
Labels: Python, enhancement

#4423 Fix typo.
  linux_os/guide/system/permissions/files/sysctl_fs_protected_hardlinks/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_symlinks/rule.yml
Labels: Text

#4421 Add option for extra repository in install_vm.py script.
  tests/install_vm.py
  tests/kickstarts/test_suite.cfg
Labels: Python

#4422 Remove duplicated CCE suffix from replace_or_append bash remediation.
  shared/bash_remediation_functions/replace_or_append.sh
Labels: Bash

#4418 Build multiple products
  CMakeLists.txt
  build_product
Labels: CMake, Infrastructure, usability

#4429 Quietly handle documentation not complete errors
  ssg/build_yaml.py
  ssg/playbook_builder.py
  ssg/yaml.py
Labels: enhancement, usability

#4428 Add Ansible macros for lineinfile remediations
  docs/manual/developer_guide.adoc
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_allow_only_protocol2/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_kerb_auth/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts_rsa/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_x11_forwarding/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_print_last_log/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/ansible/shared.yml
  shared/macros-ansible.jinja
  ssg/constants.py
  ssg/jinja.py
Labels: Ansible, Infrastructure, Question - Seeking Feedback, usability

#4403 Various bash fixes.
  linux_os/guide/system/entropy/kernel_disable_entropy_contribution_for_solid_state_drives/bash/rhel6.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
  linux_os/guide/system/permissions/partitions/mount_option_nodev_nonroot_local_partitions/bash/rhel6.sh
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_oracle_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh
  shared/bash_remediation_functions/fix_audit_syscall_rule.sh
  shared/bash_remediation_functions/fix_audit_watch_rule.sh
  shared/bash_remediation_functions/include_dconf_settings.sh
  shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh
Labels: Bash

#4545 Check if all rules in profile exist
  build-scripts/yaml_to_shorthand.py
  rhel6/profiles/C2S.profile
  rhel6/profiles/CS2.profile
  rhel6/profiles/nist-CL-IL-AL.profile
  ssg/build_yaml.py
Labels: Python

#3679 Do not add dconf value type for login banner text
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/login_banner_text.var
  shared/bash_remediation_functions/include_dconf_settings.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/correct_value.pass.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/correct_value_stig.pass.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/missing_value_stig.fail.sh
  tests/data/group_system/group_accounts/group_accounts-banners/group_gui_login_banner/rule_dconf_gnome_login_banner_text/wrong_value_stig.fail.sh
Labels: Bash, Text, bugfix
