Repository ComplianceAsCode/content, pull requests merged in 2020-05, with the labels that each got.

#5620 create new ignition files for /etc/audit/auditd.conf
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/ignition/shared.yml
Labels: ok-to-test

#5749 Cis partitions rules
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nodev_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nosuid_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_home/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_tmp/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log_audit/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_tmp/rule.yml
Labels: ok-to-test

#5755 Warn about findings from rpm_verify_permissions and rpm_verify_ownership
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/rule.yml
Labels: bugfix

#5750 Add ubuntu cis profile
  ubuntu1804/profiles/cis.profile
Labels: ok-to-test

#5756 fix grub2_bootloader_argument template
  linux_os/guide/system/auditing/grub2_audit_argument/tests/double_value_rhel7.fail.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/double_value_rhel8.fail.sh
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/tests/correct_grubby.pass.sh
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/tests/correct_grubenv.pass.sh
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/tests/wrong_value_etcdefaultgrub.fail.sh
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/tests/wrong_value_rhel8.fail.sh
  shared/templates/template_ANSIBLE_grub2_bootloader_argument
  shared/templates/template_BASH_grub2_bootloader_argument
  shared/templates/template_OVAL_grub2_bootloader_argument
Labels: bugfix

#5765 Ansible mount_option: split mount and option task
  shared/templates/template_ANSIBLE_mount_option
Labels: bugfix

#5774 Upgrade to using compliance-operator v0.1.9
  ocp-resources/compliance-operator-alpha-subscription.yaml
  tests/ocp4e2e/go.mod
  tests/ocp4e2e/go.sum
  tests/ocp4e2e/vendor/github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  tests/ocp4e2e/vendor/github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  tests/ocp4e2e/vendor/github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1/compliancescan_types.go
  tests/ocp4e2e/vendor/github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  tests/ocp4e2e/vendor/github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  tests/ocp4e2e/vendor/modules.txt
Labels: ok-to-test

#5763 rsyslog: Improve OVAL and Bash handling of include() syntax
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_groupownership/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_ownership/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/oval/shared.xml
Labels: bugfix

#5326 Introduced a rule that uses non-standard yaml checks
  CMakeLists.txt
  applications/openshift/ocp_data_root.var
  applications/openshift/ocp_idp_no_htpasswd/oval/shared.xml
  applications/openshift/ocp_idp_no_htpasswd/rule.yml
  applications/openshift/ocp_idp_no_htpasswd/tests/correct.pass.sh
  applications/openshift/ocp_idp_no_htpasswd/tests/htpasswd.fail.sh
  applications/openshift/ocp_idp_no_htpasswd/tests/no_file.fail.sh
  applications/openshift/ocp_idp_no_htpasswd/tests/nothing_wrong.pass.sh
  cmake/SSGCommon.cmake
  ocp4/product.yml
  ocp4/profiles/moderate.profile
  ocp4/profiles/platform-moderate.profile
  shared/macros.jinja
  shared/references/cce-redhat-avail.txt
  ssg/oval.py
Labels: OVAL

#5764 Fix db in which Ansible remediation sets banner_enable
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/ansible/shared.yml
Labels: bugfix

#5772 Made the rule sshd_rekey_limit parametrized.
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/tests/bad_size.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/tests/bad_time.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/tests/no_line.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/tests/ok.pass.sh
  linux_os/guide/services/ssh/ssh_server/var_rekey_limit_size.var
  linux_os/guide/services/ssh/ssh_server/var_rekey_limit_time.var
  rhel8/profiles/ospp.profile
  shared/macros-ansible.jinja
  shared/macros-bash.jinja
  tests/data/profile_stability/rhel8/ospp.profile
  tests/data/profile_stability/rhel8/stig.profile
Labels: Bash, OVAL

#5790 Add k8s remediations for several audit rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_networkconfig_modification/ignition/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification/ignition/shared.yml
  shared/templates/template_KUBERNETES_audit_rules_dac_modification
  shared/templates/template_KUBERNETES_audit_rules_login_events
  shared/templates/template_KUBERNETES_audit_rules_privileged_commands
  ssg/templates.py
Labels: ok-to-test

#5785 Create macro for selinux ansible/bash remediation.
  linux_os/guide/system/selinux/selinux_policytype/ansible/shared.yml
  linux_os/guide/system/selinux/selinux_policytype/bash/shared.sh
  linux_os/guide/system/selinux/selinux_policytype/oval/shared.xml
  linux_os/guide/system/selinux/selinux_state/ansible/shared.yml
  linux_os/guide/system/selinux/selinux_state/bash/shared.sh
  linux_os/guide/system/selinux/selinux_state/oval/shared.xml
  linux_os/guide/system/selinux/selinux_state/tests/selinux_missing.fail.sh
  linux_os/guide/system/selinux/selinux_state/tests/selinux_permissive.fail.sh
  shared/macros-ansible.jinja
  shared/macros-bash.jinja
Labels: ok-to-test

#5794 ocp4: Check for diminishing failures in e2e test
  tests/ocp4e2e/e2e_test.go
  tests/ocp4e2e/helpers.go
Labels: ok-to-test
