Repository ComplianceAsCode/content, pull requests merged in 2020-06, with the labels that each got.

#5792 ocp4: Change auditd flush frequency to incremental_async by default
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/kubernetes/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/kubernetes/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/kubernetes/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/kubernetes/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/kubernetes/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/ignition/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/kubernetes/shared.yml
Labels: ok-to-test

#5797 devguide: Add Kubernetes as the supported platform for several templates
  docs/manual/developer_guide.adoc
Labels: needs-ok-to-test

#5784 Add rules to configure zIPL
  linux_os/guide/system/bootloader-zipl/group.yml
  linux_os/guide/system/bootloader-zipl/zipl_audit_argument/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_audit_backlog_limit_argument/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_enable_selinux/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_page_poison_argument/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_pti_argument/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_slub_debug_argument/rule.yml
  linux_os/guide/system/bootloader-zipl/zipl_vsyscall_argument/rule.yml
Labels: ok-to-test

#5809 pkgname@debian auditd
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
Labels: bugfix, needs-ok-to-test

#5803 ocp4: Test amount of check results for scans
  tests/ocp4e2e/e2e_test.go
  tests/ocp4e2e/helpers.go
Labels: ok-to-test

#5807 Sle15 cis
  sle15/profiles/cis.profile
Labels: needs-ok-to-test

#5812 Remove result files when test scenarios pass.
  tests/ssg_test_suite/oscap.py
Labels: SSGTestSuite

#5813 Avoid duplicates in the srg mapping
  shared/transforms/srg-overlay.xslt
Labels: bugfix

#5806 Update unowned user rule warning
  linux_os/guide/system/permissions/files/no_files_unowned_by_user/rule.yml
Labels: bugfix

#5828 Sle15 cis
  linux_os/guide/services/obsolete/service_rsyncd_disabled/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/set_firewalld_default_zone/rule.yml
  sle15/profiles/cis.profile
Labels: enhancement, needs-ok-to-test

#5830 Add dev_shm rules to rhel7 stig profile
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/rule.yml
  rhel7/profiles/stig.profile
Labels: bugfix, needs-ok-to-test

#5826 rhcos4: Remove checks for nmcli permissions
  rhcos4/profiles/moderate.profile
Labels: bugfix

#5621 Ignition for audit_create_failed, audit_modify_success, chronyd_client_only, chronyd_no_chronyc_network
  linux_os/guide/services/ntp/chronyd_client_only/ignition/shared.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_create_failed/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_success/ignition/shared.yml
Labels: needs-ok-to-test

#5827 Add test scenario for sshd_rekey_limit to cover OSPP profile
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/tests/ospp_ok.pass.sh
Labels: SSGTestSuite

#5818 Add error message to the crypto policy remediation
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/bash/shared.sh
Labels: Bash

#5851 Remove grub documentation links from RHEL7 rationale
  linux_os/guide/system/bootloader-grub2/grub2_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_password/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_uefi_password/rule.yml
Labels: bugfix

#5758 Template for yamlfilecontent checks
  applications/openshift/ocp_idp_no_htpasswd/oval/shared.xml
  applications/openshift/ocp_idp_no_htpasswd/rule.yml
  docs/manual/developer_guide.adoc
  shared/templates/template_OVAL_yamlfile_value
  ssg/templates.py
Labels: OVAL

#5858 Updating Firefox content
  firefox/guide/firefox/firefox_preferences-addons_plugin_updates/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-addons_plugin_updates/rule.yml
  firefox/guide/firefox/firefox_preferences-auto-download_actions/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-auto-download_actions/rule.yml
  firefox/guide/firefox/firefox_preferences-auto-update_of_firefox/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-autofill_forms/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-autofill_forms/rule.yml
  firefox/guide/firefox/firefox_preferences-autofill_passwords/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-autofill_passwords/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-autofill_passwords/rule.yml
  firefox/guide/firefox/firefox_preferences-background_data/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-background_data/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-background_data/rule.yml
  firefox/guide/firefox/firefox_preferences-cookies/firefox_preferences-cookies_clear/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-cookies/firefox_preferences-cookies_user_notice/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-development_tools/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-development_tools/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-development_tools/rule.yml
  firefox/guide/firefox/firefox_preferences-home_page/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-install_extensions/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-install_extensions/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-install_extensions/rule.yml
  firefox/guide/firefox/firefox_preferences-javascript_context_menus/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_context_menus/rule.yml
  firefox/guide/firefox/firefox_preferences-javascript_status_bar_changes/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_status_bar_text/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_window_changes/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_window_changes/rule.yml
  firefox/guide/firefox/firefox_preferences-javascript_window_resizing/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-javascript_window_resizing/rule.yml
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_config_file/rule.yml
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_obscure/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-lock_settings/firefox_preferences-lock_settings_obscure/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-non-secure_page_warning/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-open_confirmation/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-open_confirmation/rule.yml
  firefox/guide/firefox/firefox_preferences-password_store/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-password_store/rule.yml
  firefox/guide/firefox/firefox_preferences-pop-up_windows/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-pop-up_windows/rule.yml
  firefox/guide/firefox/firefox_preferences-search_update/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-search_update/rule.yml
  firefox/guide/firefox/firefox_preferences-shell_protocol/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-shell_protocol/rule.yml
  firefox/guide/firefox/firefox_preferences-ssl_protocol_tls/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-ssl_protocol_tls/oval/firefox.xml
  firefox/guide/firefox/firefox_preferences-ssl_protocol_tls/rule.yml
  firefox/guide/firefox/firefox_preferences-ssl_version_2/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-ssl_version_3/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-verification/bash/firefox.sh
  firefox/guide/firefox/firefox_preferences-verification/rule.yml
  firefox/guide/firefox/installed_firefox_version_supported/oval/firefox.xml
  firefox/guide/firefox/installed_firefox_version_supported/rule.yml
  firefox/guide/firefox/var_required_file_types.var
  firefox/overlays/stig_overlay.xml
  firefox/profiles/stig.profile
  shared/macros-bash.jinja
Labels: needs-ok-to-test

#5839 OCP4 allowed registries
  applications/openshift/registry/group.yml
  applications/openshift/registry/ocp_allowed_registries_for_import/oval/shared.xml
  applications/openshift/registry/ocp_allowed_registries_for_import/rule.yml
  applications/openshift/registry/ocp_allowed_registries_for_import/tests/correct.pass.sh
  applications/openshift/registry/ocp_allowed_registries_for_import/tests/no_file.fail.sh
  applications/openshift/registry/ocp_allowed_registries_for_import/tests/registries.fail.sh
  ocp4/profiles/e8.profile
  ocp4/profiles/moderate.profile
Labels: ok-to-test

#5889 Change the CPE identifier for RHCOS to indicate it's an OS
  rhcos4/cpe/rhcos4-cpe-dictionary.xml
  shared/checks/oval/installed_OS_is_rhcos4.xml
  ssg/constants.py
Labels: needs-ok-to-test

#5890 Update RHEL7 documentation link for grub2_uefi_admin_username.
  linux_os/guide/system/bootloader-grub2/grub2_uefi_admin_username/rule.yml
Labels: Text
