Repository ComplianceAsCode/content, pull requests merged in 2020-04, with the labels that each got.

#5548 Feature suse 15.1
  linux_os/guide/services/http/disabling_httpd/package_httpd_removed/rule.yml
  linux_os/guide/services/http/disabling_httpd/service_httpd_disabled/rule.yml
  linux_os/guide/services/ssh/package_openssh_installed/rule.yml
  linux_os/guide/services/ssh/service_sshd_enabled/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/package_firewalld_installed/rule.yml
  sle15/CMakeLists.txt
  sle15/cpe/sle15-cpe-dictionary.xml
  sle15/profiles/standard.profile
  ssg/constants.py
Labels: needs-ok-to-test

#5558 Fix grub path in grub2_enable_fips_mode bash script
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
Labels: bugfix, needs-ok-to-test

#5559 Fix ol8 condition in accounts-physical rules
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/rule.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml
Labels: needs-ok-to-test

#5557 Fix rsyslog_nolisten regex to match rule description
  linux_os/guide/system/logging/rsyslog_accepting_remote_messages/rsyslog_nolisten/oval/shared.xml
Labels: needs-ok-to-test

#5555 Add ol7 stigid prefix mapping
  ol7/transforms/constants.xslt
  ssg/constants.py
Labels: needs-ok-to-test

#5553 Make the datastream namespaces readable again
  build-scripts/enable_derivatives.py
  build-scripts/sds_move_ocil_to_checks.py
  build-scripts/unselect_empty_xccdf_groups.py
  build-scripts/update_sds_version.py
  ssg/constants.py
  ssg/xml.py
Labels: Python

#5581 Fix the profile compilation.
  build-scripts/compile_profiles.py
Labels: Python, bugfix

#5560 Add e8 profile for ocp4
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  ocp4/profiles/e8.profile
Labels: needs-ok-to-test

#5570 Fix covscan issues.
  shared/bash_remediation_functions/fix_audit_syscall_rule.sh
  shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh
Labels: Bash

#5580 don't add boot UUID if same as root UUID
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh
Labels: ok-to-test

#5597 Add ansible and bash remediation for rule sshd_set_max_auth_tries.
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/tests/correct_value_less_than.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/tests/wrong_value.fail.sh
  rhel7/profiles/cis.profile
Labels: Ansible, Bash

#5607 Allow tcp forwarding
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/wrong_value.fail.sh
  rhel8/profiles/cis.profile
  sle15/profiles/cis.profile
Labels: needs-ok-to-test

#5598 Use jinja macros for bash remediation in rule sshd_set_keepalive.
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/bash/shared.sh
Labels: Bash

#5596 add linux_os/guide/system/permissions/restrictions/sysctl_kernel_core…
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_redirects/ignition/shared.yml
  linux_os/guide/system/network/network-kernel/network_host_parameters/sysctl_net_ipv4_ip_forward/ignition/75-sysctl_net_ipv4_ip_forward.conf
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_pattern/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/sysctl_user_max_user_namespaces/ignition/shared.yml
Labels: needs-ok-to-test

#5618 Audit modify failed
  linux_os/guide/system/auditing/policy_rules/audit_modify_failed/ignition/shared.yml
Labels: needs-ok-to-test

#5579 Issue 5529
  linux_os/guide/services/ssh/package_openssh-server_installed/rule.yml
  linux_os/guide/services/ssh/package_openssh-server_removed/rule.yml
  linux_os/guide/services/ssh/package_openssh_removed/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/rule.yml
  linux_os/guide/services/ssh/var_sshd_max_sessions.var
  rhel8/profiles/cis.profile
  sle15/profiles/standard.profile
Labels: needs-ok-to-test

#5617 Audit module load
  linux_os/guide/system/auditing/policy_rules/audit_module_load/ignition/shared.yml
Labels: needs-ok-to-test

#5616 Audit ospp general
  linux_os/guide/system/auditing/policy_rules/audit_ospp_general/ignition/shared.yml
Labels: needs-ok-to-test

#5615 Audit basic configuration
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/ignition/shared.yml
Labels: ok-to-test

#5613 Added more SLES Support
  linux_os/guide/services/ssh/package_openssh-server_installed/rule.yml
  linux_os/guide/services/ssh/package_openssh-server_removed/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
Labels: needs-ok-to-test

#5604 Added ignition files for disable_ctrlaltdel_burstaction and disable_u…
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_kerb_auth/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts_rsa/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_x11_forwarding/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_print_last_log/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/ignition/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/ignition/shared.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_access_failed/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_access_success/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_failed/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_success/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/coredumps/disable_users_coredumps/ignition/shared.yml
Labels: ok-to-test

#5631 OL7 stig profile update to align to DISA STIG for OL7 v1r1
  ol7/profiles/stig.profile
Labels: ok-to-test

#5278 Fix template mount_option_removable_partitions
  docs/manual/developer_guide.adoc
  linux_os/guide/system/permissions/partitions/mount_option_nodev_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_bad_opts.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_good_opts.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_multiple_opts.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_multiple_opts.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_multiple_opts_first.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/cd_multiple_opts_last.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/dvd_bad_opts.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/dvd_good_opts.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/tests/no_partitions.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_nosuid_removable_partitions/rule.yml
  shared/templates/template_ANACONDA_mount_option_removable_partitions
  shared/templates/template_ANSIBLE_mount_option_removable_partitions
  shared/templates/template_BASH_mount_option_removable_partitions
  shared/templates/template_OVAL_mount_option_removable_partitions
  ssg/templates.py
Labels: OVAL

#5646 Add multi_platform_rhel,multi_platform_fedora to the rest of the ignition remediations
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins/ignition/shared.yml
  linux_os/guide/system/auditing/grub2_audit_argument/ignition/shared.yml
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/ignition/shared.yml
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/ignition/shared.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_atm_disabled/ignition/shared.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_can_disabled/ignition/shared.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_firewire-core_disabled/ignition/shared.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_sctp_disabled/ignition/shared.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_tipc_disabled/ignition/shared.yml
  linux_os/guide/system/network/network-wireless/wireless_software/kernel_module_bluetooth_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_squashfs_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_udf_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/mounting/kernel_module_vfat_disabled/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/coredumps/coredump_disable_backtraces/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/coredumps/coredump_disable_storage/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_page_poison_argument/ignition/shared.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_slub_debug_argument/ignition/shared.yml
Labels: ok-to-test

#5632 Add transforms and html tables for ol7 and ol8
  ol7/CMakeLists.txt
  ol7/transforms/cci2html.xsl
  ol7/transforms/table-add-srgitems.xslt
  ol7/transforms/table-sortbyref.xslt
  ol7/transforms/table-srgmap.xslt
  ol7/transforms/table-style.xslt
  ol7/transforms/xccdf-apply-overlay-stig.xslt
  ol7/transforms/xccdf2stigformat.xslt
  ol7/transforms/xccdf2table-byref.xslt
  ol7/transforms/xccdf2table-profileanssirefs.xslt
  ol7/transforms/xccdf2table-profileccirefs.xslt
  ol7/transforms/xccdf2table-profilecisrefs.xslt
  ol7/transforms/xccdf2table-profilenistrefs-cui.xslt
  ol7/transforms/xccdf2table-profilenistrefs.xslt
  ol7/transforms/xccdf2table-stig.xslt
  ol8/CMakeLists.txt
  ol8/transforms/cci2html.xsl
  ol8/transforms/table-sortbyref.xslt
  ol8/transforms/table-style.xslt
  ol8/transforms/xccdf2table-byref.xslt
  ol8/transforms/xccdf2table-profileanssirefs.xslt
  ol8/transforms/xccdf2table-profileccirefs.xslt
  ol8/transforms/xccdf2table-profilecisrefs.xslt
  ol8/transforms/xccdf2table-profilenistrefs-cui.xslt
  ol8/transforms/xccdf2table-profilenistrefs.xslt
Labels: ok-to-test

#5648 ocp4: Expand unit tests to validate profile selections
  ocp4/profiles/coreos-ncp.profile
  tests/unit/kubernetes/go.mod
  tests/unit/kubernetes/helpers.go
  tests/unit/kubernetes/unit_test.go
Labels: ok-to-test

#5649 Add yum CPE entry for SLE15 product.
  sle15/cpe/sle15-cpe-dictionary.xml
Labels: SLES

#5642 Fix audit_basic_configuration ignition remediation
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/rule.yml
Labels: ok-to-test

#5641 Create machine configuration for the rule no tmux in shells
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/ignition/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/rule.yml
  ocp4/profiles/moderate.profile
Labels: ok-to-test

#5655 Add DISA STIG OL7 v1r1 stig_overlay
  ol7/CMakeLists.txt
  ol7/overlays/stig_overlay.xml
  shared/references/disa-stig-ol7-v1r1-xccdf-manual.xml
Labels: needs-ok-to-test

#5660 Reference should not point to OS version.
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/package_tmux_installed/rule.yml
Labels: needs-ok-to-test

#5651 Fix several audit-related ignition remediations
  linux_os/guide/system/auditing/policy_rules/audit_modify_failed/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_module_load/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_module_load/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_ospp_general/ignition/shared.yml
  linux_os/guide/system/auditing/policy_rules/audit_ospp_general/rule.yml
Labels: ok-to-test

#5628 Sshd use strong rng
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/ignition/shared.yml
Labels: needs-ok-to-test

#5625 Add check and remediation for xwindows_runlevel_target and select in profiles that remove package xorg-x11-server-common
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/ansible/shared.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/bash/shared.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/oval/shared.xml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/tests/correct_target.pass.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/tests/correct_target_under_lib.pass.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/tests/wrong_target.fail.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/tests/wrong_target_under_lib.fail.sh
  rhel7/profiles/C2S.profile
  rhel7/profiles/cis.profile
  rhel8/profiles/cis.profile
  shared/references/cce-redhat-avail.txt
  sle15/profiles/cis.profile
  tests/ssg_test_suite/oscap.py
Labels: Ansible, Bash

#5566 shared/partition.sh: Increase the size of a test device
  tests/shared/partition.sh
Labels: SSGTestSuite

#5711 Fix SSGTS when running with python3 and writing binary data to file.
  tests/ssg_test_suite/oscap.py
Labels: SSGTestSuite

#5656 use freq param for both 'incremental' and 'incremental_async' of var_…
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/bash/shared.sh
Labels: ok-to-test

#5550 Added possibility of the test suite to expand platforms of the benchmark
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/xml_operations.py
  tests/test_suite.py
Labels: Python, SSGTestSuite

#5722 Ubuntu1804/cis kernel module rules
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_udf_disabled/rule.yml
  shared/templates/template_OVAL_kernel_module_disabled
Labels: ok-to-test
