Repository ComplianceAsCode/content, pull requests merged in 2020-03, with the labels that each got.

#5266 fix OVAL template for audit_rules_unsuccessful_file_modification
  shared/templates/template_OVAL_audit_rules_unsuccessful_file_modification
Labels: bugfix

#5270 Added support for rawhide gpgkey check/remediation.
  fedora/product.yml
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/oval/shared.xml
Labels: Bash, OVAL

#5274 Add dconf_db_up_to_date to RHEL8 STIG profile.
  rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
Labels: bugfix

#5275 Fix ansible linting issue on rule ensure_gpgcheck_never_disabled.
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/ansible/shared.yml
Labels: Ansible

#5272 Fix the utils/ignition-remediation.py helper script
  utils/ignition-remediation.py
Labels: bugfix

#5050 Simplify banner text syntax and add utility to generate banner regular expression
  docs/manual/developer_guide.adoc
  linux_os/guide/services/http/securing_httpd/httpd_secure_content/var_web_login_banner_text.var
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/oval/shared.xml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/tests/banner_etc_issue_disa_dod_default_banner_no_newline.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/tests/banner_etc_issue_disa_with_extra_line.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/tests/banner_etc_issue_ospp_usbcg_banner.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/tests/banner_etc_issue_ospp_usbcg_banner.pass.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/correct_value_stig.pass.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/missing_value_stig.fail.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/wrapped_banner.fail.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/tests/wrong_value_stig.fail.sh
  linux_os/guide/system/accounts/accounts-banners/login_banner_text.var
  rhel8/profiles/stig.profile
  shared/macros-ansible.jinja
  shared/macros-bash.jinja
  ssg/build_yaml.py
  ssg/jinja.py
  ssg/utils.py
  tests/data/profile_stability/rhel8/stig.profile
  utils/regexify_banner.py
Labels: bugfix

#5269 Fix description of sysctl rules.
  shared/macros.jinja
Labels: Text, bugfix

#5217 SSGTS: profile mode extended to reboot VM before performing the final scan
  tests/install_vm.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/test_env.py
  tests/ssg_test_suite/virt.py
  tests/test_suite.py
Labels: bugfix

#5300 Ticket40400 sshd use approved macs
  linux_os/guide/services/ssh/sshd_approved_macs.var
  rhel7/profiles/stig.profile
Labels: bugfix

#5284 adding oval check for rule
  linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/oval/shared.xml
  linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/tests/absent.fail.sh
  linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/tests/defective.fail.sh
  linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/tests/ok.pass.sh
Labels: OVAL

#5308 Parametrized the sshd_use_approved_ciphers rule
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_correct_reduced_list.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_correct_scrambled.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_correct_value_full.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/stig_wrong_value.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/tests/wrong_value.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
  linux_os/guide/services/ssh/sshd_approved_ciphers.var
  rhel7/profiles/stig.profile
  shared/macros.jinja
Labels: OVAL, Text

#5334 Add initial macOS content
  CMakeLists.txt
  apple_os/auditing/configure_auditing/audit_failure_halt/bash/shared.sh
  apple_os/auditing/configure_auditing/audit_failure_halt/oval/shared.xml
  apple_os/auditing/configure_auditing/audit_failure_halt/rule.yml
  apple_os/auditing/configure_auditing/group.yml
  apple_os/auditing/group.yml
  apple_os/auditing/service_auditd_enabled/bash/shared.sh
  apple_os/auditing/service_auditd_enabled/rule.yml
  apple_os/benchmark.yml
  apple_os/intro/general-principles/group.yml
  apple_os/intro/general-principles/principle-encrypt-transmitted-data/group.yml
  apple_os/intro/general-principles/principle-least-privilege/group.yml
  apple_os/intro/general-principles/principle-minimize-software/group.yml
  apple_os/intro/general-principles/principle-separate-servers/group.yml
  apple_os/intro/general-principles/principle-use-security-tools/group.yml
  apple_os/intro/group.yml
  apple_os/intro/how-to-use/group.yml
  apple_os/intro/how-to-use/intro-formatting-conventions/group.yml
  apple_os/intro/how-to-use/intro-read-sections-completely/group.yml
  apple_os/intro/how-to-use/intro-reboot-required/group.yml
  apple_os/intro/how-to-use/intro-root-shell-assumed/group.yml
  apple_os/intro/how-to-use/intro-test-non-production/group.yml
  apple_os/services/group.yml
  build-scripts/cpe_generate.py
  macos1015/CMakeLists.txt
  macos1015/cpe/macos1015-cpe-dictionary.xml
  macos1015/overlays/.gitkeep
  macos1015/product.yml
  macos1015/profiles/moderate.profile
  macos1015/transforms/cci2html.xsl
  macos1015/transforms/constants.xslt
  macos1015/transforms/shorthand2xccdf.xslt
  macos1015/transforms/table-add-srgitems.xslt
  macos1015/transforms/table-sortbyref.xslt
  macos1015/transforms/table-srgmap.xslt
  macos1015/transforms/table-style.xslt
  macos1015/transforms/xccdf-apply-overlay-stig.xslt
  macos1015/transforms/xccdf2stigformat.xslt
  macos1015/transforms/xccdf2table-byref.xslt
  macos1015/transforms/xccdf2table-cce.xslt
  macos1015/transforms/xccdf2table-profileanssirefs.xslt
  macos1015/transforms/xccdf2table-profileccirefs.xslt
  macos1015/transforms/xccdf2table-profilecisrefs.xslt
  macos1015/transforms/xccdf2table-profilenistrefs-cui.xslt
  macos1015/transforms/xccdf2table-profilenistrefs.xslt
  macos1015/transforms/xccdf2table-stig.xslt
  shared/checks/oval/installed_OS_is_macos1015.xml
  ssg/build_ovals.py
  ssg/constants.py
Labels: enhancement

#5347 macOS build fixes
  macos1015/profiles/moderate.profile
  ssg/utils.py
Labels: bugfix

#5346 Various macro and description fixes
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/oval/shared.xml
  linux_os/guide/system/auditing/grub_legacy_audit_argument/oval/rhel6.xml
  linux_os/guide/system/bootloader-grub2/grub2_enable_iommu_force/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/harden_ssh_client_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/oval/shared.xml
  shared/macros-highlevel.jinja
  shared/macros-oval.jinja
  shared/templates/template_OVAL_grub2_bootloader_argument
Labels: bugfix
