Repository ComplianceAsCode/content, pull requests merged in 2020-12, with the labels that each got.

#6447 Translate CPE check ids for derivative products.
  build-scripts/enable_derivatives.py
  cmake/SSGCommon.cmake
  ssg/build_derivatives.py
Labels: Python, bugfix

#6454 Update SUSE Linux Enterprise Server 12 STIG XML
  shared/references/disa-stig-sle12-v1r2-xccdf-manual.xml
  shared/references/disa-stig-sle12-v2r1-xccdf-manual.xml
Labels: ok-to-test

#6459 Add supported languages doc for lineinfile template.
  docs/manual/developer/06_contributing_with_content.md
Labels: documentation

#6461 Add platform_package_overrides to OL7 and OL8
  ol7/product.yml
  ol8/product.yml
Labels: ok-to-test

#6462 Set platform package mapping to None for not_s390x_arch CPE.
  ssg/constants.py
Labels: bugfix

#6476 Add stricter permissions option to file permissions template
  applications/openshift/master/file_permissions_multus_conf/rule.yml
  docs/manual/developer/06_contributing_with_content.md
  shared/templates/file_permissions/oval.template
  shared/templates/file_permissions/template.py
Labels: OVAL

#6472 Support SLES-12-010380, SLES-12-010110, and SLES-12-030150
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/rule.yml
  linux_os/guide/system/software/sudo/sudo_remove_no_authenticate/rule.yml
  linux_os/guide/system/software/sudo/sudo_remove_nopasswd/rule.yml
  sle12/profiles/stig.profile
Labels: needs-ok-to-test

#6488 Add noauto option to /boot in ANSSI kickstart files.
  rhel7/kickstart/ssg-rhel7-anssi_nt28_high-ks.cfg
  rhel8/kickstart/ssg-rhel8-anssi_bp28_high-ks.cfg
Labels: bugfix

#6481 Add s390x (IBM Z) as a 64bit architecture
  shared/checks/oval/system_info_architecture_64bit.xml
  shared/checks/oval/system_info_architecture_s390_64.xml
Labels: needs-ok-to-test

#6491 Add bootloader password to RHEL8 ANSSI kickstart file.
  rhel8/kickstart/ssg-rhel8-anssi_bp28_high-ks.cfg
Labels: bugfix

#6485 Enable checks and remediations for the following SLES-12 STIGs:
  linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias/ansible/shared.yml
  linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias/rule.yml
  linux_os/guide/services/obsolete/r_services/no_host_based_files/rule.yml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/ansible/shared.yml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_x11_forwarding/rule.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_motd/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_motd/rule.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_full_action/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_full_action/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_full_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_action_mail_acct/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_action_mail_acct/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_action_mail_acct/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left/rule.yml
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
  shared/checks/oval/installed_env_has_login_defs.xml
  shared/macros-bash.jinja
  shared/templates/package_installed/bash.template
  shared/templates/service_disabled/bash.template
  shared/templates/service_enabled/bash.template
  sle12/product.yml
  sle12/profiles/stig.profile
Labels: ok-to-test
