Repository ComplianceAsCode/content, pull requests merged in 2021-12, with the labels that each got.

#7939 Add stig_gui profile for ol7
  products/ol7/CMakeLists.txt
  products/ol7/profiles/stig_gui.profile
Labels: ok-to-test

#7942 File attributes template: Create directory first if doesn't exist.
  shared/templates/file_groupowner/tests/correct_groupowner.pass.sh
  shared/templates/file_groupowner/tests/incorrect_groupowner.fail.sh
  shared/templates/file_owner/tests/correct_owner.pass.sh
  shared/templates/file_owner/tests/incorrect_owner.fail.sh
  shared/templates/file_permissions/tests/correct_permissions.pass.sh
  shared/templates/file_permissions/tests/lenient_permissions.fail.sh
Labels: bugfix

#7945 Fix typos from previous PRs
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/rule.yml
Labels: bugfix

#7912 Add pam pwhistory remember rules to OL7 stig
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
  products/ol7/profiles/stig.profile
Labels: ok-to-test

#7955 Update reference to disa-os-srg file
  shared/transforms/shared_xccdf2table-profileccirefs.xslt
Labels: needs-ok-to-test

#7960 Fix issues with dividing a str by str in `utils/render-policy.py`
  utils/render-policy.py
Labels: bugfix, Infrastructure

#7959 Improve `create_srg_export.py`
  utils/create_srg_export.py
Labels: Infrastructure

#7974 Fix the metadata propagation of SCE checks
  ssg/build_yaml.py
Labels: needs-ok-to-test

#7975 Add rationale to controls
  docs/manual/developer/03_creating_content.md
  ssg/controls.py
  tests/unit/ssg-module/data/controls_dir/abcd.yml
  tests/unit/ssg-module/data/controls_dir/jklm.yml
  tests/unit/ssg-module/data/controls_dir/qrst/r2_r3.yml
  tests/unit/ssg-module/test_controls.py
  utils/create_srg_export.py
Labels: Infrastructure

#7971 Fix RHEL9 rule auditd_audispd_syslog_plugin_activated
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audit_syslog_plugin_activated.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audit_syslog_plugin_activated_not_there.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audit_syslog_plugin_not_activated.fail.sh
Labels: bugfix, RHEL9

#7986 Fix typo in configure_usbguard_auditbackend rule
  linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml
Labels: ok-to-test

#7985 Exclude EKS content from validation and scap_val SRC-329.
  .github/workflows/gate.yaml
  cmake/SSGCommon.cmake
  tests/run_scapval.py
Labels: bugfix

#7982 Fix OCP4 and EKS SCAP validation
  applications/openshift/general/resource_requests_quota_per_project/oval/shared.xml
  applications/openshift/networking/configure_network_policies_namespaces/oval/shared.xml
  shared/templates/yamlfile_value/oval.template
Labels: bugfix

#7989 Fix typo in OCIL of coreos_slub_debug_kernel_argument
  linux_os/guide/system/permissions/restrictions/poisoning/coreos_slub_debug_kernel_argument/rule.yml
Labels: bugfix

#7976 Add docs for create srg export
  controls/stig_rhel9/SRG-OS-000004-GPOS-00004.yml
  docs/manual/developer/03_creating_content.md
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_emergency_expire_date/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_temp_expire_date/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers_d/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_group/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_gshadow/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_opasswd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_passwd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_shadow/rule.yml
  shared/macros.jinja
Labels: Documentation, RHEL9

#7990 Use product defined dconf dir in dconf_db_up_to_date check
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/oval/shared.xml
Labels: bugfix

#7993 fix_rules.py: Set subcommand required
  utils/fix_rules.py
Labels: bugfix

#7962 Remediation improvements for file_permissions_home_directories rule
  controls/cis_rhel8.yml
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/tests/special_permissions.fail.sh
Labels: enhancement, RHEL8 CIS Alignment

#7936 fix enable_fips_mode remediations
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
Labels: bugfix, Update Rule

#8003 Select rules for users' min/max password age in RHEL8 CIS
  controls/cis_rhel8.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/rule.yml
Labels: RHEL8 CIS Alignment

#8000 Item 5.7 from RHEL8 CIS is not fully automatable
  controls/cis_rhel8.yml
Labels: RHEL8 CIS Alignment

#7995 Fix compare-ds GH Action
  .github/workflows/compare-ds.yaml
Labels: bugfix

#8005 Select rules for RHEL7 CIS 5.1.9 - ensure at is restricted
  controls/cis_rhel7.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_at_deny_not_exist/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_at_allow/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL7 CIS Alignment

#8006 RHEL7 CIS: Select rules for home dirpermission and owners
  controls/cis_rhel7.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_ownership_home_directories/rule.yml
Labels: RHEL7 CIS Alignment

#8004 Add "Manual" Control status and update RHEL8 CIS Control file
  controls/cis_rhel8.yml
  docs/manual/developer/03_creating_content.md
  linux_os/guide/system/accounts/accounts-session/file_ownership_home_directories/rule.yml
  shared/references/cce-redhat-avail.txt
  ssg/controls.py
  utils/controleval.py
Labels: RHEL8 CIS Alignment

#8008 Mark as Manual RHEL7 CIS items that are manual
  controls/cis_rhel7.yml
Labels: RHEL7 CIS Alignment

#8010 Set automated controls in RHEL7 to automated
  controls/cis_rhel7.yml
Labels: RHEL7 CIS Alignment

#8009 Align RHEL7 and 8 CIS requirement for .rhosts file
  controls/cis_rhel7.yml
  controls/cis_rhel8.yml
Labels: RHEL8 CIS Alignment, RHEL7 CIS Alignment

#8011 Fix confusing wording in var_accounts_tmout
  linux_os/guide/system/accounts/accounts-session/var_accounts_tmout.var
Labels: needs-ok-to-test

#7999 Update sysctl template remediation to comment parameters from /etc/sysctl.d/*.conf
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_randomize_va_space/tests/wrong_value_d_directory.fail.sh
  shared/templates/sysctl/ansible.template
  shared/templates/sysctl/bash.template
Labels: DISA RHEL8 STIG Alignment

#8016 Fix Profile title to Node instead of Platform
  products/ocp4/profiles/nerc-cip-node.profile
Labels: needs-ok-to-test
