Repository ComplianceAsCode/content, pull requests merged in 2021-03, with the labels that each got.

#6647 Sort file lists
  build-scripts/combine_remediations.py
  build-scripts/compile_profiles.py
  build-scripts/cpe_generate.py
  build-scripts/generate_bash_remediation_functions.py
  build-scripts/generate_fixes_xml.py
  ssg/build_cpe.py
  ssg/build_remediations.py
  ssg/build_yaml.py
  ssg/controls.py
  ssg/oval.py
  ssg/playbook_builder.py
  ssg/rules.py
  ssg/templates.py
  utils/ansible_playbook_to_role.py
  utils/duplicated_prodtypes.py
  utils/find_duplicates.py
  utils/find_shadowed_files.py
  utils/fix-rules.py
  utils/fix_file_ocilclause.py
  utils/gen_tables.py
  utils/ignition-remediation.py
  utils/migrate_template_csv_to_rule.py
  utils/move_rules.py
Labels: ok-to-test

#6650 Add missing ol platform to remediations
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/ansible/shared.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
  linux_os/guide/system/selinux/selinux_state/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot/bash/shared.sh
Labels: needs-ok-to-test

#6642 Allow to override build date with SOURCE_DATE_EPOCH
  ssg/constants.py
Labels: ok-to-test

#6655 Improve developer documentation and add reproducible builds docs
  docs/manual/developer/02_building_complianceascode.md
Labels: documentation

#6631 SLES-12 add checks and remediations.
  docs/manual/developer/06_contributing_with_content.md
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faildelay_delay/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_password_pam_delay.var
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_password_pam_remember.var
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_difok/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_minlen/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_retry/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_ucredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/group.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_chcon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_media_export/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/ansible/shared.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/bash/shared.sh
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/rule.yml
  linux_os/guide/system/software/gnome/enable_dconf_user_profile/oval/shared.xml
  linux_os/guide/system/software/gnome/enable_dconf_user_profile/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/oval/shared.xml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/sap_host/accounts_authorized_local_users/rule.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/rule.yml
  shared/templates/pam_options/ansible.template
  shared/templates/pam_options/oval.template
  shared/templates/pam_options/template.py
  shared/templates/pam_options/template.yml
  sle12/profiles/stig.profile
Labels: ok-to-test

#6635 SLES-12 add checks and remediations.
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount2/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_acl_commands/audit_rules_execution_chacl/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_acl_commands/audit_rules_execution_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_acl_commands/audit_rules_execution_setfacl/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_acl_commands/group.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_chcon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_rm/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_chfn/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_passmass/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_ssh_agent/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_usermod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
  shared/templates/audit_rules_privileged_commands/ansible.template
  shared/templates/audit_rules_privileged_commands/oval.template
Labels: needs-ok-to-test

#6665 Add new rules to sle12/profiles/stig.profile
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/banner_etc_gdm_banner/ansible/shared.yml
  shared/bash_remediation_functions/ensure_pam_module_options.sh
  sle12/profiles/stig.profile
Labels: needs-ok-to-test

#6671 Fix test scenario of rpm_verify_permissions rule
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/tests/all_permissions_ok.pass.sh
Labels: bugfix

#6670 Update license
  LICENSE
Labels: documentation

#6666 Initial support for SUSE SLE-15
  linux_os/guide/system/network/network-susefirewall2/susefirewall2_ddos_protection/oval/shared.xml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/rule.yml
  shared/references/disa-stig-sle15-v1r1-xccdf-manual.xml
  sle12/CMakeLists.txt
  sle12/overlays/stig_overlay.xml
  sle15/CMakeLists.txt
  sle15/overlays/stig_overlay.xml
  sle15/profiles/stig.profile
  sle15/transforms/constants.xslt
  sle15/transforms/xccdf-apply-overlay-stig.xslt
Labels: needs-ok-to-test

#6652 Adds classification-banner rule
  applications/openshift/classification-banner/classification_banner/rule.yml
  applications/openshift/classification-banner/classification_banner/tests/ocp4/e2e-remediation.sh
  applications/openshift/classification-banner/classification_banner/tests/ocp4/e2e.yml
  applications/openshift/classification-banner/group.yml
  ocp4/profiles/moderate.profile
Labels: ok-to-test

#6691 fix: rule for kubelet_authorization_mode
  applications/openshift/kubelet/kubelet_authorization_mode/rule.yml
Labels: ok-to-test

#6692 fix oval of ensure_logrotate_activated
  linux_os/guide/system/logging/log_rotation/ensure_logrotate_activated/oval/shared.xml
Labels: bugfix

#6694 fix test for smartcard_auth
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/tests/installed_enabled.pass.sh
Labels: bugfix

#6702 Ignore trailing whitespaces in the unique references test
  tests/assert_reference_unique.sh
Labels: Bash

#6710 fix remediations of ensure_logrotate_activated
  linux_os/guide/system/logging/log_rotation/ensure_logrotate_activated/ansible/shared.yml
  linux_os/guide/system/logging/log_rotation/ensure_logrotate_activated/bash/shared.sh
  linux_os/guide/system/logging/log_rotation/ensure_logrotate_activated/tests/logrotate_configured.pass.sh
Labels: bugfix, productization-issue

#6709 Fix file permissions template when checking directories and allowing stricter permissions
  shared/templates/file_groupowner/template.py
  shared/templates/file_owner/template.py
  shared/templates/file_permissions/oval.template
  shared/templates/file_permissions/template.py
  ssg/utils.py
Labels: ok-to-test

#6717 Use helper function when parsing template boolean options.
  shared/templates/auditd_lineinfile/template.py
  shared/templates/shell_lineinfile/template.py
  shared/templates/sshd_lineinfile/template.py
  shared/templates/sudo_defaults_option/template.py
  shared/templates/yamlfile_value/template.py
Labels: Python

#6730 Need to set pipefail when using shell in ansible
  linux_os/guide/services/obsolete/r_services/no_host_based_files/ansible/shared.yml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/gui_login_dod_acknowledgement/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/pam_disable_automatic_configuration/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/ansible/shared.yml
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/ansible/shared.yml
  linux_os/guide/system/permissions/permissions_local/file_permissions_var_log_messages/ansible/shared.yml
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_acls/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_ext_attributes/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/ansible/shared.yml
  shared/templates/pam_options/ansible.template
Labels: needs-ok-to-test

#6744 Switch to generic python shebang
  build-scripts/add_stig_references.py
  build-scripts/build_all_guides.py
  build-scripts/build_profile_remediations.py
  build-scripts/build_templated_content.py
  build-scripts/combine_ovals.py
  build-scripts/combine_remediations.py
  build-scripts/cpe_generate.py
  build-scripts/enable_derivatives.py
  build-scripts/generate_bash_remediation_functions.py
  build-scripts/generate_fixes_xml.py
  build-scripts/oscap_svg_support.py
  build-scripts/relabel_ids.py
  build-scripts/sds_move_ocil_to_checks.py
  build-scripts/unselect_empty_xccdf_groups.py
  build-scripts/verify_references.py
  build-scripts/yaml_to_shorthand.py
  shared/transforms/pcidss/generate_pcidss_json.py
  shared/transforms/pcidss/transform_benchmark_to_pcidss.py
  tests/ensure_paths_are_short.py
  tests/install_vm.py
  tests/ssg_test_suite/combined.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/profile.py
  tests/ssg_test_suite/virt.py
  tests/ssg_test_suite/xml_operations.py
  tests/test_suite.py
  utils/ansible_playbook_to_role.py
  utils/count_oval_objects.py
  utils/find_duplicates.py
  utils/fix-rules.py
  utils/generate_contributors.py
  utils/testoval.py
  utils/xccdf2csv-stig.py
Labels: Infrastructure

#6740 Fix oracle documentation links
  linux_os/guide/services/ldap/openldap_client/group.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/rule.yml
  linux_os/guide/system/selinux/group.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: Text

#6755 Improve devel documentation.
  docs/manual/developer/06_contributing_with_content.md
Labels: documentation

#6734 SLES-15-020101 add rule and tests, no remediation.
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/oval/shared.xml
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/rule.yml
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/tests/simple.fail.sh
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/tests/simple.pass.sh
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/tests/sudoers_d.fail.sh
  sle15/profiles/stig.profile
Labels: needs-ok-to-test

#6760 fix build system to correctly parse platforms
  ssg/build_yaml.py
Labels: bugfix

#6685 Add ansible and bash remediation for wireless_disable_interfaces.
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/ansible/shared.yml
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/bash/shared.sh
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/rule.yml
Labels: Ansible, Bash

#6674 create-stig-overlay.py: Create overlay directory if it doesn't exist
  utils/create-stig-overlay.py
Labels: Python

#6756 Add documentation links for OL7 and OL8
  jre/guide/java/group.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: needs-ok-to-test
