Repository ComplianceAsCode/content, pull requests merged in 2021-09, with the labels that each got.

#7495 OL8 was prevent build all from working
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/oval/shared.xml
Labels: bugfix

#7480 SLE15 add ensure_suse_gpgkey_installed rule to PCI-DSS profile
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/oval/shared.xml
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/tests/key_installed.pass.sh
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/tests/missing_key.fail.sh
  products/sle15/product.yml
  products/sle15/profiles/pci-dss.profile
Labels: SLES, ok-to-test

#7500 Add audit_rules_dac_modification_umount specific
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/rule.yml
Labels: ok-to-test

#7454 Add sort prodtypes to fix_rules
  docs/manual/developer/05_tools_and_utilities.md
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/ntpd_configure_restrictions/rule.yml
  linux_os/guide/services/ntp/ntpd_run_as_ntp_user/rule.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/obsolete/r_services/no_host_based_files/rule.yml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/rule.yml
  linux_os/guide/services/ssh/ssh_client/ssh_client_rekey_limit/rule.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  linux_os/guide/services/sssd/sssd_run_as_sssd_user/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_have_homedir_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_home_paths_only/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_forwarding/rule.yml
  linux_os/guide/system/network/network-ipv6/disabling_ipv6/grub2_ipv6_disable_argument/rule.yml
  linux_os/guide/system/network/network-wireless/wireless_software/service_bluetooth_disabled/rule.yml
  linux_os/guide/system/permissions/files/dir_perms_world_writable_system_owned_group/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/rule.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/rule.yml
  tests/CMakeLists.txt
  utils/fix_rules.py
Labels: enhancement, Infrastructure

#7496 OL7 DISA STIG v2r4 update
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/oval/shared.xml
  linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/bash/shared.sh
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_endpoint_security_software/agent_mfetpd_running/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_endpoint_security_software/package_mcafeetp_installed/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_hbss_software/package_MFEhiplsm_installed/rule.yml
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/rule.yml
  products/ol7/profiles/stig.profile
  shared/references/disa-stig-ol7-v2r4-xccdf-manual.xml
Labels: needs-ok-to-test

#7447 UBTU-20-010070: Add ubuntu specific bash and oval to accounts_password_pam_unix_remember
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/oval/ubuntu.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
Labels: Ubuntu, ok-to-test

#7505 Fix the offline remediation of firewalld
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_rate_limiting/bash/shared.sh
  shared/macros-bash.jinja
Labels: bugfix

#7504 SLES-15-010060 corrections
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/banner_etc_gdm_banner/bash/shared.sh
Labels: ok-to-test

#7398 Pcidss Configure Crypto Rules
  linux_os/guide/system/network/network-ipsec/package_libreswan_installed/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  products/sle15/profiles/pci-dss.profile
Labels: SLES, ok-to-test, Update Profile

#7513 OCP4: Update OpenShift CIS Benchmark version
  products/ocp4/profiles/cis-node.profile
  products/ocp4/profiles/cis.profile
Labels: OpenShift

#7510 Add bash remediation for sle15
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/bash/shared.sh
  linux_os/guide/services/sssd/sssd_memcache_timeout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sysadmin_actions/bash/shared.sh
  linux_os/guide/system/logging/ensure_rtc_utc_configuration/bash/shared.sh
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/bash/shared.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_binary_dirs/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/bash/shared.sh
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/shared.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/ansible/shared.yml
Labels: ok-to-test

#7516 Enable bash remediation of audit_rules_dac_modification for SLE
  shared/templates/audit_rules_dac_modification/bash.template
Labels: needs-ok-to-test

#7517 Enable bash remediation of audit_rules_privileged_commands for SLE
  shared/templates/audit_rules_privileged_commands/bash.template
Labels: needs-ok-to-test

#7526 Fix function call introduced by PR #7488
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/ubuntu.sh
Labels: ok-to-test

#7521 Change path in require_singleuser_auth for RHEL7
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml
Labels: DISA Content Issues

#7523 Option --no-reports for SSGTS rule and combined modes
  tests/ssg_test_suite/combined.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/rule.py
  tests/test_suite.py
Labels: Test Suite

#7470 SLE15 add smartcard rules to PCI-DSS profile
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  products/sle15/profiles/pci-dss.profile
Labels: SLES, needs-ok-to-test

#7531 Make display_login_attempts work for Ubuntu
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/default_config.fail.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/wrong_value_silent.fail.sh
Labels: ok-to-test

#7301 SCE - shared/template support
  build-scripts/build_sce.py
  cmake/SSGCommon.cmake
  shared/transforms/shared_shorthand2xccdf.xslt
  shared/transforms/xccdf-addremediations.xslt
  ssg/build_profile.py
  ssg/build_renumber.py
  ssg/build_sce.py
  ssg/build_yaml.py
  ssg/templates.py
Labels: enhancement

#7540 SLES-15-030590: products/sle15/profiles/stig.profile: Fix variable value
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#7543 Add bats to gating and docs
  .github/workflows/build.yaml
  docs/manual/developer/02_building_complianceascode.md
Labels: Documentation

#7535 SLES-15-010460: install_smartcard_packages: SLE15: don't check coolkey package presence
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
Labels: ok-to-test

#7538 SLES-15-030360: add missing umount2 checks
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount2/rule.yml
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#7549 SLES-15-010100: Fix check
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/bash/shared.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/oval/shared.xml
Labels: ok-to-test

#7545 Adjust ctrlaltdel rules for Ubuntu
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/rule.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/tests/masked.pass.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/tests/not_masked.fail.sh
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot/bash/shared.sh
Labels: ok-to-test

#7445 UBTU-20-010074: Add ubuntu remediation and oval for aide_periodic_cron_checking
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/bash/ubuntu.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/bash/ubuntu.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/oval/ubuntu.xml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/tests/crontab_monthly.fail.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/tests/crontab_yearly.fail.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/tests/not_in_cron.fail.sh
Labels: Ubuntu, ok-to-test

#7368 Rule SLES-12-010290 - added ansible,bash and tests
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/tests/correct_max_pas_age.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/tests/incorrect_max_pass_age.fail.sh
Labels: ok-to-test

#7546 Expand Fedora CPE range to cover currently supported Fedora releases
  products/fedora/product.yml
  shared/checks/oval/installed_OS_is_fedora.xml
Labels: ok-to-test

#7537 SLES-15-010570: Fix aide path
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/oval/shared.xml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/rule.yml
  products/sle12/product.yml
  products/sle15/product.yml
  ssg/constants.py
  ssg/products.py
Labels: ok-to-test

#7536 Ubuntu smartcard rules
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_ca/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_ca/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_ca/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_ca/tests/missing_ca.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_cert_checking/tests/missing_ocsp.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/tests/missing_crl.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/oval/ubuntu.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/nothing.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/substring.fail.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7554 Fix set_tests_properties for fix_rules-sort_prodtypes
  tests/CMakeLists.txt
Labels: bugfix

#7539 products/sle15/product.yml: Fix grub.cfg path
  products/sle15/product.yml
Labels: ok-to-test

#7530 Make accounts_password_pam_retry work in Ubuntu
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_enforcing/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_enforcing/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_enforcing/tests/wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/argument_missing.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/wrong_value.fail.sh
Labels: ok-to-test

#7528 Improve accounts_password_pam_tally2
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-account_pam_config_commented
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-account_pam_config_configured
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-account_pam_config_missing
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_big_deny
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_commented
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_configured
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_empty_deny
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_missing
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/common-auth_pam_config_zero_deny
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/missing_pam_tally2.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_big_deny.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_commented.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_configured.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_empty_deny.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_zero_deny.fail.sh
Labels: ok-to-test

#7557 Add Fedora Rawhide support
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_fedora_gpgkey_installed/oval/shared.xml
  products/fedora/product.yml
  shared/checks/oval/installed_OS_is_fedora.xml
Labels: ok-to-test

#7559 Allow specific Jinja processing for test suite
  shared/macros-bash.jinja
  tests/ssg_test_suite/common.py
Labels: bugfix, BLOCKER

#7566 Add metadata to chronyd or ntpd remediations
  .github/workflows/gate.yaml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/ansible/shared.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/bash/shared.sh
Labels: bugfix

#7370 Rule SLES-12-010270 extended with ansible, bash and tests
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_minimum_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/tests/correct_min_pas_age.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/tests/incorrect_min_pass_age.fail.sh
Labels: ok-to-test

#7569 Remove unnecessary debug task
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/ansible/shared.yml
Labels: bugfix

#7571 Force masking of ctrl-alt-del.target in Ansible remediation
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/ansible/shared.yml
Labels: bugfix

#7567 Add PCI-DSS remediations to some rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_immutable/bash/shared.sh
  products/sle15/profiles/pci-dss.profile
  shared/templates/audit_rules_unsuccessful_file_modification/bash.template
  shared/templates/audit_rules_usergroup_modification/bash.template
Labels: SLES, ok-to-test

#7570 Fix typo in rsyslog streamdriver remediations
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/ansible/shared.yml
Labels: bugfix

#7572 Add ubuntu platform to accounts-restrictions and accounts-session rules
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_disable_post_pw_expiration/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_maximum_age_login_defs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/bash/shared.sh
Labels: Ubuntu, ok-to-test

#7581 Update test scenarios to use authselect when authconfig is not available
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/tests/disablefaillock_authconfig.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/tests/remediable_sssd_authconfig.fail.sh
Labels: bugfix

#7580 Install wget to fix the tests pass on stabilization
  .github/workflows/stabilize.yaml
Labels: bugfix

#7583 Fix shebang run scapval
  tests/run_scapval.py
Labels: bugfix

#7584 Add ubuntu platform to rsyslog_remote_access_monitoring bash and tests
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/no_remote_methods.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_multiple_configs.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_rsyslog_conf.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_rsyslog_d.pass.sh
Labels: Ubuntu, ok-to-test

#7585 Add ubuntu platform to approved fips ciphers and macs bash
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers_ordered_stig/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs_ordered_stig/bash/shared.sh
Labels: Ubuntu, ok-to-test

#7586 Add package_apparmor_installed rule and make apparmor_configured work on Ubuntu STIG
  linux_os/guide/system/apparmor/apparmor_configured/bash/shared.sh
  linux_os/guide/system/apparmor/apparmor_configured/rule.yml
  linux_os/guide/system/apparmor/apparmor_configured/tests/installed_disabled.fail.sh
  linux_os/guide/system/apparmor/apparmor_configured/tests/installed_enabled.pass.sh
  linux_os/guide/system/apparmor/package_apparmor_installed/rule.yml
  linux_os/guide/system/apparmor/package_apparmor_installed/tests/installed.pass.sh
  linux_os/guide/system/apparmor/package_apparmor_installed/tests/removed.fail.sh
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, ok-to-test

#7575 SLE bash remediation for audit,smartcard and sysctl rules
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/bash/shared.sh
  shared/templates/audit_rules_login_events/bash.template
  shared/templates/sysctl/bash.template
Labels: SLES, ok-to-test

#7582 Merge first round of fixes from 0.1.58 stabilization
  .github/workflows/gate.yaml
  .github/workflows/stabilize.yaml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/ansible/shared.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/tests/disablefaillock_authconfig.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/tests/remediable_sssd_authconfig.fail.sh
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/ansible/shared.yml
  shared/macros-bash.jinja
  tests/run_scapval.py
  tests/ssg_test_suite/common.py
Labels: bugfix

#7324 Automated STIG Control File Creation
  controls/stig_rhel8.yml
  docs/manual/developer/05_tools_and_utilities.md
  utils/build_stig_control.py
Labels: Infrastructure

#7389 locking_out_password_attempts/accounts_password_pam_unix_remember/oval/shared.xml: sles15 fix
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/oval/shared.xml
Labels: SLES, ok-to-test, Update Rule

#7515 Add Styleguide
  CONTRIBUTING.md
  docs/manual/developer/01_introduction.md
  docs/manual/developer/04_style_guide.md
Labels: help-wanted, Documentation

#7576 SLE bash remediation enable for some account related rules
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_disable_post_pw_expiration/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions/bash/shared.sh
  products/sle12/profiles/stig.profile
  products/sle15/profiles/pci-dss.profile
  products/sle15/profiles/stig.profile
Labels: SLES, ok-to-test

#7607 Fix Ubuntu 20.04 SCAP 1.2 validation
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/oval/ubuntu.xml
Labels: bugfix

#7595 Add rule sshd_enable_pubkey_auth
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/commented.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/correct.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/disabled.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/substring.fail.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7589 Create rule verify_use_mappers
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/verify_use_mappers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/verify_use_mappers/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/verify_use_mappers/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/verify_use_mappers/tests/nothing.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/verify_use_mappers/tests/substring.fail.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7608 Fix and Add 1.2 Validation to Stabilization GitHub Action
  .github/workflows/stabilize.yaml
Labels: bugfix

#7611 Enable shell remediation for aide_check_audit_tools rule on SLE platform
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/bash/shared.sh
Labels: needs-ok-to-test

#7596 Break the shared bash install_smartcard_packages remediation
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/bash/sle12.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/bash/sle15.sh
Labels: SLES, ok-to-test

#7614 Fix CombinedChecker run_aborted traceback
  tests/ssg_test_suite/combined.py
Labels: bugfix

#7591 Add rule no_duplicate_uids
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_duplicate_uids/oval/ubuntu.xml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_duplicate_uids/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_duplicate_uids/tests/duplicate_user_uid.fail.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_duplicate_uids/tests/unique_user_uid.pass.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7602 Add rule sshd_enable_pam
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/commented.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/correct.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/disabled.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/substring.fail.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7558 Add initial support kube remediation templating
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/tests/ocp4/e2e-remediation.sh
  shared/macros-kubernetes.jinja
Labels: ok-to-test

#7622 Fix requirements of section3
  controls/pcidss_ocp4.yml
Labels: ok-to-test

#7636 Add bios_enable_execution_restrictions to Ubuntu 20.04 STIG profile
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/oval/shared.xml
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7625 Add rule audit_sudo_log_events
  linux_os/guide/system/auditing/auditd_configure_rules/audit_sudo_log_events/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7063 improve documentation
  README.md
  docs/index.rst
  docs/manual/developer/03_creating_content.md
  docs/manual/developer/06_contributing_with_content.md
  docs/templates/template_reference.md
  products/example/README.md
  shared/macros-highlevel.jinja
Labels: Documentation

#7646 Fix packing of kickstarts in zipfile
  cmake/SSGCommon.cmake
Labels: bugfix

#7645 Add sphinx missing dependency in the developer guide
  docs/manual/developer/02_building_complianceascode.md
Labels: Documentation

#7644 Add file_permissions_etc_audit_* rules to Ubuntu 20.04 STIG profile
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: needs-ok-to-test

#7648 Fix typo in audit_perm_change_success rule
  linux_os/guide/system/auditing/policy_rules/audit_perm_change_success/rule.yml
Labels: needs-ok-to-test

#7604 Add rules banner_etc_issue_net and sshd_enable_warning_banner_net
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/bash/shared.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/oval/shared.xml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/rule.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_dod_default_banner.pass.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_dod_default_banner_no_newline.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_dod_short.pass.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_double_banner.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_usgcb_banner.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_disa_with_extra_line.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_ospp_usbcg_banner.fail.sh
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/tests/banner_etc_issue_net_ospp_usbcg_banner.pass.sh
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7638 Test scenarios updates for gpgcheck rules
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/tests/comment.fail.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/tests/correct_value.pass.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/tests/line_not_there.fail.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/tests/wrong_value.fail.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/tests/gpgcheck_disabled.fail.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/tests/gpgcheck_enabled.pass.sh
  tests/shared/group_updating_utils.sh
Labels: Test Scenario

#7632 service_enabled test scenarios templates
  shared/templates/service_enabled/tests/service_disabled.fail.sh
  shared/templates/service_enabled/tests/service_enabled.pass.sh
Labels: Test Scenario

#7637 Create test scenarios for rule gid_passwd_group_same
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/tests/all_groups_exist.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/tests/user_with_nonexistent_group.fail.sh
Labels: Test Scenario

#7631 ntp/chrony remove server remediations and test scenarios
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/correct.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/correct_pool.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/file_empty.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/file_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/line_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/multiple_servers.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/server_not_specified.fail.sh
  linux_os/guide/services/ntp/ntpd_specify_remote_server/ansible/shared.yml
  linux_os/guide/services/ntp/ntpd_specify_remote_server/bash/shared.sh
  linux_os/guide/services/ntp/ntpd_specify_remote_server/tests/correct.pass.sh
  linux_os/guide/services/ntp/ntpd_specify_remote_server/tests/file_empty.fail.sh
  linux_os/guide/services/ntp/ntpd_specify_remote_server/tests/file_missing.fail.sh
  linux_os/guide/services/ntp/ntpd_specify_remote_server/tests/multiple_servers.pass.sh
Labels: Test Scenario

#7651 Merge fixes for 0.1.58 release
  .github/workflows/stabilize.yaml
  Contributors.md
  Contributors.xml
  cmake/SSGCommon.cmake
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/tests/correct_value.pass.sh
  linux_os/guide/system/software/integrity/crypto/harden_openssl_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/oval/ubuntu.xml
  ssg/contributors.py
  tests/ssg_test_suite/combined.py
Labels: bugfix

#7642 Add a fail test for accounts_password_all_shadowed
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed/oval/shared.xml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed/tests/hash.fail.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed/tests/x_in_hash.fail.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed/tests/x_in_username.fail.sh
Labels: Test Scenario

#7634 Add test scenarios specific for CIS
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/rhel7_correct_value_cis_l2.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/rhel7_correct_value_cis_l2.pass.sh
Labels: Test Scenario

#7623 Add new audit rules privileged commands for Ubuntu STIG
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_apparmor_parser/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/auditctl_correct.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/auditctl_remove_all_rules.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/auditctl_wrong_rule.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/augenrules_correct.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/augenrules_remove_all_rules.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/tests/augenrules_wrong_rule.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_unix_update/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7653 Add ensure_sudo_group_restricted to Ubuntu 20.04 STIG profile
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/ensure_sudo_group_restricted/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7654 Add rule prevent_direct_root_logins
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/prevent_direct_root_logins/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7621 remove rule disable_prelink from rhel7 cis
  controls/cis_rhel7.yml
Labels: Update Profile

#7656 Make package_mcafeetp_installed work on Ubuntu
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_endpoint_security_software/package_mcafeetp_installed/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: ok-to-test

#7641 Implementing test ssh_set_max_sessions for rhel7 profiles
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/tests/rhel7_correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/tests/wrong_value.fail.sh
Labels: Test Scenario

#7664 Add rule to stig.profiles
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#7663 Fix for issue #7655
  ssg/build_yaml.py
Labels: ok-to-test

#7662 SLE bash of accounts_authorized_local_users rule
  linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/bash/shared.sh
Labels: SLES, ok-to-test

#7661 SLE bash remediation accounts_passwords_pam_faildelay_delay
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faildelay_delay/bash/sle12.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faildelay_delay/bash/sle15.sh
  products/sle15/profiles/stig.profile
Labels: SLES, ok-to-test, Update Profile

#7658 Add rule only_allow_dod_certs
  linux_os/guide/system/network/network_ssl/only_allow_dod_certs/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, New Rule, ok-to-test

#7609 Add remaining Blueprint templates
  docs/templates/template_reference.md
  linux_os/guide/system/software/disk_partitioning/partition_for_boot/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_home/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_opt/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_srv/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_tmp/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_usr/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log_audit/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_tmp/rule.yml
  shared/templates/grub2_bootloader_argument/blueprint.template
  shared/templates/grub2_bootloader_argument/template.yml
  shared/templates/mount/blueprint.template
  shared/templates/mount/template.yml
  shared/templates/service_disabled/blueprint.template
  shared/templates/service_disabled/template.yml
  shared/templates/service_enabled/blueprint.template
  shared/templates/service_enabled/template.yml
Labels: Blueprint

#7668 Remove leftover remediation_functions calls
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue_net/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/bash/ubuntu.sh
Labels: ok-to-test

#7674 Remove STIG ref RHEL-07-040510 as its no longer in the STIG
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_invalid_ratelimit/rule.yml
Labels: DISA RHEL7 STIG Alignment

#7673 Add RHEL8 FIPS STIG ID to a few rules
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_macs_openssh_conf_crypto_policy/rule.yml
Labels: DISA RHEL8 STIG Alignment

#7672 Clarify doc for check-export in SCE
  docs/manual/developer/06_contributing_with_content.md
Labels: needs-ok-to-test

#7666 Added Build, Test on OpenSUSE Leap 15 on pull requests
  .github/workflows/gate.yaml
Labels: Infrastructure, SLES

#7529 SLES-15-030730,030740,030750 corrections
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat2/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlinkat/rule.yml
  shared/templates/audit_rules_syscall_events/ansible.template
  shared/templates/audit_rules_syscall_events/bash.template
  shared/templates/audit_rules_syscall_events/kubernetes.template
  shared/templates/audit_rules_syscall_events/oval.template
  shared/templates/audit_rules_syscall_events/template.yml
Labels: ok-to-test

#7650 Created pass/fail scripts for rule sshd_use_approved_macs
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/tests/default_correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/tests/rhel7_correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/tests/wrong_value.fail.sh
Labels: Test Scenario
