Repository ComplianceAsCode/content, pull requests merged in 2021-11, with the labels that each got.

#7613 Ground work for implementation of CPE applicability language
  build-scripts/cpe_generate.py
  ssg/build_cpe.py
  ssg/build_yaml.py
  ssg/constants.py
  tests/ssg_test_suite/xml_operations.py
  tests/test_machine_only_rules.py
Labels: Infrastructure, usability, Highlight

#7784 Fix bash remediation spurious variable substitution
  shared/macros-bash.jinja
Labels: ok-to-test

#7776 Add HIPAA profile to SLE15 platform
  products/sle15/profiles/hipaa.profile
Labels: ok-to-test, New Profile

#7817 Add HIPAA Rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_restorecon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_semanage/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_setsebool/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_postdrop/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_postqueue/rule.yml
  products/sle15/profiles/hipaa.profile
Labels: ok-to-test

#7821 Fix `utils/fix_rules.py` exit codes
  linux_os/guide/services/apt/apt_conf_disallow_unauthenticated/rule.yml
  linux_os/guide/services/apt/apt_sources_list_official/rule.yml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/snmp/disabling_snmp_service/package_net-snmp_removed/rule.yml
  linux_os/guide/services/snmp/disabling_snmp_service/service_snmpd_disabled/rule.yml
  linux_os/guide/services/snmp/snmp_configure_server/snmpd_not_default_password/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/rule.yml
  linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml
  linux_os/guide/services/usbguard/package_usbguard_installed/rule.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_ftruncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_by_handle_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_openat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_truncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_lastlog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_tallylog/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_atm_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_can_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_firewire-core_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/coredump_disable_backtraces/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/coredump_disable_storage/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/disable_users_coredumps/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/service_systemd-coredump_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/package_aide_installed/rule.yml
  utils/fix_rules.py
Labels: Infrastructure

#7785 Improve jinja docs
  docs/manual/developer/04_style_guide.md
  shared/macros-ansible.jinja
  shared/macros-bash.jinja
  shared/macros-highlevel.jinja
  shared/macros-kubernetes.jinja
  shared/macros-oval.jinja
  shared/macros.jinja
Labels: Documentation

#7799 Make datastream matching more strict when building man page
  build-scripts/generate_man_page.py
Labels: bugfix

#7787 Make sure files have newline during bash lineinfile remediation
  shared/macros-bash.jinja
Labels: Bash

#7825 Introduced graphs in the documentation
  docs/flowcharts/flowchart_benchmarks.md
  docs/flowcharts/flowchart_build.md
  docs/flowcharts/flowchart_controls.md
  docs/flowcharts/flowchart_docs.md
  docs/flowcharts/flowchart_products.md
  docs/flowcharts/flowchart_rules.md
  docs/flowcharts/flowchart_shared.md
  docs/flowcharts/flowchart_tests.md
  docs/flowcharts/flowchart_utils.md
  docs/flowcharts/introduction.rst
  docs/index.rst
Labels: Documentation

#7803 Implement partially Req 3.4 PCIDSS
  applications/openshift/integrity/crypto/ebs_encryption_enabled_on_machinesets/rule.yml
  applications/openshift/integrity/crypto/ebs_encryption_enabled_on_machinesets/tests/ebs_encrypted.pass.sh
  applications/openshift/integrity/crypto/ebs_encryption_enabled_on_machinesets/tests/no_ebs_encryption.fail.sh
  applications/openshift/integrity/crypto/ebs_encryption_enabled_on_machinesets/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/fips_mode_enabled/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/fips_mode_enabled_on_all_nodes/rule.yml
  applications/openshift/integrity/crypto/fips_mode_enabled_on_all_nodes/tests/fips_disabled.fail.sh
  applications/openshift/integrity/crypto/fips_mode_enabled_on_all_nodes/tests/fips_enabled.pass.sh
  applications/openshift/integrity/crypto/fips_mode_enabled_on_all_nodes/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/luks_enabled_on_all_nodes/rule.yml
  applications/openshift/integrity/crypto/luks_enabled_on_all_nodes/tests/luks_configured.pass.sh
  applications/openshift/integrity/crypto/luks_enabled_on_all_nodes/tests/luks_not_configured.fail.sh
  applications/openshift/integrity/crypto/luks_enabled_on_all_nodes/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/machine_volume_encrypted/oval/shared.xml
  applications/openshift/integrity/crypto/machine_volume_encrypted/rule.yml
  applications/openshift/integrity/crypto/machine_volume_encrypted/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/storageclass_encryption_enabled/rule.yml
  applications/openshift/integrity/crypto/storageclass_encryption_enabled/tests/ocp4/e2e.yml
  applications/openshift/integrity/crypto/storageclass_encryption_enabled/tests/storageclass_encrypted.pass.sh
  applications/openshift/integrity/crypto/storageclass_encryption_enabled/tests/storageclass_not_encrypted.fail.sh
  controls/pcidss_ocp4.yml
  shared/references/cce-redhat-avail.txt
Labels: ok-to-test

#7829 OCP/PCI-DSS: Add responses for Req-6.1 and Req-6.2
  controls/pcidss_ocp4.yml
Labels: OpenShift

#7830 Implement requirements 3.5, 3.6 and 3.7 of PCIDSS
  controls/pcidss_ocp4.yml
Labels: OpenShift, ok-to-test

#7819 Add More HIPAA Rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_userhelper/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/rule.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_credential_prompt/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_credential_prompt/rule.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_encryption/ansible/shared.yml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_encryption/rule.yml
  products/sle15/profiles/hipaa.profile
Labels: ok-to-test

#7812 Add CCE ids for SLE15 platform for some HIPAA related rules
  linux_os/guide/services/cron_and_at/service_crond_enabled/rule.yml
  linux_os/guide/services/obsolete/inetd_and_xinetd/package_xinetd_removed/rule.yml
  linux_os/guide/services/obsolete/inetd_and_xinetd/service_xinetd_disabled/rule.yml
  linux_os/guide/services/obsolete/r_services/no_rsh_trust_files/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk-server_removed/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk_removed/rule.yml
  linux_os/guide/services/obsolete/telnet/package_telnet_removed/rule.yml
  linux_os/guide/services/obsolete/telnet/service_telnet_disabled/rule.yml
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_allow_only_protocol2/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_kerb_auth/rule.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/restrict_serial_port_logins/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/securetty_root_login_console_only/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_umount/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/file_permissions_grub2_cfg/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/sysctl_fs_suid_dumpable/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_dmesg_restrict/rule.yml
  linux_os/guide/system/selinux/grub2_enable_selinux/rule.yml
  linux_os/guide/system/selinux/selinux_confinement_of_daemons/rule.yml
  linux_os/guide/system/selinux/selinux_policytype/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
Labels: SLES, ok-to-test

#7755 Fix Ansible for rsyslog_encrypt_offload_*
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/ansible/shared.yml
  shared/macros-ansible.jinja
Labels: bugfix

#7811 Add unit test for kubelet_enable_iptables_util_chains
  applications/openshift/kubelet/kubelet_enable_iptables_util_chains/tests/enable_iptables_util_chains.fail.sh
  applications/openshift/kubelet/kubelet_enable_iptables_util_chains/tests/enable_iptables_util_chains.pass.sh
  applications/openshift/kubelet/kubelet_enable_iptables_util_chains/tests/enable_iptables_util_chains_false_key.fail.sh
Labels: ok-to-test

#7837 Interactive user initialization files
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/expected_groupowner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/home_dirs_all_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/home_dirs_one_absent_group_ok.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/no_dot_file_ignored.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/unexpected_groupowner_system_gid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/unexpected_groupowner_unknown_gid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/tests/warning_swapped_groupowners.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/expected_permissions.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/home_dirs_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/lenient_permission.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/more_restrictive_permission.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/no_dot_file_ignored.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/expected_owner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/home_dirs_all_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/home_dirs_one_absent_owner_ok.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/no_dot_file_ignored.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/unexpected_owner_system_uid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/unexpected_owner_unknown_uid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/tests/warning_swapped_owners.pass.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/home_dirs_all_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/home_dirs_one_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/no_dot_file_ignored.pass.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/umask_defined.fail.sh
Labels: DISA RHEL7 STIG Alignment, DISA RHEL8 STIG Alignment, RHEL8 CIS Alignment

#7842 Fix banner regex to address change in PR #7784
  ssg/utils.py
Labels: bugfix, ok-to-test

#7813 SLE15 Add rsh and talk server remove rules to HIPAA profile
  linux_os/guide/services/obsolete/r_services/package_rsh-server_removed/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk-server_removed/rule.yml
  products/sle15/profiles/hipaa.profile
Labels: SLES, ok-to-test, Update Rule, Update Profile

#7779 accounts_no_uid_except_zero: Don't run `passwd` if `awk` returns nothing
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/bash/shared.sh
Labels: Bash

#7751 Change `sshd_set_idle_timeout` to require `sshd_set_keepalive_0`
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/rule.yml
  products/fedora/profiles/pci-dss.profile
  products/fedora/profiles/standard.profile
  products/rhcos4/profiles/ospp.profile
  products/rhel9/profiles/cjis.profile
  products/rhel9/profiles/ospp.profile
  products/rhel9/profiles/pci-dss.profile
  products/rhel9/profiles/rht-ccp.profile
  products/rhel9/profiles/stig.profile
  products/ubuntu2004/profiles/standard.profile
Labels: Update Profile

#7845 Add these rules as valid for RHEL9
  linux_os/guide/services/base/service_cockpit_disabled/rule.yml
  linux_os/guide/services/ldap/389_ds/package_389-ds-base_removed/rule.yml
  linux_os/guide/services/snmp/snmp_configure_server/snmpd_no_rwusers/rule.yml
Labels: ok-to-test

#7856 Fix comment replacement in Compare DS GH action.
  .github/workflows/compare-ds.yaml
Labels: bugfix

#7836 Implement PCIDSS Section 4
  applications/openshift/etcd/etcd_check_cipher_suite/rule.yml
  applications/openshift/etcd/etcd_check_cipher_suite/tests/etcd_cipher_suite.fail.sh
  applications/openshift/etcd/etcd_check_cipher_suite/tests/etcd_cipher_suite.pass.sh
  applications/openshift/etcd/etcd_check_cipher_suite/tests/ocp4/e2e.yml
  applications/openshift/general/tls_version_check_apiserver/rule.yml
  applications/openshift/general/tls_version_check_apiserver/tests/ocp4/e2e.yml
  applications/openshift/general/tls_version_check_apiserver/tests/tls_version.fail.sh
  applications/openshift/general/tls_version_check_apiserver/tests/tls_version.pass.sh
  applications/openshift/general/tls_version_check_masters_workers/rule.yml
  applications/openshift/general/tls_version_check_masters_workers/tests/ocp4/e2e.yml
  applications/openshift/general/tls_version_check_masters_workers/tests/tls_version.fail.sh
  applications/openshift/general/tls_version_check_masters_workers/tests/tls_version.pass.sh
  applications/openshift/general/tls_version_check_router/rule.yml
  applications/openshift/general/tls_version_check_router/tests/ocp4/e2e.yml
  applications/openshift/general/tls_version_check_router/tests/tls_version.fail.sh
  applications/openshift/general/tls_version_check_router/tests/tls_version.pass.sh
  controls/pcidss_ocp4.yml
  shared/references/cce-redhat-avail.txt
Labels: ok-to-test

#7824 Permissions and ownership of files under home directories
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/expected_groupowner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/home_dirs_all_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/home_dirs_one_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/unexpected_groupowner_system_gid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/unexpected_groupowner_unknown_gid.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/tests/warning_home_dirs_swapped_groupowner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/expected_owner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/home_dirs_all_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/home_dirs_one_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/unexpected_owner_system_id.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/unexpected_owner_unknown_id.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/tests/warning_home_dirs_swapped_owner.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/acceptable_permission.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/expected_permissions.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/home_dirs_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/lenient_permission.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/lenient_permission_hidden_files.fail.sh
  linux_os/guide/system/accounts/accounts-session/file_groupownership_home_directories/tests/unexpected_groupowner_system_uid.fail.sh
  linux_os/guide/system/accounts/accounts-session/file_groupownership_home_directories/tests/unexpected_groupowner_unknown_uid.fail.sh
Labels: DISA RHEL7 STIG Alignment, DISA RHEL8 STIG Alignment, RHEL8 CIS Alignment

#7858 Update tests for package_crypto-policies_installed
  linux_os/guide/system/software/integrity/crypto/package_crypto-policies_installed/tests/package-installed-removed.fail.sh
  linux_os/guide/system/software/integrity/crypto/package_crypto-policies_installed/tests/package-removed.fail.sh
Labels: Test Scenario

#7861 Revert PR #7842 and improve deregexify
  shared/macros-bash.jinja
  ssg/utils.py
Labels: bugfix, ok-to-test

#7796 Add rule schema
  shared/schemas/rule.json
Labels: Documentation

#7487 SLES-15-030720 - fixes
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat/rule.yml
Labels: SLES, ok-to-test

#7849 SLE15 Add selinux rules to HIPAA profile
  linux_os/guide/system/selinux/selinux-booleans/sebool_selinuxuser_execheap/rule.yml
  linux_os/guide/system/selinux/selinux-booleans/sebool_selinuxuser_execmod/rule.yml
  linux_os/guide/system/selinux/selinux-booleans/sebool_selinuxuser_execstack/rule.yml
  products/sle15/profiles/hipaa.profile
  shared/templates/sebool/ansible.template
  shared/templates/sebool/bash.template
Labels: ok-to-test

#7790 Home directories definition and existence
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_all_empty.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_defined_out_home.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_not_exclusive.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_one_empty.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_properly_defined.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_root.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/interactive_users_absent.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/tests/home_dir_present.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/tests/home_dirs_all_absent.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/tests/home_dirs_one_absent.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/tests/interactive_users_absent.pass.sh
Labels: DISA RHEL7 STIG Alignment, DISA RHEL8 STIG Alignment, RHEL8 CIS Alignment, RHEL7 CIS Alignment

#7851 Add Delta Tailoring Files to the Build System
  CMakeLists.txt
  cmake/SSGCommon.cmake
  docs/manual/developer/05_tools_and_utilities.md
  shared/references/disa-stig-rhel7-v3r5-xccdf-scap.xml
  shared/references/disa-stig-rhel8-v1r3-xccdf-scap.xml
  utils/create_scap_delta_tailoring.py
Labels: Infrastructure

#7852 SLE15 add service related rules to HIPAA profile
  linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml
  linux_os/guide/services/cron_and_at/service_crond_enabled/rule.yml
  linux_os/guide/services/obsolete/r_services/service_rexec_disabled/rule.yml
  linux_os/guide/services/obsolete/r_services/service_rlogin_disabled/rule.yml
  linux_os/guide/services/obsolete/telnet/service_telnet_disabled/rule.yml
  linux_os/guide/services/routing/disabling_quagga/service_zebra_disabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  products/sle15/profiles/hipaa.profile
Labels: SLES, ok-to-test, Update Profile

#7318 Make FIPS mode check idempotent
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/ansible/shared.yml
Labels: Ansible, ok-to-test

#7881 Fix typo in audit_immutable_login_uids
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/rule.yml
Labels: bugfix

#7879 Add CentOS 7 build to CI
  .github/workflows/gate.yaml
  ssg/build_yaml.py
  utils/create_scap_delta_tailoring.py
  utils/fix_rules.py
Labels: Infrastructure

#7876 Add the ability to load controls from folder
  docs/manual/developer/03_creating_content.md
  ssg/controls.py
  tests/unit/ssg-module/data/controls_dir/jklm.yml
  tests/unit/ssg-module/data/controls_dir/jklm/r1.yml
  tests/unit/ssg-module/data/controls_dir/jklm/r3.yml
  tests/unit/ssg-module/test_controls.py
Labels: Infrastructure

#7898 Fix remediation for accounts_umask_interactive_users
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/hidden_folder_ignored.pass.sh
Labels: bugfix

#7901 OCP4: Fix typos in etcd cipher
  applications/openshift/api-server/api_server_encryption_provider_cipher/rule.yml
  applications/openshift/api-server/api_server_encryption_provider_config/rule.yml
Labels: OpenShift

#7899 Rename/remove rule for package abrt-addon-python
  linux_os/guide/system/software/system-tools/package_abrt-addon-python_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_python3-abrt-addon_removed/rule.yml
  products/rhel8/profiles/ospp.profile
  products/rhel8/profiles/stig.profile
  products/rhel9/profiles/ospp.profile
  products/rhel9/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/ospp.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: New Rule

#7859 update description of grub2_uefi_password
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/rule.yml
Labels: Update Rule

#7894 Add `utils/compare_results.py`
  docs/manual/developer/05_tools_and_utilities.md
  utils/compare_results.py
Labels: Infrastructure

#7873 Introduce handling of versioned Boolean algebra expressions
  .github/workflows/compare-ds.yaml
  .github/workflows/ctf.yaml
  .github/workflows/gate-lint-ansible-roles.yaml
  .github/workflows/gate.yaml
  docs/manual/developer/02_building_complianceascode.md
  ssg/boolean_expression.py
  ssg/ext/__init__.py
  ssg/ext/boolean/README
  ssg/ext/boolean/__init__.py
  ssg/ext/boolean/boolean.py
  tests/unit/ssg-module/test_boolean_expressions.py
Labels: enhancement, Infrastructure, usability

#7906 remove ABRT related rules from RHEL9
  linux_os/guide/services/base/package_abrt_removed/rule.yml
  linux_os/guide/services/base/service_abrtd_disabled/rule.yml
  linux_os/guide/system/selinux/selinux-booleans/sebool_abrt_anon_write/rule.yml
  linux_os/guide/system/selinux/selinux-booleans/sebool_abrt_handle_event/rule.yml
  linux_os/guide/system/selinux/selinux-booleans/sebool_abrt_upload_watch_anon_write/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-addon-ccpp_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-addon-kerneloops_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-cli_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-logger_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-rhtsupport_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-sosreport_removed/rule.yml
  products/rhel9/profiles/ospp.profile
  products/rhel9/profiles/rht-ccp.profile
  products/rhel9/profiles/standard.profile
  products/rhel9/profiles/stig.profile
Labels: RHEL9, Update Rule, Update Profile

#7905 SLE15 add use_kerberos_security_all_exports rule to HIPAA profile
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/ansible/shared.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/bash/shared.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/tests/no_sec_export.fail.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/tests/sec_export_default_sys.fail.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/tests/sec_krb_auth_only.fail.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/tests/sec_krb_integr_priv.pass.sh
  products/sle15/profiles/hipaa.profile
Labels: needs-ok-to-test

#7885 Update restorecon and seunshare audit rules description to match OVAL
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_restorecon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_seunshare/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newgidmap/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newuidmap/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_pt_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_sudoedit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_unix2_chkpwd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_usernetctl/rule.yml
Labels: bugfix

#7917 OCP4/PCI-DSS: Update section-8
  applications/openshift/authentication/idp_is_configured/rule.yml
  controls/pcidss_ocp4.yml
Labels: ok-to-test

#7914 Fix typo in new_rule.md
  .github/ISSUE_TEMPLATE/new_rule.md
Labels: ok-to-test

#7909 add hint about audit backlog configuration
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/rule.yml
Labels: Documentation, Update Rule

#7910 Update `chronyd_or_ntpd_set_maxpoll` to add maxpoll option to chrony pool directives
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/oval/shared.xml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony.pass.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_configured.pass.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_misconfigured.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_missing_parameter.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_server_misconfigured.fail.sh
Labels: bugfix, Update Rule

#7925 Update OL7 030360 DISA requirement
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
  products/ol7/profiles/stig.profile
Labels: Oracle Linux, needs-ok-to-test

#7875 Fix RHEL9 content
  linux_os/guide/services/dhcp/disabling_dhcp_server/package_dhcp_removed/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/rhel8_argument_missing.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/rhel8_correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/tests/rhel8_wrong_value.fail.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/arg_not_there_rhel8.fail.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/blank_grubenv_rhel8.fail.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/correct_grubenv.pass.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/double_value_rhel8.fail.sh
  linux_os/guide/system/auditing/grub2_audit_argument/tests/grubenv
  linux_os/guide/system/auditing/grub2_audit_argument/tests/wrong_value_rhel8.fail.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/tests/fedora_key.fail.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/tests/key_installed.pass.sh
  products/rhel9/profiles/cui.profile
  products/rhel9/profiles/standard.profile
  products/rhel9/profiles/stig.profile
  products/rhel9/profiles/stig_gui.profile
  shared/templates/grub2_bootloader_argument/ansible.template
  shared/templates/sebool/ansible.template
Labels: bugfix

#7904 Add a split option to `utils/build_stig_control.py`
  docs/manual/developer/05_tools_and_utilities.md
  utils/build_stig_control.py
Labels: Infrastructure

#7930 Update RHEL8 STIG to V1R4
  controls/stig_rhel8.yml
  docs/manual/developer/05_tools_and_utilities.md
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_csh_cshrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/rule.yml
  products/rhel8/profiles/stig.profile
  products/rhel8/profiles/stig_gui.profile
  products/rhel9/profiles/stig.profile
  shared/references/disa-stig-rhel8-v1r4-xccdf-manual.xml
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment

#7826 Upgrade to F34 in Gating
  .github/workflows/gate.yaml
Labels: Infrastructure
