Repository ComplianceAsCode/content, pull requests merged in 2021-07, with the labels that each got.

#7171 Map file_ownership_library_dirs to SLES-12-010873
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/rule.yml
  products/sle12/profiles/stig.profile
Labels: ok-to-test

#7173 Map root_permissions_syslibrary_files to SLES-12-010875
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
  products/sle12/profiles/stig.profile
Labels: ok-to-test

#7158 Add SLES-12-010112
  linux_os/guide/system/software/sudo/sudoers_validate_passwd/rule.yml
  products/sle12/profiles/stig.profile
Labels: needs-ok-to-test

#7180 Adding file_groupownership_system_commands_dirs to RHEL8 STIG
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/ansible/shared.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/bash/shared.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/tests/correct_groupownership.pass.sh
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment

#7184 Map SLES-12-010877 to file_permissions_system_commands_dirs rule
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_system_commands_dirs/oval/shared.xml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_system_commands_dirs/rule.yml
  products/sle12/profiles/stig.profile
Labels: ok-to-test

#7069 Add rule to configure MaxStartups for sshd
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/var_sshd_set_maxstartups.var
  products/rhel8/profiles/cis.profile
  shared/references/cce-redhat-avail.txt
Labels: ok-to-test

#7189 Expand valid values available for auditd num_logs setting
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_max_log_file.var
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_num_logs.var
Labels: ok-to-test

#7207 Fix sshd service name in Ubuntu
  linux_os/guide/services/ssh/service_sshd_enabled/rule.yml
Labels: ok-to-test

#7205 Adjust grub2 rules and templates for Ubuntu
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/rule.yml
  shared/templates/grub2_bootloader_argument/ansible.template
  shared/templates/grub2_bootloader_argument/bash.template
  shared/templates/grub2_bootloader_argument/oval.template
Labels: ok-to-test

#7206 Improve OVAL and add bash for ensure_rtc_utc_configuration
  linux_os/guide/system/logging/ensure_rtc_utc_configuration/bash/shared.sh
  linux_os/guide/system/logging/ensure_rtc_utc_configuration/oval/shared.xml
Labels: ok-to-test

#7204 Make some rules descriptions generic and add ubuntu specific bits
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/policy_temp_passwords_immediate_change/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_usermod/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_sufficiently_large_partition/rule.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/rule.yml
Labels: ok-to-test

#7159 Map sudo_require_reauthentication to SLES-12-010113
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/rule.yml
  products/sle12/profiles/stig.profile
Labels: needs-ok-to-test

#7185 Add binary and system commands permission/ownership rules to SLE12
  linux_os/guide/system/permissions/files/dir_system_commands_group_root_owned/rule.yml
  linux_os/guide/system/permissions/files/dir_system_commands_root_owned/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_binary_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_binary_dirs/rule.yml
  products/sle12/profiles/stig.profile
Labels: ok-to-test

#7179 Add implementation of dir_group_ownership_library_dirs rule
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/ansible/shared.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/oval/shared.xml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/tests/all_dirs_ok.pass.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/tests/nobody_group_owned_dir_on_lib.fail.sh
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
Labels: needs-ok-to-test

#6990 display_login_attempts - DISA STIG compliance
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/bash/sle12.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/rule.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/wrong_value_silent.fail.sh
Labels: DISA RHEL8 STIG Alignment, SSG-DISA RHEL7 STIG Alignment, needs-ok-to-test

#7210 SSGTS: Jinja enablement for test cases
  ssg/products.py
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/test_env.py
  tests/test_suite.py
Labels: Infrastructure, SSGTestSuite, enhancement

#7221 Generate more reproducible remediations
  ssg/build_remediations.py
Labels: bugfix

#7239 Pass the input directory to the playbook builder explicitly
  cmake/SSGCommon.cmake
Labels: RHEL9, bugfix

#7237 fix problems with variables in rhel7 cis
  controls/cis_rhel7.yml
  linux_os/guide/services/ssh/sshd_approved_macs.var
  linux_os/guide/system/software/sudo/var_sudo_logfile.var
Labels: bugfix

#7224 Prioritize install_smartcard_packages like package_*_installed
  ssg/build_yaml.py
Labels: bugfix

#7244 Replace gpg keys to support Fedora 33 to 35
  products/fedora/product.yml
Labels: ok-to-test

#7242 Enable remediations for crypto policy settings
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/bash/shared.sh
Labels: RHEL9

#7250 Add RHEL-08-010590 STIG to existing rule
  linux_os/guide/system/permissions/partitions/mount_option_home_noexec/rule.yml
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment

#7209 Update 'Configure Notification of Post-AIDE Scan Details' for RHEL8 DISA STIG Alignment
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/var_aide_scan_notification_email.var
Labels: DISA RHEL8 STIG Alignment, ok-to-test

#7255 fix ansible of accounts_root_path_dirs_no_write
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/tests/wrong.fail.sh
Labels: Ansible, Test Scenario, bugfix

#7217 Select two more rules in RHEL7 STIG
  products/rhel7/profiles/stig.profile
Labels: DISA RHEL7 STIG Alignment

#7252 add / fix remediations for audit rules wrt modules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_insmod/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_insmod/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_modprobe/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_modprobe/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_rmmod/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_rmmod/bash/shared.sh
Labels: bugfix

#7241 Added RHEL9 kickstarts
  products/rhel9/kickstart/ssg-rhel9-anssi_bp28_enhanced-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-anssi_bp28_high-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-anssi_bp28_intermediary-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-anssi_bp28_minimal-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-cis-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-cui-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-e8-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-hipaa-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-ospp-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-pci-dss-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-stig-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-stig_gui-ks.cfg
Labels: RHEL9

#6916 Document rule.yml modification utilities
  docs/manual/developer/05_tools_and_utilities.md
Labels: Documentation

#7256 Add rules for RHEL-08-030610
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/tests/correct_permissions.pass.sh
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/tests/incorrect_permissions.fail.sh
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/tests/correct_permissions.pass.sh
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/tests/incorrect_permissions.fail.sh
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7227 Add oval check for bios_enable_execution_restrictions
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/oval/shared.xml
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/rule.yml
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, OVAL

#7259 Correct some issues with the CIS ICMP redirects rule on RHEL 7/8
  controls/cis_rhel7.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_redirects/rule.yml
Labels: Update Profile, Update Rule, bugfix, ok-to-test

#7223 Add Ubuntu to cron.allow, at.allow rules for CIS
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_cron_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_cron_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_cron_allow/rule.yml
  products/ubuntu2004/profiles/cis_level1_server.profile
Labels: New Rule, Ubuntu

#7083 Add some more tests
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_issue/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_issue/tests/incorrect.fail.sh
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_motd/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_motd/tests/incorrect.fail.sh
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_motd/tests/missing.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_issue/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_issue/tests/incorrect.fail.sh
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_motd/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_motd/tests/incorrect.fail.sh
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_motd/tests/missing.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_issue/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_issue/tests/open.fail.sh
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_motd/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_motd/tests/missing.pass.sh
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_motd/tests/open.fail.sh
  linux_os/guide/system/bootloader-grub2/non-uefi/file_owner_grub2_cfg/tests/correct.pass.sh
  linux_os/guide/system/bootloader-grub2/non-uefi/file_owner_grub2_cfg/tests/wrong.fail.sh
  linux_os/guide/system/bootloader-grub2/non-uefi/file_permissions_grub2_cfg/tests/correct.pass.sh
  linux_os/guide/system/bootloader-grub2/non-uefi/file_permissions_grub2_cfg/tests/wrong.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/tests/comment.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/tests/correct_value.pass.sh
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/tests/file_not_there.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_freevxfs_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/tests/comment.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/tests/correct_value.pass.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/tests/file_not_there.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfs_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/tests/comment.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/tests/correct_value.pass.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/tests/file_not_there.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_hfsplus_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/tests/comment.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/tests/correct_value.pass.sh
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/tests/file_not_there.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_jffs2_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_squashfs_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_squashfs_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_udf_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_udf_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/tests/empty.fail.sh
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/tests/wrong_value.fail.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/tests/aide_not_installed.fail.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/package_aide_installed/tests/installed.pass.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/package_aide_installed/tests/notinstalled.fail.sh
  linux_os/guide/system/software/sudo/sudo_add_use_pty/tests/use_pty_absent.fail.sh
  linux_os/guide/system/software/sudo/sudo_add_use_pty/tests/use_pty_enabled.pass.sh
  linux_os/guide/system/software/sudo/sudo_add_use_pty/tests/use_pty_enabled_dir.pass.sh
Labels: Test Suite, Ubuntu

#7262 remove broken links to support.ntp.org
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/ntp/service_ntp_enabled/rule.yml
  linux_os/guide/services/ntp/service_ntpd_enabled/rule.yml
Labels: Update Rule, bugfix

#7081 Mount option template updates
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/tests/no_partition.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/no_partition.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/tests/no_partition.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/tests/separate.pass.sh
  shared/templates/mount_option/bash.template
  shared/templates/mount_option/oval.template
Labels: Bash, OVAL, bugfix

#7169 New rules for RHEL-08-010291
  linux_os/guide/services/ssh/sshd_approved_ciphers.var
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_correct.pass.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_correct_commented.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_correct_followed_by_incorrect_commented.pass.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_empty_file.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_empty_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_incorrect_followed_by_correct_commented.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_incorrect_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_openssh_conf_crypto_policy/tests/stig_missing_file.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/tests/rhel8_stig_correct.pass.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/tests/rhel8_stig_empty_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/tests/rhel8_stig_incorrect_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/harden_sshd_ciphers_opensshserver_conf_crypto_policy/tests/rhel8_stig_missing_file.fail.sh
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7267 OCP4: fips_mode_enabled rule relates to IA-7
  applications/openshift/integrity/crypto/fips_mode_enabled/rule.yml
Labels: Update Rule

#7265 audit_rules_file_deletion_events rules for SLES15 PCI-DSS
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
  products/sle15/profiles/pci-dss.profile
  shared/templates/audit_rules_file_deletion_events/ansible.template
Labels: ok-to-test

#7258 Fix coverity problems
  shared/macros-bash.jinja
Labels: Bash

#7271 Fix ansible remediation of display_login_attempts
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/default_config.fail.sh
Labels: Ansible

#7274 Update package_vim_installed to point to vim-enhanced package
  linux_os/guide/system/software/system-tools/package_vim_installed/rule.yml
Labels: bugfix

#7275 SSGTS - add rhel9 install command, add rhel9 platform to crypto policy rule test scenarios
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/tests/absent.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/tests/bind_not_installed.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/tests/no_config_file.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/tests/ok.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/tests/overrides.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/config_and_current_same_time.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/config_newer_than_current.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/missing_nss_config.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/missing_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/missing_policy_file.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/nss_config_as_file.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/nss_config_as_symlink.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/policy_default_nosha1_set.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/policy_default_set.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/policy_fips_ospp_set.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/tests/wrong_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/tests/kerberos_correct_policy.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/tests/kerberos_missing_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/tests/kerberos_wrong_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/tests/libreswan_not_installed.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/tests/line_commented.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/tests/line_is_there.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/tests/line_not_there.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/tests/wrong_value.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/tests/nothing.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/tests/ok.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/tests/section_not_include.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/tests/wrong.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/tests/absent.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/tests/comment.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/tests/no_config_file.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/tests/overrides.fail.sh
  tests/ssg_test_suite/common.py
Labels: bugfix

#7129 Add /var/log/audit individual ownership rules
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/tests/correct_value_non-root_group.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/tests/wrong_value.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/tests/wrong_value.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value_non-root_group.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/wrong_value.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/tests/wrong_value.fail.sh
  products/rhel8/profiles/stig.profile
  shared/checks/oval/auditd_conf_log_group_not_root.xml
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment

#7276 New rule for RHEL-08-020270
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_emergency_expire_date/rule.yml
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7277 Disable ctrl-alt-del.target before masking it
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/bash/shared.sh
Labels: bugfix

#7272 Update regex for openssl TLS MinProtocol parameter
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/ansible/shared.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/rule.yml
Labels: bugfix

#7251 Add Jinja-based RHEL minor verison check
  products/rhel8/product.yml
  shared/checks/oval/installed_OS_is_rhel8.xml
Labels: DISA RHEL8 STIG Alignment

#7264 Add rule new for RHEL-08-030700
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/commented_out.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/empty.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/file_not_present.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/halt.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/ignore.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/not_present.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/setup.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/single.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/tests/syslog.pass.sh
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7268 Added new rule for RHEL-08-030710
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/default_no_pass.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/rsyslog.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/rsyslog_wrong_value.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/rsyslogd.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/rsyslogd_wrong_value.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/tests/setup.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/default_no_pass.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/rsyslog.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/rsyslog_wrong_value.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/rsyslogd.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/rsyslogd_wrong_value.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/tests/setup.sh
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7281 Replace deprecated command in RHEL8/9 kickstart files
  products/rhel8/kickstart/ssg-rhel8-cui-ks.cfg
  products/rhel8/kickstart/ssg-rhel8-ospp-ks.cfg
  products/rhel8/kickstart/ssg-rhel8-pci-dss-ks.cfg
  products/rhel8/kickstart/ssg-rhel8-stig-ks.cfg
  products/rhel8/kickstart/ssg-rhel8-stig_gui-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-cui-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-ospp-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-pci-dss-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-stig-ks.cfg
  products/rhel9/kickstart/ssg-rhel9-stig_gui-ks.cfg
  tests/kickstarts/test_suite.cfg
Labels: RHEL

#7257 Fixed the remediations when there are no previous kernelopts
  shared/templates/grub2_bootloader_argument/bash.template
Labels: RHEL9, bugfix

#7147 Enable generic rules for RHEL9
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_servers/use_kerberos_security_all_exports/rule.yml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/rule.yml
  linux_os/guide/services/obsolete/r_services/service_rexec_disabled/rule.yml
  linux_os/guide/services/obsolete/r_services/service_rlogin_disabled/rule.yml
  linux_os/guide/services/snmp/snmp_configure_server/snmpd_use_newer_protocol/rule.yml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/rule.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_libuserconf/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_logindefs/rule.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/rule.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/rule.yml
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_bashrc_exec_tmux/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_command/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/rule.yml
  linux_os/guide/system/network/network-ipsec/libreswan_approved_tunnels/rule.yml
  linux_os/guide/system/network/network_nmcli_permissions/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/install_hids/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/rule.yml
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/rule.yml
  linux_os/guide/system/software/sudo/sudoers_validate_passwd/rule.yml
  products/rhel9/profiles/cjis.profile
  products/rhel9/profiles/hipaa.profile
  products/rhel9/profiles/ism_o.profile
  products/rhel9/profiles/ospp.profile
  products/rhel9/profiles/pci-dss.profile
  products/rhel9/profiles/rht-ccp.profile
  products/rhel9/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
Labels: RHEL9

#7254 Remove specific metadata in shared Bash remediations
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_run_as_chrony_user/bash/shared.sh
  linux_os/guide/services/usbguard/usbguard_allow_hid/bash/shared.sh
  linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/bash/shared.sh
  linux_os/guide/services/usbguard/usbguard_allow_hub/bash/shared.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_remove_packages/bash/shared.sh
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_minimum_age_login_defs/bash/fedora.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_minimum_age_login_defs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/bash/fedora.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/bash/wrlinux.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_group/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_passwd/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_shadow/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_polyinstantiated_tmp/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_polyinstantiated_var_tmp/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_access_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/policy_rules/audit_rules_for_ospp/bash/shared.sh
  linux_os/guide/system/bootloader-zipl/zipl_bootmap_is_up_to_date/bash/shared.sh
  linux_os/guide/system/network/network-iptables/iptables_activation/set_ip6tables_default_rule/bash/shared.sh
  linux_os/guide/system/network/network-iptables/iptables_ruleset_modifications/set_iptables_default_rule/bash/shared.sh
  linux_os/guide/system/network/network-iptables/iptables_ruleset_modifications/set_iptables_default_rule_forward/bash/shared.sh
  linux_os/guide/system/permissions/files/dir_perms_world_writable_root_owned/bash/shared.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_permissions_library_dirs/bash/shared.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/bash/shared.sh
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/bash/shared.sh
  linux_os/guide/system/software/integrity/crypto/harden_ssh_client_crypto_policy/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/bash/shared.sh
  linux_os/guide/system/software/updating/clean_components_post_updating/bash/shared.sh
  linux_os/guide/system/software/updating/dnf-automatic_apply_updates/bash/shared.sh
  linux_os/guide/system/software/updating/dnf-automatic_security_updates_only/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/bash/shared.sh
Labels: RHEL9

#7293 Update Mailing list location in docs
  docs/manual/developer/01_introduction.md
Labels: Documentation

#7289 Add rule for RHEL-08-020300
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/tests/disabled.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/tests/enable.pass.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/tests/not_defined.fail.sh
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/var_password_pam_dictcheck.var
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment, New Rule

#7298 Add rules to SLE15 PCI-DSS profile for accounts,passwords,pam and audit
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  products/sle15/profiles/pci-dss.profile
  shared/templates/accounts_password/ansible.template
  shared/templates/accounts_password/bash.template
Labels: ok-to-test

#7075 Add SCE Support to build system
  CMakeLists.txt
  build-scripts/build_sce.py
  build-scripts/profile_tool.py
  build-scripts/verify_references.py
  build-scripts/yaml_to_shorthand.py
  build_config.yml.in
  cmake/SSGCommon.cmake
  linux_os/guide/system/accounts/accounts-session/accounts_users_own_home_directories/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_own_home_directories/sce/ubuntu2004.sh
  products/ubuntu2004/profiles/standard.profile
  shared/transforms/shared_constants.xslt
  ssg/build_profile.py
  ssg/build_sce.py
  ssg/build_yaml.py
  ssg/constants.py
  ssg/rules.py
Labels: Highlight, Infrastructure

#7302 Ensure test scenarios and helper scripts are excutable
  tests/ssg_test_suite/common.py
Labels: bugfix

#7308 Add a Gitter chat badge to README.md
  README.md
Labels: needs-ok-to-test

#7311 Fix links to repo: SSG->CaC
  CMakeLists.txt
  README.md
  build-scripts/sds_move_ocil_to_checks.py
  docs/man_page_template.jinja
  docs/manual/user_guide.adoc
  shared/transforms/shared_constants.xslt
  shared/transforms/shared_shorthand2xccdf.xslt
  shared/transforms/xccdf-ocilcheck2ref.xslt
  ssg/build_ovals.py
  ssg/constants.py
Labels: Documentation
