Repository ComplianceAsCode/content, pull requests merged in 2022-05, with the labels that each got.

#8601 Bad use of double quotes in rsyslog_files_permissions/bash/shared.sh (second try)
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/tests/IncludeConfig_glob_perms_0600.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/tests/IncludeConfig_glob_perms_0601.fail.sh
Labels: ok-to-test

#8656 Update template sysctl to fail if more than one file configure the same parameter
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/one_sysctl_conf_one_sysctl_d.fail.sh
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/two_sysctls_on_d.fail.sh
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/two_sysctls_on_same_file.pass.sh
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/two_sysctls_on_same_file_name.fail.sh
  shared/templates/sysctl/bash.template
  shared/templates/sysctl/oval.template
Labels: DISA RHEL8 STIG Alignment

#8670 Update rhel8 stig to v1r6
  products/rhel8/profiles/stig.profile
  products/rhel8/profiles/stig_gui.profile
  shared/references/disa-stig-rhel8-v1r5-xccdf-scap.xml
  shared/references/disa-stig-rhel8-v1r6-xccdf-manual.xml
Labels: DISA RHEL8 STIG Alignment

#8666 fix: fedora: define login_defs in platform_package_overrides
  products/fedora/product.yml
Labels: Fedora, ok-to-test

#8645 Update SRG-OS-000467-GPOS-00211 for RHEL 9 STIG
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_rules_for_ospp/rule.yml
  shared/macros/fixtext.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8634 `utils/compare_results.py` to work with `--stig-viewer` results and print rule identifiers
  utils/compare_results.py
Labels: Infrastructure

#8663 display_login_attempts regexp fixes
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/no_space_before_showfailed.fail.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/no_space_before_silent.pass.sh
Labels: ok-to-test

#8676 Update rules for SRG-OS-000373-GPOS-00156
  controls/srg_gpos/SRG-OS-000373-GPOS-00156.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/rule.yml
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8596 Update SRG-OS-000420-GPOS-00186 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000420-GPOS-00186.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_invalid_ratelimit/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8497 Update SRG-OS-000096-GPOS-00050 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000096-GPOS-00050.yml
  linux_os/guide/services/ntp/chronyd_client_only/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/rule.yml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/rule.yml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/no_nic_in_ssh_zone.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/no_ssh_zone.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_port_enabled.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_zone_and_nic_mismatch.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_zone_nic_bounded.pass.sh
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/oval/shared.xml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_dccp_disabled/rule.yml
  shared/macros/general.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8600 Update SRG-OS-000312-GPOS-00123
  controls/srg_gpos/SRG-OS-000312-GPOS-00123.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_hardlinks/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_symlinks/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8505 Update SRG-OS-000114-GPOS-00059 for RHEL 9 STIG
  linux_os/guide/services/usbguard/usbguard_allow_hid/ansible/shared.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid/rule.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/ansible/shared.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/rule.yml
  linux_os/guide/services/usbguard/usbguard_allow_hub/ansible/shared.yml
  linux_os/guide/services/usbguard/usbguard_allow_hub/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/rule.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/rule.yml
  shared/macros/fixtext.jinja
  shared/references/cce-redhat-avail.txt
Labels: RHEL9, Update Rule, DISA RHEL9 STIG Alignment

#8628 Update SRG-OS-000433-GPOS-00192 for RHEL 9 STIG
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/ansible/shared.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/bash/shared.sh
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/oval/shared.xml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_kptr_restrict/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/rule.yml
  shared/macros/ansible.jinja
  shared/macros/bash.jinja
  shared/macros/fixtext.jinja
  shared/macros/general.jinja
  shared/macros/ocil.jinja
  shared/templates/grub2_bootloader_argument/ansible.template
  shared/templates/grub2_bootloader_argument_absent/ansible.template
  shared/templates/grub2_bootloader_argument_absent/bash.template
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8674 Update SRG-OS-000424-GPOS-00188 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000424-GPOS-00188.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8664 platform magic comment cleanup
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/ansible/shared.yml
  linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/kubernetes/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/missing_pam_tally2.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_big_deny.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_commented.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_configured.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_empty_deny.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/tests/pam_tally2_zero_deny.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/ansible/shared.yml
  products/jre/guide/java/java_jre_configure_crypto_policy/bash/shared.sh
  products/vsel/guide/vsel/general_settings/virus_notification/bash/shared.sh
  products/vsel/guide/vsel/general_settings/web_client_disabled/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_app_primary/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_app_secondary/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_default_primary/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_default_secondary/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_error/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_action_timeout/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_allFiles/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_decompArchive/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_enabled/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_heuristicAnalysis/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_macroAnalysis/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_program/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_scanMaxTmo/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_scanNWFiles/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_scanOnRead/bash/shared.sh
  products/vsel/guide/vsel/on_access_settings/oas_scanOnWrite/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_action_app_primary/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_action_app_secondary/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_action_default_primary/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_action_default_secondary/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_allFiles/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_decompArchive/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_extensions/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_heuristicAnalysis/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_macroAnalysis/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_mime/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_program/bash/shared.sh
  products/vsel/guide/vsel/on_demand_settings/ods_scanNWFiles_local/bash/shared.sh
Labels: bugfix, ok-to-test

#8665 Update SRG-OS-000341-GPOS-00132
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_sufficiently_large_partition/rule.yml
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log_audit/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8684 Fix grub_command macro for Ubuntu
  shared/macros/general.jinja
Labels: bugfix, Ubuntu

#8683 Fix variable substitution in SRG export
  utils/create_srg_export.py
Labels: bugfix, Infrastructure, DISA RHEL9 STIG Alignment

#8689 OL7 STIG v2r7 update
  products/ol7/profiles/stig.profile
  shared/references/disa-stig-ol7-v2r7-xccdf-manual.xml
Labels: Oracle Linux, ok-to-test

#8687 Update SRG-OS-000057-GPOS-00027 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000057-GPOS-00027.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_immutable/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_permissions_var_log_audit/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8691 Add variables to SRG GPOS control according to RHEL9 STIG profile
  controls/srg_gpos.yml
Labels: DISA RHEL9 STIG Alignment

#8688 Add macroed ocil clause for service disabled rules
  linux_os/guide/services/avahi/disable_avahi_group/service_avahi-daemon_disabled/rule.yml
  linux_os/guide/services/base/service_abrtd_disabled/rule.yml
  linux_os/guide/services/base/service_acpid_disabled/rule.yml
  linux_os/guide/services/base/service_certmonger_disabled/rule.yml
  linux_os/guide/services/base/service_cgconfig_disabled/rule.yml
  linux_os/guide/services/base/service_cgred_disabled/rule.yml
  linux_os/guide/services/base/service_cockpit_disabled/rule.yml
  linux_os/guide/services/base/service_cpupower_disabled/rule.yml
  linux_os/guide/services/base/service_irqbalance_enabled/rule.yml
  linux_os/guide/services/base/service_kdump_disabled/rule.yml
  linux_os/guide/services/base/service_mdmonitor_disabled/rule.yml
  linux_os/guide/services/base/service_messagebus_disabled/rule.yml
  linux_os/guide/services/base/service_netconsole_disabled/rule.yml
  linux_os/guide/services/base/service_ntpdate_disabled/rule.yml
  linux_os/guide/services/base/service_oddjobd_disabled/rule.yml
  linux_os/guide/services/base/service_portreserve_disabled/rule.yml
  linux_os/guide/services/base/service_psacct_enabled/rule.yml
  linux_os/guide/services/base/service_qpidd_disabled/rule.yml
  linux_os/guide/services/base/service_quota_nld_disabled/rule.yml
  linux_os/guide/services/base/service_rdisc_disabled/rule.yml
  linux_os/guide/services/base/service_rhnsd_disabled/rule.yml
  linux_os/guide/services/base/service_rhsmcertd_disabled/rule.yml
  linux_os/guide/services/base/service_saslauthd_disabled/rule.yml
  linux_os/guide/services/base/service_smartd_disabled/rule.yml
  linux_os/guide/services/base/service_sysstat_disabled/rule.yml
  linux_os/guide/services/cron_and_at/service_atd_disabled/rule.yml
  linux_os/guide/services/dhcp/disabling_dhcp_server/service_dhcpd_disabled/rule.yml
  linux_os/guide/services/dns/disabling_dns_server/service_named_disabled/rule.yml
  linux_os/guide/services/ftp/disabling_vsftpd/service_vsftpd_disabled/rule.yml
  linux_os/guide/services/http/disabling_httpd/service_httpd_disabled/rule.yml
  linux_os/guide/services/imap/disabling_dovecot/service_dovecot_disabled/rule.yml
  linux_os/guide/services/ldap/openldap_server/service_slapd_disabled/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/disabling_nfsd/service_nfs_disabled/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/disabling_nfsd/service_rpcsvcgssd_disabled/rule.yml
  linux_os/guide/services/obsolete/inetd_and_xinetd/service_xinetd_disabled/rule.yml
  linux_os/guide/services/obsolete/nis/service_ypbind_disabled/rule.yml
  linux_os/guide/services/obsolete/nis/service_ypserv_disabled/rule.yml
  linux_os/guide/services/obsolete/service_rsyncd_disabled/rule.yml
  linux_os/guide/services/obsolete/tftp/service_tftp_disabled/rule.yml
  linux_os/guide/services/printing/service_cups_disabled/rule.yml
  linux_os/guide/services/proxy/disabling_squid/service_squid_disabled/rule.yml
  linux_os/guide/services/routing/disabling_quagga/service_zebra_disabled/rule.yml
  linux_os/guide/services/smb/disabling_samba/service_smb_disabled/rule.yml
  linux_os/guide/services/snmp/disabling_snmp_service/service_snmpd_disabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  linux_os/guide/system/network/network-wireless/wireless_software/service_bluetooth_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  shared/macros/ocil.jinja
Labels: DISA RHEL9 STIG Alignment

#8690 Fix title text of SRG-OS-000163-GPOS-00072
  controls/srg_gpos/SRG-OS-000163-GPOS-00072.yml
Labels: DISA RHEL9 STIG Alignment

#8681 Update SRG-OS-000069-GPOS-00037
  controls/srg_gpos.yml
  controls/srg_gpos/SRG-OS-000069-GPOS-00037.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ucredit/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8693 Update SRG-OS-000024-GPOS-00007
  controls/srg_gpos/SRG-OS-000024-GPOS-00007.yml
Labels: DISA RHEL9 STIG Alignment

#8540 Initial definition of ANSSI BP28 minmal profile for SLE
  controls/anssi_sle.yml
  linux_os/guide/services/dhcp/disabling_dhcp_server/package_dhcp_removed/rule.yml
  linux_os/guide/services/mail/package_sendmail_removed/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypbind_removed/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypserv_removed/rule.yml
  linux_os/guide/services/obsolete/r_services/package_rsh_removed/rule.yml
  linux_os/guide/services/obsolete/tftp/package_tftp_removed/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  linux_os/guide/system/logging/package_rsyslog_installed/rule.yml
  linux_os/guide/system/logging/service_rsyslog_enabled/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/rule.yml
  linux_os/guide/system/software/updating/dnf-automatic_apply_updates/ansible/shared.yml
  linux_os/guide/system/software/updating/dnf-automatic_apply_updates/rule.yml
  linux_os/guide/system/software/updating/dnf-automatic_security_updates_only/ansible/shared.yml
  linux_os/guide/system/software/updating/dnf-automatic_security_updates_only/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/package_dnf-automatic_installed/rule.yml
  linux_os/guide/system/software/updating/timer_dnf-automatic_enabled/rule.yml
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: ok-to-test

#8432 Update grub2_password rule to be compliant with OL08-00-010150 & RHEL-08-010150
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/tests/no-grub.pass.sh
Labels: ok-to-test

#8624 Update SRG-OS-000376-GPOS-00161 for RHEL 9 STIG
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_opensc_installed/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_enable_smartcard_auth/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8673 Update SRG-OS-000255-GPOS-00096
  controls/srg_gpos/SRG-OS-000255-GPOS-00096.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_freq/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/rule.yml
  shared/macros/fixtext.jinja
Labels: DISA RHEL9 STIG Alignment

#8685 Update SRG-OS-000046-GPOS-00022 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000046-GPOS-00022.yml
  linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_system_shutdown/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_action_mail_acct/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8692 Add rationale to SRG-OS-000112-GPOS-00057
  controls/srg_gpos/SRG-OS-000112-GPOS-00057.yml
Labels: DISA RHEL9 STIG Alignment

#8694 Clean up the text in account_temp_expire_date
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_temp_expire_date/rule.yml
Labels: DISA RHEL9 STIG Alignment

#8699 Update SRG-OS-000259-GPOS-00100 for RHEL 9 STIG
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_binary_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_binary_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8698 Sysctl filter out symlinks to files already collected
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/symlink_different_option.pass.sh
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/symlink_repeated_sysctl_conf.pass.sh
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/tests/symlink_same_option.fail.sh
  shared/templates/sysctl/oval.template
Labels: bugfix

#8705 Add custom requirement
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_emergency_expire_date/rule.yml
  ssg/build_yaml.py
  utils/create_srg_export.py
Labels: Infrastructure

#8672 Update SRG-OS-000254-GPOS-00095
  controls/srg_gpos/SRG-OS-000254-GPOS-00095.yml
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
  shared/macros/general.jinja
Labels: DISA RHEL9 STIG Alignment

#8651 Update SRG-OS-000297-GPOS-00115 for RHEL9 STIG
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/tests/installed_disabled.fail.sh
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/tests/installed_enabled.pass.sh
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configure_firewalld_ports/rule.yml
  shared/macros/general.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8706 Add `srg_requirement` to file watch rules
  docs/jinja_macros/srg_requirement.rst
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_lastlog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_tallylog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers_d/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_group/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_gshadow/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_opasswd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_passwd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification_shadow/rule.yml
  shared/macros/srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8713 Update SRG-OS-000058-GPOS-00028 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000058-GPOS-00028.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8714 Update SRG-OS-000059-GPOS-00029 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000059-GPOS-00029.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8703 Update SRG-OS-000072-GPOS-00040 for RHEL 9 STIG
  controls/srg_gpos.yml
  controls/srg_gpos/SRG-OS-000072-GPOS-00040.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_difok/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxclassrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minclass/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8721 Sysctl template: Restrict the check for option definition in single file to OVAL 5.11
  shared/templates/sysctl/oval.template
Labels: DISA RHEL8 STIG Alignment

#8711 Update SRG-OS-000478-GPOS-00223 for RHEL9 STIG
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/rule.yml
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/tests/fips_dracut_module_missing.fail.sh
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/tests/fips_dracut_module_present.pass.sh
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8717 RHEL 9 STIG Fixes - Round Two
  controls/srg_gpos/SRG-OS-000095-GPOS-00049.yml
  controls/srg_gpos/SRG-OS-000120-GPOS-00061.yml
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_id/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_vsyscall_argument/rule.yml
  linux_os/guide/system/logging/package_rsyslog-gnutls_installed/rule.yml
  linux_os/guide/system/network/network-ipsec/libreswan_approved_tunnels/rule.yml
  linux_os/guide/system/network/network-wireless/wireless_software/kernel_module_bluetooth_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_page_poison_argument/rule.yml
  linux_os/guide/system/software/system-tools/package_krb5-workstation_removed/rule.yml
  shared/macros/ocil.jinja
  shared/references/cce-redhat-avail.txt
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8702 Update SRG-OS-000368-GPOS-00154 for RHEL 9 STIG
  linux_os/guide/system/permissions/partitions/mount_option_boot_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_boot_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nodev_nonroot_local_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_audit_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_audit_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_audit_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_log_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/rule.yml
  shared/macros/fixtext.jinja
  shared/macros/ocil.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8715 Update SRG-OS-000458-GPOS-00203 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000458-GPOS-00203.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchmodat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchownat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_removexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_setxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_ftruncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_by_handle_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_openat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_truncate/rule.yml
  shared/macros/fixtext.jinja
  shared/macros/srg_requirement.jinja
Labels: DISA RHEL9 STIG Alignment

#8716 Update SRG-OS-000073-GPOS-00041 for RHEL 9 STIG
  controls/srg_gpos.yml
  controls/srg_gpos/SRG-OS-000073-GPOS-00041.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_libuserconf/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_logindefs/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed_sha512/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8722 Update SRG-OS-000393-GPOS-00173
  controls/srg_gpos.yml
  controls/srg_gpos/SRG-OS-000393-GPOS-00173.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8724 Update SRG-OS-000375-GPOS-00160 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000375-GPOS-00160.yml
  controls/srg_gpos/SRG-OS-000377-GPOS-00162.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/package_pcsc-lite_installed/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8719 Update SRG-OS-000021-GPOS-00005 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000021-GPOS-00005.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_enforce_local/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8700 Ubuntu 20.04 STIG chrony rules
  linux_os/guide/services/ntp/chronyd_client_only/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_client_only/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_client_only/oval/shared.xml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/ntp/chronyd_client_only/tests/chrony.pass.sh
  linux_os/guide/services/ntp/chronyd_client_only/tests/nonzero.fail.sh
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/oval/shared.xml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/rule.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/tests/chrony.pass.sh
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/tests/nonzero.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/oval/shared.xml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony.pass.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_no_pool_nor_servers.pass.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_configured.pass.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_misconfigured.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_pool_missing_parameter.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/chrony_one_server_misconfigured.fail.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/chronyd_server_directive/rule.yml
  linux_os/guide/services/ntp/chronyd_server_directive/tests/file_empty.fail.sh
  linux_os/guide/services/ntp/chronyd_server_directive/tests/file_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_server_directive/tests/line_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_server_directive/tests/multiple_servers.pass.sh
  linux_os/guide/services/ntp/chronyd_server_directive/tests/only_pool.fail.sh
  linux_os/guide/services/ntp/chronyd_server_directive/tests/only_server.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_specify_remote_server/bash/shared.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/correct.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/correct_pool.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/file_empty.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/file_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/line_missing.fail.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/multiple_servers.pass.sh
  linux_os/guide/services/ntp/chronyd_specify_remote_server/tests/server_not_specified.fail.sh
  linux_os/guide/services/ntp/chronyd_sync_clock/rule.yml
  linux_os/guide/services/ntp/chronyd_sync_clock/tests/commented.fail.sh
  linux_os/guide/services/ntp/chronyd_sync_clock/tests/correct_value.pass.sh
  linux_os/guide/services/ntp/chronyd_sync_clock/tests/incorrect_value.fail.sh
  linux_os/guide/services/ntp/package_chrony_installed/rule.yml
  products/debian10/product.yml
  products/debian9/product.yml
  products/ubuntu1604/product.yml
  products/ubuntu1804/product.yml
  products/ubuntu2004/product.yml
  products/ubuntu2004/profiles/stig.profile
  ssg/constants.py
  ssg/products.py
Labels: ok-to-test

#8740 Add templated tests for dconf_ini_file
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_lock_screen_on_smartcard_removal/tests/correct_value.pass.sh
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_lock_screen_on_smartcard_removal/tests/wrong_value.fail.sh
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_user_admin/tests/correct_value.pass.sh
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_user_admin/tests/wrong_value.fail.sh
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_user_admin/tests/wrong_value_2.fail.sh
  shared/templates/dconf_ini_file/tests/correct_value.pass.sh
  shared/templates/dconf_ini_file/tests/missing.fail.sh
  shared/templates/dconf_ini_file/tests/wrong_value.fail.sh
Labels: Test Scenario

#8752 Cleanup tests package installed or removed
  linux_os/guide/services/ldap/openldap_client/package_openldap-clients_removed/tests/installed.fail.sh
  linux_os/guide/services/ldap/openldap_client/package_openldap-clients_removed/tests/removed.pass.sh
  linux_os/guide/services/obsolete/inetd_and_xinetd/package_xinetd_removed/tests/installed.fail.sh
  linux_os/guide/services/obsolete/inetd_and_xinetd/package_xinetd_removed/tests/removed.pass.sh
  linux_os/guide/services/obsolete/nis/package_ypbind_removed/tests/installed.fail.sh
  linux_os/guide/services/obsolete/nis/package_ypbind_removed/tests/removed.pass.sh
  linux_os/guide/services/obsolete/telnet/package_telnet_removed/tests/installed.fail.sh
  linux_os/guide/services/obsolete/telnet/package_telnet_removed/tests/removed.pass.sh
  linux_os/guide/services/proxy/disabling_squid/package_squid_removed/tests/installed.fail.sh
  linux_os/guide/services/proxy/disabling_squid/package_squid_removed/tests/removed.pass.sh
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/tests/installed.fail.sh
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/tests/removed.pass.sh
  linux_os/guide/system/apparmor/package_apparmor_installed/tests/installed.pass.sh
  linux_os/guide/system/apparmor/package_apparmor_installed/tests/removed.fail.sh
  linux_os/guide/system/selinux/package_libselinux_installed/tests/custom-package-removed.fail.sh
  linux_os/guide/system/selinux/package_libselinux_installed/tests/package-removed.fail.sh
  linux_os/guide/system/selinux/package_libselinux_installed/tests/test_config.yml
  linux_os/guide/system/selinux/package_mcstrans_removed/tests/installed.fail.sh
  linux_os/guide/system/selinux/package_mcstrans_removed/tests/removed.pass.sh
  linux_os/guide/system/selinux/package_setroubleshoot_removed/tests/installed.fail.sh
  linux_os/guide/system/selinux/package_setroubleshoot_removed/tests/removed.pass.sh
Labels: Test Scenario

#8742 Cleanup duplicate scenarios for sshd_lineinfile template
  linux_os/guide/services/ssh/ssh_server/sshd_disable_pubkey_auth/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_pubkey_auth/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_gssapi_auth/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_gssapi_auth/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/commented.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/correct.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/disabled.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/commented.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/correct.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/disabled.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/tests/wrong_value.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_x11_forwarding/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_enable_x11_forwarding/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive_0/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive_0/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/tests/line_not_there.fail.sh
Labels: Test Scenario

#8745 Remove Link Checker from README
  README.md
Labels: Documentation

#8729 Include snapshot cleanup functions for SSGTS
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/test_env.py
  tests/test_suite.py
Labels: Test Suite

#8750 test scenario adjustments for file_permissions template
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/tests/incorrect_permissions.fail.sh
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_backup_etc_shadow/tests/missing_file_test.pass.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_permissions/tests/missing_file_test.pass.sh
Labels: Test Scenario

#8754 Add templated test scenarios for shell_lineinfile template
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/tests/bad_config.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/tests/good_config.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/tests/no_config.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/tests/quoted.fail.sh
  linux_os/guide/system/logging/journald/journald_compress/tests/correct_value.pass.sh
  linux_os/guide/system/logging/journald/journald_compress/tests/missing.fail.sh
  linux_os/guide/system/logging/journald/journald_compress/tests/wrong_value.fail.sh
  linux_os/guide/system/logging/journald/journald_forward_to_syslog/tests/correct_value.pass.sh
  linux_os/guide/system/logging/journald/journald_forward_to_syslog/tests/missing.fail.sh
  linux_os/guide/system/logging/journald/journald_forward_to_syslog/tests/wrong_value.fail.sh
  linux_os/guide/system/logging/journald/journald_storage/tests/correct_value.pass.sh
  linux_os/guide/system/logging/journald/journald_storage/tests/missing.fail.sh
  linux_os/guide/system/logging/journald/journald_storage/tests/wrong_value.fail.sh
  shared/macros/oval.jinja
  shared/templates/shell_lineinfile/tests/correct_value.pass.sh
  shared/templates/shell_lineinfile/tests/missing.fail.sh
  shared/templates/shell_lineinfile/tests/quoted.fail.sh
  shared/templates/shell_lineinfile/tests/wrong_value.fail.sh
Labels: Test Scenario

#8137 GH actions nightly builds
  .github/workflows/nightly_build.yml
  .github/workflows/nightly_build_5_10.yml
Labels: Infrastructure

#8757 Use correct path for sshd options in ansible remediation.
  shared/macros/ansible.jinja
Labels: bugfix

#8730 Add template mode to SSGTS
  tests/README.md
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/template.py
  tests/test_suite.py
Labels: Test Suite

#8760 Remove redundant custom test scenarios for service enabled/disabled rules
  linux_os/guide/services/avahi/disable_avahi_group/service_avahi-daemon_disabled/tests/service_disabled.pass.sh
  linux_os/guide/services/cron_and_at/service_crond_enabled/tests/disabled.fail.sh
  linux_os/guide/services/cron_and_at/service_crond_enabled/tests/enabled.pass.sh
  linux_os/guide/services/dhcp/disabling_dhcp_server/service_dhcpd_disabled/rule.yml
  linux_os/guide/services/nfs_and_rpc/disabling_nfs/disabling_nfs_services/service_rpcbind_disabled/tests/service_disabled.pass.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/disabling_nfsd/service_nfs_disabled/tests/service_disabled.pass.sh
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/disabling_nfsd/service_nfs_disabled/tests/service_enabled.fail.sh
  linux_os/guide/services/ntp/service_chronyd_enabled/tests/disabled.fail.sh
  linux_os/guide/services/ntp/service_chronyd_enabled/tests/enabled.pass.sh
  linux_os/guide/system/auditing/service_auditd_enabled/tests/disabled.fail.sh
  linux_os/guide/system/auditing/service_auditd_enabled/tests/enabled.pass.sh
  linux_os/guide/system/logging/service_rsyslog_enabled/tests/disabled.fail.sh
  linux_os/guide/system/logging/service_rsyslog_enabled/tests/enabled.pass.sh
Labels: Test Scenario

#8727 RHEL9 STIG Fixup - Round 3
  controls/srg_gpos/SRG-OS-000114-GPOS-00059.yml
  controls/srg_gpos/SRG-OS-000191-GPOS-00080.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_enforce_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/package_firewalld_installed/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
  linux_os/guide/system/permissions/files/dir_perms_world_writable_root_owned/rule.yml
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_group_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_binary_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_binary_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_slub_debug_argument/rule.yml
  linux_os/guide/system/selinux/package_policycoreutils_installed/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/fips/sysctl_crypto_fips_enabled/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8771 Update SRG-OS-000378-GPOS-00163 for RHEL 9 STIG
  linux_os/guide/services/usbguard/package_usbguard_installed/rule.yml
  linux_os/guide/services/usbguard/service_usbguard_enabled/rule.yml
  linux_os/guide/services/usbguard/usbguard_generate_policy/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_dccp_disabled/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8764 clean_components_post_updating, enable bash remediation for sle15
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/shared.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/sle12.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/sle15.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/bash/shared.sh
  linux_os/guide/system/software/updating/clean_components_post_updating/bash/sle12.sh
Labels: SLES, ok-to-test, Update Rule

#8775 Rename test scenario with wrong extension
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_session_events/tests/augen_correct.pass.sh
Labels: bugfix

#8701 Ubuntu 20.04 STIG UFW rules
  linux_os/guide/system/network/network-ufw/group.yml
  linux_os/guide/system/network/network-ufw/package_ufw_installed/rule.yml
  linux_os/guide/system/network/network-ufw/service_ufw_enabled/rule.yml
  linux_os/guide/system/network/network-ufw/ufw_only_required_services/rule.yml
  linux_os/guide/system/network/network-ufw/ufw_rate_limit/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, New Rule, ok-to-test, Update Profile

#8777 SUSE SLE15 create profile for hardening cloud images
  products/sle15/profiles/pcs-hardening.profile
Labels: SLES, ok-to-test, New Profile

#8780 [Backport] Rename test scenario with wrong extension
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_session_events/tests/augen_correct.pass.sh
Labels: bugfix

#8781 Do not include symlink_state in 5.10 content
  shared/templates/sysctl/oval.template
Labels: bugfix, backported-into-stabilization

#8782 [Backport] Refix sysctl oval 5.10
  shared/templates/sysctl/oval.template
Labels: bugfix

#8791 Stop SSGTS when a wrong domain name is informed
  tests/ssg_test_suite/test_env.py
Labels: Test Suite

#8749 Clean Up README
  README.md
Labels: Documentation

#8788 Document `fixtext` and `check` attributes on controls and rules
  docs/manual/developer/03_creating_content.md
  docs/manual/developer/04_style_guide.md
  docs/manual/developer/06_contributing_with_content.md
Labels: Documentation

#8796 Set check_root_user to true on multiple "audit_rules_dac_modification" rules ol8
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_removexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_setxattr/rule.yml
Labels: ok-to-test

#8797 Update OVAL, bash and tests for set_password_hashing_min_rounds_logindefs
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/tests/argument_missing.pass.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/tests/common.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/tests/wrong_value.fail.sh
Labels: needs-ok-to-test

#8798 Update OL8 STIG rules severities
  linux_os/guide/system/software/integrity/crypto/harden_sshd_macs_openssh_conf_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_endpoint_security_software/package_mcafeetp_installed/rule.yml
  products/ol8/profiles/stig.profile
Labels: needs-ok-to-test

#8822 update information in `creating a new Product` segment
  docs/manual/developer/03_creating_content.md
Labels: needs-ok-to-test

#8823 fix ansible remediation of enable_dracut_fips_module
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/ansible/shared.yml
Labels: bugfix, Ansible

#8816 update compliance as code documentation
  docs/manual/developer/03_creating_content.md
Labels: Documentation, ok-to-test

#8820 Remove ol8 from rsyslog_remote_loghost fixes
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/ansible/shared.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/bash/shared.sh
Labels: Bash, Oracle Linux, ok-to-test

#8826 OCP4 build: Don't use fedora-33 anymore
  ocp-resources/ds-build-remote.yaml
Labels: OpenShift

#8795 Update sssd_offline_cred_expiration OVAL for OL8 and RHEL8
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/oval/shared.xml
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/rule.yml
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/tests/cache_credentials_false.pass.sh
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/tests/comment.fail.sh
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/tests/correct_value.pass.sh
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/tests/wrong_section.fail.sh
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/tests/wrong_value.fail.sh
Labels: ok-to-test

#8827 Update SRG-OS-000258-GPOS-00099 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000257-GPOS-00098.yml
  controls/srg_gpos/SRG-OS-000258-GPOS-00099.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_group_ownership/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_ownership/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_permissions/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8824 Update SRG-OS-000384-GPOS-00167 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000066-GPOS-00034.yml
  controls/srg_gpos/SRG-OS-000384-GPOS-00167.yml
  linux_os/guide/services/sssd/sssd_has_trust_anchor/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, DISA RHEL9 STIG Alignment

#8828 Update rule accounts_users_home_files_permissions and add it to OL8 and RHEL8 STIG
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/lenient_permission_hidden_files.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/tests/lenient_permissions_directory.fail.sh
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: needs-ok-to-test

#8805 strip trailing blank lines for some templated audit rules
  linux_os/guide/system/auditing/policy_rules/audit_access_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_access_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_create_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_create_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_module_load/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_ospp_general/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_owner_change_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_owner_change_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_perm_change_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_perm_change_success/rule.yml
Labels: bugfix, Update Rule

#8555 Update SRG-OS-000163-GPOS-00072 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000163-GPOS-00072.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8616 Update SRG-OS-000080-GPOS-00048 for RHEL 9 STIG
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/rule.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/rule.yml
  shared/macros/general.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8812 Fix sssd_enable_certmap OVAL
  docs/templates/template_reference.md
  linux_os/guide/services/sssd/sssd_enable_certmap/rule.yml
  shared/templates/lineinfile/oval.template
  shared/templates/lineinfile/template.py
Labels: needs-ok-to-test

#8832 fix ansible remediation of enable_dracut_fips_module
  linux_os/guide/system/software/integrity/fips/enable_dracut_fips_module/ansible/shared.yml
Labels: Ansible

#8789 Add OCP4 to the SRG Mapping CI job
  .github/workflows/srg-mapping-table.yaml
Labels: OpenShift

#8845 Update SRG-OS-000042-GPOS-00020 for RHEL9 STIG
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_pt_chown/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8836 Update SRG-OS-000095-GPOS-00049 for RHEL9
  controls/srg_gpos/SRG-OS-000095-GPOS-00049.yml
  linux_os/guide/services/mail/package_sendmail_removed/rule.yml
  linux_os/guide/services/nfs_and_rpc/package_nfs-utils_removed/rule.yml
  linux_os/guide/services/ntp/chronyd_client_only/rule.yml
  linux_os/guide/services/ntp/chronyd_no_chronyc_network/rule.yml
  linux_os/guide/services/obsolete/telnet/package_telnet-server_removed/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_atm_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_can_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_dccp_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_firewire-core_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_rds_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_sctp_disabled/rule.yml
  linux_os/guide/system/network/network-uncommon/kernel_module_tipc_disabled/rule.yml
  linux_os/guide/system/network/network-wireless/wireless_software/kernel_module_bluetooth_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/rule.yml
  linux_os/guide/system/software/system-tools/package_gssproxy_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_iprutils_removed/rule.yml
  shared/macros/fixtext.jinja
  shared/macros/srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8846 Update SRG-OS-000062-GPOS-00031 for RHEL9 STIG
  linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8837 Update SRG-OS-000365-GPOS-00152 for RHEL9
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
  shared/macros/srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8847 Update SRG-OS-000274-GPOS-00104 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000274-GPOS-00104.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8848 Update SRG-OS-000465-GPOS-00209 for RHEL9 STIG
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_restorecon/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8830 Update bash of rsyslog_encrypt_offload_actionsendstreamdriverauthmode
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/bash/shared.sh
Labels: Bash, ok-to-test

#8850 Update SRG-OS-000477-GPOS-00222 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000477-GPOS-00222.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_privileged_commands_init/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_privileged_commands_poweroff/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_privileged_commands_reboot/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_privileged_commands_shutdown/rule.yml
  shared/references/cce-redhat-avail.txt
  shared/schemas/rule.json
Labels: New Rule, RHEL9, DISA RHEL9 STIG Alignment
