Repository ComplianceAsCode/content, pull requests merged in 2022-03, with the labels that each got.

#8277 Add disallow_bypass_password_sudo rule to SLE stig profiles
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/rule.yml
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/tests/pam_succeed_if_absent.pass.sh
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/tests/pam_succeed_if_present.fail.sh
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#8279 update SLE CIS profiles to specify cron service
  controls/cis_sle12.yml
  controls/cis_sle_15.yml
Labels: ok-to-test

#8276 Add no_empty_passwords_etc_shadow rule to SLE stig profiles
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/rule.yml
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#8121 Removed criteria in OVAL check of require_singleuser_auth
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/oval/shared.xml
Labels: RHEL, Oracle Linux, ok-to-test, Update Rule

#8283 Update rsyslog rules to work on RHEL9
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/ansible/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/no_remote_methods.fail.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_multiple_configs.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_rsyslog_conf.pass.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/tests/remote_method_set_rsyslog_d.pass.sh
Labels: RHEL9

#8281 Unify grub2 bash macro and template
  shared/macros-bash.jinja
  shared/templates/grub2_bootloader_argument/bash.template
Labels: bugfix

#8292 no iptables.service in sle15
  controls/cis_sle_15.yml
Labels: SLES, ok-to-test, Update Profile

#8282 Add GRUB2 rule for slab_nomerge and mce
  linux_os/guide/system/bootloader-grub2/grub2_mce_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_slab_nomerge_argument/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8287 fix aide_build_database rule and remediation to work with sles 12 and 15
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/oval/shared.xml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/tests/db_malformed.fail.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/tests/db_not_present.fail.sh
Labels: SLES, ok-to-test, Update Rule

#8295 SLE 12 and 15 merge auditd file modification rules STIG IDs
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fchmodat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_ftruncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_by_handle_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_openat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat2/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_truncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlinkat/rule.yml
  products/sle12/profiles/stig.profile
Labels: SLES, ok-to-test, Update Rule, Update Profile

#8313 Use FQDN comparison when finding the profile in STIG tailoring
  utils/create_scap_delta_tailoring.py
Labels: bugfix

#8310 Remove grub2_pti_argument tests
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/arg_not_there.fail.sh
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/correct.pass.sh
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/tests/wrong_value.fail.sh
Labels: Test Scenario

#8309 Delete test scenario that removes SSH keys from machine
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/tests/missing_file_test.pass.sh
Labels: Test Scenario

#8311 Remove RHEL7 platform from invalid_rescue.pass.sh
  shared/templates/grub2_bootloader_argument/tests/invalid_rescue.pass.sh
Labels: Test Scenario

#8278 Update OVAL content for grub2_admin_username
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/tests/no-grub.pass.sh
Labels: ok-to-test

#8318 SRG-OS-000023-GPOS-00006 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000023-GPOS-00006.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/rule.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/rule.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/rule.yml
Labels: RHEL9

#8317 Update SRG-OS-000004-GPOS-00004 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000004-GPOS-00004.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers_d/rule.yml
Labels: RHEL9

#8306 On sle15 accounts_authorized_local_users removes accounts it should not
  linux_os/guide/system/accounts/accounts-restrictions/var_accounts_authorized_local_users_regex.var
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
Labels: ok-to-test

#8294 fix require_singleuser_auth for sle12/sle15
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/oval/shared.xml
Labels: ok-to-test

#8293 fix require_emergency_target_auth for sle12/sle15
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/oval/shared.xml
Labels: ok-to-test

#8297 Fix accounts_umask_etc_bashrc to work with sle12/15
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/rule.yml
Labels: ok-to-test

#8312 Add custom ansible remediation for service_pcscd_enabled
  .github/workflows/gate-lint-ansible-roles.yaml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/ansible/shared.yml
  tests/ansible-lint_config.yml
Labels: bugfix

#8304 New sysctl fs parameters
  linux_os/guide/system/permissions/files/sysctl_fs_protected_fifos/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_fifos/tests/expected_value.pass.sh
  linux_os/guide/system/permissions/files/sysctl_fs_protected_fifos/tests/missing_parameter.fail.sh
  linux_os/guide/system/permissions/files/sysctl_fs_protected_fifos/tests/unexpected_value.fail.sh
  linux_os/guide/system/permissions/files/sysctl_fs_protected_regular/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_regular/tests/expected_value.pass.sh
  linux_os/guide/system/permissions/files/sysctl_fs_protected_regular/tests/missing_parameter.fail.sh
  linux_os/guide/system/permissions/files/sysctl_fs_protected_regular/tests/unexpected_value.fail.sh
  shared/references/cce-redhat-avail.txt
  shared/templates/sysctl/oval.template
Labels: New Rule, RHEL9

#8161 Oval update for two rules to only allow results from only one file [ol7]
  linux_os/guide/system/software/sudo/sudoers_validate_passwd/oval/shared.xml
  linux_os/guide/system/software/sudo/sudoers_validate_passwd/tests/sudoers_validate_passwd_multiple_files.fail.sh
Labels: Oracle Linux, ok-to-test, DISA RHEL8 STIG Alignment, Update Rule

#8324 Update template_reference.md
  docs/templates/template_reference.md
Labels: needs-ok-to-test

#8330 Update OVAL in sshd_disable_compression for ol8
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/oval/shared.xml
Labels: needs-ok-to-test

#8328 make macros-bash.jinja more bash -e safe
  shared/macros-bash.jinja
Labels: ok-to-test

#8333 grub2_bootloader_argument: Edit /etc/default/grub ourselves on certain systems
  shared/macros-bash.jinja
  shared/templates/grub2_bootloader_argument/ansible.template
Labels: bugfix

#8339 Update regex in no_tmux_in_shells rule
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/oval/shared.xml
Labels: needs-ok-to-test

#8341 Update rule description configure_openssl_tls_crypto_policy
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/rule.yml
Labels: needs-ok-to-test

#8296 gid_passwd_group_same oval does not allow ! in passwd field
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/oval/shared.xml
Labels: needs-ok-to-test

#8342 Fix RHEL8 and RHEL7 STIG references
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/rule.yml
  products/rhel8/profiles/stig.profile
  products/rhel9/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL7 STIG Alignment, DISA RHEL8 STIG Alignment

#8321 Update SRG-OS-000028-GPOS-00009 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000028-GPOS-00009.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_bashrc_exec_tmux/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_command/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/no_tmux_in_shells/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_lock_screen_on_smartcard_removal/rule.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/rule.yml
  shared/macros.jinja
Labels: RHEL9, Update Rule

#8366 Override templated test for rule grub2_kernel_trust_cpu_rng
  linux_os/guide/system/bootloader-grub2/grub2_kernel_trust_cpu_rng/tests/arg_not_there_grubenv.fail.sh
Labels: bugfix

#8365 Fix Set Maxpoll Ansible remediation to handle multiple entries
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/ansible/shared.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/tests/ntp_multiple_misconfigured.fail.sh
  tests/ssg_test_suite/common.py
Labels: bugfix

#8347 Refactor pam_faillock remediation
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_enforce_local/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_enforce_local/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/bash/shared.sh
  shared/macros-ansible.jinja
  shared/macros-bash.jinja
Labels: Ansible, Bash, productization-issue

#8367 Add <pre> tag HTML element to STIG mapping tables
  shared/transforms/shared_xccdf2table-stig.xslt
Labels: Infrastructure

#8346 Allow service disabled check pass when ActiveState is also failed.
  shared/templates/service_disabled/oval.template
Labels: bugfix

#8370 Remove reference to a nonexistent file
  shared/transforms/shared_xccdf2table-profileccirefs.xslt
  utils/create_srg_export.py
Labels: bugfix, Infrastructure

#8362 Skip comparison of non existent benchmark during compare ds
  utils/compare_ds.py
Labels: bugfix

#8337 Fix bash remediation of disable_users_coredumps
  linux_os/guide/system/permissions/restrictions/coredumps/disable_users_coredumps/bash/shared.sh
Labels: needs-ok-to-test

#8363 Update SRG-OS-000032-GPOS-00013 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000032-GPOS-00013.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/rule.yml
  shared/macros.jinja
Labels: Infrastructure, RHEL9, Update Rule

#8368 Allow lines between pam_env.so and pam_pkcs11.so
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/tests/installed_enabled_with_faillock.pass.sh
Labels: bugfix

#8372 Remove nonexistent package rules in recent distro releases
  products/ol8/profiles/ospp.profile
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/ospp.profile
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/ospp.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: bugfix

#8336 Update oval name resolution
  linux_os/guide/system/network/network_configure_name_resolution/oval/shared.xml
  linux_os/guide/system/network/network_configure_name_resolution/rule.yml
  linux_os/guide/system/network/network_configure_name_resolution/tests/commented_nameservers.fail.sh
  linux_os/guide/system/network/network_configure_name_resolution/tests/common.sh
  linux_os/guide/system/network/network_configure_name_resolution/tests/dns_not_in_nsswitch_and_resolv_is_empty.pass.sh
  linux_os/guide/system/network/network_configure_name_resolution/tests/dns_not_in_nsswitch_and_resolv_isnt_empty.fail.sh
  linux_os/guide/system/network/network_configure_name_resolution/tests/one_nameserver.fail.sh
  linux_os/guide/system/network/network_configure_name_resolution/tests/two_nameserver.pass.sh
Labels: ok-to-test

#8340 Remove -F euid=0 parameter from audit_rules_suid_privilege_function for ol8
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
Labels: ok-to-test

#8376 SRG-OS-000038-GPOS-00016
  controls/stig_rhel9/SRG-OS-000038-GPOS-00016.yml
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
  shared/macros.jinja
Labels: RHEL9

#8377 SRG-OS-000039-GPOS-00017
  controls/stig_rhel9/SRG-OS-000039-GPOS-00017.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/rule.yml
Labels: RHEL9

#8379 Update SRG-OS-000055-GPOS-00026 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000055-GPOS-00026.yml
Labels: RHEL9

#8378 Update SRGs only containing service_auditd_enabled for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000040-GPOS-00018.yml
  controls/stig_rhel9/SRG-OS-000041-GPOS-00019.yml
  controls/stig_rhel9/SRG-OS-000042-GPOS-00021.yml
  controls/stig_rhel9/SRG-OS-000054-GPOS-00025.yml
Labels: RHEL9

#8382 Update abrt package rules for ol8
  linux_os/guide/system/software/system-tools/package_abrt-addon-ccpp_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-addon-kerneloops_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-addon-python_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-cli_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-libs_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-logger_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-rhtsupport_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-plugin-sosreport_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_abrt-server-info-page_removed/rule.yml
  products/ol8/profiles/stig.profile
Labels: needs-ok-to-test

#8386 Turn all wireless interfaces off
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/bash/shared.sh
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/rule.yml
Labels: needs-ok-to-test

#8385 Ignore commented lines in bash_fix_audit_watch_rule
  shared/macros-bash.jinja
Labels: needs-ok-to-test

#8387 Override dconf_gdm_dir for OL8
  linux_os/guide/system/software/gnome/dconf_db_up_to_date/oval/shared.xml
  products/ol8/product.yml
Labels: needs-ok-to-test

#8384 Audit changes to rsyslogd binary
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/oval/shared.xml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/rule.yml
Labels: needs-ok-to-test

#8171 Fix for bug 1195520
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/bash/shared.sh
Labels: SLES, ok-to-test

#8380 Update SRG-OS-000063-GPOS-00032 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000063-GPOS-00032.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/rule.yml
Labels: RHEL9

#8388 Update SRG-OS-000068-GPOS-00036 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000068-GPOS-00036.yml
  linux_os/guide/services/sssd/sssd_enable_certmap/rule.yml
Labels: RHEL9

#8389 Update SRG-OS-000070-GPOS-00038.yml for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000070-GPOS-00038.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_enforce_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL9

#8396 Update SRG-OS-000122-GPOS-00063 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000122-GPOS-00063.yml
Labels: RHEL9

#8395 Update SRG-OS-000118-GPOS-00060 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000118-GPOS-00060.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_disable_post_pw_expiration/rule.yml
Labels: RHEL9

#8394 Update SRG-OS-000112-GPOS-00057 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000112-GPOS-00057.yml
Labels: RHEL9

#8392 Update SRG-OS-000076-GPOS-00044 for RHEL9
  controls/stig_rhel9/SRG-OS-000076-GPOS-00044.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_maximum_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/rule.yml
Labels: RHEL9

#8390 Update SRG-OS-000071-GPOS-00039 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000071-GPOS-00039.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dcredit/rule.yml
Labels: RHEL9

#8325 Grub2 bootloader CPU mitigations
  linux_os/guide/system/bootloader-grub2/grub2_l1tf_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_mds_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_rng_core_default_quality_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_spec_store_bypass_disable_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_spectre_v2_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/var_l1tf_options.var
  linux_os/guide/system/bootloader-grub2/var_mds_options.var
  linux_os/guide/system/bootloader-grub2/var_rng_core_default_quality.var
  linux_os/guide/system/bootloader-grub2/var_spec_store_bypass_disable_options.var
  shared/references/cce-redhat-avail.txt
  shared/templates/grub2_bootloader_argument/oval.template
Labels: New Rule

#8383 Update privileged commands templates
  shared/macros-bash.jinja
  shared/templates/audit_rules_privileged_commands/bash.template
  shared/templates/audit_rules_privileged_commands/oval.template
Labels: ok-to-test

#8338 Oval updatein rule sshd_set_idle_timeout
  linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/oval/shared.xml
Labels: ok-to-test

#8373 OCP : Update control response for AC-6(8)
  controls/nist_ocp4.yml
Labels: needs-ok-to-test

#8399 Fix missing "to" in account restriction warnings
  linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_id/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_name/rule.yml
Labels: bugfix, Update Rule

#8393 RHEL7 - exclude the user 'nfsnobody' from accounts_users_home_files_*
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/oval/shared.xml
Labels: bugfix

#8398 Use UID field for bash remediation of homedirs
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/bash/shared.sh
Labels: bugfix, Bash

#8397 Introduce new abrt related rules to replace obsolete packages
  linux_os/guide/system/software/system-tools/package_libreport-plugin-logger_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_libreport-plugin-rhtsupport_removed/rule.yml
  products/ol8/profiles/ospp.profile
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/ospp.profile
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/ospp.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: bugfix

#8357 Unify a custom_command
  cmake/SSGCommon.cmake
Labels: Infrastructure

#7891 SLE15 add sysctl_kernel_exec_shield to HIPAA profile5
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/ansible/shared.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/bash/shared.sh
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/oval/shared.xml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_exec_shield/rule.yml
  products/sle15/profiles/hipaa.profile
Labels: SLES, ok-to-test, Update Rule

#8401 Update SRG-OS-000123-GPOS-00064 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000123-GPOS-00064.yml
Labels: RHEL9

#8411 Update RHEL9 auxiliary gpg key to auxiliary key 3
  products/rhel9/product.yml
Labels: bugfix

#8405 Update SRG-OS-000480-GPOS-00229 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000480-GPOS-00229.yml
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_automatic_login/rule.yml
Labels: RHEL9, Update Rule

#8403 Update SRG-OS-000480-GPOS-00232 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000480-GPOS-00232.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/package_firewalld_installed/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
Labels: RHEL9, Update Rule

#8413 Update SRG-OS-000030-GPOS-00011 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000030-GPOS-00011.yml
Labels: RHEL9

#8052 Test template filtering
  linux_os/guide/system/bootloader-grub2/grub2_kernel_trust_cpu_rng/tests/test_config.yml
  tests/README.md
  tests/ssg_test_suite/common.py
  tests/ssg_test_suite/rule.py
Labels: Test Suite

#8404 File owners, groupowners, permissions should be able to recurse and file_regex
  docs/templates/template_reference.md
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/tests/incorrect_owner_within_dir.fail.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/tests/incorrect_symlink.fail.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/tests/lenient_permissions.fail.sh
  shared/templates/file_groupowner/ansible.template
  shared/templates/file_groupowner/bash.template
  shared/templates/file_groupowner/oval.template
  shared/templates/file_owner/ansible.template
  shared/templates/file_owner/bash.template
  shared/templates/file_owner/oval.template
  shared/templates/file_permissions/ansible.template
  shared/templates/file_permissions/bash.template
  shared/templates/file_permissions/oval.template
Labels: bugfix

#8406 Add sudoers_default_includedir rule support to SLE12 and SLE15 platforms
  linux_os/guide/system/software/sudo/sudoers_default_includedir/ansible/shared.yml
  linux_os/guide/system/software/sudo/sudoers_default_includedir/rule.yml
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
Labels: SLES, ok-to-test, Update Profile

#8402 Fix docs build
  docs/requirements.txt
Labels: Documentation

#8420 File permissions library dirs shall act on files when 'file_regex' is set
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/tests/incorrect_symlink.fail.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/tests/incorrect_symlink.pass.sh
  shared/templates/file_groupowner/bash.template
  shared/templates/file_owner/bash.template
  shared/templates/file_permissions/bash.template
Labels: bugfix

#8414 Update SRG-OS-000031-GPOS-00012 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000031-GPOS-00012.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/rule.yml
Labels: RHEL9, Update Rule

#8425 Ansible: When 'file_regex` is set, only operate on files
  shared/templates/file_groupowner/ansible.template
  shared/templates/file_owner/ansible.template
  shared/templates/file_permissions/ansible.template
Labels: bugfix

#8409 Group rules for removexattr and setxattr under sam SUSE STIG IDs
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_removexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_setxattr/rule.yml
  products/sle12/profiles/stig.profile
Labels: needs-ok-to-test

#8415 Update SRG-OS-000445-GPOS-00199 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000445-GPOS-00199.yml
  linux_os/guide/system/selinux/selinux_policytype/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
Labels: RHEL9, Update Rule

#8418 Update SRG-OS-000432-GPOS-00191 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000432-GPOS-00191.yml
Labels: RHEL9

#8423 Update SRG-OS-000364-GPOS-00151 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000364-GPOS-00151.yml
Labels: RHEL9

#8434 Bump Fedora version, rawhide is now 37, drop 33
  products/fedora/product.yml
Labels: ok-to-test

#8436 Use the correct command in bash to list fingerprint of RHEL9 gpg keys
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/bash/shared.sh
Labels: RHEL9

#8416 Update SRG-OS-000437-GPOS-00194 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000437-GPOS-00194.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/rule.yml
Labels: RHEL9, Update Rule

#8440 Like the docs requirments GitPod should also use https vs the lagecy git protocol
  .gitpod.yml
Labels: Infrastructure

#8449 Introduce CPE for tftp-server
  linux_os/guide/services/obsolete/tftp/tftpd_uses_secure_mode/rule.yml
  shared/applicability/general.yml
  shared/checks/oval/installed_env_has_tftp_server_package.xml
Labels: needs-ok-to-test

#8450 Update accounts_password template OVAL for ol8
  shared/templates/accounts_password/oval.template
Labels: needs-ok-to-test

#8446 Add rule vlock_installed to STIG profile in OL8
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/vlock_installed/rule.yml
  products/ol8/profiles/stig.profile
Labels: needs-ok-to-test

#8437 Update utils/create_srg_export.py
  utils/create_srg_export.py
Labels: Infrastructure

#8439 Update SRG-OS-000445-GPOS-00199
  controls/stig_rhel9/SRG-OS-000445-GPOS-00199.yml
  linux_os/guide/system/selinux/selinux_policytype/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
Labels: RHEL9, Update Rule

#8443 Update regex to detect nfs filesystems in fstab
  shared/macros-bash.jinja
  shared/templates/mount_option_remote_filesystems/oval.template
  shared/templates/mount_option_remote_filesystems/tests/correct_option.pass.sh
  shared/templates/mount_option_remote_filesystems/tests/wrong_option.fail.sh
Labels: needs-ok-to-test

#8441 Update grub2_bootloader_argument template for ol8
  shared/templates/grub2_bootloader_argument/oval.template
Labels: needs-ok-to-test

#8458 Fix same shadow field bug in tests
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/tests/home_dir_present.pass.sh
Labels: Test Suite

#8459 Fix spacing issue on ansible lint check
  shared/templates/file_permissions/ansible.template
Labels: bugfix

#8457 Improve pam_faillock macro remediation to fix wrong control
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/tests/pam_faillock_not_required_pam_files.fail.sh
  shared/macros-bash.jinja
Labels: bugfix

#8456 Performance improvements for file permission and ownership templates
  shared/templates/file_groupowner/oval.template
  shared/templates/file_groupowner/tests/correct_groupowner.pass.sh
  shared/templates/file_groupowner/tests/incorrect_groupowner.fail.sh
  shared/templates/file_groupowner/tests/missing_file_test.pass.sh
  shared/templates/file_owner/oval.template
  shared/templates/file_owner/tests/correct_owner.pass.sh
  shared/templates/file_owner/tests/incorrect_owner.fail.sh
  shared/templates/file_owner/tests/missing_file_test.pass.sh
  shared/templates/file_permissions/oval.template
  shared/templates/file_permissions/template.py
  shared/templates/file_permissions/tests/correct_permissions.pass.sh
  shared/templates/file_permissions/tests/lenient_permissions.fail.sh
Labels: bugfix, Update Rule

#8447 Add a rule to STIG profile in OL8 and RHEL8
  linux_os/guide/system/permissions/files/dir_perms_world_writable_system_owned_group/rule.yml
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: RHEL, Oracle Linux, DISA RHEL8 STIG Alignment, Update Profile

#8448 Add a rule to STIG profile in OL8 and RHEL8
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/rule.yml
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: needs-ok-to-test

#8462 Fix variable path access issue
  shared/templates/sysctl/ansible.template
Labels: needs-ok-to-test

#8445 Introduce usbguard cpe and apply it to configure_usbguard_auditbackend
  linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml
  shared/applicability/general.yml
  shared/checks/oval/installed_env_has_usbguard_package.xml
Labels: needs-ok-to-test

#8435 Add new template to check kernel build configurations
  docs/templates/template_reference.md
  linux_os/guide/system/kernel_build_config/group.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_fs/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_strict_kernel_rwx/rule.yml
  shared/macros.jinja
  shared/references/cce-redhat-avail.txt
  shared/templates/kernel_build_config/oval.template
  shared/templates/kernel_build_config/template.py
  shared/templates/kernel_build_config/template.yml
  shared/templates/kernel_build_config/tests/fail1.fail.sh
  shared/templates/kernel_build_config/tests/fail1_multiple_files.fail.sh
  shared/templates/kernel_build_config/tests/fail2.fail.sh
  shared/templates/kernel_build_config/tests/pass1.pass.sh
  shared/templates/kernel_build_config/tests/pass2.pass.sh
Labels: New Rule

#8466 file_owner, file_groupowner, file_permission changed to no follow symlinks
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_library_dirs/tests/incorrect_symlink.pass.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/tests/dir_symlink_incorrect_dir_perm.pass.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/tests/dir_symlink_incorrect_file_perm.pass.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_library_dirs/tests/file_symlink_incorrect_target_perm.pass.sh
  shared/templates/file_groupowner/ansible.template
  shared/templates/file_groupowner/bash.template
  shared/templates/file_groupowner/oval.template
  shared/templates/file_owner/ansible.template
  shared/templates/file_owner/bash.template
  shared/templates/file_owner/oval.template
  shared/templates/file_permissions/ansible.template
  shared/templates/file_permissions/bash.template
  shared/templates/file_permissions/oval.template
Labels: bugfix

#8460 Improve the list of HTML guides
  utils/gen_html_guides_index.py
  utils/generate_html_pages.sh
  utils/html_guides_index_template.html
Labels: Infrastructure
