Repository ComplianceAsCode/content, pull requests merged in 2022-10, with the labels that each got.

#9569 Clarify instructions for implementing SCCs
  applications/openshift/general/general_apply_scc/rule.yml
Labels: OpenShift, OCIL, Update Rule

#9603 Remove ident_size for .py files from editorconfig
  .editorconfig
Labels: Infrastructure

#9607 Added 2 SLES-15/12' CCE codes for the rule package_bind_removed
  linux_os/guide/services/dns/disabling_dns_server/package_bind_removed/rule.yml
Labels: needs-ok-to-test

#9608 Added 2 SLES15/12' CCE codes to the rule package_httpd_removed
  linux_os/guide/services/http/disabling_httpd/package_httpd_removed/rule.yml
Labels: needs-ok-to-test

#9609 Added 2 SLES-15/12' CCE codes to the rule package_samba_removed
  linux_os/guide/services/smb/disabling_samba/package_samba_removed/rule.yml
Labels: needs-ok-to-test

#9610 Added 2 SLES-15/12' CCE codes for the rule package_net-snmp-removed
  linux_os/guide/services/snmp/disabling_snmp_service/package_net-snmp_removed/rule.yml
Labels: needs-ok-to-test

#9614 Added a CCE code (SLES 12) for the rule 'Enable cron Service'
  linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml
Labels: needs-ok-to-test

#9606 Added two CCE codes for SLES-12/15 to the rule package_nfs-utils_removed
  linux_os/guide/services/nfs_and_rpc/package_nfs-utils_removed/rule.yml
Labels: needs-ok-to-test

#9618 Some corrections in rule service_rsyncd_disabled.
  linux_os/guide/services/obsolete/service_rsyncd_disabled/rule.yml
Labels: needs-ok-to-test

#9619 Added SLES 15/12 CCE codes to different rules related to sshd
  linux_os/guide/services/ssh/file_permissions_sshd_config/rule.yml
  linux_os/guide/services/ssh/ssh_server/disable_host_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_x11_forwarding/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/rule.yml
Labels: needs-ok-to-test

#9622 Remove duplicated CCE
  linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml
Labels: bugfix

#9611 Add PR gating guideline
  docs/manual/developer/04_style_guide.md
Labels: Documentation

#9605 Added SLES 12 and SLES 15 CCE codes to the rule package_openldap-serv…
  linux_os/guide/services/ldap/openldap_server/package_openldap-servers_removed/rule.yml
Labels: needs-ok-to-test

#9630 Make CodeClimate to use .editorconfig
  .codeclimate.yml
Labels: Infrastructure

#9629 Remove function drop_oval_definitions
  ssg/build_renumber.py
Labels: Infrastructure

#9616 Added 10 SLES_15/12 codes to the rules file_permissions_cron_
  linux_os/guide/services/cron_and_at/file_permissions_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_weekly/rule.yml
Labels: needs-ok-to-test

#9642 Added 8 SLES 15/12 CCE codes to rules related to group restrict_at_cr…
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_cron_deny_not_exist/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_cron_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_cron_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_cron_allow/rule.yml
Labels: needs-ok-to-test

#9643 Added SLES_15/12 CCE codes related to rules in the group restict_at_c…
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_at_deny_not_exist/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_groupowner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_owner_at_allow/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_at_allow/rule.yml
Labels: needs-ok-to-test, Update Rule

#9627 Add pci-dss rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
  products/sle15/profiles/pci-dss.profile
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#9644 Two small corrections
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_cron_deny_not_exist/rule.yml
  linux_os/guide/services/cron_and_at/restrict_at_cron_users/file_permissions_cron_allow/rule.yml
Labels: SLES, needs-ok-to-test, Update Rule

#9649 Require a Github account for gitpod.io workshops
  docs/workshop/README.adoc
Labels: needs-ok-to-test

#9548 Remove shorthand.xml from the build process
  build-scripts/build_xccdf.py
  build-scripts/relabel_ids.py
  cmake/SSGCommon.cmake
  docs/manual/developer/07_understanding_build_system.md
  ssg/build_renumber.py
  ssg/build_yaml.py
Labels: Infrastructure, XCCDF12

#9654 Remove XCCDF 1.1 from enable_derivatives.py
  build-scripts/enable_derivatives.py
Labels: Infrastructure, XCCDF12

#9658 SLES 15/12 CCE codes were added to 2 rules related to avahi-daemon an…
  linux_os/guide/services/avahi/disable_avahi_group/service_avahi-daemon_disabled/rule.yml
  linux_os/guide/services/printing/service_cups_disabled/rule.yml
Labels: needs-ok-to-test

#9655 Remove XCCDF 1.1 from profile tool
  ssg/build_profile.py
Labels: Infrastructure, XCCDF12

#9656 Remove unused import
  ssg/fixes.py
Labels: Infrastructure, XCCDF12

#9657 Remove XCCDF 1.1 from ssg/xccdf.py
  ssg/xccdf.py
Labels: Infrastructure, XCCDF12

#9604 Remove Support for OVAL 5.10
  .github/workflows/gate.yaml
  .github/workflows/nightly_build_5_10.yml
  .github/workflows/release.yaml
  .github/workflows/stabilize.yaml
  CMakeLists.txt
  README.md
  build_product
  docs/manual/user_guide.adoc
  linux_os/guide/services/obsolete/r_services/no_host_based_files/oval/shared.xml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/oval/shared.xml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/oval/shared.xml
  linux_os/guide/system/accounts/enable_authselect/oval/shared.xml
  linux_os/guide/system/logging/ensure_rtc_utc_configuration/oval/shared.xml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_pattern_empty_string/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_antivirus_definitions_updated/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/oval/rhcos4.xml
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/etc_system_fips_exists/oval/shared.xml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/oval/shared.xml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/oval/ubuntu.xml
  linux_os/guide/system/software/updating/clean_components_post_updating/oval/shared.xml
  linux_os/guide/system/software/updating/clean_components_post_updating/oval/sle12.xml
  linux_os/guide/system/software/updating/clean_components_post_updating/oval/sle15.xml
  ssg/build_ovals.py
Labels: Infrastructure, Highlight

#9665 Added SLES 15/12 codes to rules ..._backup_etc_passwd
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_backup_etc_passwd/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_backup_etc_passwd/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_backup_etc_passwd/rule.yml
Labels: SLES, needs-ok-to-test

#9666 Added 6 SLES-15/12 CCE codes to the rules ..._backup_etc_shadow
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_backup_etc_shadow/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_backup_etc_shadow/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_backup_etc_shadow/rule.yml
Labels: SLES, needs-ok-to-test

#9660 Improve statistics collection from control files
  ssg/controls.py
  utils/controleval.py
Labels: enhancement, refactoring

#9661 Remove get_fixgroup_for_type
  ssg/build_remediations.py
Labels: Infrastructure, XCCDF12

#9458 Update sysctl template's OVAL and tests to align with STIG
  docs/templates/template_reference.md
  shared/templates/sysctl/oval.template
  shared/templates/sysctl/template.py
  shared/templates/sysctl/tests/one_sysctl_conf_one_sysctl_d.pass.sh
  shared/templates/sysctl/tests/one_sysctl_conf_one_sysctl_d_conflicting.fail.sh
  shared/templates/sysctl/tests/symlink_conflicting.fail.sh
  shared/templates/sysctl/tests/symlink_root_duplicate.pass.sh
  shared/templates/sysctl/tests/symlink_root_duplicate_conflicting.fail.sh
  shared/templates/sysctl/tests/symlink_same_option.pass.sh
  shared/templates/sysctl/tests/two_sysctls_on_d.pass.sh
  shared/templates/sysctl/tests/two_sysctls_on_d_conflicting.fail.sh
  shared/templates/sysctl/tests/two_sysctls_on_same_file_name.pass.sh
  shared/templates/sysctl/tests/two_sysctls_on_same_file_name_conflicting.fail.sh
Labels: Infrastructure, needs-ok-to-test

#9659 Remove unused XSLT xccdf2table-profileanssirefs.xslt
  docs/manual/developer/03_creating_content.md
  products/alinux2/transforms/xccdf2table-profileanssirefs.xslt
  products/alinux3/transforms/xccdf2table-profileanssirefs.xslt
  products/example/new_product.sh
  products/uos20/transforms/xccdf2table-profileanssirefs.xslt
Labels: Infrastructure

#9669 Added 6 SLES 15/12 CCE codes to the rules sshd_...
  linux_os/guide/services/ssh/ssh_server/sshd_disable_tcp_forwarding/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pam/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_auth_tries/rule.yml
Labels: SLES, needs-ok-to-test, Update Rule, CIS

#9645 Add PCI-DSS rules
  linux_os/guide/system/software/sudo/sudo_custom_logfile/rule.yml
  products/sle15/profiles/pci-dss.profile
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#9670 CIS RHEL8 gnome related requirements
  controls/cis_rhel8.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_disable_user_list/rule.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/gnome_gdm_disable_xdmcp/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL8, CIS

#9664 Fix a few tests in rules used by OL7
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/tests/altcorrect_permissions.pass.sh
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/tests/altlenient_permissions.fail.sh
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/tests/supercompliance.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/nothing.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/wrong_value_no.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_priv_separation/tests/wrong_value_yes.fail.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/tests/missing.fail.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/tests/wrong_multiple.fail.sh
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/tests/disabled_wireless_interfaces.pass.sh
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/tests/enabled_wireless_interface.fail.sh
  products/ol7/product.yml
  products/ol8/product.yml
  products/ol9/product.yml
  shared/templates/kernel_module_disabled/tests/missing_blacklist.fail.sh
  shared/templates/service_enabled/tests/service_disabled.fail.sh
  shared/templates/service_enabled/tests/service_enabled.pass.sh
Labels: needs-ok-to-test

#9646 CMake Improvements
  CMakeLists.txt
Labels: Infrastructure

#9672 Add PCI-DSS Rules
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action/rule.yml
  products/sle15/profiles/pci-dss.profile
Labels: needs-ok-to-test

#9674 New rules for usrquota and grpquota in /home
  controls/cis_rhel8.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_grpquota/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_usrquota/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL8, CIS

#9677 Add dconf_gnome_disable_user_list to the RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_disable_user_list/policy/stig/shared.yml
Labels: Update Profile, STIG

#9681 Added SLES 15 CCE and STIG ID code to the rule
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml
Labels: needs-ok-to-test

#9680 Added CCE number for SLES_15 in the rule sshd_use_approved_ciphers
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
Labels: SLES, needs-ok-to-test, Update Rule, CIS

#9682 Added 4 SLES 15/12 codes to the rules group_unique_id/name
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_id/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_name/rule.yml
Labels: SLES, needs-ok-to-test, Update Rule, CIS

#9685 SLE Add rpm verify rules for sle12
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/rule.yml
Labels: needs-ok-to-test

#9683 Remove Travis CI
  .travis.yml
Labels: Infrastructure

#9663 Add tests to mount_option template
  linux_os/guide/system/permissions/partitions/mount_option_boot_noauto/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/tests/separate.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_proc_hidepid/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_noexec/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nosuid/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_nodev/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_noexec/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_nosuid/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_bind/tests/test_config.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_noexec/tests/separate.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/tests/fstab.fail.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/tests/runtime.pass.sh
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nosuid/tests/separate.fail.sh
  shared/templates/mount_option/tests/fstab.fail.sh
  shared/templates/mount_option/tests/runtime.pass.sh
  shared/templates/mount_option/tests/separate.fail.sh
Labels: needs-ok-to-test

#9560 Move to MyST as recommonmark and CommonMark are not supported
  .gitpod.yml
  CMakeLists.txt
  Dockerfiles/opensuse_leap_15_2
  docs/conf.py
  docs/requirements.txt
Labels: Documentation

#9673 Complete the 1.4.2 requirement for CIS RHEL7 and RHEL8
  controls/cis_rhel7.yml
  controls/cis_rhel8.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/file_groupowner_user_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/file_owner_user_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/non-uefi/file_permissions_user_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/file_groupowner_efi_user_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/file_owner_efi_user_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/file_permissions_efi_user_cfg/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL7, RHEL8, CIS

#9691 Include the status tag in SRG-OS-000163-GPOS-00072
  controls/srg_gpos/SRG-OS-000163-GPOS-00072.yml
Labels: RHEL9, STIG

#9675 Refactor json output function in controleval.py
  utils/controleval.py
Labels: enhancement, refactoring

#9412 Remove jinja condition to make rule applicability to all products in Kerberos rules
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/rule.yml
  linux_os/guide/services/kerberos/package_krb5-server_removed/rule.yml
  linux_os/guide/system/software/system-tools/package_krb5-workstation_removed/rule.yml
  shared/checks/oval/krb5_workstation_older_than_1_17_18.xml
  ssg/build_cpe.py
  tests/unit/ssg-module/data/applicability/general.yml
  tests/unit/ssg-module/test_build_yaml.py
Labels: OVAL

#9693 Add tests to sebool template
  linux_os/guide/system/selinux/selinux-booleans/sebool_secure_mode_policyload/tests/test_config.yml
  shared/templates/sebool/template.py
  shared/templates/sebool/tests/correct_value.pass.sh
  shared/templates/sebool/tests/wrong_value.fail.sh
Labels: needs-ok-to-test

#9688 Remove comparison utilities
  shared/transforms/xccdf-get-only-ovals-sorted.xslt
  shared/transforms/xccdf-get-only-remediations-sorted.xslt
  tests/python2_vs_python3_sanity.sh
  utils/compare_generated.sh
  utils/compare_remediations.sh
Labels: Infrastructure

#9634 compare_ds.py: Identify new and missing rules while comparing content
  ssg/content_diff.py
Labels: bugfix, enhancement

#9702 Fix OL documentation links
  linux_os/guide/services/ldap/openldap_client/group.yml
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/system/selinux/group.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: bugfix, needs-ok-to-test

#9707 service_ntp_enabled: Fix description as service name is ntp
  linux_os/guide/services/ntp/service_ntp_enabled/rule.yml
Labels: needs-ok-to-test, Update Rule

#9692 Fix issue introduced in commit 1ba11cb
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/tests/correct_groupowner.pass.sh
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/tests/incorrect_groupowner.fail.sh
Labels: Test Suite, needs-ok-to-test, Update Rule

#9703 CIS: Update etcd encryption provider rationale
  applications/openshift/api-server/api_server_encryption_provider_cipher/rule.yml
Labels: OpenShift

#9710 remove ospp-mls.profile
  docs/workshop/lab3_profiles.adoc
  products/rhel8/profiles/ospp-mls.profile
Labels: needs-ok-to-test, Update Profile, RHEL8

#9701 Add tests to rule dconf_gnome_screensaver_idle_activation_enabled
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/tests/comment.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/tests/correct_value.pass.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/tests/missing_lock.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/tests/setting_not_there.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/tests/wrong_value.fail.sh
Labels: Test Suite, needs-ok-to-test

#9704 Fix docs refs
  docs/conf.py
  docs/manual/developer/02_building_complianceascode.md
  docs/manual/developer/03_creating_content.md
  docs/manual/developer/04_style_guide.md
  docs/manual/developer/05_tools_and_utilities.md
  docs/manual/developer/06_contributing_with_content.md
  docs/modules/utils.rst
  tests/README.md
Labels: Documentation

#9705 Add pcidss Req-ids
  linux_os/guide/services/ftp/disabling_vsftpd/package_vsftpd_removed/rule.yml
  linux_os/guide/services/ldap/openldap_client/package_openldap-clients_removed/rule.yml
  linux_os/guide/services/mail/postfix_client/postfix_network_listening_disabled/rule.yml
  linux_os/guide/services/ntp/package_chrony_installed/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypserv_removed/rule.yml
  linux_os/guide/services/obsolete/telnet/package_telnet-server_removed/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_pub_key/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_do_not_permit_user_env/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_verbose/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_minlen/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_retry/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pamcracklib/cracklib_accounts_password_pam_ucredit/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_minimum_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_warn_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/securetty_root_login_console_only/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/rule.yml
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_nx/bios_enable_execution_restrictions/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_nx/install_PAE_kernel_on_x86-32/rule.yml
  linux_os/guide/system/software/sudo/package_sudo_installed/rule.yml
  linux_os/guide/system/software/sudo/sudo_add_use_pty/rule.yml
  linux_os/guide/system/software/sudo/sudo_custom_logfile/rule.yml
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#9708 Ubuntu 20.04: fix grub2 password related rules
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/oval/ubuntu.xml
  products/ubuntu2004/product.yml
  products/ubuntu2004/profiles/cis_level1_server.profile
  products/ubuntu2004/profiles/stig.profile
Labels: OVAL, Ubuntu, Update Profile

#9711 Fix rsyslog_remote_tls Remediations
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls/ansible/shared.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls/bash/shared.sh
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls/tests/no_server.fail.sh
Labels: Ansible, Bash, Update Rule

#9709 Free CCE codes for SLES 12/15 OSes
  shared/references/cce-sles12-avail.txt
  shared/references/cce-sles15-avail.txt
Labels: needs-ok-to-test

#9624 Create unit tests for ssg.id_translate
  .github/workflows/gate.yaml
  tests/unit/ssg-module/data/draft_ocil.xml
  tests/unit/ssg-module/data/draft_oval.xml
  tests/unit/ssg-module/test_id_translate.py
Labels: Infrastructure, XCCDF12

#9706 Added 2 SLES 15/12 CCE codes to the rule disable_prelink
  linux_os/guide/system/software/integrity/disable_prelink/ansible/shared.yml
  linux_os/guide/system/software/integrity/disable_prelink/rule.yml
Labels: SLES, needs-ok-to-test, Update Rule, CIS

#9632 Add unit tests for ssg/build_renumber.py
  ssg/build_renumber.py
  tests/unit/ssg-module/data/oval_with_broken_extend_definition.xml
  tests/unit/ssg-module/data/oval_with_correct_extend_definition.xml
  tests/unit/ssg-module/test_build_renumber.py
Labels: XCCDF12

#9717 Assign RHEL-07-010271 to account_emergency_expire_date.
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_emergency_expire_date/policy/stig/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_emergency_expire_date/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_temp_expire_date/policy/stig/shared.yml
  products/rhel7/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
Labels: Update Profile, RHEL7, STIG

#9617 Add unit tests of XCCDF 1.2 elements
  docs/manual/developer/02_building_complianceascode.md
  ssg/build_yaml.py
  tests/unit/ssg-module/data/accounts_tmout.xml
  tests/unit/ssg-module/data/accounts_tmout.yml
  tests/unit/ssg-module/data/ospp.profile
  tests/unit/ssg-module/data/ospp.xml
  tests/unit/ssg-module/data/selinux.xml
  tests/unit/ssg-module/data/selinux.yml
  tests/unit/ssg-module/data/var_system_crypto_policy.xml
  tests/unit/ssg-module/data/var_system_crypto_policy.yml
  tests/unit/ssg-module/test_build_yaml.py
Labels: Infrastructure, XCCDF12

#9721 Ubuntu 20.04 CIS Level1 profile: add package_pam_pwquality_installed
  products/ubuntu2004/profiles/cis_level1_server.profile
Labels: Ubuntu, needs-ok-to-test, Update Profile, CIS

#9652 Automated rule to check for insecure image registries
  applications/openshift/registry/ocp_insecure_allowed_registries_for_import/rule.yml
  applications/openshift/registry/ocp_insecure_allowed_registries_for_import/tests/correct.pass.sh
  applications/openshift/registry/ocp_insecure_allowed_registries_for_import/tests/no_file.fail.sh
  applications/openshift/registry/ocp_insecure_allowed_registries_for_import/tests/ocp4/e2e.yml
  applications/openshift/registry/ocp_insecure_allowed_registries_for_import/tests/registries.fail.sh
  applications/openshift/registry/ocp_insecure_registries/rule.yml
  applications/openshift/registry/ocp_insecure_registries/tests/correct.pass.sh
  applications/openshift/registry/ocp_insecure_registries/tests/no_file.fail.sh
  applications/openshift/registry/ocp_insecure_registries/tests/ocp4/e2e.yml
  applications/openshift/registry/ocp_insecure_registries/tests/registries.fail.sh
  controls/nist_ocp4.yml
  controls/srg_ctr/SRG-APP-000014-CTR-000035.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenShift, ok-to-test

#9715 Improve remediation of dir_perms_world_writable_sticky_bits
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/bash/shared.sh
  linux_os/guide/system/permissions/files/dir_perms_world_writable_sticky_bits/tests/correct.pass.sh
Labels: needs-ok-to-test

#9719 Add Ubuntu specific bash for ensure_rsyslog_log_file_configuration
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/bash/shared.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/bash/ubuntu.sh
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/oval/shared.xml
Labels: OVAL, Bash, Ubuntu, needs-ok-to-test, Update Rule

#9637 Add unit tests for warnings and sub elements
  tests/unit/ssg-module/test_build_yaml.py
Labels: Infrastructure, XCCDF12

#9636 Add an unit test for the to_ocil() method
  tests/unit/ssg-module/data/accounts_tmout_action.xml
  tests/unit/ssg-module/data/accounts_tmout_boolean_question.xml
  tests/unit/ssg-module/data/accounts_tmout_questionnaire.xml
  tests/unit/ssg-module/data/accounts_tmout_without_ocil.yml
  tests/unit/ssg-module/test_build_yaml.py
Labels: XCCDF12

#9714 Include SLE products into the CCE tooling for auto assignment
  docs/manual/developer/05_tools_and_utilities.md
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
  ssg/cce.py
Labels: Documentation, SLES

#9720 install_smartcard_packages: Add Ubuntu specific remediation
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/bash/ubuntu.sh
Labels: Bash, Ubuntu, needs-ok-to-test, Update Rule

#9722 Ubuntu 20.04: Make sure xatrr audit rules contains a check for root user
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_fsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_removexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_setxattr/rule.yml
Labels: Ubuntu, needs-ok-to-test, Update Rule

#9695 Fix config file and interpreter check control flow
  shared/templates/firefox_policy-setting/bash.template
Labels: Bash, needs-ok-to-test

#9689 Refactor and speed up combine_ovals.py
  ssg/build_ovals.py
Labels: Infrastructure

#9716 Added rules to PCI DSS 4.0 SLES 15 profile
  linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/rule.yml
  products/sle15/profiles/pci-dss-4.profile
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#9727 Fix unit tests to work with CentOS 7
  tests/unit/ssg-module/test_id_translate.py
Labels: bugfix, Infrastructure

#9667 Added SLES 15/12 CCE codes related to the rules ...backup_etc_group
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_backup_etc_group/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_backup_etc_group/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_backup_etc_group/rule.yml
Labels: SLES, needs-ok-to-test

#9729 Created SLES 12 PCI DSS 4.0 profile and added rules to it
  products/sle12/profiles/pci-dss-4.profile
Labels: SLES, needs-ok-to-test, New Profile, pci-dss

#9712 Refactor firewalld_sshd_port_enabled rule
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/rule.yml
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/customized_zone_configured.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/customized_zone_without_ssh.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/new_zone_configured.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/new_zone_without_ssh.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/no_nic_in_ssh_zone.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/no_ssh_zone.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/only_nics_configured.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/only_zones_configured.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_port_enabled.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_zone_and_nic_mismatch.fail.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/ssh_zone_nic_bounded.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/zones_and_nics_configured.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/zones_and_nics_ok_no_custom_files.pass.sh
  linux_os/guide/services/ssh/ssh_server/firewalld_sshd_port_enabled/tests/zones_and_nics_ok_port_changed.pass.sh
Labels: Ansible, Test Suite, refactoring, OVAL, Bash, Update Rule

#9735 Added 4 rules to SLES 12/15 PCI DSS 4.0 profiles
  products/sle12/profiles/pci-dss-4.profile
  products/sle15/profiles/pci-dss-4.profile
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#9733 Add new rules related to system banners - /etc/issue.net
  controls/cis_rhel7.yml
  controls/cis_rhel8.yml
  linux_os/guide/system/accounts/accounts-banners/file_groupowner_etc_issue_net/rule.yml
  linux_os/guide/system/accounts/accounts-banners/file_owner_etc_issue_net/rule.yml
  linux_os/guide/system/accounts/accounts-banners/file_permissions_etc_issue_net/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL7, RHEL8, CIS

#9742 Update SLE 15 SAP hardening profile
  products/sle15/profiles/pcs-hardening-sap.profile
Labels: SLES, needs-ok-to-test, Update Profile

#9739 Complete tests to validate Ol9 pci dss profile
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/tests/missing_value.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/tests/wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/tests/missing_value.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/tests/wrong_value.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit/tests/wrong_value.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action/tests/correct_value.pass.sh
Labels: Test Suite, Oracle Linux, needs-ok-to-test, pci-dss

#9475 add new rule logind_session_timeout
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/rule.yml
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/correct_not_directly_after_section.pass.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/correct_value_no_section.fail.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/correct_value_wrong_section.fail.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/file_missing.fail.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/incorrect.fail.sh
  linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/tests/not_configured.fail.sh
  linux_os/guide/system/accounts/accounts-physical/var_logind_session_timeout.var
  shared/macros/10-bash.jinja
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, RHEL8

#9736 Reformulate the release process documentation
  docs/release_process.md
Labels: enhancement, Documentation
