Repository ComplianceAsCode/content, pull requests merged in 2022-04, with the labels that each got.

#8471 SRG-OS-000349-GPOS-00137 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000349-GPOS-00137.yml
  linux_os/guide/system/auditing/service_auditd_enabled/rule.yml
Labels: RHEL9, Update Rule

#8470 Update SRG-OS-000281-GPOS-00111 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000281-GPOS-00111.yml
Labels: RHEL9

#8469 Cleanups
  build-scripts/add_stig_references.py
  build-scripts/build_all_guides.py
  build-scripts/build_profile_remediations.py
  build-scripts/build_sce.py
  build-scripts/build_shorthand.py
  build-scripts/build_templated_content.py
  build-scripts/collect_remediations.py
  build-scripts/combine_ovals.py
  build-scripts/cpe_generate.py
  build-scripts/enable_derivatives.py
  build-scripts/generate_fixes_xml.py
  build-scripts/generate_man_page.py
  build-scripts/oscap_svg_support.py
  build-scripts/profile_tool.py
  build-scripts/relabel_ids.py
  build-scripts/unselect_empty_xccdf_groups.py
  build-scripts/verify_references.py
  release_tools/content_gh.py
  shared/references/disa-stig-rhel7-v3r6-xccdf-scap.xml
  tests/analyze_results.py
  tests/assert_ansible_schema.py
  tests/ensure_paths_are_short.py
  tests/install_vm.py
  tests/run_scapval.py
  tests/ssg_test_suite/combined.py
  tests/ssg_test_suite/oscap.py
  tests/ssg_test_suite/profile.py
  tests/ssg_test_suite/virt.py
  tests/ssg_test_suite/xml_operations.py
  tests/stable_profile_ids.py
  tests/test_parse_affected.py
  tests/test_parse_platform.py
  tests/test_suite.py
  utils/ansible_playbook_to_role.py
  utils/autoprodtyper.py
  utils/build_ds_container.py
  utils/build_stig_control.py
  utils/compare_disa_xml.py
  utils/compare_results.py
  utils/controleval.py
  utils/count_oval_objects.py
  utils/create-stig-overlay.py
  utils/create_scap_delta_tailoring.py
  utils/create_srg_export.py
  utils/duplicated_prodtypes.py
  utils/find_duplicates.py
  utils/fix_rules.py
  utils/generate_contributors.py
  utils/ignition-remediation.py
  utils/mod_checks.py
  utils/mod_fixes.py
  utils/mod_prodtype.py
  utils/refchecker.py
  utils/regexify_banner.py
  utils/rule_dir_diff.py
  utils/rule_dir_json.py
  utils/rule_dir_stats.py
  utils/srg_audit.py
  utils/xccdf2csv-stig.py
Labels: ok-to-test

#8476 Update SRG-OS-000121-GPOS-00062 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000121-GPOS-00062.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_unique_id/rule.yml
Labels: RHEL9

#8369 Remove update_sds_version.py
  build-scripts/compose_ds.py
  build-scripts/update_sds_version.py
  cmake/SSGCommon.cmake
  docs/manual/developer/07_understanding_build_system.md
Labels: Infrastructure

#8477 Kernel memory configs
  linux_os/guide/system/kernel_build_config/kernel_config_acpi_custom_method/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_compat_vdso/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_wx/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_devkmem/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_fortify_source/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hardened_usercopy/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hardened_usercopy_fallback/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_emulate/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_none/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_xonly/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_proc_kcore/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_refcount_full/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_retpoline/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_sched_stack_end_check/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_security_dmesg_restrict/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_stackprotector/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_stackprotector_strong/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_vmap_stack/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_x86_vsyscall_emulation/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8479 Fix OCIL macro call for some kernel build config rules
  linux_os/guide/system/kernel_build_config/kernel_config_debug_wx/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_fortify_source/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hardened_usercopy/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_none/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_refcount_full/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_retpoline/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_sched_stack_end_check/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_vmap_stack/rule.yml
Labels: bugfix

#8486 Change the OCIL clause of kernel build config rules to negative form
  linux_os/guide/system/kernel_build_config/kernel_config_acpi_custom_method/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_compat_vdso/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_fs/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_wx/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_devkmem/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_fortify_source/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hardened_usercopy/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hardened_usercopy_fallback/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_emulate/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_none/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_vsyscall_xonly/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_proc_kcore/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_refcount_full/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_retpoline/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_sched_stack_end_check/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_security_dmesg_restrict/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_stackprotector/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_stackprotector_strong/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_strict_kernel_rwx/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_vmap_stack/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_x86_vsyscall_emulation/rule.yml
Labels: bugfix

#8484 Set Benchmark's resolved attribute to true
  ssg/build_yaml.py
Labels: bugfix

#8488 Add rules for kernel memory allocators settings
  linux_os/guide/system/kernel_build_config/kernel_config_compat_brk/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_page_poisoning/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_page_poisoning_no_sanity/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_page_poisoning_zero/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_slab_freelist_hardened/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_slab_freelist_random/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_slab_merge_default/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_slub_debug/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8483 Add rules for kernel data structure configs
  linux_os/guide/system/kernel_build_config/kernel_config_bug_on_data_corruption/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_credentials/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_list/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_notifiers/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_debug_sg/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8327 Add auid criteria to rules related to syscall audit rules
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/tests/correct_rules.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/tests/missing_auid_filter.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/tests/rules_not_there.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/tests/wrong_list_action.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/tests/wrong_syscall.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/tests/correct_rules.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/tests/default.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/tests/missing_auid_filter.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/tests/correct_rules.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/tests/default.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/tests/missing_auid_filter.fail.sh
Labels: ok-to-test, Test Scenario, Update Rule

#8452 Update package_krb5-server_removed
  linux_os/guide/services/kerberos/package_krb5-server_removed/rule.yml
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: ok-to-test

#8502 Add rules for various kernel behaviors
  linux_os/guide/system/kernel_build_config/kernel_config_binfmt_misc/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_hibernation/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_kexec/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_legacy_ptys/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8501 Add rules to check kernel IP stack configs
  linux_os/guide/system/kernel_build_config/kernel_config_ipv6/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_syn_cookies/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8499 Add rules for kernel compiler features
  linux_os/guide/system/kernel_build_config/gcc_plugin/group.yml
  linux_os/guide/system/kernel_build_config/gcc_plugin/kernel_config_gcc_plugin_latent_entropy/rule.yml
  linux_os/guide/system/kernel_build_config/gcc_plugin/kernel_config_gcc_plugin_randstruct/rule.yml
  linux_os/guide/system/kernel_build_config/gcc_plugin/kernel_config_gcc_plugin_stackleak/rule.yml
  linux_os/guide/system/kernel_build_config/gcc_plugin/kernel_config_gcc_plugin_structleak/rule.yml
  linux_os/guide/system/kernel_build_config/gcc_plugin/kernel_config_gcc_plugin_structleak_byref_all/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8498 Add rules for kernel security options
  linux_os/guide/system/kernel_build_config/kernel_config_seccomp/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_seccomp_filter/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_security/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_security_writable_hooks/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_security_yama/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8481 Add Centos Stream 8/9 support in install_vm script
  tests/install_vm.py
Labels: Test Suite

#8494 Update SRG-OS-000104-GPOS-00051 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000104-GPOS-00051.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/force_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/group_unique_id/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/gid_passwd_group_same/rule.yml
Labels: RHEL9

#8506 Add rules for ARM64 kernel
  linux_os/guide/system/kernel_build_config/kernel_config_arm64_sw_ttbr0_pan/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_unmap_kernel_at_el0/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8504 Add rules for 64b kernel
  linux_os/guide/system/kernel_build_config/kernel_config_default_mmap_min_addr/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_ia32_emulation/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_modify_ldt_syscall/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_page_table_isolation/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_randomize_base/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_randomize_memory/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8503 Add rules to configure Kernel panic behavior
  linux_os/guide/system/kernel_build_config/kernel_config_bug/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_panic_on_oops/rule.yml
  linux_os/guide/system/kernel_build_config/kernel_config_panic_timeout/rule.yml
  linux_os/guide/system/kernel_build_config/var_kernel_config_panic_timeout.var
  shared/references/cce-redhat-avail.txt
Labels: New Rule

#8509 remove redundant rule from HIPAA profiles
  products/rhel7/profiles/hipaa.profile
  products/rhel8/profiles/hipaa.profile
  products/rhel9/profiles/hipaa.profile
Labels: Update Profile

#8514 Update SRG-OS-000120-GPOS-00061 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000120-GPOS-00061.yml
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/ansible/shared.yml
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/rule.yml
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/tests/file_absent.pass.sh
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/tests/file_present.fail.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed_sha512/rule.yml
  linux_os/guide/system/logging/package_rsyslog-gnutls_installed/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls/rule.yml
  linux_os/guide/system/network/network-ipsec/package_libreswan_installed/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  linux_os/guide/system/software/system-tools/package_krb5-workstation_removed/rule.yml
Labels: RHEL9, Update Rule, DISA RHEL9 STIG Alignment

#8455 Add utils/convert_srg_export_to_xlsx.py
  utils/convert_srg_export_to_xlsx.py
  utils/create_srg_export.py
Labels: DISA RHEL9 STIG Alignment

#8508 align RHEL8 OSPP with certification requirements
  products/rhel8/profiles/ospp.profile
  tests/data/profile_stability/rhel8/ospp.profile
Labels: Update Profile

#8478 Define CPE and detection logic for OCP4 on HyperShift
  products/ocp4/product.yml
  shared/checks/oval/installed_app_is_ocp4.xml
Labels: needs-ok-to-test

#8326 Add new GH job to generate XLSX table and HTML page with SRG mapping
  .github/workflows/gh-pages.yaml
  .github/workflows/srg-mapping-table.yaml
  utils/convert_srg_export_to_html.py
  utils/convert_srg_export_to_xlsx.py
  utils/create_srg_export.py
  utils/generate_html_pages.sh
Labels: Infrastructure

#8533 Fix index page generation for guides artifacts.
  .github/workflows/gh-pages.yaml
  utils/generate_html_pages.sh
Labels: Infrastructure

#8534 typo: kernel_config_slub_debug Enale -> Enable
  linux_os/guide/system/kernel_build_config/kernel_config_slub_debug/rule.yml
Labels: bugfix, ok-to-test

#8536 Exclude package_libreport-plugin-rhtsupport_removed from stig_gui profile
  products/rhel8/profiles/stig_gui.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: DISA RHEL8 STIG Alignment

#8538 Fix broken Oracle Linux doc links.
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_multiple_servers/rule.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/group.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/sssd/group.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: bugfix, Update Rule

#8525 RHEL 9 STIG for Multifactor Auth SRG Items
  controls/stig_rhel9/SRG-OS-000105-GPOS-00052.yml
  controls/stig_rhel9/SRG-OS-000106-GPOS-00053.yml
  controls/stig_rhel9/SRG-OS-000107-GPOS-00054.yml
  controls/stig_rhel9/SRG-OS-000108-GPOS-00055.yml
  controls/stig_rhel9/SRG-OS-000109-GPOS-00056.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_pubkey_auth/rule.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/install_smartcard_packages/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8096 Document GHA release process
  docs/conf.py
  docs/index.rst
  docs/release_process.md
  release_tools/README.md
  release_tools/bump_release_in_cmake.sh
  release_tools/check_rhel_stig_ids.sh
  release_tools/content_gh.py
  release_tools/make_tarball.sh
  release_tools/release_content.py
Labels: Documentation

#8542 Fix gh-pages SRG mapping index page generation and deployment
  .github/workflows/srg-mapping-table.yaml
  utils/generate_html_index_srg_mapping.sh
  utils/generate_html_pages.sh
Labels: DISA RHEL9 STIG Alignment

#8535 Update SRG-OS-000134-GPOS-00068 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000134-GPOS-00068.yml
  linux_os/guide/system/bootloader-grub2/grub2_vsyscall_argument/rule.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_page_poison_argument/rule.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_slub_debug_argument/rule.yml
  linux_os/guide/system/selinux/package_policycoreutils_installed/rule.yml
  linux_os/guide/system/selinux/selinux_state/rule.yml
  shared/macros.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8544 Add docuemntion for Pandas dependancy
  docs/manual/developer/02_building_complianceascode.md
Labels: Documentation

#8537 Update SRG-OS-000142-GPOS-00071 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000142-GPOS-00071.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
  shared/macros.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8554 For sle systems the etc shadow is group shadow
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_etc_shadow/rule.yml
Labels: needs-ok-to-test

#8545 Enable for ansible and bash remediation for SLE15 and SLE12.
  linux_os/guide/system/accounts/accounts-banners/banner_etc_motd/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_motd/bash/shared.sh
Labels: SLES, ok-to-test, Update Rule

#8551 SUSE add multi_platform_sle to audit_rules_file_deletion_events/bash.…
  shared/templates/audit_rules_file_deletion_events/bash.template
Labels: SLES, ok-to-test

#8560 bugfix: auditing: Fix documentation distro
  linux_os/guide/system/auditing/group.yml
Labels: bugfix, ok-to-test

#8552 SUSE add bash remediation for file_etc_security_opasswd
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_etc_security_opasswd/bash/shared.sh
Labels: ok-to-test

#8559 Add Fedora to disk_partitioning/encrypt_partitions
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: ok-to-test

#8553 SUSE fix file_groupowner_backup_etc_shadow
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_backup_etc_shadow/rule.yml
Labels: needs-ok-to-test

#8558 SUSE disable_users_coredumps enable bash remediation for sle.
  linux_os/guide/system/permissions/restrictions/coredumps/disable_users_coredumps/bash/shared.sh
Labels: Bash, SLES, ok-to-test

#8438 Update grub2_uefi_password & grub2_uefi_admin_username
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/tests/no-grub.pass.sh
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/tests/no-grub.pass.sh
  products/ol8/product.yml
Labels: ok-to-test

#8569 Update SRG-OS-000113-GPOS-00058 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000113-GPOS-00058.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8568 Update SRG-OS-000380-GPOS-00165 for RHEL9 STIG
  controls/stig_rhel9/SRG-OS-000380-GPOS-00165.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8556 Update SRG-OS-000185-GPOS-00079 for RHEL 9 STIG
  controls/stig_rhel9/SRG-OS-000185-GPOS-00079.yml
  linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8573 OCP: Added Control Response for SC group
  controls/nist_ocp4.yml
Labels: OpenShift

#8549 SUSE SLE fix audit_rules_unsuccessful_file_modification_renameat2
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat2/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlinkat/rule.yml
Labels: ok-to-test

#8571 Add cce to srg export
  docs/manual/developer/02_building_complianceascode.md
  utils/create_srg_export.py
Labels: Infrastructure

#8563 fix grub2 remediations for sle12 and sle15
  shared/macros/bash.jinja
  shared/templates/grub2_bootloader_argument/ansible.template
Labels: bugfix, ok-to-test

#8582 SUSE enable no_rsh_trust_files remediation bash and ansible
  linux_os/guide/services/obsolete/r_services/no_rsh_trust_files/ansible/shared.yml
  linux_os/guide/services/obsolete/r_services/no_rsh_trust_files/bash/shared.sh
Labels: needs-ok-to-test

#8581 SUSE enable bash remediation for accounts_logon_fail_delay
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/bash/shared.sh
Labels: needs-ok-to-test

#8584 SUSE auditd_data_retention_flush enable bash remediation
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_flush/bash/shared.sh
Labels: needs-ok-to-test

#8557 Align kernel_module_loading remediations
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/auditctl_syscalls_multiple_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/auditctl_syscalls_one_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/auditctl_syscalls_one_per_line.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/auditctl_syscalls_one_per_line_one_missing.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/augen_syscalls_multiple_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/augen_syscalls_one_per_arg.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/augen_syscalls_one_per_line.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/tests/augen_syscalls_one_per_line_one_missing.fail.sh
Labels: bugfix

#8583 SUSE enable selinux_policytype remediation bash and ansible
  linux_os/guide/system/selinux/selinux_policytype/ansible/shared.yml
  linux_os/guide/system/selinux/selinux_policytype/bash/shared.sh
Labels: needs-ok-to-test

#8570 Update SRG-OS-000356-GPOS-00144 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000356-GPOS-00144.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8491 Update SRG-OS-000324-GPOS-00125 for RHEL 9
  controls/srg_gpos/SRG-OS-000324-GPOS-00125.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_burstaction/rule.yml
  linux_os/guide/system/accounts/accounts-physical/disable_ctrlaltdel_reboot/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_hardlinks/rule.yml
  linux_os/guide/system/permissions/files/sysctl_fs_protected_symlinks/rule.yml
  linux_os/guide/system/software/sudo/package_sudo_installed/rule.yml
  shared/macros/fixtext.jinja
  shared/macros/general.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8587 Update SRG-OS-000057-GPOS-00027 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000027-GPOS-00008.yml
  linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8589 Update SRG-OS-000383-GPOS-00166 for RHEL9 STIG
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8593 Update SRG-OS-000228-GPOS-00088 and general fixes to the srg export python script
  controls/srg_gpos/SRG-OS-000024-GPOS-00007.yml
  controls/srg_gpos/SRG-OS-000228-GPOS-00088.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/rule.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/rule.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/rule.yml
  utils/create_srg_export.py
Labels: DISA RHEL9 STIG Alignment

#8595 Update SRG-OS-000239-GPOS-00089
  controls/srg_gpos/SRG-OS-000239-GPOS-00089.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification/rule.yml
Labels: DISA RHEL9 STIG Alignment

#8597 Update SRG-OS-000481-GPOS-000481 for RHEL9 STIG
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/rule.yml
Labels: DISA RHEL9 STIG Alignment

#8427 AIDE RHEL9 STIG
  controls/srg_gpos/SRG-OS-000256-GPOS-00097.yml
  controls/srg_gpos/SRG-OS-000363-GPOS-00150.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_group_ownership/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_ownership/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/file_audit_tools_permissions/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/package_aide_installed/rule.yml
  products/rhel8/profiles/stig.profile
  products/rhel9/profiles/stig.profile
  shared/macros/general.jinja
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: New Rule, DISA RHEL8 STIG Alignment, RHEL9, Update Rule, DISA RHEL9 STIG Alignment

#8548 Update accounts_umask_etc_profile remediation regex to handle comments
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/tests/commented_out.fail.sh
Labels: ok-to-test

#8585 SUSE no_empty_passwords enable bash remediation.
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/bash/shared.sh
Labels: Bash, SLES, ok-to-test

#8613 Remove rules that do not belong to SRG-OS-000240-GPOS-00090 and SRG-OS-000240-GPOS-00091
  controls/srg_gpos/SRG-OS-000240-GPOS-00090.yml
  controls/srg_gpos/SRG-OS-000241-GPOS-00091.yml
Labels: DISA RHEL9 STIG Alignment

#8615 Update SRG-OS-000374-GPOS-00159
  controls/srg_gpos/SRG-OS-000374-GPOS-00159.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8619 Update SRG-OS-000298-GPOS-00116
  controls/srg_gpos/SRG-OS-000298-GPOS-00116.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8614 Update SRG-OS-000359-GPOS-00146
  controls/srg_gpos/SRG-OS-000359-GPOS-00146.yml
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
  linux_os/guide/system/auditing/package_audit_installed/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8621 Update SRG-OS-000355-GPOS-00143
  controls/srg_gpos/SRG-OS-000355-GPOS-00143.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8629 Update SRG-OS-000433-GPOS-00193 for RHEL 9 STIG
  linux_os/guide/system/bootloader-grub2/grub2_pti_argument/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_randomize_va_space/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8632 package_mcafeetp_installed: fix package name
  linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/mcafee_endpoint_security_software/package_mcafeetp_installed/rule.yml
Labels: bugfix, DISA RHEL7 STIG Alignment, Update Rule

#8633 Update SRG-OS-000473-GPOS-00218 for RHEL 9 STIG
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_lastlog/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_tallylog/rule.yml
  linux_os/guide/system/auditing/grub2_audit_argument/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8636 Update RHEL7 STIG to v3r7
  products/rhel7/profiles/stig.profile
  products/rhel7/profiles/stig_gui.profile
  shared/references/disa-stig-rhel7-v3r7-xccdf-manual.xml
  shared/references/disa-stig-rhel7-v3r7-xccdf-scap.xml
Labels: DISA RHEL7 STIG Alignment

#8594 Update SRG-OS-000206-GPOS-00084 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000206-GPOS-00084.yml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_group_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_ownership_var_log_audit_stig/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_groupowner_var_log/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_groupowner_var_log_messages/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_owner_var_log/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_owner_var_log_messages/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_permissions_var_log/rule.yml
  linux_os/guide/system/permissions/files/permissions_var_log_dir/file_permissions_var_log_messages/rule.yml
  shared/macros/ocil.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8590 SUSE enable remediiation for grub2_disable_interactive_boot
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/rule.yml
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/tests/disabled_recovery_boot.pass.sh
  linux_os/guide/system/accounts/accounts-physical/grub2_disable_interactive_boot/tests/enabled_recovery_boot.fail.sh
Labels: Ansible, Bash, SLES, ok-to-test

#8626 Update SRG-OS-000425-GPOS-00189 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000424-GPOS-00188.yml
  controls/srg_gpos/SRG-OS-000425-GPOS-00189.yml
  controls/srg_gpos/SRG-OS-000426-GPOS-00190.yml
  linux_os/guide/services/ssh/package_openssh-server_installed/rule.yml
  linux_os/guide/services/ssh/service_sshd_enabled/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8625 Update SRG-OS-000377-GPOS-00162 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000375-GPOS-00160.yml
  controls/srg_gpos/SRG-OS-000376-GPOS-00161.yml
  controls/srg_gpos/SRG-OS-000377-GPOS-00162.yml
  linux_os/guide/services/sssd/sssd_certificate_verification/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8606 use grub2_uefi_boot_path
  linux_os/guide/system/bootloader-grub2/uefi/file_groupowner_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/file_owner_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/file_permissions_efi_grub2_cfg/rule.yml
  linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_password/oval/shared.xml
  linux_os/guide/system/bootloader-grub2/uefi/uefi_no_removeable_media/rule.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/rule.yml
Labels: ok-to-test

#8627 Update SRG-OS-000426-GPOS-00190 for RHEL 9 STIG
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8631 Update SRG-OS-000472-GPOS-00217 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000472-GPOS-00217.yml
  linux_os/guide/system/auditing/policy_rules/audit_rules_for_ospp/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8640 Update SRG-OS-000396-GPOS-00176 for RHEL 9 STIG
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8547 Enable bash remediation for SUSE smartcard_pam_enabled
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/bash/shared.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/bash/ubuntu.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/commented.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/correct.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/nothing.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/substring.fail.sh
Labels: SLES, ok-to-test, Update Rule

#8642 More improvements to SRG export script and mappings
  controls/srg_gpos/SRG-OS-000062-GPOS-00031.yml
  controls/srg_gpos/SRG-OS-000064-GPOS-00033.yml
  controls/srg_gpos/SRG-OS-000303-GPOS-00120.yml
  controls/srg_gpos/SRG-OS-000327-GPOS-00127.yml
  controls/srg_gpos/SRG-OS-000337-GPOS-00129.yml
  controls/srg_gpos/SRG-OS-000348-GPOS-00136.yml
  controls/srg_gpos/SRG-OS-000350-GPOS-00138.yml
  controls/srg_gpos/SRG-OS-000351-GPOS-00139.yml
  controls/srg_gpos/SRG-OS-000352-GPOS-00140.yml
  controls/srg_gpos/SRG-OS-000353-GPOS-00141.yml
  controls/srg_gpos/SRG-OS-000354-GPOS-00142.yml
  controls/srg_gpos/SRG-OS-000358-GPOS-00145.yml
  controls/srg_gpos/SRG-OS-000365-GPOS-00152.yml
  controls/srg_gpos/SRG-OS-000458-GPOS-00203.yml
  controls/srg_gpos/SRG-OS-000461-GPOS-00205.yml
  controls/srg_gpos/SRG-OS-000462-GPOS-00206.yml
  controls/srg_gpos/SRG-OS-000463-GPOS-00207.yml
  controls/srg_gpos/SRG-OS-000465-GPOS-00209.yml
  controls/srg_gpos/SRG-OS-000466-GPOS-00210.yml
  controls/srg_gpos/SRG-OS-000467-GPOS-00211.yml
  controls/srg_gpos/SRG-OS-000468-GPOS-00212.yml
  controls/srg_gpos/SRG-OS-000470-GPOS-00214.yml
  controls/srg_gpos/SRG-OS-000471-GPOS-00215.yml
  controls/srg_gpos/SRG-OS-000471-GPOS-00216.yml
  controls/srg_gpos/SRG-OS-000474-GPOS-00219.yml
  controls/srg_gpos/SRG-OS-000475-GPOS-00220.yml
  controls/srg_gpos/SRG-OS-000476-GPOS-00221.yml
  controls/srg_gpos/SRG-OS-000477-GPOS-00222.yml
  utils/create_srg_export.py
  utils/rule_dir_diff.py
Labels: Infrastructure, DISA RHEL9 STIG Alignment

#8649 Update SRG-OS-000366-GPOS-00153 for RHEL 9 STIG
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_kexec_load_disabled/rule.yml
  linux_os/guide/system/software/system-tools/package_subscription-manager_installed/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8654 Fix typo in accounts_passwords_pam_faillock_unlock_time ocil
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
Labels: DISA RHEL9 STIG Alignment

#8647 Update SRG-OS-000480-GPOS-00226 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00226.yml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8602 bugfix: no_shelllogin_for_systemaccounts: value parsing fixes
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/oval/shared.xml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/first_sys_uid_max.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/first_sys_uid_min.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/first_uid_min.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/last_sys_uid_max.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/last_sys_uid_min.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/last_uid_min.pass.sh
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/tests/space_uid_min.pass.sh
Labels: ok-to-test

#8608 configure_openssl_crypto_policy: OpenSSL v3.0 has = in include
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/tests/include_with_equal_sign.pass.sh
Labels: ok-to-test

#8607 consistent perm_x product filtering
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_chcon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_restorecon/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_semanage/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_setfiles/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_setsebool/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_execution_selinux_commands/audit_rules_execution_seunshare/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_chage/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_chsh/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_crontab/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_gpasswd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_mount/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newgidmap/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newgrp/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newuidmap/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_pam_timestamp_check/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_passwd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_postdrop/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_postqueue/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_pt_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_ssh_keysign/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_su/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_sudo/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_sudoedit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_umount/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_unix_chkpwd/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_userhelper/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_usernetctl/rule.yml
  shared/templates/audit_rules_privileged_commands/ansible.template
  shared/templates/audit_rules_privileged_commands/bash.template
  shared/templates/audit_rules_privileged_commands/oval.template
Labels: Ansible, Bash, ok-to-test, Update Rule

#8550 SUSE audit_rules_privileged_commands_kmod add bash remediation SLE12/15
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/bash/sle12.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/bash/sle15.sh
Labels: SLES, ok-to-test

#8578 Fix Grub remediation
  shared/macros/bash.jinja
Labels: bugfix

#8648 Update SRG-OS-000480-GPOS-00228 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00228.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_csh_cshrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8641 Update SRG-OS-000423-GPOS-00187 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000423-GPOS-00187.yml
  controls/srg_gpos/SRG-OS-000424-GPOS-00188.yml
  linux_os/guide/services/ssh/ssh_client/ssh_client_rekey_limit/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8605 change: use pkg_manager_config_file to allow fedora to work
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/shared.yml
  linux_os/guide/system/software/updating/clean_components_post_updating/bash/shared.sh
  linux_os/guide/system/software/updating/clean_components_post_updating/oval/shared.xml
  linux_os/guide/system/software/updating/clean_components_post_updating/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_repo_metadata/oval/shared.xml
  linux_os/guide/system/software/updating/ensure_gpgcheck_repo_metadata/rule.yml
Labels: ok-to-test

#8646 Update SRG-OS-000480-GPOS-00225 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00225.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8617 Update Audit System SRGs
  controls/srg_gpos/SRG-OS-000358-GPOS-00145.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8662 Shade rows that don't have fix text in SRG Export
  utils/convert_srg_export_to_xlsx.py
Labels: DISA RHEL9 STIG Alignment
