Repository ComplianceAsCode/content, pull requests merged in 2022-06, with the labels that each got.

#8829 Update configure_bashrc_exec_tmux rule
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_bashrc_exec_tmux/rule.yml
  shared/applicability/general.yml
  shared/checks/oval/installed_env_has_tmux_package.xml
  tests/ssg_test_suite/common.py
Labels: Test Suite, Bash, ok-to-test, Update Rule

#8854 Update documentation for labels and issues
  CONTRIBUTING.md
  docs/manual/developer/04_style_guide.md
Labels: Documentation

#8866 Revert undesired change made in 6404c2075
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_chage/rule.yml
Labels: bugfix

#8855 Update the SRG GPOS reference file to the latest version (V2R3)
  .github/workflows/srg-mapping-table.yaml
  controls/srg_gpos/SRG-OS-000481-GPOS-00481.yml
  docs/manual/developer/03_creating_content.md
  shared/references/disa-os-srg-v2r3.xml
  shared/transforms/shared_xccdf2table-profileccirefs.xslt
  utils/create_srg_export.py
Labels: DISA RHEL9 STIG Alignment

#8877 Cleanup RHEL7 stigids and fix rule sections
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
  linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_admin_space_left_action/rule.yml
  products/rhel7/profiles/stig.profile
Labels: DISA RHEL7 STIG Alignment

#8871 Fix typo in rule ID
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: bugfix

#8878 Group rules from SRG-OS-000480-GPOS-00227 into categories
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
Labels: DISA RHEL9 STIG Alignment

#8834 Add policy for removal of products
  docs/manual/developer/01_introduction.md
Labels: Documentation, Governance

#8875 Fix a python2 syntax issue in the Test Suite
  tests/ssg_test_suite/rule.py
Labels: bugfix

#8874 Update SRG-OS-000392-GPOS-00172 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000392-GPOS-00172.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8884 correctly load compiled content with multiple dots in file names
  ssg/build_yaml.py
  tests/unit/ssg-module/test_build_yaml.py
Labels: Infrastructure

#8894 SRG-OS-000480-GPOS-00227 File Permission Sections
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_weekly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_crontab/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_weekly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_crontab/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_cron_weekly/rule.yml
  linux_os/guide/services/cron_and_at/file_permissions_crontab/rule.yml
  linux_os/guide/services/ssh/file_groupowner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_owner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_pub_key/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_groupownership_home_directories/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_permissions_home_directories/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_ungroupowned/rule.yml
  shared/macros/fixtext.jinja
  shared/macros/srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8899 Update SRG-OS-000480-GPOS-00227 Mount Options Section for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/mounting_remote_filesystems/mount_option_nodev_remote_filesystems/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/mounting_remote_filesystems/mount_option_noexec_remote_filesystems/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/mounting_remote_filesystems/mount_option_nosuid_remote_filesystems/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_boot_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nodev_nonroot_local_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nodev_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nosuid_removable_partitions/rule.yml
  shared/macros/srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8898 Add ensure_gpgcheck_never_disabled to STIG in OL8 and RHEL8
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  products/ol8/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: needs-ok-to-test

#8860 Update audit_immutable_login_uids template
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/rule.yml
Labels: ok-to-test

#8735 Documention Fix Up
  docs/jinja_macros/fixtext.rst
  docs/jinja_macros/srg_requirement.rst
  docs/manual/developer/02_building_complianceascode.md
  docs/manual/developer/03_creating_content.md
  docs/manual/developer/04_style_guide.md
  docs/requirements.txt
  shared/schemas/rule.json
Labels: Documentation

#8126 Create krb5 related CPEs and applied to a rule for ol8 and rhel8
  linux_os/guide/services/kerberos/kerberos_disable_no_keytab/rule.yml
  shared/applicability/general.yml
  shared/checks/oval/krb5_server_older_than_1_17_18.xml
  shared/checks/oval/krb5_workstation_older_than_1_17_18.xml
Labels: RHEL, Oracle Linux, ok-to-test, DISA RHEL8 STIG Alignment

#8732 Move to CI to Fedora 35
  .github/workflows/gate.yaml
  .github/workflows/release.yaml
Labels: Infrastructure

#7534 linux_os/guide/system/*/*/*/dconf_*/oval/shared.xml: Try fixing wrong regexp
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_disable_restart_shutdown/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_disable_user_list/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_enable_smartcard_auth/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_login_retries/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_thumbnailers/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_network_settings/dconf_gnome_disable_wifi_create/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_network_settings/dconf_gnome_disable_wifi_notification/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_credential_prompt/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_remote_access_settings/dconf_gnome_remote_access_encryption/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_activation_enabled/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_delay/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/tests/comment.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/tests/correct_value.pass.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/tests/correct_value_unlocked.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/tests/setting_not_there.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/tests/wrong_value.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_info/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_geolocation/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_power_settings/oval/shared.xml
Labels: ok-to-test

#8840 Make macros loading procedure deterministic and designate _general.jinja file to be first in the sequence
  docs/jinja_macros/01-general.rst
  docs/jinja_macros/10-ansible.rst
  docs/jinja_macros/10-bash.rst
  docs/jinja_macros/10-fixtext.rst
  docs/jinja_macros/10-kubernetes.rst
  docs/jinja_macros/10-ocil.rst
  docs/jinja_macros/10-oval.rst
  docs/jinja_macros/10-srg_requirement.rst
  docs/jinja_macros/10-warning.rst
  docs/jinja_macros/ansible.rst
  docs/jinja_macros/bash.rst
  docs/jinja_macros/fixtext.rst
  docs/jinja_macros/general.rst
  docs/jinja_macros/kubernetes.rst
  docs/jinja_macros/ocil.rst
  docs/jinja_macros/oval.rst
  docs/jinja_macros/srg_requirement.rst
  docs/jinja_macros/warning.rst
  shared/macros/01-general.jinja
  shared/macros/10-ansible.jinja
  shared/macros/10-bash.jinja
  shared/macros/10-fixtext.jinja
  shared/macros/10-ignition.jinja
  shared/macros/10-kubernetes.jinja
  shared/macros/10-ocil.jinja
  shared/macros/10-oval.jinja
  shared/macros/10-srg_requirement.jinja
  shared/macros/10-warning.jinja
  ssg/jinja.py
Labels: Infrastructure

#8900 Update SRG-OS-000480-GPOS-00227 SSHD Section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_empty_passwords/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_gssapi_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_kerb_auth/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_user_known_hosts/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_x11_forwarding/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_print_last_log/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_rekey_limit/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_x11_use_localhost/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8892 Update SRG-OS-000480-GPOS-00227 Services Section for RHEL9 STIG
  linux_os/guide/services/base/service_kdump_disabled/rule.yml
  linux_os/guide/services/rng/service_rngd_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-physical/service_debug-shell_disabled/rule.yml
  linux_os/guide/system/logging/rsyslog_accepting_remote_messages/service_syslogng_enabled/rule.yml
  linux_os/guide/system/logging/service_rsyslog_enabled/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
  linux_os/guide/system/permissions/restrictions/coredumps/service_systemd-coredump_disabled/rule.yml
  shared/macros/10-fixtext.jinja
  shared/macros/10-ocil.jinja
  shared/macros/10-srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8904 Update SRG-OS-000480-GPOS-00227 auditd section for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_log_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_write_logs/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8906 Update SRG-OS-000480-GPOS-00227 dconf section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_ctrlaltdel_reboot/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8908 Update SRG-OS-000480-GPOS-00227 rsyslog section
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/rule.yml
  linux_os/guide/system/logging/rsyslog_accepting_remote_messages/rsyslog_nolisten/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8891 Fix template mode
  tests/ssg_test_suite/rule.py
  tests/ssg_test_suite/xml_operations.py
Labels: Test Suite

#8907 Update SRG-OS-000480-GPOS-00227 partition section
  linux_os/guide/system/software/disk_partitioning/partition_for_home/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_tmp/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_log_audit/rule.yml
  linux_os/guide/system/software/disk_partitioning/partition_for_var_tmp/rule.yml
  shared/macros/10-fixtext.jinja
  shared/macros/10-srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8761 Fix bash in umask related rules to manage correctly commented lines
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_csh_cshrc/bash/shared.sh
Labels: ok-to-test

#8909 Set OL8 stig_gui profile metadata and update rule rationale
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/rule.yml
  products/ol8/profiles/stig_gui.profile
Labels: Oracle Linux, needs-ok-to-test

#8915 Remove unnecessary rule test scenario for RHEL7 and STIG profile
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_max_log_file_action/tests/max_log_file_action_stig_rhel7.pass.sh
Labels: DISA RHEL7 STIG Alignment, productization-issue

#8873 Update SRG-OS-000064-GPOS-00033 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000064-GPOS-00033.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fchmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fchmodat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fchownat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_fsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_ftruncate/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_lchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_lremovexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_lsetxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_by_handle_at/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_openat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_removexattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_renameat2/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_setxattr/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlinkat/rule.yml
  shared/macros/10-ocil.jinja
  shared/macros/10-srg_requirement.jinja
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8921 Include SRG reference for dconf_gnome_disable_user_list
  controls/stig_rhel8.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_disable_user_list/rule.yml
Labels: productization-issue, DISA RHEL8 STIG Alignment

#8868 Review of Issues Templates
  .github/ISSUE_TEMPLATE/new_rule.md
  .github/ISSUE_TEMPLATE/product_removal.md
  .github/ISSUE_TEMPLATE/propose_change.md
Labels: Governance

#8825 Update pam password hash algo ol8 stig
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_passwordauth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_passwordauth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_systemauth/rule.yml
  products/ol8/profiles/stig.profile
Labels: Bash, Oracle Linux, ok-to-test

#8917 Update SRG-OS-000480-GPOS-00227 sysctl section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_accept_source_route/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_forwarding/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_ra/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_redirects/rule.yml
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_accept_source_route/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_accept_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_accept_source_route/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_log_martians/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_rp_filter/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_secure_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_accept_source_route/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_icmp_echo_ignore_broadcasts/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_parameters/sysctl_net_ipv4_conf_all_send_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_parameters/sysctl_net_ipv4_conf_default_send_redirects/rule.yml
  linux_os/guide/system/network/network-kernel/network_host_parameters/sysctl_net_ipv4_ip_forward/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_kptr_restrict/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_execshield_settings/sysctl_kernel_randomize_va_space/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_pattern/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_kexec_load_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_unprivileged_bpf_disabled/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_net_core_bpf_jit_harden/rule.yml
  linux_os/guide/system/permissions/restrictions/sysctl_user_max_user_namespaces/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8922 Update SRG-OS-000480-GPOS-00227 AIDE section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_acls/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8885 Simplify kernel module disabled template
  shared/templates/kernel_module_disabled/oval.template
Labels: enhancement

#8928 ANSSI enabled for file_permissions_unaurorized_world_writable
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_world_writable/rule.yml
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: needs-ok-to-test

#8918 Update SRG-OS-000250-GPOS-00093 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000250-GPOS-00093.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8920 Fix Ansible remediation for accounts_umask_etc_profile
  linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/ansible/shared.yml
Labels: Ansible, productization-issue

#8931 Update Readme.md
  Contributors.md
  README.md
Labels: Documentation

#8934 Add file_owner_etc_shadow to anssi
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: needs-ok-to-test

#8806 Update OVAL for enable_fips_mode
  linux_os/guide/system/software/integrity/fips/enable_fips_mode/oval/shared.xml
Labels: needs-ok-to-test

#8869 Update directory_ownership_var_log_audit
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/directory_ownership_var_log_audit/rule.yml
Labels: ok-to-test

#8938 More accurate CodeClimate reporting
  .codeclimate.yml
  tests/CMakeLists.txt
Labels: enhancement

#8940 fix dconf_gnome_screensaver_mode_blank rule
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/oval/shared.xml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/rule.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/tests/comment.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/tests/correct_value.pass.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/tests/correct_value_not_locked.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/tests/setting_not_there.fail.sh
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_mode_blank/tests/wrong_value.fail.sh
Labels: bugfix, Test Suite, OVAL, Update Rule

#8943 Template issue to request merge rights
  .github/ISSUE_TEMPLATE/request_merge_rights.md
  docs/manual/developer/01_introduction.md
Labels: governance

#8949 Add file_permissions_etc_passwd
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: SLES, ok-to-test, Update Profile

#8770 Add ANSSI minimal profile to SLE12
  controls/anssi_sle.yml
  linux_os/guide/services/dhcp/disabling_dhcp_server/package_dhcp_removed/rule.yml
  linux_os/guide/services/mail/package_sendmail_removed/rule.yml
  linux_os/guide/services/obsolete/inetd_and_xinetd/package_xinetd_removed/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypbind_removed/rule.yml
  linux_os/guide/services/obsolete/nis/package_ypserv_removed/rule.yml
  linux_os/guide/services/obsolete/r_services/package_rsh-server_removed/rule.yml
  linux_os/guide/services/obsolete/r_services/package_rsh_removed/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk-server_removed/rule.yml
  linux_os/guide/services/obsolete/talk/package_talk_removed/rule.yml
  linux_os/guide/services/obsolete/telnet/package_telnet_removed/rule.yml
  linux_os/guide/services/obsolete/tftp/package_tftp_removed/rule.yml
  linux_os/guide/services/sssd/sssd_enable_smartcards/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  linux_os/guide/system/logging/package_rsyslog_installed/rule.yml
  linux_os/guide/system/logging/service_rsyslog_enabled/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/package_firewalld_installed/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_etc_shadow/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_group/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_passwd/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_shadow/rule.yml
  linux_os/guide/system/software/updating/dnf-automatic_apply_updates/rule.yml
  linux_os/guide/system/software/updating/dnf-automatic_security_updates_only/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/ansible/shared.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/bash/shared.sh
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  linux_os/guide/system/software/updating/ensure_suse_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/package_dnf-automatic_installed/rule.yml
  linux_os/guide/system/software/updating/timer_dnf-automatic_enabled/rule.yml
  products/sle12/profiles/anssi_bp28_minmal.profile
Labels: SLES, ok-to-test, New Profile, Update Rule

#8950 Remove automated field from controls documentation
  docs/manual/developer/03_creating_content.md
Labels: Documentation, ok-to-test

#7594 Audisp plugin config path implied property
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/tests/audisp_remote_server_hostname.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/tests/audisp_remote_server_not_there.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/tests/audit_remote_server_hostname.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/tests/audit_remote_server_not_there.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_sufficiently_large_partition/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_disk_full_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/tests/encrypt_sent_records.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/tests/encrypt_sent_records_not_activated.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/tests/encrypt_sent_records_not_there.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_network_failure_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audisp_syslog_plugin_activated.pass.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audisp_syslog_plugin_activated_not_there.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/tests/audisp_syslog_plugin_not_activated.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/rule.yml
  products/ol7/product.yml
  products/rhel7/product.yml
  ssg/constants.py
  ssg/products.py
Labels: needs-ok-to-test

#8957 Update aide_verify_ext_attributes for RHEL9 STIG
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_verify_ext_attributes/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8958 Properly exclude all files from analysis
  .codeclimate.yml
Labels: enhancement

#8961 Update SRG-OS-000312-GPOS-00124 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000312-GPOS-00124.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8960 Update SRG-OS-000480-GPOS-00227 accounts section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_runlevel_target/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/accounts_no_uid_except_zero/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_have_homedir_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_home_paths_only/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_exists/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/rule.yml
  linux_os/guide/system/software/sudo/sudo_restrict_privilege_elevation_to_authorized/rule.yml
  linux_os/guide/system/software/sudo/sudoers_validate_passwd/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8953 Fail sshd_disable_compression if parameter missing
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_disable_compression/tests/openssh-7.4.pass.sh
Labels: DISA RHEL7 STIG Alignment, DISA RHEL8 STIG Alignment

#8929 Update accounts_user_dot_no_world_writable_programs
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/common.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/expected_permissions.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/lenient_permission.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/more_restrictive_permission.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/no_dot_file_ignored.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/no_world_writable_in_dot_file.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_no_world_writable_programs/tests/world_writable_in_dot_file.fail.sh
  linux_os/guide/system/accounts/accounts-session/var_user_initialization_files_regex.var
Labels: needs-ok-to-test

#8966 Update SRG-OS-000480-GPOS-00227 network section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configured_firewalld_default_deny/rule.yml
  linux_os/guide/system/network/network_configure_name_resolution/rule.yml
  linux_os/guide/system/network/network_sniffer_disabled/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, DISA RHEL9 STIG Alignment

#8965 Update SRG-OS-000480-GPOS-00227 grub2 section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8658 products/alinux3: supports Alibaba Cloud Linux 3
  .github/workflows/gate.yaml
  CMakeLists.txt
  build_product
  linux_os/guide/services/base/service_abrtd_disabled/rule.yml
  linux_os/guide/services/base/service_ntpdate_disabled/rule.yml
  linux_os/guide/services/base/service_oddjobd_disabled/rule.yml
  linux_os/guide/services/base/service_qpidd_disabled/rule.yml
  linux_os/guide/services/base/service_rdisc_disabled/rule.yml
  linux_os/guide/services/cron_and_at/service_atd_disabled/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/security_patches_up_to_date/rule.yml
  products/alinux3/CMakeLists.txt
  products/alinux3/overlays/.gitkeep
  products/alinux3/product.yml
  products/alinux3/profiles/standard.profile
  products/alinux3/transforms/constants.xslt
  products/alinux3/transforms/shorthand2xccdf.xslt
  products/alinux3/transforms/table-srgmap.xslt
  products/alinux3/transforms/table-style.xslt
  products/alinux3/transforms/xccdf-apply-overlay-stig.xslt
  products/alinux3/transforms/xccdf2table-byref.xslt
  products/alinux3/transforms/xccdf2table-cce.xslt
  products/alinux3/transforms/xccdf2table-profileanssirefs.xslt
  products/alinux3/transforms/xccdf2table-profileccirefs.xslt
  products/alinux3/transforms/xccdf2table-profilecisrefs.xslt
  products/alinux3/transforms/xccdf2table-profilenistrefs.xslt
  products/alinux3/transforms/xccdf2table-stig.xslt
  shared/checks/oval/installed_OS_is_alinux3.xml
  ssg/constants.py
  tests/unit/ssg-module/test_utils.py
  utils/duplicated_prodtypes.py
  utils/fix_file_ocilclause.py
Labels: Highlight, ok-to-test, New Profile, New Product

#8962 Update SRG-OS-000312-GPOS-00122 for the RHEL9 STIG
  controls/srg_gpos/SRG-OS-000312-GPOS-00122.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8955 Update the status with does not meet for OCP4 controls
  controls/srg_ctr/SRG-APP-000090-CTR-000155.yml
  controls/srg_ctr/SRG-APP-000109-CTR-000215.yml
  controls/srg_ctr/SRG-APP-000118-CTR-000240.yml
  controls/srg_ctr/SRG-APP-000142-CTR-000325.yml
  controls/srg_ctr/SRG-APP-000474-CTR-001180.yml
  controls/srg_ctr/SRG-APP-000516-CTR-000790.yml
Labels: ok-to-test

#8951 Update SRG-APP-000089-CTR-000150 for OCP4 STIG
  controls/srg_ctr.yml
  controls/srg_ctr/SRG-APP-000089-CTR-000150.yml
Labels: ok-to-test

#8936 Update SRG-APP-000014-CTR-000040 for OCP4 STIG
  controls/srg_ctr/SRG-APP-000014-CTR-000040.yml
Labels: ok-to-test

#8952 Update the status with not applicable for OCP4 controls
  controls/srg_ctr/SRG-APP-000024-CTR-000060.yml
  controls/srg_ctr/SRG-APP-000025-CTR-000065.yml
  controls/srg_ctr/SRG-APP-000026-CTR-000070.yml
  controls/srg_ctr/SRG-APP-000027-CTR-000075.yml
  controls/srg_ctr/SRG-APP-000028-CTR-000080.yml
  controls/srg_ctr/SRG-APP-000029-CTR-000085.yml
  controls/srg_ctr/SRG-APP-000065-CTR-000115.yml
  controls/srg_ctr/SRG-APP-000123-CTR-000265.yml
  controls/srg_ctr/SRG-APP-000149-CTR-000355.yml
  controls/srg_ctr/SRG-APP-000150-CTR-000360.yml
  controls/srg_ctr/SRG-APP-000151-CTR-000365.yml
  controls/srg_ctr/SRG-APP-000152-CTR-000370.yml
  controls/srg_ctr/SRG-APP-000157-CTR-000385.yml
  controls/srg_ctr/SRG-APP-000163-CTR-000395.yml
  controls/srg_ctr/SRG-APP-000164-CTR-000400.yml
  controls/srg_ctr/SRG-APP-000165-CTR-000405.yml
  controls/srg_ctr/SRG-APP-000166-CTR-000410.yml
  controls/srg_ctr/SRG-APP-000167-CTR-000415.yml
  controls/srg_ctr/SRG-APP-000168-CTR-000420.yml
  controls/srg_ctr/SRG-APP-000169-CTR-000425.yml
  controls/srg_ctr/SRG-APP-000170-CTR-000430.yml
  controls/srg_ctr/SRG-APP-000171-CTR-000435.yml
  controls/srg_ctr/SRG-APP-000172-CTR-000440.yml
  controls/srg_ctr/SRG-APP-000173-CTR-000445.yml
  controls/srg_ctr/SRG-APP-000174-CTR-000450.yml
  controls/srg_ctr/SRG-APP-000177-CTR-000465.yml
  controls/srg_ctr/SRG-APP-000181-CTR-000485.yml
  controls/srg_ctr/SRG-APP-000291-CTR-000675.yml
  controls/srg_ctr/SRG-APP-000292-CTR-000680.yml
  controls/srg_ctr/SRG-APP-000293-CTR-000685.yml
  controls/srg_ctr/SRG-APP-000294-CTR-000690.yml
  controls/srg_ctr/SRG-APP-000317-CTR-000735.yml
  controls/srg_ctr/SRG-APP-000318-CTR-000740.yml
  controls/srg_ctr/SRG-APP-000319-CTR-000745.yml
  controls/srg_ctr/SRG-APP-000320-CTR-000750.yml
  controls/srg_ctr/SRG-APP-000345-CTR-000785.yml
  controls/srg_ctr/SRG-APP-000357-CTR-000800.yml
  controls/srg_ctr/SRG-APP-000358-CTR-000805.yml
  controls/srg_ctr/SRG-APP-000359-CTR-000810.yml
  controls/srg_ctr/SRG-APP-000391-CTR-000935.yml
  controls/srg_ctr/SRG-APP-000397-CTR-000955.yml
  controls/srg_ctr/SRG-APP-000401-CTR-000965.yml
  controls/srg_ctr/SRG-APP-000402-CTR-000970.yml
  controls/srg_ctr/SRG-APP-000456-CTR-001130.yml
  controls/srg_ctr/SRG-APP-000503-CTR-001275.yml
  controls/srg_ctr/SRG-APP-000505-CTR-001285.yml
  controls/srg_ctr/SRG-APP-000506-CTR-001290.yml
Labels: ok-to-test

#8839 strip trailing blank lines for some templated audit rules
  linux_os/guide/system/auditing/policy_rules/audit_access_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_access_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_basic_configuration/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_create_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_create_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_delete_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_modify_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_module_load/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_ospp_general/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_owner_change_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_owner_change_success/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_perm_change_failed/rule.yml
  linux_os/guide/system/auditing/policy_rules/audit_perm_change_success/rule.yml
Labels: bugfix, Update Rule

#8980 Add missing OL7 stig IDs
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
  linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_autorun/rule.yml
  products/ol7/profiles/stig.profile
Labels: Oracle Linux, ok-to-test, Update Rule

#8639 Update SRG-OS-000394-GPOS-00174 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000033-GPOS-00014.yml
  controls/srg_gpos/SRG-OS-000394-GPOS-00174.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/package_crypto-policies_installed/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8968 Update SRG-OS-000269-GPOS-00103
  controls/srg_gpos/SRG-OS-000269-GPOS-00103.yml
  linux_os/guide/system/logging/journald/service_systemd-journald_enabled/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, DISA RHEL9 STIG Alignment

#8967 Update SRG-OS-000480-GPOS-00227 misc section
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/obsolete/r_services/no_host_based_files/rule.yml
  linux_os/guide/services/obsolete/r_services/no_user_host_based_files/rule.yml
  linux_os/guide/services/obsolete/tftp/tftpd_uses_secure_mode/rule.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/rule.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/updating/security_patches_up_to_date/rule.yml
Labels: RHEL9, DISA RHEL9 STIG Alignment

#8964 Update SRG-OS-000480-GPOS-00230 for RHEL9 STIG
  controls/srg_gpos/SRG-OS-000480-GPOS-00230.yml
  linux_os/guide/services/fapolicyd/fapolicyd_prevent_home_folder_access/rule.yml
  linux_os/guide/services/fapolicyd/package_fapolicyd_installed/rule.yml
  linux_os/guide/services/fapolicyd/service_fapolicyd_enabled/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, DISA RHEL9 STIG Alignment

#8942 Align kernel module rules with DISA STIG Benchmarks
  docs/templates/template_reference.md
  shared/macros/01-general.jinja
  shared/macros/10-ocil.jinja
  shared/templates/kernel_module_disabled/ansible.template
  shared/templates/kernel_module_disabled/bash.template
  shared/templates/kernel_module_disabled/kubernetes.template
  shared/templates/kernel_module_disabled/oval.template
  shared/templates/kernel_module_disabled/tests/correct_value_modprobe_d.pass.sh
  shared/templates/kernel_module_disabled/tests/correct_value_modules_load_d.pass.sh
  shared/templates/kernel_module_disabled/tests/correct_value_run_modprobe_d.pass.sh
  shared/templates/kernel_module_disabled/tests/correct_value_run_modules_load_d.pass.sh
  shared/templates/kernel_module_disabled/tests/correct_value_usr_lib_modprobe_d.pass.sh
  shared/templates/kernel_module_disabled/tests/correct_value_usr_lib_modules_load_d.pass.sh
Labels: DISA RHEL8 STIG Alignment

#8937 Update SRG-APP-000023-CTR-000055 for OCP4 STIG
  applications/openshift/authentication/ocp_no_ldap_insecure/rule.yml
  applications/openshift/general/kubeadmin_removed/rule.yml
  controls/srg_ctr/SRG-APP-000023-CTR-000055.yml
Labels: ok-to-test

#8810 Update configure_openssl_tls_crypto_policy
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/oval/shared.xml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/correct.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/correct_commented.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/correct_followed_by_incorrect.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/correct_value_old.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/empty_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/incorrect_followed_by_correct.pass.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/incorrect_policy.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/missing_file.fail.sh
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/tests/wrong_value_new.fail.sh
Labels: needs-ok-to-test

#8992 Add sysctl rules to anssi
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: needs-ok-to-test

#8989 fedora 34 is EOL since 2022-06-07
  products/fedora/product.yml
  tests/unit/ssg-module/test_playbook_builder_data/product.yml
Labels: needs-ok-to-test

#8988 fix: ansible_sshd_set: sshd_config is case-insensitive
  shared/macros/10-ansible.jinja
Labels: needs-ok-to-test

#8978 Update SRG-APP-000101-CTR-000205 for OCP4 STIG
  controls/srg_ctr/SRG-APP-000101-CTR-000205.yml
Labels: ok-to-test

#8981 Fix Nightly builds
  .github/workflows/nightly_build.yml
  .github/workflows/nightly_build_5_10.yml
Labels: Infrastructure

#9002 Introduce rules for lastlog permissions and ownerships
  linux_os/guide/system/accounts/accounts-session/file_groupownership_lastlog/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_ownership_lastlog/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_permissions_lastlog/rule.yml
  products/ol8/profiles/stig.profile
  shared/templates/file_groupowner/oval.template
  shared/templates/file_owner/oval.template
  shared/templates/file_permissions/oval.template
  shared/templates/file_permissions/tests/stricter_permisions.pass.sh
Labels: needs-ok-to-test

#8999 Create rule to cover OL08-00-010572
  linux_os/guide/system/permissions/partitions/mount_option_boot_efi_nosuid/rule.yml
  products/ol8/profiles/stig.profile
Labels: needs-ok-to-test

#8998 Create rule to cover OL08-00-010424
  linux_os/guide/system/bootloader-grub2/grub2_mitigation_argument/rule.yml
  linux_os/guide/system/bootloader-grub2/grub2_mitigation_argument/tests/grubby_correct_value.pass.sh
  linux_os/guide/system/bootloader-grub2/grub2_mitigation_argument/tests/grubby_wrong_value.fail.sh
  products/ol8/profiles/stig.profile
Labels: needs-ok-to-test

#8997 Update configure_tmux_lock_after_time check conditions
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/oval/shared.xml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/tests/correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/tests/lenient_value.fail.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/tests/stricter_value.pass.sh
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_after_time/tests/zero_as_value.fail.sh
Labels: needs-ok-to-test

#9004 accounts_tmout: Export and readonly TMOUT
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/correct_value_profile.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/correct_value_profile_d.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/duplicate_correct_value_profile.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/duplicate_correct_value_profile_d.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/multiline.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/multiline_profile.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/multiline_profile_d.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/multiline_profile_d.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/supercompliance_profile.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/supercompliance_profile_d.pass.sh
Labels: DISA RHEL7 STIG Alignment, Update Rule, CIS

#8994 Follow symlinks in ensure_gpgcheck_local_packages
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/ansible/shared.yml
Labels: bugfix, DISA RHEL8 STIG Alignment

#8127 OL8 missing parameter pass
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/tests/commented.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/tests/missing_file.fail.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_local_events/tests/missing_value.fail.sh
Labels: Oracle Linux, ok-to-test, Update Rule

#9020 A EditorConfig file
  .codeclimate.yml
  .editorconfig
Labels: Documentation

#8993 RHEL8 STIG: Install redhat gpg key
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: Update Profile, RHEL8, STIG

#8941 Add file_permissions_etc_group to anssi
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: needs-ok-to-test

#9013 Fix auditd_overflow_action OVAL to work properly on RHEL9
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/oval/shared.xml
Labels: bugfix

#9016 Fill gaps in the RHEL8/RHEL9 STIG
  controls/srg_gpos/SRG-OS-000021-GPOS-00005.yml
  controls/srg_gpos/SRG-OS-000373-GPOS-00156.yml
  controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml
  linux_os/guide/services/fapolicyd/fapolicy_default_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_password_pam_faillock_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_password_pam_faillock_system_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_password_selinux_faillock_dir/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_passwords_pam_faillock_audit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_passwords_pam_faillock_dir/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/network/network-firewalld/firewalld-backend/rule.yml
  linux_os/guide/system/network/network-firewalld/ruleset_modifications/configured_firewalld_default_deny/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_boot_efi_nosuid/rule.yml
  linux_os/guide/system/permissions/restrictions/kernel_module_uvcvideo_disabled/rule.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_locked/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, Update Rule, RHEL8, STIG

#9009 Remove any ocurrence of silent from /etc/pam.d/postlogin
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/rule.yml
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/authselect_line_present.pass.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/authselect_silent_present.fail.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/no_space_before_silent.pass.sh
  linux_os/guide/system/accounts/accounts-pam/display_login_attempts/tests/wrong_value_silent.fail.sh
Labels: RHEL7, STIG

#8991 Add ssh rules to ANSSI
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: needs-ok-to-test

#9030 Add whitespace in macro function so CTF can properly parse tokens
  shared/macros/10-bash.jinja
Labels: bugfix, Bash

#9027 Do not include OCIL content in rules that define OVAL external content
  ssg/build_yaml.py
Labels: bugfix

#9021 convert to jinja template
  shared/templates/audit_rules_syscall_events/bash.template
Labels: needs-ok-to-test

#9034 Fix quoting issues in RHEL9 STIG
  linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_maximum_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_minimum_age_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/rule.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/rule.yml
  linux_os/guide/system/permissions/files/dir_perms_world_writable_root_owned/rule.yml
Labels: RHEL9, STIG

#9033 SRG Requirements Additions
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/rule.yml
  linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/rule.yml
  linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_difok/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_lcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxclassrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxrepeat/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minclass/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minlen/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ucredit/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_disable_post_pw_expiration/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/account_expiration/account_temp_expire_date/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_logon_fail_delay/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_csh_cshrc/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/rule.yml
  tests/unit/ssg-module/test_playbook_builder_data/guide/configure_crypto_policy/rule.yml
Labels: RHEL9, STIG

#9010 OCP4: Update policy.json verification
  ocp-resources/e2e/mc-hardened-policy-json.yaml
Labels: OpenShift

#9014 Add 4.11 test manifests to several rules
  applications/openshift/api-server/api_server_kubelet_client_cert/tests/ocp4/4.11.yml
  applications/openshift/api-server/api_server_kubelet_client_key/tests/ocp4/4.11.yml
  applications/openshift/kubelet/kubelet_configure_tls_cert/tests/ocp4/4.11.yml
  applications/openshift/kubelet/kubelet_configure_tls_key/tests/ocp4/4.11.yml
Labels: OpenShift

#9045 Add anssi_bp28_intermediary profile
  products/sle15/profiles/anssi_bp28_intermediary.profile
Labels: SLES, ok-to-test, New Profile

#9035 Create rule ssh_private_keys_have_passcode to cover OL08-00-010100
  linux_os/guide/services/ssh/ssh_private_keys_have_passcode/rule.yml
  products/ol8/profiles/stig.profile
Labels: Oracle Linux, needs-ok-to-test, STIG

#9005 Extract function
  ssg/parse_oval.py
Labels: refactoring

#9046 More RHEL9 STIG Bug Fixes
  controls/srg_gpos/SRG-OS-000024-GPOS-00007.yml
  controls/srg_gpos/SRG-OS-000033-GPOS-00014.yml
  controls/srg_gpos/SRG-OS-000104-GPOS-00051.yml
  controls/srg_gpos/SRG-OS-000106-GPOS-00053.yml
  controls/srg_gpos/SRG-OS-000107-GPOS-00054.yml
  controls/srg_gpos/SRG-OS-000108-GPOS-00055.yml
  controls/srg_gpos/SRG-OS-000109-GPOS-00056.yml
  controls/srg_gpos/SRG-OS-000298-GPOS-00116.yml
  controls/srg_gpos/SRG-OS-000312-GPOS-00124.yml
  controls/srg_gpos/SRG-OS-000358-GPOS-00145.yml
  controls/srg_gpos/SRG-OS-000374-GPOS-00159.yml
  controls/srg_gpos/SRG-OS-000379-GPOS-00164.yml
  controls/srg_gpos/SRG-OS-000380-GPOS-00165.yml
  linux_os/guide/services/ftp/disabling_vsftpd/package_vsftpd_removed/rule.yml
  linux_os/guide/services/obsolete/tftp/package_tftp-server_removed/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_private_key/rule.yml
  linux_os/guide/services/ssh/file_permissions_sshd_pub_key/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_difok/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/rule.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/service_pcscd_enabled/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_all_shadowed_sha512/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  linux_os/guide/system/logging/service_rsyslog_enabled/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_tls_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_local_packages/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
  shared/macros/10-fixtext.jinja
  shared/macros/10-srg_requirement.jinja
  utils/create_srg_export.py
Labels: RHEL9, STIG

#9040 Fix #9039
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/account_password_selinux_faillock_dir/rule.yml
  linux_os/guide/system/permissions/restrictions/kernel_module_uvcvideo_disabled/rule.yml
Labels: bugfix, RHEL8, STIG

#9050 Do not include symlink tests into OVAL 5.10
  linux_os/guide/system/accounts/enable_authselect/oval/shared.xml
Labels: bugfix

#8924 Update SRG-OS-000342-GPOS-00133 for RHEL 9 STIG
  controls/srg_gpos/SRG-OS-000341-GPOS-00132.yml
  controls/srg_gpos/SRG-OS-000342-GPOS-00133.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_sufficiently_large_partition/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_disk_full_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_encrypt_sent_records/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_network_failure_action/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_syslog_plugin_activated/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_overflow_action/rule.yml
  linux_os/guide/system/auditing/package_audispd-plugins_installed/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/rule.yml
Labels: RHEL9, STIG

#9051 Proper home directory regex in `accounts_user_interactive_home_directory_defined` OVAL
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/tests/home_dir_special_chars.pass.sh
Labels: bugfix, productization-issue

#9054 Minor srg_requirement fixes
  controls/srg_gpos/SRG-OS-000001-GPOS-00001.yml
  linux_os/guide/services/fapolicyd/service_fapolicyd_enabled/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_usermod/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_auditd/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_etc_audit_rulesd/rule.yml
  shared/macros/10-fixtext.jinja
Labels: RHEL9, STIG

#8779 add products/uos20 to support UnionTech OS Server 20
  .github/workflows/gate.yaml
  CMakeLists.txt
  build_product
  linux_os/guide/services/base/service_abrtd_disabled/rule.yml
  linux_os/guide/services/base/service_ntpdate_disabled/rule.yml
  linux_os/guide/services/base/service_oddjobd_disabled/rule.yml
  linux_os/guide/services/base/service_qpidd_disabled/rule.yml
  linux_os/guide/services/base/service_rdisc_disabled/rule.yml
  linux_os/guide/services/cron_and_at/service_atd_disabled/rule.yml
  linux_os/guide/services/dns/disabling_dns_server/package_bind_removed/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events/rule.yml
  linux_os/guide/system/network/network-ipsec/package_libreswan_installed/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_sgid/rule.yml
  linux_os/guide/system/permissions/files/file_permissions_unauthorized_suid/rule.yml
  linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_bind_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_kerberos_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_libreswan_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_openssl_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/crypto/configure_ssh_crypto_policy/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_hashes/rule.yml
  linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/rule.yml
  linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
  linux_os/guide/system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
  linux_os/guide/system/software/updating/security_patches_up_to_date/rule.yml
  products/uos20/CMakeLists.txt
  products/uos20/overlays/.gitkeep
  products/uos20/product.yml
  products/uos20/profiles/standard.profile
  products/uos20/transforms/constants.xslt
  products/uos20/transforms/shorthand2xccdf.xslt
  products/uos20/transforms/table-srgmap.xslt
  products/uos20/transforms/table-style.xslt
  products/uos20/transforms/xccdf-apply-overlay-stig.xslt
  products/uos20/transforms/xccdf2table-byref.xslt
  products/uos20/transforms/xccdf2table-cce.xslt
  products/uos20/transforms/xccdf2table-profileanssirefs.xslt
  products/uos20/transforms/xccdf2table-profileccirefs.xslt
  products/uos20/transforms/xccdf2table-profilecisrefs.xslt
  products/uos20/transforms/xccdf2table-profilenistrefs.xslt
  products/uos20/transforms/xccdf2table-stig.xslt
  shared/checks/oval/installed_OS_is_uos20.xml
  shared/checks/oval/sysctl_kernel_ipv6_disable.xml
  ssg/constants.py
  tests/unit/ssg-module/test_utils.py
Labels: needs-ok-to-test, New Product

#9052 Fix failing test scenarios in rule audit_rules_login_events
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/tests/default.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/group.yml
Labels: productization-issue

#9061 Remove test scenario that is no longer relevant
  linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/tests/file_not_identical.fail.sh
Labels: productization-issue

#9063 Fix regular expression in Ansible remediation
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/ansible/shared.yml
Labels: bugfix, Ansible

#8927 Add ANSSI rules
  linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_default_rp_filter/rule.yml
  products/sle15/profiles/anssi_bp28_minmal.profile
Labels: SLES, ok-to-test, ANSSI

#9069 Update testing container name in gitpod integration
  .gitpod.launch.json
  .gitpod.yml
Labels: enhancement

#9068 Build content in debug mode when generating coverage statistics
  .github/workflows/gh-pages.yaml
Labels: RHEL9, STIG

#9071 RHEL8 STIG: Select new faillock audit rule and fix network forwarding selections
  linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_all_forwarding/rule.yml
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: RHEL8, STIG

#9074 Add python vscode extension to the gitpod environment
  .gitpod.yml
Labels: Infrastructure

#9007 Update sysctl bash template
  shared/macros/10-bash.jinja
  shared/templates/sysctl/bash.template
  shared/templates/sysctl/oval.template
  tests/unit/bash/test_bash_replace_or_append.bats.jinja
Labels: ok-to-test
