Repository ComplianceAsCode/content, pull requests merged in 2022-12, with the labels that each got.

#9790 Add file_permissions_var_log_audit rule to SLE12
  linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/rule.yml
  shared/references/cce-sle12-avail.txt
Labels: SLES, needs-ok-to-test

#9902 Sort conditional remediation platform checks
  ssg/build_remediations.py
Labels: Infrastructure

#9876 CIS / CCE numbers for SLE 12/15 covering special services
  linux_os/guide/services/dhcp/disabling_dhcp_server/service_dhcpd_disabled/rule.yml
  linux_os/guide/services/dns/disabling_dns_server/service_named_disabled/rule.yml
  linux_os/guide/services/ftp/disabling_vsftpd/service_vsftpd_disabled/rule.yml
  linux_os/guide/services/http/disabling_httpd/service_httpd_disabled/rule.yml
  linux_os/guide/services/imap/disabling_dovecot/package_dovecot_removed/rule.yml
  linux_os/guide/services/imap/disabling_dovecot/service_dovecot_disabled/rule.yml
  linux_os/guide/services/nfs_and_rpc/nfs_configuring_clients/disabling_nfsd/service_nfs_disabled/rule.yml
  linux_os/guide/services/ntp/chronyd_run_as_chrony_user/rule.yml
  linux_os/guide/services/obsolete/inetd_and_xinetd/service_xinetd_disabled/rule.yml
  linux_os/guide/services/proxy/disabling_squid/package_squid_removed/rule.yml
  linux_os/guide/services/proxy/disabling_squid/service_squid_disabled/rule.yml
  linux_os/guide/services/smb/disabling_samba/service_smb_disabled/rule.yml
  linux_os/guide/services/snmp/disabling_snmp_service/service_snmpd_disabled/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/package_xorg-x11-server-common_removed/rule.yml
  linux_os/guide/services/xwindows/disabling_xwindows/xwindows_remove_packages/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test, CIS

#9918 Add sanity tests for controleval.py
  tests/CMakeLists.txt
  tests/unit/ssg-module/data/controls_dir/qrst-levels.yml
  tests/unit/ssg-module/data/controls_dir/qrst-levels/R1.yml
  tests/unit/ssg-module/data/controls_dir/qrst-levels/r2_r3.yml
  tests/unit/ssg-module/data/controls_dir/qrst-levels/r4.yml
  tests/unit/ssg-module/data/controls_dir/qrst-levels/r5.yml
Labels: Infrastructure

#9912 Add nonessential services rule
  linux_os/guide/services/mask_nonessential_services/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, New Rule

#9936 Changing a few harcoded OS names for full_name
  linux_os/guide/services/fapolicyd/fapolicy_default_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minlen/policy/stig/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/package_tmux_installed/policy/stig/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/configure_opensc_card_drivers/policy/stig/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_immutable/policy/stig/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_sudoers_d/rule.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/policy/stig/shared.yml
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/policy/stig/shared.yml
  linux_os/guide/system/network/network-firewalld/firewalld_activation/service_firewalld_enabled/policy/stig/shared.yml
  linux_os/guide/system/permissions/files/file_permissions_ungroupowned/rule.yml
  linux_os/guide/system/permissions/restrictions/enable_nx/group.yml
  linux_os/guide/system/permissions/restrictions/poisoning/grub2_slub_debug_argument/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_login_screen/dconf_gnome_lock_screen_on_smartcard_removal/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_delay/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_delay/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_lock_enabled/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_user_locks/policy/stig/shared.yml
  linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_session_idle_user_locks/policy/stig/shared.yml
  linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/policy/stig/shared.yml
  linux_os/guide/system/software/updating/security_patches_up_to_date/policy/stig/shared.yml
Labels: needs-ok-to-test, Update Rule

#9919 Remove ansible_distribution usage where unnecesary
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/tests/grub_cmdline_linux_correct_value.pass.sh
  linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/tests/grub_cmdline_linux_wrong_value.fail.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/tests/package_installed.pass.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/tests/package_removed.fail.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/anaconda/shared.anaconda
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/ansible/shared.yml
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/bash/shared.sh
  linux_os/guide/system/software/integrity/fips/package_dracut-fips_installed/rule.yml
Labels: needs-ok-to-test

#9862 Add Refchecker to Tests
  tests/CMakeLists.txt
  utils/refchecker.py
Labels: Infrastructure, Test Suite

#9881 SLE 12/15 CCE/CIS codes added and CIS codes updated
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_insmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_modprobe/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_rmmod/rule.yml
  linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml
  linux_os/guide/system/logging/journald/journald_compress/rule.yml
  linux_os/guide/system/logging/journald/journald_forward_to_syslog/rule.yml
  linux_os/guide/system/logging/journald/journald_storage/rule.yml
  linux_os/guide/system/logging/rsyslog_accepting_remote_messages/rsyslog_nolisten/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test, CIS

#9933 Wait for buffer flushes to finish writes
  cmake/SSGCommon.cmake
Labels: Infrastructure

#9943 Fix file name for CIS SLE15 control file in CODEOWNERS
  CODEOWNERS
Labels: Documentation

#9883 SLE 12/15 CCE and CIS numbers for the CIS group job schedulers
  linux_os/guide/services/cron_and_at/file_groupowner_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_cron_weekly/rule.yml
  linux_os/guide/services/cron_and_at/file_groupowner_crontab/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_d/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_daily/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_hourly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_monthly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_cron_weekly/rule.yml
  linux_os/guide/services/cron_and_at/file_owner_crontab/rule.yml
  linux_os/guide/services/cron_and_at/service_crond_enabled/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test, CIS

#9915 accounts_tmout: Handle conflicting and duplicate values, plus /etc/bashrc on rhel7
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/conflicting_values_diff_file.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/conflicting_values_same_file.fail.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/correct_value_bashrc.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/duplicate_correct_value_diff_files.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/duplicate_correct_value_profile.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/duplicate_correct_value_profile_d.pass.sh
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/tests/wrong_value_bashrc.fail.sh
Labels: Oracle Linux, RHEL7, STIG

#9885 CCE and CIS codes for SLE 12/15 rules which belong to CIS group 5.2 c…
  linux_os/guide/services/ssh/file_groupowner_sshd_config/rule.yml
  linux_os/guide/services/ssh/file_owner_sshd_config/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_login_grace_time/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_loglevel_info/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_ciphers/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_macs/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test

#9886 CCE / CIS numbers assigment to SLE 12/15 rules
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dcredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_minlen/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ocredit/rule.yml
  linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ucredit/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test

#9888 CCE and CIS numbers assignments for SLE 12/15 rules which belong to u…
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_passwd/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_shadow/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_shadow/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_user_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_groupownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_ownership/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_home_files_permissions/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_users_own_home_directories/rule.yml
  linux_os/guide/system/accounts/accounts-session/file_ownership_home_directories/rule.yml
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/root_paths/accounts_root_path_dirs_no_write/rule.yml
  linux_os/guide/system/accounts/accounts-session/root_paths/root_path_no_dot/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test

#9929 Fix typing import in `create_srg_export.py`
  utils/create_srg_export.py
Labels: Infrastructure

#9925 New template `key_value_pair_in_file` and audispd remote daemon rules
  docs/templates/template_reference.md
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_activated/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_direction/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_path/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_type/rule.yml
  products/rhel7/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  shared/templates/key_value_pair_in_file/ansible.template
  shared/templates/key_value_pair_in_file/bash.template
  shared/templates/key_value_pair_in_file/oval.template
  shared/templates/key_value_pair_in_file/template.py
  shared/templates/key_value_pair_in_file/template.yml
  shared/templates/key_value_pair_in_file/tests/commented_value.fail.sh
  shared/templates/key_value_pair_in_file/tests/conflicting_values.fail.sh
  shared/templates/key_value_pair_in_file/tests/correct_value.pass.sh
  shared/templates/key_value_pair_in_file/tests/duplicate_values.pass.sh
  shared/templates/key_value_pair_in_file/tests/missing_file.fail.sh
  shared/templates/key_value_pair_in_file/tests/missing_value.fail.sh
  shared/templates/key_value_pair_in_file/tests/wrong_value.fail.sh
Labels: RHEL7, STIG, New Template

#9946 Build all profiles on all CentOS and CentOS Streams
  build-scripts/enable_derivatives.py
Labels: Infrastructure

#9923 Update sudo_require_reauthentication
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/ansible/shared.yml
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/bash/shared.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/oval/shared.xml
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/rule.yml
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/correct_value.pass.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/correct_value_with_spaces.pass.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/missing_value.fail.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/multiple_conflicting_value.fail.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/multiple_correct_value.fail.sh
  linux_os/guide/system/software/sudo/sudo_require_reauthentication/tests/wrong_value.fail.sh
Labels: Ansible, OVAL, Bash, Update Rule

#9960 Fix typo.
  controls/srg_ctr/SRG-APP-000014-CTR-000040.yml
Labels: OpenShift

#9962 CTest Fixes
  tests/CMakeLists.txt
Labels: Infrastructure

#9956 accounts_user_dot_group_ownership: Improve OVAL to avoid nobody group
  linux_os/guide/system/accounts/accounts-session/accounts_user_dot_group_ownership/oval/shared.xml
Labels: OVAL

#9964 Fix Variable in CTest for srg-export-rhel9
  tests/CMakeLists.txt
Labels: bugfix

#9900 CCE / CIS numbers for SLE 12/15 rules which belong to CIS group Initi…
  linux_os/guide/system/permissions/mounting/kernel_module_cramfs_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_squashfs_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_udf_disabled/rule.yml
  linux_os/guide/system/permissions/mounting/kernel_module_vfat_disabled/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_home_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_nodev_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_noexec_removable_partitions/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_tmp_nodev/rule.yml
  linux_os/guide/system/permissions/partitions/mount_option_var_tmp_nodev/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test

#9952 Update Upstream Release doc
  docs/release_process.md
Labels: enhancement, Documentation

#9969 Fix references and add CCE ids for backup_etc_gshadow related rules
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_groupowner_backup_etc_gshadow/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_owner_backup_etc_gshadow/rule.yml
  linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_backup_etc_gshadow/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: needs-ok-to-test

#9921 Improve the arguments for Ansible command module
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/ansible/shared.yml
Labels: Ansible, productization-issue

#9945 CPE AL: Introduce version specifiers support
  docs/manual/developer/06_contributing_with_content.md
  shared/applicability/package.yml
  shared/macros/10-oval.jinja
  shared/templates/platform_package/oval.template
  ssg/boolean_expression.py
  ssg/build_cpe.py
  ssg/build_yaml.py
  ssg/entities/common.py
  ssg/requirement_specs.py
  ssg/utils.py
  tests/unit/ssg-module/test_boolean_expressions.py
  tests/unit/ssg-module/test_platform_expressions.py
  tests/unit/ssg-module/test_requirement_specs.py
  tests/unit/ssg-module/test_utils.py
Labels: Infrastructure, CPE-AL

#9959 Correctly process templated Ansible conditionals and introduce os_linux platform
  shared/applicability/os_linux.yml
  shared/templates/platform_os_linux/ansible.template
  shared/templates/platform_os_linux/oval.template
  shared/templates/platform_os_linux/template.yml
  ssg/build_cpe.py
  ssg/build_yaml.py
  ssg/templates.py
  tests/unit/ssg-module/test_build_yaml.py
Labels: Infrastructure, CPE-AL

#9991 Fix CIS SLEs requirement id in sshd_set_keepalive
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
Labels: SLES, needs-ok-to-test, CIS

#9989 Assign SLE CCE ids and CIS references to no_netrc_files rule
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_netrc_files/rule.yml
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: needs-ok-to-test

#9926 CMP-1389: SRG-APP-000014-CTR-000040: Needs an automated rule to check Kubelet tlsSecurityProfile
  applications/openshift/kubelet/kubelet_configure_tls_min_version/kubernetes/shared.yml
  applications/openshift/kubelet/kubelet_configure_tls_min_version/rule.yml
  applications/openshift/kubelet/kubelet_configure_tls_min_version/tests/ocp4/e2e.yml
  applications/openshift/kubelet/kubelet_configure_tls_min_version_master/rule.yml
  applications/openshift/kubelet/kubelet_configure_tls_min_version_worker/rule.yml
  applications/openshift/kubelet/var_kubelet_tls_min_version.var
  applications/openshift/kubelet/var_kubelet_tls_min_version_regex.var
  controls/nist_ocp4.yml
  controls/srg_ctr/SRG-APP-000014-CTR-000040.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenShift, ok-to-test

#9994 Update rules related to pam_pwhistory module to consider pwhistory.conf file
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_conflict_settings.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_correct_value_conf.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_correct_value_pam.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_missing_argument.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_missing_line.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_modified_pam.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_wrong_control.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_wrong_value_conf.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_password_auth/tests/authselect_wrong_value_pam.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_conflict_settings.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_correct_value_conf.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_correct_value_pam.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_missing_argument.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_missing_line.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_modified_pam.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_wrong_control.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_wrong_value_conf.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember_system_auth/tests/authselect_wrong_value_pam.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_conflict_settings.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_correct_value.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_correct_value_conf.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_correct_value_pam.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_missing_argument.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_missing_line.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_modified_pam.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_pam_unix_legacy_correct.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_pam_unix_legacy_wrong.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_wrong_value.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_wrong_value_conf.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/tests/authselect_wrong_value_pam.fail.sh
  shared/macros/10-ansible.jinja
  shared/macros/10-bash.jinja
Labels: Ansible, Test Suite, OVAL, Bash, Update Rule
