Repository ComplianceAsCode/content, pull requests merged in 2023-06, with the labels that each got.

#10636 Add automation content for rule file_permission_user_init_files
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/oval/shared.xml
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/all_permissions.fail.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/common.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/correct_permissions.pass.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/different_home_correct_permissions.pass.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/different_home_wrong_permissions.fail.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/lenient_permissions.fail.sh
  linux_os/guide/system/accounts/accounts-session/file_permission_user_init_files/tests/stricter_permissions.pass.sh
Labels: ok-to-test

#10661 Fix Ansible fatal error from `configure_tmux_lock_keybinding`
  linux_os/guide/system/accounts/accounts-physical/screen_locking/console_screen_locking/configure_tmux_lock_keybinding/ansible/shared.yml
Labels: bugfix

#10663 Fix var_firewalld_default_zone_filename datatype
  linux_os/guide/system/network/network_implement_access_control/oval/shared.xml
Labels: bugfix

#10667 Fix compare datastream check to correctly treat new line characters.
  .github/workflows/compare-ds.yaml
Labels: Infrastructure

#10679 Add warning to rsyslog_remote_tls_cacert
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/rule.yml
Labels: backported-into-stabilization

#10676 Add warning to rsyslog_remote_tls_cacert
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_tls_cacert/rule.yml
Labels: bugfix

#10684 Add a sanity test of install_vm.py
  tests/CMakeLists.txt
Labels: Infrastructure

#10683 [Stabilization] revert modifications to file_groupownership template and respective rules
  controls/cis_rhel7.yml
  controls/cis_rhel8.yml
  controls/cis_rhel9.yml
  linux_os/guide/services/ssh/file_groupownership_sshd_private_key/rule.yml
  linux_os/guide/services/ssh/file_groupownership_sshd_private_key/tests/correct_groupowner.pass.sh
  linux_os/guide/services/ssh/file_groupownership_sshd_private_key/tests/incorrect_groupowner.fail.sh
  linux_os/guide/services/ssh/file_groupownership_sshd_private_key/tests/multiple_keys.fail.sh
  linux_os/guide/services/ssh/file_groupownership_sshd_pub_key/rule.yml
  linux_os/guide/services/ssh/file_groupownership_sshd_pub_key/tests/correct_groupowner.pass.sh
  linux_os/guide/services/ssh/file_groupownership_sshd_pub_key/tests/incorrect_groupowner.fail.sh
  linux_os/guide/services/ssh/file_groupownership_sshd_pub_key/tests/multiple_keys.fail.sh
  shared/templates/file_groupowner/oval.template
Labels: bugfix

#10678 Add Automatus Testing
  .github/workflows/automatus-sanity.yaml
  products/fedora/profiles/test.profile
  tests/CMakeLists.txt
Labels: Test Suite

#10689 Fix of rule sudo_dedicated_group for sle 12/15
  linux_os/guide/system/software/sudo/sudo_dedicated_group/rule.yml
  products/sle12/profiles/anssi_bp28_enhanced.profile
  products/sle12/profiles/anssi_bp28_high.profile
  products/sle12/profiles/anssi_bp28_intermediary.profile
  products/sle12/profiles/anssi_bp28_minimal.profile
  products/sle15/profiles/anssi_bp28_enhanced.profile
  products/sle15/profiles/anssi_bp28_high.profile
  products/sle15/profiles/anssi_bp28_intermediary.profile
  products/sle15/profiles/anssi_bp28_minimal.profile
Labels: SLES, needs-ok-to-test, Update Profile, ANSSI

#10539 OCP4 Add the suppress warning tag
  shared/macros/01-general.jinja
Labels: OpenShift

#10692 Typo correction in CIS profile for SLE 12
  controls/cis_sle12.yml
Labels: SLES, needs-ok-to-test

#10410 cmake style and some bugfixes
  .cmakelintrc
  .editorconfig
  CMakeLists.txt
  cmake/CopyFiles.cmake
  cmake/FindOpenSCAP.cmake
  cmake/FindPythonModule.cmake
  cmake/GNUInstallDirs.cmake
  cmake/SSGCommon.cmake
  docs/CMakeLists.txt
  docs/manual/developer/03_creating_content.md
  docs/manual/developer/04_style_guide.md
  products/alinux2/CMakeLists.txt
  products/alinux3/CMakeLists.txt
  products/anolis8/CMakeLists.txt
  products/chromium/CMakeLists.txt
  products/debian10/CMakeLists.txt
  products/debian11/CMakeLists.txt
  products/eks/CMakeLists.txt
  products/example/CMakeLists.txt
  products/example/new_product.sh
  products/fedora/CMakeLists.txt
  products/firefox/CMakeLists.txt
  products/macos1015/CMakeLists.txt
  products/ocp4/CMakeLists.txt
  products/ol7/CMakeLists.txt
  products/ol8/CMakeLists.txt
  products/ol9/CMakeLists.txt
  products/opensuse/CMakeLists.txt
  products/rhcos4/CMakeLists.txt
  products/rhel7/CMakeLists.txt
  products/rhel8/CMakeLists.txt
  products/rhel9/CMakeLists.txt
  products/rhv4/CMakeLists.txt
  products/sle12/CMakeLists.txt
  products/sle15/CMakeLists.txt
  products/ubuntu1604/CMakeLists.txt
  products/ubuntu1804/CMakeLists.txt
  products/ubuntu2004/CMakeLists.txt
  products/ubuntu2204/CMakeLists.txt
  products/uos20/CMakeLists.txt
  tests/CMakeLists.txt
Labels: enhancement, needs-ok-to-test

#10699 Pretty minor fix in product title
  products/rhel7/product.yml
  tests/data/product_stability/rhel7.yml
Labels: RHEL7

#10698 Complete some CIS requirements for RHEL7
  controls/cis_rhel7.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_password_auth_for_systemaccounts/rule.yml
  linux_os/guide/system/accounts/accounts-session/accounts_tmout/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
  linux_os/guide/system/auditing/package_audit-libs_installed/rule.yml
  linux_os/guide/system/network/network-nftables/package_nftables_installed/rule.yml
  linux_os/guide/system/network/network-nftables/package_nftables_removed/rule.yml
  linux_os/guide/system/network/network-nftables/service_nftables_disabled/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: RHEL7, CIS

#10700 Change of anssi recommendation for the rule mount_option_home_nosuid
  linux_os/guide/system/permissions/partitions/mount_option_home_nosuid/rule.yml
Labels: needs-ok-to-test

#10701 Fix CMakelint
  tests/CMakeLists.txt
Labels: bugfix, Infrastructure

#10703 New templated rule to remove iptables-services package
  controls/cis_rhel7.yml
  controls/cis_rhel8.yml
  linux_os/guide/system/network/network-iptables/package_iptables-services_removed/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL7, RHEL8, CIS

#10612 OCP4 STIG: Several RBAC related controls are no longer Inherently Met, let's use a manual rule to cut duplication
  applications/openshift/rbac/rbac_least_privilege/policy/stig/shared.yml
  applications/openshift/rbac/rbac_least_privilege/rule.yml
  applications/openshift/rbac/rbac_least_privilege/tests/ocp4/e2e.yml
  controls/srg_ctr/SRG-APP-000033-CTR-000090.yml
  controls/srg_ctr/SRG-APP-000033-CTR-000095.yml
  controls/srg_ctr/SRG-APP-000033-CTR-000100.yml
  controls/srg_ctr/SRG-APP-000133-CTR-000290.yml
  controls/srg_ctr/SRG-APP-000133-CTR-000295.yml
  controls/srg_ctr/SRG-APP-000133-CTR-000300.yml
  controls/srg_ctr/SRG-APP-000133-CTR-000305.yml
  controls/srg_ctr/SRG-APP-000133-CTR-000310.yml
  controls/srg_ctr/SRG-APP-000148-CTR-000350.yml
  controls/srg_ctr/SRG-APP-000153-CTR-000375.yml
  controls/srg_ctr/SRG-APP-000340-CTR-000770.yml
  controls/srg_ctr/SRG-APP-000378-CTR-000880.yml
  controls/srg_ctr/SRG-APP-000378-CTR-000885.yml
  controls/srg_ctr/SRG-APP-000378-CTR-000890.yml
  controls/srg_ctr/SRG-APP-000380-CTR-000900.yml
  controls/srg_ctr/SRG-APP-000386-CTR-000920.yml
  shared/macros/10-fixtext.jinja
  shared/macros/10-ocil.jinja
  shared/references/cce-redhat-avail.txt
Labels: OpenShift

#10617 SRG-APP-000390-CTR-000930 is now not applicable
  controls/srg_ctr/SRG-APP-000390-CTR-000930.yml
Labels: OpenShift

#10616 SRG-APP-000266-CTR-000625: Inherently met SRG Was missing status justification
  controls/srg_ctr/SRG-APP-000266-CTR-000625.yml
Labels: OpenShift

#10494 Link api_server_encryption_provider_cipher with CIS 2.8
  applications/openshift/api-server/api_server_encryption_provider_cipher/rule.yml
  products/ocp4/profiles/cis.profile
Labels: OpenShift, Update Rule, CIS

#10614 SRG-APP-000441-CTR-001090,SRG-APP-000442-CTR-001095: Add justification to a rule that's inherently met
  controls/srg_ctr/SRG-APP-000441-CTR-001090.yml
  controls/srg_ctr/SRG-APP-000442-CTR-001095.yml
Labels: OpenShift

#10680 Fixes in 1.3.1 GC rules with updated doc links and completing control response
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_imagefs_available/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_imagefs_available_master/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_imagefs_available_worker/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_memory_available/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_memory_available_master/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_memory_available_worker/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_available/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_available_master/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_available_worker/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_inodesfree/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_inodesfree_master/rule.yml
  applications/openshift/kubelet/kubelet_eviction_thresholds_set_hard_nodefs_inodesfree_worker/rule.yml
  controls/cis_ocp_1_3_0/section-1.yml
Labels: OpenShift, needs-ok-to-test

#10404 OCP4: Update instructions of scc/scc_limit_container_allowed_capabilities
  applications/openshift/scc/scc_limit_container_allowed_capabilities/rule.yml
Labels: OpenShift

#10618 SRG-APP-000090-CTR-000155: No longer Does not Meet, but instead covered by setting the OCP audit profile
  applications/openshift/logging/audit_profile_set/rule.yml
  controls/srg_ctr/SRG-APP-000090-CTR-000155.yml
Labels: OpenShift

#10615 SRG-APP-000158-CTR-000390: Add supporting evidence to an Inherently Met rule
  controls/srg_ctr/SRG-APP-000158-CTR-000390.yml
Labels: OpenShift

#10705 Increase RHEL7 STIG Coverage
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/rule.yml
  linux_os/guide/system/selinux/selinux_confine_to_least_privilege/rule.yml
  products/rhel7/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
Labels: Update Profile, RHEL7, STIG

#10708 A fix in macro sshd_oval_check
  shared/macros/10-oval.jinja
Labels: SLES, needs-ok-to-test

#10712 Stabilization: Add a Playbook name to Ansible Playbooks
  ssg/ansible.py
  ssg/build_profile_remediations.py
Labels: BLOCKER, Ansible

#10713 Add a Playbook name to Ansible Playbooks
  ssg/ansible.py
  ssg/build_profile_remediations.py
Labels: Ansible, backported-into-stabilization

#10549 Fixes of cron package/service for SLE 12/15
  controls/cis_sle12.yml
  controls/cis_sle15.yml
  controls/pcidss_4.yml
  linux_os/guide/services/cron_and_at/package_cron_installed/rule.yml
  linux_os/guide/services/cron_and_at/service_crond_enabled/rule.yml
  products/sle12/profiles/pci-dss-4.profile
  products/sle15/profiles/hipaa.profile
Labels: SLES, needs-ok-to-test, Update Rule, Update Profile, CIS

#10707 A fix in the rule sshd_set_keepalive
  controls/anssi.yml
  controls/cis_sle12.yml
  controls/cis_sle15.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml
Labels: bugfix, SLES, needs-ok-to-test

#10673 Changes in SLE 12/15 profiles related to time_sync services
  controls/anssi.yml
  linux_os/guide/services/ntp/chronyd_configure_pool_and_server/rule.yml
  linux_os/guide/services/ntp/chronyd_specify_remote_server/rule.yml
  linux_os/guide/services/ntp/package_chrony_installed/rule.yml
  linux_os/guide/services/ntp/service_chronyd_or_ntpd_enabled/rule.yml
  linux_os/guide/services/ntp/service_ntp_enabled/rule.yml
  products/sle12/profiles/cis.profile
  products/sle12/profiles/cis_server_l1.profile
  products/sle12/profiles/cis_workstation_l1.profile
  products/sle12/profiles/cis_workstation_l2.profile
  products/sle12/profiles/pci-dss-4.profile
  products/sle12/profiles/pci-dss.profile
  products/sle15/profiles/cis.profile
  products/sle15/profiles/cis_server_l1.profile
  products/sle15/profiles/cis_workstation_l1.profile
  products/sle15/profiles/cis_workstation_l2.profile
  products/sle15/profiles/pci-dss-4.profile
  products/sle15/profiles/pci-dss.profile
Labels: SLES, needs-ok-to-test

#10568 Fix in SLE 12/15 rule accounts_passwords_pam_tally2_unlock_time
  controls/anssi.yml
  controls/cis_sle12.yml
  controls/cis_sle15.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/tests/pam_tally2_absent_account_config.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/tests/pam_tally2_auth_unlock_time_configured.pass.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/tests/pam_tally2_deny_missing.fail.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/tests/pam_tally2_unlock_time_missing.fail.sh
Labels: SLES, needs-ok-to-test

#10717 Fix grub2 remediation instructions
  linux_os/guide/system/bootloader-grub2/non-uefi/grub2_admin_username/rule.yml
Labels: needs-ok-to-test, Update Rule

#10715 Add graphs to represent the life cycle of controls file
  docs/manual/developer/03_creating_content.md
Labels: Documentation

#10693 Test and use rules to components mapping
  components/chrony.yml
  components/firewalld.yml
  components/iptables.yml
  docs/manual/developer/03_creating_content.md
  products/example/product.yml
  products/fedora/product.yml
  products/rhel7/product.yml
  products/rhel8/product.yml
  products/rhel9/product.yml
  ssg/build_yaml.py
  ssg/components.py
  tests/CMakeLists.txt
  tests/data/product_stability/fedora.yml
  tests/data/product_stability/rhel7.yml
  tests/data/product_stability/rhel8.yml
  tests/data/product_stability/rhel9.yml
  tests/test_components.py
  tests/unit/ssg-module/data/components_dir/fapolicyd.yml
  tests/unit/ssg-module/test_components.py
Labels: enhancement, Highlight

#10718 Fix traceback in release helper
  utils/release_helper.py
Labels: Infrastructure

#10724 Fix attribute for args root
  utils/build_stig_control.py
Labels: bugfix, needs-ok-to-test

#10721 Add components_root to example stability
  tests/data/product_stability/example.yml
Labels: bugfix

#10728 Improve error message
  ssg/build_yaml.py
Labels: Infrastructure

#10733 Updated fix_rules to use product class
  utils/fix_rules.py
Labels: bugfix

#10696 Removal of package_libreswan_installed from SLE 12/15 profiles
  linux_os/guide/system/network/network-ipsec/package_libreswan_installed/rule.yml
  products/sle12/profiles/pci-dss-4.profile
  products/sle12/profiles/pci-dss.profile
  products/sle15/profiles/pci-dss-4.profile
  products/sle15/profiles/pci-dss.profile
Labels: SLES, needs-ok-to-test, Update Profile, pci-dss

#10711 add-rules sles-15-010418 sles-12-010498
  linux_os/guide/services/mail/package_mailx_installed/rule.yml
  products/sle12/profiles/stig.profile
  products/sle15/profiles/stig.profile
  shared/references/cce-sle12-avail.txt
  shared/references/cce-sle15-avail.txt
Labels: SLES, needs-ok-to-test, Update Profile, STIG

#10672 SLE Add rsyslog_remote_loghost droping remediations
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/ansible/shared.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/ansible/sle15.yml
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/bash/shared.sh
  linux_os/guide/system/logging/rsyslog_sending_messages/rsyslog_remote_loghost/bash/sle15.sh
  shared/macros/10-bash.jinja
  tests/unit/bash/test_bash_comment_config_line.bats.jinja
Labels: Ansible, Bash, SLES

#10702 Update of anssi profile for SLE 12/15
  linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_system_auth/rule.yml
  products/sle12/profiles/anssi_bp28_enhanced.profile
  products/sle12/profiles/anssi_bp28_high.profile
  products/sle12/profiles/anssi_bp28_intermediary.profile
  products/sle12/profiles/anssi_bp28_minimal.profile
  products/sle15/profiles/anssi_bp28_enhanced.profile
  products/sle15/profiles/anssi_bp28_high.profile
  products/sle15/profiles/anssi_bp28_intermediary.profile
  products/sle15/profiles/anssi_bp28_minimal.profile
Labels: SLES, needs-ok-to-test, Update Profile, ANSSI

#10709 Render components to HTML
  docs/manual/developer/03_creating_content.md
  ssg/components.py
  ssg/jinja.py
  tests/unit/ssg-module/data/components_dir/fapolicyd.yml
  tests/unit/ssg-module/test_components.py
  utils/gen_html_guides_index.py
  utils/gen_rendered_policies_index.py
  utils/gen_srg_table.py
  utils/gen_stig_table.py
  utils/gen_tables_common.py
  utils/generate_html_pages.sh
  utils/render_components.py
  utils/rendering/component-index-template.html
  utils/rendering/component-template.html
  utils/template_renderer.py
Labels: Infrastructure, Highlight

#10697 Increase RHEL8 STIG Coverage
  linux_os/guide/services/sssd/sssd_has_trust_anchor/rule.yml
  linux_os/guide/system/accounts/accounts-pam/disallow_bypass_password_sudo/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny_root/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_minlen_login_defs/rule.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/rule.yml
  products/rhel8/profiles/stig.profile
  shared/references/cce-redhat-avail.txt
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: RHEL8, STIG

#10730 OCP4: Remove obsolete rule scheduler_no_bind_address
  controls/nist_ocp4.yml
  controls/srg_ctr/SRG-APP-000516-CTR-001325.yml
  products/ocp4/profiles/cis.profile
Labels: OpenShift

#10744 Remove component SuSEfirewall2
  components/SuSEfirewall2.yml
Labels: bugfix

#10435 OCP4: Don't limit prometheus rules to 500
  applications/openshift/general/compliance_notification_enabled/rule.yml
  applications/openshift/general/file_integrity_notification_enabled/rule.yml
  applications/openshift/logging/audit_error_alert_exists/rule.yml
Labels: OpenShift

#10747 Generate CIS OpenShift 1.4.0 Section 1
  controls/cis_ocp_1_4_0/section-1.yml
Labels: OpenShift, CIS

#10748 Generate CIS OpenShift 1.4.0 Section 2
  controls/cis_ocp_1_4_0/section-2.yml
Labels: OpenShift, CIS

#10750 Generate CIS OpenShift 1.4.0 Section 4
  controls/cis_ocp_1_4_0/section-4.yml
Labels: OpenShift, CIS

#10720 add rules UBTU-20-010045
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/ansible/shared.yml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/bash/shared.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, ok-to-test, STIG

#10751 Generate OpenShift CIS 1.4.0 Section 5
  controls/cis_ocp_1_4_0/section-5.yml
Labels: OpenShift, CIS

#10656 Store rendered control files
  build-scripts/compile_all.py
  docs/manual/developer/03_creating_content.md
  ssg/controls.py
  ssg/entities/common.py
  tests/unit/ssg-module/test_controls.py
Labels: Infrastructure, Highlight, New Feature

#10745 Move the most important links to a better place
  README.md
Labels: Documentation

#10755 Various fixes for Ubuntu
  linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/sce/shared.sh
  linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/bash/ubuntu.sh
  shared/macros/10-bash.jinja
Labels: Bash, Ubuntu, CIS

#10758 utils: Add SRG to NIST control mapping for the OCP4 STIG
  utils/create_srg_export.py
  utils/srg_export/data.py
Labels: Infrastructure, STIG

#10754 macros: bash: Avoid matching comments in fstab macros
  shared/macros/10-bash.jinja
Labels: bugfix, Bash

#10752 Fix grep for Automatus sanity
  .github/workflows/automatus-sanity.yaml
Labels: Test Suite

#10729 Add modified audit suid privilege function rule for CIS
  components/audit.yml
  controls/cis_rhel8.yml
  controls/cis_rhel9.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/correct_value.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/miss_arch.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/miss_c.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/no_rules.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/other_key.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/use_f_key.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/wrong_a.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/wrong_c_euid.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/tests/wrong_f_auid.fail.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_suid_privilege_function/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: Ansible, Bash, New Rule, needs-ok-to-test, Update Profile

#10763 Add a section guiding through the process of rule divergence
  docs/manual/developer/03_creating_content.md
Labels: Documentation

#10766 Revert "fix: aide/remediations: add crontabs"
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/bash/shared.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_periodic_cron_checking/bash/ubuntu.sh
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_scan_notification/bash/shared.sh
Labels: bugfix

#10756 OCP: fix etcd_unique_ca rule e2e failures
  applications/openshift/etcd/etcd_unique_ca/rule.yml
Labels: OpenShift

#10761 Introduce a JSON build manifest
  build-scripts/generate_manifest.py
  cmake/SSGCommon.cmake
Labels: Highlight

#10764 Fix platform comparison in content_diff
  ssg/content_diff.py
  ssg/xml.py
  utils/compare_ds.py
Labels: bugfix

#10736 SRG-APP-000148-CTR-000335,SRG-APP-000190-CTR-000500: Covered by sshd_disable_root_login
  controls/srg_ctr/SRG-APP-000148-CTR-000335.yml
  controls/srg_ctr/SRG-APP-000190-CTR-000500.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/rule.yml
  linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login/tests/ocp4/e2e.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenShift, STIG

#10735 RHCOS4 STIG: Cover controls related to NIST CM family
  controls/srg_ctr/SRG-APP-000141-CTR-000315.yml
  controls/srg_ctr/SRG-APP-000185-CTR-000490.yml
  linux_os/guide/services/ssh/service_sshd_disabled/rule.yml
  linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: OpenShift
