Repository ComplianceAsCode/content, pull requests merged in 2023-09, with the labels that each got.

#11043 Add SCAPVal to Stabilize task
  .github/workflows/stabilize.yaml
Labels: Infrastructure

#11048 Ensure Python dependencies in Gate tests
  .github/workflows/gate.yaml
Labels: bugfix, Test Suite

#11047 Fix Gate Test on Fedora Rawhide
  .github/workflows/gate.yaml
Labels: bugfix, Test Suite

#11052 Include new options in var_accounts_minimum_age_login_defs
  linux_os/guide/system/accounts/accounts-restrictions/password_expiration/var_accounts_minimum_age_login_defs.var
Labels: usability

#11040 Introduce controleval_metrics.py tool to generate metrics in Prometheus format
  CMakeLists.txt
  requirements.txt
  tests/CMakeLists.txt
  utils/controleval.py
  utils/controleval_metrics.py
Labels: enhancement, New Feature

#11046 scap-security-guide: Add Poky support
  products/openembedded/product.yml
  shared/checks/oval/installed_OS_is_poky.xml
Labels: needs-ok-to-test

#11055 Expose Prometheus metrics on GitHub Pages
  .github/workflows/gh-pages.yaml
  utils/generate_html_pages.sh
Labels: Documentation

#11077 Remove override-true-all-profile-* tests
  cmake/SSGCommon.cmake
Labels: Infrastructure, Test Suite

#11100 Remove DRAFT wording for OpenShift STIG
  products/ocp4/profiles/stig-node.profile
  products/ocp4/profiles/stig.profile
  products/rhcos4/profiles/stig.profile
Labels: OpenShift, Highlight, STIG

#11045 Enable logrotate.timer check on RHCOS4
  linux_os/guide/system/logging/log_rotation/ensure_logrotate_activated/oval/shared.xml
  linux_os/guide/system/logging/log_rotation/timer_logrotate_enabled/rule.yml
Labels: OpenShift

#11060 Add UBTU-20-010462 to lock accounts without passwords
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, ok-to-test, STIG

#11084 Fix UBTU-20-010267 and deprecate STIGs
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_renameat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, needs-ok-to-test, STIG

#11096 Update Ubuntu 20.04 DISA Manual STIG to v1r9
  products/ubuntu2004/profiles/stig.profile
  shared/references/disa-stig-ubuntu2004-v1r9-xccdf-manual.xml
Labels: Ubuntu, needs-ok-to-test, STIG

#11109 Standard Profile Improvements
  products/rhel7/profiles/standard.profile
  products/rhel8/profiles/standard.profile
Labels: Update Profile

#11095 Replace shell command with find for chrony.conf files on UBTU-20-010435
  linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/ansible/shared.yml
Labels: enhancement, Ansible, needs-ok-to-test

#11057 Add UBTU-20-010181 for generating audit record for unsuccessful attem…
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_delete/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, needs-ok-to-test, STIG

#11058 Fix UBTU-20-10450 STIG
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, needs-ok-to-test, STIG

#11068 Fix UBTU-20-010449 ansible remediation to proper path and substitution
  linux_os/guide/system/software/updating/clean_components_post_updating/ansible/shared.yml
Labels: Ansible, needs-ok-to-test

#11087 Fix path and add ansible remediation UBTU-20-010298
  linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_fdisk/ansible/shared.yml
Labels: Ubuntu, ok-to-test, STIG

#11063 Add UBTU-20-010401 to restrict kernel message buffer
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_dmesg_restrict/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, ok-to-test, STIG

#11062 Add UBTU-20-010461 to ensure kernel module usb-storage is blacklisted…
  linux_os/guide/system/permissions/mounting/kernel_module_usb-storage_disabled/rule.yml
  products/ubuntu2004/profiles/stig.profile
  shared/templates/kernel_module_disabled/ansible.template
  shared/templates/kernel_module_disabled/bash.template
Labels: Ubuntu, ok-to-test, STIG

#11056 fix naming for UBTU-20-010430
  linux_os/guide/system/permissions/files/permissions_within_important_dirs/root_permissions_syslibrary_files/rule.yml
Labels: Ubuntu, ok-to-test, STIG

#11108 Fix umask bash
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_profile/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/bash/shared.sh
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/tests/umask_defined_whith_spaces.fail.sh
Labels: Bash, needs-ok-to-test

#11112 Dependabot Preperation
  .github/workflows/automatus-cs8.yaml
  .github/workflows/automatus-cs9.yaml
  .github/workflows/automatus-sanity.yaml
  .github/workflows/automatus-sle15.yaml
  .github/workflows/automatus.yaml
  .github/workflows/compare-ds.yaml
  .github/workflows/ctf.yaml
  .github/workflows/gate-lint-ansible-roles.yaml
  .github/workflows/gate.yaml
  .github/workflows/gh-pages.yaml
  .github/workflows/nightly_build.yml
  .github/workflows/release-changelog.json
  .github/workflows/release.yaml
  .github/workflows/srg-mapping-table.yaml
  .github/workflows/stabilize.yaml
Labels: Infrastructure

#11110 Use var_accounts_passwords_pam_faillock_dir in audit_rules_login_events
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/tests/default.pass.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events/tests/rules_without_keys.pass.sh
  products/rhel7/profiles/C2S.profile
  products/rhel7/profiles/cjis.profile
  products/rhel7/profiles/e8.profile
  products/rhel7/profiles/pci-dss.profile
  tests/data/profile_stability/rhel7/e8.profile
Labels: bugfix, Bash, Update Rule

#11080 Fix UBTU-20-010179 to use proper parameters and key
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/bash/shared.sh
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/oval/shared.xml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/rule.yml
Labels: Ubuntu, ok-to-test, STIG

#11079 Deprecate UBTU-20-010180
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, needs-ok-to-test, STIG

#11061 Add UBTU-20-010463 to ensure system does not allow accounts configure…
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/bash/shared.sh
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/oval/shared.xml
  linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/rule.yml
  products/ubuntu2004/profiles/stig.profile
Labels: Ubuntu, ok-to-test, STIG

#11111 Fix Automatus traceback
  tests/ssg_test_suite/common.py
Labels: Test Suite, SLES

#11086 Fix excluded_files and recursive for UBTU-20-010416
  linux_os/guide/system/permissions/files/permissions_local_var_log/bash/ubuntu.sh
  linux_os/guide/system/permissions/files/permissions_local_var_log/rule.yml
Labels: Ubuntu, ok-to-test, STIG

#11094 Add rsyslog ansible remediation for UBTU-20-010403
  linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_remote_access_monitoring/ansible/ubuntu.yml
Labels: Ubuntu, ok-to-test, STIG

#11019 Add variable support to `auditd_name_format` rule
  .github/workflows/automatus-cs8.yaml
  .github/workflows/automatus-cs9.yaml
  .github/workflows/automatus-sle15.yaml
  .github/workflows/automatus.yaml
  controls/srg_gpos.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/ansible/shared.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/bash/shared.sh
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/oval/shared.xml
  linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_name_format/rule.yml
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_flush.var
  linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_name_format.var
  products/rhel7/profiles/stig.profile
  products/rhel8/profiles/stig.profile
  tests/data/profile_stability/rhel8/stig.profile
  tests/data/profile_stability/rhel8/stig_gui.profile
Labels: RHEL, Update Rule, STIG

#11115 Remove the rule accounts_passwords_pam_faillock_interval from SLE pro…
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/bash/shared.sh
  linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml
Labels: SLES, needs-ok-to-test, Update Profile

#11113 Add Dependabot
  .github/dependabot.yml
Labels: Infrastructure

#11073 Add UBTU-20-010044 to existing ansible remediation
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_ciphers_ordered_stig/ansible/shared.yml
Labels: Ubuntu, ok-to-test, STIG

#11114 Fix stig overlay
  utils/create-stig-overlay.py
Labels: Infrastructure

#11117 Fix Ansible Tasks order
  build-scripts/generate_profile_remediations.py
Labels: bugfix, Infrastructure, Ansible

#11124 accounts_umask_etc_bashrc: ansible: Fix bashrc path for Ubuntu
  linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/ansible/shared.yml
Labels: Ansible, Ubuntu

#11034 exclude some audit rules from aarch64 platform
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_lchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_lchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_successful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_chmod/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_chown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_lchown/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_o_creat/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_o_trunc_write/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_open_rule_order/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_rename/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_file_modification/audit_rules_unsuccessful_file_modification_unlink/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_create/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_query/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_group_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_gshadow_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_shadow_open/rule.yml
  linux_os/guide/system/auditing/auditd_configure_rules/audit_time_rules/audit_rules_time_stime/rule.yml
Labels: bugfix

#11053 Improve sshd_use_approved_kex_ordered_stig
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/oval/shared.xml
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/comment.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/common.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/correct_reduced_list.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/correct_scrambled.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/correct_value.pass.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/line_not_there.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/no_parameters.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/tests/wrong_value.fail.sh
  linux_os/guide/services/ssh/ssh_server/sshd_use_strong_kex/oval/shared.xml
Labels: enhancement, STIG

#11123 Change how example ROLE_LIST are formatted
  applications/openshift/scc/scc_limit_privileged_containers/rule.yml
  applications/openshift/scc/scc_limit_root_containers/rule.yml
Labels: OpenShift

#11097 Enable ansible and bash remediation for sssd for UBTU-20-010441
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/ansible/shared.yml
  linux_os/guide/services/sssd/sssd_offline_cred_expiration/bash/shared.sh
Labels: Ubuntu, ok-to-test, STIG

#11126 Unify file saving
  build-scripts/compile_all.py
Labels: Infrastructure

#11121 Fix OrderedDict definition
  ssg/build_remediations.py
Labels: Infrastructure

#11041 OVAL object model
  ssg/constants.py
  ssg/oval_object_model/__init__.py
  ssg/oval_object_model/general.py
  ssg/oval_object_model/oval_document.py
  ssg/oval_object_model/oval_entities/__init__.py
  ssg/oval_object_model/oval_entities/definition.py
  ssg/oval_object_model/oval_entities/object.py
  ssg/oval_object_model/oval_entities/state.py
  ssg/oval_object_model/oval_entities/test.py
  ssg/oval_object_model/oval_entities/variable.py
  ssg/xml.py
  tests/unit/ssg-module/data/minimal_oval_of_oval_ssg-sshd_rekey_limit_def.xml
  tests/unit/ssg-module/data/shorthand_with_all_components.xml
  tests/unit/ssg-module/test_oval_object_model/test_load_and_store.py
Labels: enhancement, Infrastructure, ok-to-test

#11127 Fix package_audit-libs_installed rule.yml
  linux_os/guide/system/auditing/package_audit-libs_installed/rule.yml
Labels: needs-ok-to-test

#11129 Add support of derivatives to Automatus
  ssg/constants.py
  tests/automatus.py
Labels: Test Suite

#11128 Include metrics for rules and variables selected in Controls
  ssg/controls.py
  utils/controleval.py
  utils/controleval_metrics.py
Labels: enhancement, Documentation

#11064 Modify adie db exist path for UBTU-20-010450
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml
  linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/ubuntu.yml
Labels: Ubuntu, ok-to-test, STIG

#11132 Build OCP STIG profiles by default
  products/ocp4/profiles/stig-node.profile
  products/ocp4/profiles/stig.profile
Labels: OpenShift, STIG

#11131 Move master to use merge groups
  .github/workflows/gate.yaml
Labels: Infrastructure, Highlight

#11065 Fix rule ubtu 20 010033
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/ansible/shared.yml
  linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/rule.yml
Labels: SLES, Ubuntu, ok-to-test, STIG

#10928 Sphinx apidocs
  .gitignore
  docs/conf.py
  docs/index.rst
  docs/manual/developer/02_building_complianceascode.md
  docs/requirements.txt
  tox.ini
Labels: Documentation, needs-ok-to-test

#11139 Disable sysctl_kernel_yama_ptrace_scope rule for sle15
  linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml
Labels: SLES

#11138 Add SELinux as platform
  linux_os/guide/system/selinux/selinux-booleans/group.yml
  shared/applicability/oval/selinux_is_enabled.xml
  shared/applicability/selinux.yml
Labels: Update Rule

#11140 Fix scenario applicability in Automatus combined mode
  tests/ssg_test_suite/combined.py
  tests/ssg_test_suite/rule.py
Labels: bugfix, Test Suite

#11144 Add rule `package_s-nail-installed`
  components/s-nail.yml
  controls/srg_gpos/SRG-OS-000363-GPOS-00150.yml
  linux_os/guide/services/mail/package_s-nail_installed/rule.yml
  shared/references/cce-redhat-avail.txt
Labels: New Rule, RHEL9, STIG

#11145 Fix scap delta tailoring
  utils/create_scap_delta_tailoring.py
Labels: Infrastructure

#11146 Running locally unit tests of `ssg` module using python2 and 3
  .gitignore
  tests/CMakeLists.txt
  tests/unit/build-scripts/test_relabel_ids.py
  tests/unit/ssg-module/test_build_yaml.py
  tests/unit/ssg-module/test_controls.py
  tox.ini
Labels: do-not-merge/work-in-progress

#11134 Ubuntu: Add missing nftables variables and improve remediation and checks
  linux_os/guide/system/network/network-nftables/nftables_rules_permanent/bash/ubuntu.sh
  linux_os/guide/system/network/network-nftables/nftables_rules_permanent/oval/ubuntu.xml
  linux_os/guide/system/network/network-nftables/nftables_rules_permanent/sce/ubuntu.sh
  linux_os/guide/system/network/network-nftables/set_nftables_base_chain/sce/shared.sh
  linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/bash/shared.sh
  linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/sce/ubuntu.sh
  products/ubuntu2004/profiles/cis_level1_server.profile
  products/ubuntu2204/profiles/cis_level1_server.profile
Labels: Ubuntu, CIS

#11147 Update Packit Config
  .packit.yaml
Labels: Infrastructure

#11156 Add JSON schema for variables
  shared/schemas/variable.json
Labels: Documentation

#11157 Add JSON schema for controls
  shared/schemas/control.json
Labels: Documentation

#11155 Add version metadata to the OCP PCI-DSS profile
  products/ocp4/profiles/pci-dss-node.profile
  products/ocp4/profiles/pci-dss.profile
Labels: OpenShift, Update Profile

#11152 Add version for OCP CIS
  products/ocp4/profiles/cis-node.profile
  products/ocp4/profiles/cis.profile
Labels: OpenShift, Update Profile

#11150 Update contributors for 0.1.70
  .mailmap
  Contributors.md
  Contributors.xml
Labels: Documentation

#11154 Version FedRAMP high and moderate profiles for OpenShift
  products/ocp4/profiles/high-node.profile
  products/ocp4/profiles/high.profile
  products/ocp4/profiles/moderate-node.profile
  products/ocp4/profiles/moderate.profile
  products/rhcos4/profiles/high.profile
  products/rhcos4/profiles/moderate.profile
Labels: OpenShift, Update Profile

#11143 Add support for Variable and Node rules in `add_platform_rule.py`
  utils/add_platform_rule.py
Labels: OpenShift

#11153 Add version for OCP STIG
  products/ocp4/profiles/stig-node.profile
  products/ocp4/profiles/stig.profile
  products/rhcos4/profiles/stig.profile
Labels: OpenShift, Update Profile
